### ISSUE TITLE
Import Error of react-intl in Safari.

### ISSUE THREAD

**Issue by njsuperfreak** [yahoo/react-intl#100]
Hello, 

I am using the react-hot-loader that uses webpack-dev-server. 

I am seeing the following error in Safari when I try to import react-int as a ES6 module (using babel):
![screen shot 2015-04-02 at 10 13 22 am](https://cloud.githubusercontent.com/assets/1198354/6965605/efc6ba0e-d920-11e4-8374-9c7d4517215c.png)

```
import {IntlMixin, FormattedDate } from 'react-intl';

```

Or
 
```
import ReactIntl, {IntlMixin, FormattedDate } from 'react-intl';
```

**Comment by ericf** [comment]
Looks like you're missing the Intl.js polyfill that's needed for Safari since it doesn't yet have the `Intl` APIs built-in.

There are more details on the site:
http://formatjs.io/guides/runtime-environments/
http://formatjs.io/guides/runtime-environments/#client

**Comment by njsuperfreak** [comment]
Thanks! This fixed the issue with the missing `Intl`
`npm install intl`

```
import Intl from 'intl';
import {IntlMixin, FormattedDate } from 'react-intl';
```
However I still seeing this and I am wondering if it needs a loader for webpack:
![screen shot 2015-04-02 at 1 34 40 pm](https://cloud.githubusercontent.com/assets/1198354/6969488/0be33138-d93d-11e4-8ae4-be638c86f81c.png)

**Comment by ericf** [comment]
Related to this: https://github.com/esnext/es6-module-transpiler/issues/164
We'll have to revamp our build process at some point to not produce source maps for CommonJS modules.

**Comment by njsuperfreak** [comment]
Thanks! I'll look forward to the update.

**Comment by jefferyvincent** [comment]
Still seeing these errors in build 1.4.0

**Comment by Dindaleon** [comment]
Any updates on this? I am getting these errors as well. I have several sites using react-intl but they are all broken in safari unless i disable react-intl.

**Comment by olivierlambert** [comment]
Hi lads, any news on this? Or a known workaround?
