### ISSUE TITLE
What are the fallback "sources"?

### ISSUE THREAD

**Issue by rasenplanscher** [yahoo/react-intl#1002]
According to [the docs](https://github.com/yahoo/react-intl/wiki/API#message-formatting-fallbacks), message fallback goes through this chain:
1. Lookup and format the translated message at `id`, passed to `<IntlProvider>`.
1. Fallback to formatting the `defaultMessage`.
1. Fallback to translated message at `id`'s source.
1. Fallback to `defaultMessage` source.
1. Fallback to the literal message `id`.

What I don't get are steps `3` and `4`. What do they mean?

**Comment by okovpashko** [comment]
@rasenplanscher as I understood from the [source](https://github.com/yahoo/react-intl/blob/master/src/format.js#L175) those two fallbacks are used only if message descriptor has values and there was an error during formatting the message. In that case, either translated message or `defaultMessage` will be returned exactly as it was defined (without variables substitution).

**Comment by rasenplanscher** [comment]
@okovpashko 
Ah, yes, that's it. On that day, I couldn't wrap my head around the source. But with your explanation, now I get it. Thank you 😄
