### ISSUE TITLE
Possible to call formatMessage in a utils file?

### ISSUE THREAD

**Issue by AndroidDoctorr** [yahoo/react-intl#1009]
If I have a utility file containing a set of exported functions, rather than a component with props, is there a way to use formatMessage here?

**Comment by ghostd** [comment]
You'll need to pass the format* functions as parameters if you want to reuse your react-intl settings

**Comment by AndroidDoctorr** [comment]
Oh yeah, that makes sense. I think that will work.

**Comment by ghostd** [comment]
If you need more than the formatMessage methods (current locale...), pass the [intl shape](https://github.com/yahoo/react-intl/wiki/API#intlshape)

If you think your issue is answered, please close the thread.
