### ISSUE TITLE
FormatNumber :: using style as props. 

### ISSUE THREAD

**Issue by Peripona** [yahoo/react-intl#1010]
> style as props. :: creates problem if user wants to add customStyles to the component.

We are using formatNumber in our projects and found that style used as a prop could create problems. 
Since we creating an HOC and passing an object with price and other values to use this as a priceFormattingComponent. 
possibly this component will be shared with other teams and as react component we want other teams to be able to pass other props to this. like ...transferableProps, along with priceDetails.

Now if someone pass style as a prop which they want to use to style this, currency formatter will fail. 

as a suggestion, can you update this prop name to be something not from the default availble props for HTML tags please.

**Comment by ghostd** [comment]
`style` is the official name in the [API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)

**Comment by Peripona** [comment]
@ghostd Thanks but yes its really bad. but since, FormatNumber is a wrapper for numberFormat from intl. 
May be we can fix this. allowing style to be used as style and expect ```type``` as a prop for FormatNumber !?

**Comment by okovpashko** [comment]
@Peripona I think the authors of `react-intl` tried to use the same props names for `FormattedNumber` as `Intl.NumberFormat` uses for options. It allows anyone to look for possible values in `Intl.NumberFormat` documentation.
Also, I think it's not so easy to change the prop name without breaking backward compatibility. Considering this project not being under active development, I think your suggestion doesn't have chances to be implemented.

**Comment by Peripona** [comment]
Thanks @okovpashko I would close this ticket, 
I found a way, i will not allow rest props to contain style, by using style explicitly, 
but just it blocks the other teams to apply dynamic styles, however they could wrap my CurrencyFormatter in a div to be able to do any Style specific change. 
Thanks 👍
