### ISSUE TITLE
Incoherent number formatting for 'fr-CH' and 'de-CH'

### ISSUE THREAD

**Issue by Floriferous** [yahoo/react-intl#1016]
Number formatting for these 2 locales should be the same, but the first is displayed with spaces as thousands' separators, whereas the second uses apostrophes:

1 million: 
-> fr-CH: 1 000 000
-> de-CH: 1'000'000

I'm not sure this is the right place for this issue, but maybe someone can redirect me to the correct repo/forum for fixing this.

**Comment by okovpashko** [comment]
`react-intl` uses `Intl.NumberFormat` under the hood for number formatting. Using it, I get the same [result](http://jsbin.com/hovimix/edit?js,console), so it's not the issue in `react-intl`.

**Comment by okuryu** [comment]
Yes. I guess it's a bug of react-intl. Please check Unicode CLDR and file an issue for CLDR if you see any problems in CLDR.
