### ISSUE TITLE
Isomorphic?

### ISSUE THREAD

**Issue by iam4x** [yahoo/react-intl#102]
I have different render on server and client for this: 

```
<FormattedNumber value={1000} style="currency" currency="USD" />
```

* Server: US$99.95
* Client: $99.95

I use `iojs-v1.6.4` and `react-v0.13.1`

**Comment by ericf** [comment]
Which browsers?

**Comment by iam4x** [comment]
`Google Chrome Canary Version 44.0.2368.0 canary (64-bit)`

**Comment by gpbl** [comment]
[Related](https://github.com/yahoo/react-intl/issues/57)

**Comment by iam4x** [comment]
Nice catch @gpbl !
