### ISSUE TITLE
Missing de-DE in de locale data

### ISSUE THREAD

**Issue by Inoir** [yahoo/react-intl#1021]
Missing the reference for de-DE in [de.js](https://unpkg.com/react-intl@2.3.0/locale-data/de.js)

Atm i need a workaround for this.

For example Safari on Iphone7 will send de-DE if you use german settings

**Comment by okuryu** [comment]
The `de-DE` isn't available in Unicode CLDR.
https://github.com/unicode-cldr/cldr-dates-full/tree/master/main

Please file a ticket if it's bug for Unicode CLDR.
http://unicode.org/cldr/trac/newticket
