### ISSUE TITLE
React-Native : FormattedDate does not seem to Localise according to the device settings until remote chrome debugger is on.

### ISSUE THREAD

**Issue by rimzici** [yahoo/react-intl#1025]
### BUG REPORT
using 'FormattedDate' as below in React-Native : Android.

`
<FormattedDate`
									`value={Date.now()}`
									`localeMatcher= "best fit"`
									`formatMatcher= "best fit"`
									`weekday="long"`
									`day="2-digit"`
									`month="long"/>`

rendering it in 'Text' replacing 'Span' . It prints the data but does not seem to localise date according to  phone settings. But It does work fine when remote debug is enabled.

importing polyfills at top of my project 

`import 'intl';`
`import 'intl/locale-data/jsonp/en';`

### Expected behavior
Was expecting to print something like 
when locale is set to "en"

`Saturday, 2 September`

when locale is set to "fr"

`samedi, 2 septembre`

### Current behavior
when locale is set to "en" as well as "fr"
`Sat, Sep 2`

remote debug on, 
when locale is set to "fr"
`samedi, 2 septembre`
when locale is set to "en"
`Saturday, 2 September`

### Step to reproduce for BUG REPORT
Usage as I have mentioned above, change the language in phone settings open the app, locale has no effect on date, now turn remote debugger on and check, everything works as expected.

### Your Environment
Trying on React Native, Android.
"react-native": "0.42.3",

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | react-intl@2.3.0 |
| `npm ls react` | react@15.4.2 |
| `npm --version` | 3.10.3 |
| `node --version` | v6.3.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

Thank you.

**Comment by jcurtis** [comment]
This works when using Chrome debugger because the JavaScript is run through Chrome's V8 instead of JavaScriptCore, which is what is used on the device. Chrome has built in Intl and JavaScriptCore does not. You will need to import the locale data for the language you want to support.

**Comment by rimzici** [comment]
Thanks @jcurtis , you are right :)
I must probably close this issue!

**Comment by remicoges** [comment]
@rimzici I have this problem even when I import all locale data in my provider. Have you done anything else to make it work ?

**Comment by rimzici** [comment]
@remicoges  In my case that is all I had to do.
at the root component had to import locale data as,

`import 'intl/locale-data/jsonp/fr';`

hope you have the polyfill too at the same component.

import 'intl';
