### ISSUE TITLE
checksum errors with v.2.4.0

### ISSUE THREAD

**Issue by bluebeckie** [yahoo/react-intl#1029]
We start to see checksum errors in our latest build with react-intl@2.4.0.
Basically it fails to find locale info on client side and falls back to "en" for strings. This discrepancy causes react checksum errors on browser.

thanks!!

### Expected behavior
Client side should render langs in different locale as before.

### Current behavior
It fails to find locale info on client side, falls back to en for locale and then causes checksum errors.

### Step to reproduce for BUG REPORT
install react-intl@2.3.0 and strings are translated as expected
install react-intl@2.4.0 and strings fail to translate on client side and there's checksum errors on page.

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 15.6.1 |
| `npm --version` | 3.10.9 |
| `node --version` | 6 |

| OS | Version |
| --- | --- |
| ios | 10.3.3 |

| Browser | Version |
| --- | --- |
| safari |  |

**Comment by redonkulus** [comment]
@bluebeckie This is actually an internal issue for us and not because of the package itself. It should be fixed for you internally. Once resolved, please close this issue.

**Comment by bluebeckie** [comment]
yes, I've verified that our build works with react-intl v2.4.0.
thanks!!
