### ISSUE TITLE
On some browsers, FormattedNumber doesn't show currency symbol

### ISSUE THREAD

**Issue by Zephir77167** [yahoo/react-intl#1032]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
BUG

### Expected behavior
I would expect the currency symbol to show everytime (e.g. 100 **€**)

### Current behavior
On some browsers, including:
- iOS9: iOS Webview, Safari, Chrome
- Android last version: Firefox

It only shows `100` (instead of `100€`).

### Step to reproduce for BUG REPORT
```
import { FormattedNumber } from 'react-intl';

<FormattedNumber
  style="currency"
  currency="EUR"
  value={100}
/>
```

### Your Environment
OS: described in the previous section

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.3.0 |
| `npm ls react` | 15.6.1 |
| `npm --version` | 5.0.3 |
| `node --version` | 8.1.4 |

Thanks in advance, and also thank you for this awesome library!

**Comment by papasmile** [comment]
Currency format is provided via Intl.NumberFormat (not react-intl itself).  According to their doc[1] it looks like it might not be supported on those browsers you listed, e.g. under 'Mobile', iOS is only supported from 10.2 and higher.

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat#Browser_compatibility

**Comment by Zephir77167** [comment]
Thanks for your answer! I have one last question before closing the issue: shouldn't that work if I am using a polyfill (`import 'intl';`)?

**Comment by papasmile** [comment]
Sure, I think you want a shim for older browsers e.g. https://github.com/andyearnshaw/Intl.js

**Comment by Zephir77167** [comment]
Ok, this is weird because I do include this shim. Thanks for the answers, I will go ask on their repository :)
