### ISSUE TITLE
Using named formats in <FormattedDate>

### ISSUE THREAD

**Issue by hectorsabina** [yahoo/react-intl#1033]
Hello, 

I'm trying to use named formats, but I can't manage to get it working. Based in my research, I think this should be a minimal example:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { IntlProvider, FormattedDate } from 'react-intl';

const Testy = (props) => (
    <FormattedDate
        value={ props.myDate }
        format='year-only'
      />
 )

const app = (
  <IntlProvider formats={{ date: { 'year-only': { year: 'numeric' } } }}>
    <Testy myDate={ "2010/10/01" }/>
  </IntlProvider>
)

ReactDOM.render(app, document.getElementById('App'));
```

But then, at runtime an error says: `[React Intl] No date format named: year-only`

What am I doing wrong?

**Comment by hectorsabina** [comment]
No one? This seems to be [documented](https://github.com/yahoo/react-intl/wiki/Components#formatteddate)  but I must be missing something... 

I can see there are unit tests using the `dateFormat` function with [named formats](https://github.com/yahoo/react-intl/blob/b82a899a59c762fcc590e1fa824b87da6ad409d9/test/unit/format.js#L154), but I can't see any tests of the `<FormattedDate>` component.

I guess I could use the function directly passed via props, but I'd like to avoid that if possible.

**Comment by papasmile** [comment]
I have code almost identical to your example but it's working.  Is it something simple like you need to set a `locale` on `IntlProvider`?

**Comment by hectorsabina** [comment]
Hey @papasmile, you got it, thanks for your answer. I thought having a fallback mechanism that kicks in when no locale is set (e.g. `[React Intl] Missing locale data for locale: "undefined". Using default locale: "en" as fallback.`) shouldn't have nothing to do with named formats you're passing as props.

But setting a locale did fix the issue.

I asked on SO as well, if you want to answer there I'll accept it: https://stackoverflow.com/questions/46323982/using-named-formats-in-formatteddate-in-react-intl
