### ISSUE TITLE
Please hoist statics in injectIntl

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#1047]
### Expected behavior
statics are hoisted

### Current behavior
statics are not being hoisted
This is breaking stuff for some libraries such as react-navigation, that use:

```
class MyScreen extends React.Component{
    static navigationOptions = {
       [...]
    }
}
````
### Solution

use `hoist-non-react-statics` as described here: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over

This issue is further described at https://github.com/react-community/react-navigation/issues/332 

An example solution can be viewed here:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/withRouter.js

**Comment by Ephys** [comment]
As a temporary fix, people can use this custom `injectIntl` function instead of the one provided by react-intl:

```
import { injectIntl as baseInjectIntl } from 'react-intl';
import hoistNonReactStatic from 'hoist-non-react-statics';

/**
 * A fixed injectIntl that hoists statics.
 */
export function injectIntl(WrappedComponent: Function): Function {
  const WrapperComponent = baseInjectIntl(WrappedComponent);

  hoistNonReactStatic(WrapperComponent, WrappedComponent);

  return WrapperComponent;
}
```

**Comment by infiman** [comment]
Having `preload` static method in my components for my SSR implementation, but `injectIntl` is not hoisting it after wrapping them. Any chance this will be fixed/implemented? Thanks in advance!
