### ISSUE TITLE
Nested IntlProvider?

### ISSUE THREAD

**Issue by afonsoSoares** [yahoo/react-intl#1049]
Hello everyone,
I'm working on an backoffice that have two IntlProviders.  I have my App wrapped by IntlProvider that have a locale assign. It's working as expected. But I want to have a component inside that as its own IntlProvider and assign locale. I wrapped the component with an IntlProvider as this.

`<IntlProvider
        locale={secondLocale}
        messages={messages}
        defaultLocale="en-GB"
        key={secondLocale}
      > `

I export my component with injectIntl .

`const mapStateToProps = (state, ownProps) => ({
  messages: state.intl.messages,
  secondLocale: state.intl.secondLocale
});
injectIntl(connect(mapStateToProps, mapDispatch)(withStyles(s)(Viewer)));`

But when I change the secondLocale i can't have the translations changed.
Any idea? Thank you

**Comment by ghostd** [comment]
Do you mean you have something like that ?
```
<IntlProvider locale="fr" messages={frMessages} defaultLocale="fr-FR">
...
  <IntlProvider locale="en" messages={enMessages} defaultLocale="en-GB" key="en" >
    ...
      <MyComponent />
    ...
  </IntlProvider>
...
</IntlProvider>
```

**Comment by afonsoSoares** [comment]
Hi, yes exactly the French IntlProvider is working but can't get the English IntlProvider working inside MyComponent. Thanks

**Comment by afonsoSoares** [comment]
Hi, I have managed to make working. Thanks to the help Ghostd. In fact I was passing all the messages but as you mentioned passing only 'messages[secondLocale]' worked. Thanks.
