### ISSUE TITLE
Support for missing locale data

### ISSUE THREAD

**Issue by chenrozenes** [yahoo/react-intl#1050]
Hi,

I need to translate my web site to Haitian Creole, (codes: "ht", "hat") and I couldn't find the locale data.
I looked in the index file as well - and none.
Even if I have all the strings translated, I still can't use it because react-intl throws an error (Missing locale data for locale: "ht". Using default locale: "en" as fallback.)
Currently I used another language's code but its pretty hacky.

Can you add support it? Maybe support and docs on writing missing locale data.
I also think a documentation about the current supported language will be awesome. 

Thanks

**Comment by papasmile** [comment]
@chenrozenes react-intl relies on cldr-json for built-in translations:  https://github.com/unicode-cldr/cldr-json

From that site: "It should be noted that XML (not JSON) is the "official" format for all CLDR data. The JSON data contained in the packages described below is provided as a convenience for the development community"

And I don't see Haitian in their metadata:  https://github.com/unicode-cldr/cldr-core/blob/master/scriptMetadata.json

I'd suggest either logging a request to that group, `unicode-cldr`, or building your own translations and contributing them back to the open source community :)

**Comment by chenrozenes** [comment]
@papasmile Thanks for the response.
Any recommendations of how to configure react-intl with my own custom language?

**Comment by papasmile** [comment]
Just use `addLocaleData` https://github.com/yahoo/react-intl/wiki/API#addlocaledata

**Comment by chenrozenes** [comment]
Ok thanks. FYI I had to add this object for it to work:
```
{
   locale: 'ht',
   pluralRuleFunction(e, t) {
      return t && e === 1 ? 'one' : 'other';
}
```
The ```pluralRuleFunction``` is mandatory for it to work.

**Comment by okuryu** [comment]
I think this question is resolved. please free to open an new issue if you still have any issues. closing.

@papasmile Thanks for your help!
