### ISSUE TITLE
Call formatMessage() as a function and get a string back?

### ISSUE THREAD

**Issue by chovy** [yahoo/react-intl#1051]
Is this possible? I want to call a function formatMessage() and get the translated string back.

**Comment by clearlyTHUYDOAN** [comment]
What's the use case for this? A one-time translation? 🤔 

I've used `formatMessage` off the imperative formatting API before to translate in a hard-to-wrap place but other than that not for a one-off translation that doesn't affect other formatted messages.

**Comment by chovy** [comment]
Can you provide an example? We have strings all over the front-end and not always doable to translate via a component. I would like to call formatNumber, formatDate, etc. as a function that returns the translated strings for specific cases where the string gets passed as a property to another component.

**Comment by chovy** [comment]
`<Foo title={formatMessage({ id: 'foo' })} />`

**Comment by clearlyTHUYDOAN** [comment]
You'll have to import `injectIntl` from `react-intl` and wrap the component _(that's trying to use the function)_ with it, AFAIK 🤓  @chovy 

Doing this, you'll get access to the informative formatting API via the wrapped component's `props`.

A sample case for this would be translating the value of the alt attribute on an `img` tag.

You can define your default message like this and make sure there's a corresponding translation.

```javascript
import { defineMessages, injectIntl };

const img = defineMessages({
    alt: {
        id: "test.alt",
        description: "testing translating things that can't be wrapped",
        defaultMessage: "a super cool logo"
    }
})
...
```

And then apply it like this:

```javascript
import { defineMessages, injectIntl };
...
render(){
    return (
        <img alt={intl.formatMessage(img.alt)}/>
    )
}

export default injectIntl(Component);
```

For your case, where you're trying to pass props to another component, you can do this:

```javascript
<Foo title={intl.formatMessage(id)} />
```

Let me know if this helps! 🙏

**Comment by chovy** [comment]
I'm trying this but its not working:


```
import React from 'react';
import {injectIntl} from 'react-intl';

// Does not actually render anything visible.
// We need it to provide access to internationalization for classes
// which are not a React component
class CurrentLocale extends React.Component {
    constructor(){
        super()
        const { intl } = this.props;

        this.formatMessage = intl.formatMessage
    }

    render() {
        return false;
    }
}

injectIntl(CurrentLocale);

function intl() {
    return new CurrentLocale();
}

function formatMessage(...args) {
    return intl().formatMessage(...args);
}

function formatDate(...args) {
    return intl().formatDate(...args);
}

function formatNumber(...args) {
    return intl().formatNumber(...args);
}

const t = opts => {
        const id = opts.id
        const type = opts.type
        const values = opts.values
        let t

        switch(type){
            // case 'date':
            //     t = formatDate(id, values)
            //     break;
            //
            // case 'number':
            //     t = formatNumber(id, values)
            //     break;
            //
            case 'message':
            default:
                t = formatMessage(id, values)
        }

        return t
}

export default t
```

I want to be able to do `import t from './t'` and call `t.formatMessage(myId)`

**Comment by ghostd** [comment]
Just a guess: `return new CurrentLocale();` returns a CurrentLocale, not an enhanced CurrentLocale.
 You could try `const enhanced = injectIntl(CurrentLocale)`, then `new enhanced()`, but i'm not sure it will work, since your call seem outside of the react-intl context (handled by the IntlProvider)

Why not use the https://github.com/yahoo/intl-messageformat#how-it-works ?

**Comment by chovy** [comment]
I got it working by adding `  static contextTypes = {intl: PropTypes.object}` to the class and then passing in `this.context.intl` to my implementation.

**Comment by andrewzjl** [comment]
why not put it as an API to provide the quick getter?
I have the same problem that I want to use the formattedMessage in redux-saga.

**Comment by andrewzjl** [comment]
Updated based on @chovy 's code. I fixed the context issues. 
```
import React from 'react'
import { injectIntl } from 'react-intl'

// Does not actually render anything visible.
// We need it to provide access to internationalization for classes
// which are not a React component
class LocalizeComponent extends React.Component {
  static __singletonRef = React.createRef
  static getInstance () {
    return LocalizeComponent.__singletonRef
  }

   constructor () {
    super()
    LocalizeComponent.__singletonRef = this
  }

   formatMessage (...args) {
    const { intl } = this.props
    return intl.formatMessage(...args)
  }
  render () {
    return false
  }
}

 export const IntlReact = injectIntl(LocalizeComponent)

 export default (...args) => {
  return LocalizeComponent.getInstance().formatMessage(...args)
}
```
Then put the component in your app
```
<IntlProvider ...>
     <React.Fragment> 
       <IntlReact />  
        <App />	                
      </React.Fragment>  
...
```

**Comment by WebKieth** [comment]
@andrewzjl LocalizeComponent into export default isnt called. Your code doesnt work

**Comment by WebKieth** [comment]
Why this issue is closed? 
Anybody find solution? I think not. I fuck this issue more than three hours.
Guys, your API is terrible peace of shit.

**Comment by andrewzjl** [comment]
@WebKieth , what do you mean 'export default' isn't called?
The exported IntelReact is used to integrate to the visual tree, and default is as the utility method for other method not in React Component.
i.e.

```
import getLocalizedString from '../Localization/getLocalizedString';   // the path to the class

const printLocalizedMessageInConsole = ()=>{
const errorMsg = getLocalizedString({ id: 'Error.getAsyncApiBroken' });
console.error(errorMsg);
}

```
