### ISSUE TITLE
React intl showing keys instead of string values in Edge

### ISSUE THREAD

**Issue by falvariza-brightplan** [yahoo/react-intl#1061]
### BUG REPORT

I started testing my app in Edge and found out that react intl is showing the keys to string values, instead of the actual strings. It's happening all across my app.
I have to point out that I tested in a different computer with an older Edge version and it did work fine.
Having no problems in other browsers / OS.

### Environment

| react-intl | 2.4.0 |
| Windows 10 Home | Fall Creators Update | 1709 |
| Edge | 41.16299.15.0 |

**Comment by ghostd** [comment]
Do you have a small project to reproduct?

**Comment by okovpashko** [comment]
@falvariza-brightplan it's hard to make any suggestion without minimal example. react-intl works file for thousands of projects and the possible reasons for your issue are invalid configuration or usage.

**Comment by Marcsimm** [comment]
I am having the same problem in my web application om iOS 9. I have tested my application on IOS 10 and 11 is it works and the strings are displayed correctly. iOS 9 this is showing

![screen shot 2018-09-18 at 11 22 05](https://user-images.githubusercontent.com/5435048/45677864-88f1aa00-bb35-11e8-900f-aa7573a3060a.png)

jus the key is showing and iam not getting any errors in the console

Environment
| react-intl | 2.4.0 |
iOS 9
Safari 9

**Comment by redonkulus** [comment]
@Marcsimm as others suggested, if you could create a simple example it would help us debug the issue. Thanks!

**Comment by Marcsimm** [comment]
I found the problem with safari. It seems that Safari 9 does not have support for the Internationalization API https://caniuse.com/#search=intl so I simply have to tell users to upgrade their safari version to 10 or more.

**Comment by redonkulus** [comment]
Its mentioned in the readme that you need to polyfill for browsers that do not support it: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

**Comment by Marcsimm** [comment]
a polyfill won't help much when the API is not even supported on some browsers

**Comment by redonkulus** [comment]
@Marcsimm I'm confused, the purpose of the polyfill is to add supports for browsers that do not have it. So for Safari 9, the polyfill would add the `intl` API. Which API were you referring to?

**Comment by redonkulus** [comment]
No problem, happy to help
