### ISSUE TITLE
Symbols/Accents not showing correctly for Spanish (locale ES)

### ISSUE THREAD

**Issue by obedparla** [yahoo/react-intl#1063]
This can't be a bug as I'm sure someone would have found it by now, however I can't seem to find what's causing it.

In Spanish the symbols are not showing correctly. For example the word "Móvil" shows as "M?vil". (see screenshot). I'm supporting several languages (en, fi, sv, dk, es and others) and this issue is not happening on any but in Spanish only. I added several of these letters with accents in other languages such as Finnish and they show as expected (see screenshot 2). Note also in screenshot 1 that text that is not directly translated with react-intl is being displayed correctly, so it's not an encoding issue within the site.

I'm not doing anything particular with Spanish. I'm using the 'es' locale and sending it to react-intl the same way as for all other languages. My file es.json is correctly translated and I even tried adding new letters with symbols myself to see if maybe the translator added strange unicode, but that's not the case, the same letter É works fine in Finnish but shows as "?" in Spanish.

Any idea why this could be happening? I'm not sure how reproducible this is.

(1)
[![Screenshot from Gyazo](https://gyazo.com/2a5a5d2d9bbe0b6fbc4b2a9b90e8c259/raw)](https://gyazo.com/2a5a5d2d9bbe0b6fbc4b2a9b90e8c259)

(2)
[![Screenshot from Gyazo](https://gyazo.com/edfce566603edd4e29ef1374f504db69/raw)](https://gyazo.com/edfce566603edd4e29ef1374f504db69)

**Comment by mayanksaxena** [comment]
I am also facing the same issue for Nederlands language translation.

**Comment by ghostd** [comment]
I have no other ideas than:
* check the character with a hexadecial editor (and compare with the UTF-8 table) (even you already checked that)
* the font does not support this character (that'd be weird... but that my last idea for the moment)

**Comment by mayanksaxena** [comment]
Got the issue, in my json file encoding was different if i update it to UTF-8 from my text editor it started working.

**Comment by obedparla** [comment]
@ghostd checked both, I supported 7 languages or  so, and the font (Lato) def. supports those chars. 
@mayanksaxena what do you mean? Your .json file was encoded differently than the other json files? Or you only support 1 lang? Funny thing is all my json files are a copy of the EN one. But I'll check this

**Comment by mayanksaxena** [comment]
@obedparla yeah my JSON file was encoded in windows format or something like thag. I have changed it to utf8 and it startrd working.

**Comment by obedparla** [comment]
Thanks @mayanksaxena it was due to the same issue, for some reason the json file had the wrong encoding, even though it was a copy of the original one. Re-creating it and pasting the text (with no styling, simple copy) fixed it.
