### ISSUE TITLE
How to avoid defineMessages declaration

### ISSUE THREAD

**Issue by kud** [yahoo/react-intl#1067]
Sometimes I can't use `<FormattedMessage />` as the component I use waits for a string and not a react component.

So I use intl.

However, when I use it, I have to make this:

```
const messages = defineMessages({
  searchFilterReset: {
    id: "search.filter.reset",
  },

  searchFilterSeeMore: {
    id: "search.filter.seeMore",
  },
  searchFilterSeeLess: {
    id: "search.filter.seeLess",
  },
  searchFilterSeeAll: {
    id: "search.filter.seeAll",
  },

  searchFilterTitleDate: {
    id: "search.filter.title.date",
  },

  searchFilterTitleDocumentType: {
    id: "search.filter.title.documentType",
  },

  searchFilterTitleBill: {
    id: "search.filter.title.bill",
  },

  searchFilterTitleFate: {
    id: "search.filter.title.fate",
  },

  searchFilterTitleCommittee: {
    id: "search.filter.title.committee",
  },
})
```

it's rather boring, and always the same:

- Taking the key
- Use it as id
- And set as object attribute of the object given to defineMessages the same sentence but with lowerCase.

I'd like to be able to do something like:

```
intl.formatMessage(defineMessages('search.filter.title.committee'))
```

or something like this.

Is it possible?

**Comment by kud** [comment]
Okay, you can do: 

` intl.formatMessage({ id: 'search.filter.reset' })`

https://github.com/yahoo/react-intl/wiki/API#formatmessage

Thank you.

**Comment by lauterry** [comment]
Please close this issue
