### ISSUE TITLE
Feature: Add event props on Components API

### ISSUE THREAD

**Issue by Robertmw** [yahoo/react-intl#1071]
Hello,

I would like to propose you to add/allow the events props on Components API like `<FormattedMessage>`
and `<FormattedHTMLMessage>`. 

I know it's easy to wrap this in another element but if I only need the `<span>` produced by `<FormattedMessage>` it will be nice to be able to send an event like **onClick** to it without wrapping it in another `<span>`.

**Comment by ghostd** [comment]
Maybe you can use the render function of [FormattedMessage](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage), see the example named "function as the child"

**Comment by johanneslumpe** [comment]
@Robertmw what @ghostd said is spot on. In this case you could easily wrap `FormattedMessage` in another component which accepts click handlers which you then set on the element returned from the child function.

```js
const FormattedMessageWithHandlers = ({ onClick, ...rest }) =>
  <FormattedMessage {...rest}>
    {message => <span onClick={onClick}>{message}</span>}
  </FormattedMessage>
```

**Comment by Robertmw** [comment]
Yep, seems legit. Thank you!

**Comment by wtkaczyk** [comment]
> @Robertmw what @ghostd said is spot on. In this case you could easily wrap `FormattedMessage` in another component which accepts click handlers which you then set on the element returned from the child function.
> 
> ```js
> const FormattedMessageWithHandlers = ({ onClick, ...rest }) =>
>   <FormattedMessage {...rest}>
>     {message => <span onClick={onClick}>{message}</span>}
>   </FormattedMessage>
> ```

Same answer, but with FormattedHTMLMessage. I find it useful. Don't be worry about dangerouslySetInnerHTML (formattedHTMLMessage is already formatted)

`        const FormattedHTMLMessageWithHandlers = ({ onClick, ...rest }) =>
            <FormattedHTMLMessage {...rest}>
                {formattedHTMLMessage => <span onClick={onClick} dangerouslySetInnerHTML={{ __html: formattedHTMLMessage }}/>}
            </FormattedHTMLMessage>;`
