### ISSUE TITLE
Incorrect FormattedNumber output when using percentages

### ISSUE THREAD

**Issue by benhodgson87** [yahoo/react-intl#1072]
### Expected behavior
`<FormattedNumber value={1234} style='percent' />`
should return a value of `1234%`

`<FormattedNumber value={12.34} style='percent' />`
should return a value of `12.34%`

### Current behavior
Setting `style='percent'` seems to be putting a decimal one digit too far to the left, as well as using an incorrect decimal (`en` should use a decimal point, not a comma); see below rendered results from React Devtools:

<img width="334" alt="screenshot 2017-12-07 18 14 47" src="https://user-images.githubusercontent.com/189707/33731305-97043ebe-db7a-11e7-8d69-ffa5ae7192ce.png">

<img width="343" alt="screenshot 2017-12-07 18 09 23" src="https://user-images.githubusercontent.com/189707/33731287-8b94a5be-db7a-11e7-8456-1e71cf9aad60.png">

Output is same regardless of whether provided value is a string or int.

Above examples are with the locale set to `en`. Same issue occurs - just with different decimal formatting - when set to other locales.

### Environment
Occurs in both Chrome & Firefox on OS X 10.13

"react": "^16.1.1",
"react-intl": "^2.4.0"

$ node -v && npm -v
v8.9.1
5.5.1

**Comment by neha-ot** [comment]
Hey @benhodgson87 I am facing similar issue. Can you please tell me how did you fix it? Thanks

**Comment by benhodgson87** [comment]
@neha-ot The number needs to be divided by 100. Taking the above two examples I had:

```jsx
<FormattedNumber
  value={1234 / 100}
  style='percent'
/>
// outputs: 1,234%

<FormattedNumber
  value={12.34 / 100}
  maximumFractionDigits={2}
  style="percent"
/>
// outputs: 12.34%
```

**Comment by markfswe** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/49815452/165429690-5b998593-1ff7-457a-97e8-76c9c402a28d.png">

Why `{value, number, ::percent}` applies `scale/100` by default?
