### ISSUE TITLE
withRef only work before React 16

### ISSUE THREAD

**Issue by ealvarezk** [yahoo/react-intl#1078]
BUG REPORT 
### Expected behavior
getWrappedInstance should return the WrappedInstance ref

### Current behavior
getWrappedInstance is not returning the WrappedInstance ref

### Step to reproduce for BUG REPORT
use injectIntl(..., { withRef: true });
### Your Environment
React 16

The problem is related that you are using a deprecated way of setting refs.
To fix it you should change in injectl.js:
-at line 52 change to `ref={withRef ? (wrappedInstance) => { this.wrappedInstance= wrappedInstance; } : null}`
-at line 44 change to `return this.wrappedInstance;`

**Comment by ghostd** [comment]
The PR already exists: #1040

**Comment by ptomasroos** [comment]
Can confirm this is a problem when running 16.6.alpha's
