### ISSUE TITLE
FormattedRelative throw an Error, I track it and it looks like a library bug.

### ISSUE THREAD

**Issue by dbyzero** [yahoo/react-intl#108]
There is my code :

    var React = require('react');
    var ReactIntl = require('react-intl');
    var FormattedDate = ReactIntl.FormattedDate;
    var FormattedRelative = ReactIntl.FormattedRelative;
    var _ = require("lodash");

    var testDate = React.createClass({
        mixins: [React.addons.PureRenderMixin],

        render: function () {

            <div>
                <FormattedRelative value={new Date().toDateString()}/>
            </div>
        }
    });

    module.exports = testDate;

The error is at node_modules/intl-relativeformat/lib/core.js:232 on this row :

    locales = (locales || []).concat(MessageFormat.defaultLocale);

It look like `function MessageFormat(message, locales, formats) {` has wrong params given. Indeed message = 'en-us' , locales is an wempty object and formats are ok.

The error code is : `Uncaught TypeError: undefined is not a function`

FormattedDate and FormattedNumber work well.

**Comment by dbyzero** [comment]
The error is at core.js on this row :

    locales = (locales || []).concat(MessageFormat.defaultLocale);

It look like `function MessageFormat(message, locales, formats) {` has wrong params given. Indeed message = 'en-us' , locales is an wempty object and formats are ok.

The error code is : `Uncaught TypeError: undefined is not a function`

FormattedDate and FormattedNumber work well.

**Comment by dbyzero** [comment]
I use the last relaese (v1.2.0)

**Comment by dbyzero** [comment]
Fint the issue here : http://stackoverflow.com/questions/29223392/react-intl-and-react-router-formatrelative-problems

**Comment by ericf** [comment]
Yeah, this is the Browserify issue where it doesn't bundle things correctly. Glad you figured it out!

**Comment by ericf** [comment]
Dup of #84
