### ISSUE TITLE
How to export React class getter with injectIntl?

### ISSUE THREAD

**Issue by pbalan** [yahoo/react-intl#1084]
### BUG REPORT

How to export React class getter with injectIntl?

### Expected behavior
Translated text.

### Current behavior
Nothing

### Step to reproduce for BUG REPORT
```
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { injectIntl, intlShape } from 'react-intl';

class MyClass extends Component {
  constructor(props) {
    super(props);
  }
  get pageTitle() {
    const { intl } = this.props;
    return intl.formatMessage({id: 'messages_my_class_page_title'});
  }
  render() {
    return (
      <div>
        Dummy content
      </div>
    );
  }
}
MyClass.propTypes = {
  intl: intlShape.isRequired
}

export default injectIntl(MyClass);
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 0.14.9 |
| `npm --version` | 5.5.1 |
| `node --version` | 8.9.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

| Browser | Version |
| --- | --- |
| Chrome | 61.0.3163.71 |

**Comment by pbalan** [comment]
I can fix this using <FormattedMessage id="messages_my_class_page_title"/>
**But I want to know how to fix it using injectIntl way.**

**Comment by asrytis** [comment]
Use `withRef: true` as per documentation:
https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#dom-rendering

**Comment by pbalan** [comment]
Thanks @asrytis. That fixed my issue.
