### ISSUE TITLE
Maybe capture error & warn instead of throw?

### ISSUE THREAD

**Issue by longlho** [yahoo/react-intl#109]
Hi @ericf ,

Quick question/suggestion: on this [line](https://github.com/yahoo/react-intl/blob/master/src/mixin.js#L26) react-intl actually `throw`s error for invalid input. Is this by design? If yes any chance we can be a bit more forgiving and `warn` instead of `throw`? The reason is that this gets bubbled up and croak the server/create unexpected behavior on client and with the React stack trace bloat it's incredibly difficult to trace it.

Thanks!

**Comment by ericf** [comment]
Yes this is intentional, it's an early throw since the underlying `Intl.DateTimeFormat()` that will be called will throw if the value is not finite.

There's other discussions that have brought up error/warn handling — so we're thinking about it.

**Comment by longlho** [comment]
@ericf possible to support a `default`/`fallback` prop of some sort? I'm happy to push a PR too if it's cool.

**Comment by ericf** [comment]
I don't understand what you're proposing… can you explain in more detail?

**Comment by longlho** [comment]
ping @ericf :)

**Comment by ericf** [comment]
What are the actual real-world use cases where you're seeing `<FormattedDate>` throw? Also, how do you deal with these sorts of exceptions for other data that you try to render in your React components that might be `null` or something?

**Comment by longlho** [comment]
The real world use case is rather simple: Say I fetch some data from the server that has a field called `date`, which subsequently gets rendered out via `<FormattedDate value={date} />`. Now if `date` is a correct representation of a `Date` of some sort, everything's happy.

However, if `date` is `undefined`, `new Date(undefined) per this [line](https://github.com/yahoo/react-intl/blob/master/src/mixin.js#L68) will result in an `Invalid Date`, which throws at this [line](https://github.com/yahoo/react-intl/blob/master/src/mixin.js#L25) and on the server side, the process got shut down :(

For other React components, if given an invalid data type it would just render nothing (`null`/`undefined`) so since the `throw` was by design, supporting a `default` prop in `FormattedDate` would be a more forgiving opt-in alternative for this behavior.

**Comment by ericf** [comment]
<FormattedDate> uses `React.PropTypes.any.isRequired` so you should be seeing warns from React. My main worry is about silent failures, but I see you're point about rendering `null` being a reasonable thing to do in this case.

**Comment by ericf** [comment]
See: #162
