### ISSUE TITLE
Dynamically passing message id's?

### ISSUE THREAD

**Issue by clouditinerary** [yahoo/react-intl#1092]
Hello - I would like to pass a message id dynamically depending on the context. E.g. 

`<FormattedHTMLMessage id={`${this.props.some.parameter}`}/>
`

However, this simple requirement doesn't work. It evaluates the string, but does not pick up the message. If I use this with a static string every works fine... Please advise - I have looked everywhere I can think of for answers including in the "issues" section, but unless I missed something, there's nothing.

**Comment by clouditinerary** [comment]
dumb mistake on - this works beautifully..  :)

**Comment by VeselinKirevJisc** [comment]
Do you ind sharing how you solved this?
