### ISSUE TITLE
How can I use .po formatted file instead of json

### ISSUE THREAD

**Issue by munkhorgil** [yahoo/react-intl#1100]
I am trying to use react-intl with transifex. How can I use **.po** formatted file. Maybe something like this
```
import translation from './translation' # translation.po

const messages = defineMessages({
    msgid: 'someid',
    msgstring: 'default message'
})

formatMessage(messages);
```

**Comment by okovpashko** [comment]
@munkhorgil it's not necessary to use `defineMessages` if you already have translations file as it only instructs babel plugin to extract messages to a separate JSON file.
If you use webpack po-loader and it provides key-value pairs with message ids and text you can import **.po** file at the top level of your app and provide the result to `IntlProvider`:
```javascript
import localeMessages from './translation' # translation.po

ReactDOM.render(
    <IntlProvider
        locale={usersLocale}
        messages={localeMessages}
    >
        <App/>
    </IntlProvider>,
    document.getElementById('container')
);
```

**Comment by natterstefan** [comment]
Hi @okovpashko, thanks for the comment. Do you have a shareable webpack 4 config ready [using po-loader](https://www.npmjs.com/package/po-loader) and importing a *.po file? I can't get it to work :/ Would be awesome. Thanks.

**Comment by okovpashko** [comment]
@natterstefan unfortunately no, I don't have one. But I think there shouldn't be any issues with integrating it.
If you experience any difficulties with it feel free to describe them and I will try to help.

**Comment by natterstefan** [comment]
@okovpashko Thank you, will do.
