### ISSUE TITLE
Convert Formatted message to custom text with time

### ISSUE THREAD

**Issue by palaniichukdmytro** [yahoo/react-intl#1105]
I try to convert to simple object to date with the custom message.

### Expected behavior

I pass to FormattedMessage an object with value ({days: 1, hours: 2, minutes: 01, seconds: 48,}) and return `3d. 02:01:48`
### Current behavior

Actyally I can do it with message syntax  but maybe another way to do this.

`<FormattedMessage id='history.responseTime' values={{days: 1, hours: 2, minutes: 01, seconds: 48,}} />`

'history.responseTime': `'{days, plural, =0 {} one {{days}d.} other {{days}d.}} {hours, plural, =0 {} one {0{hours}:} two {0{hours}:} =3 {0{hours}:} =4 {0{hours}:} =5 {0{hours}:} =6 {0{hours}:} =7 {0{hours}:} =8 {0{hours}:} =9 {0{hours}:} other {{hours}:}}{minutes, plural, =0 {} one {0{minutes}:} two {0{minutes}:} =3 {0{minutes}:} =4 {0{minutes}:} =5 {0{minutes}:} =6 {0{minutes}:} =7 {0{minutes}:} =8 {0{minutes}:} =9 {0{minutes}:} other {{minutes}:}}{seconds, plural, =0 {} one {0{seconds}} two {0{seconds}} =3 {0{seconds}} =4 {0{seconds}} =5 {0{seconds}} =6 {0{seconds}} =7 {0{seconds}} =8 {0{seconds}:} =9 {0{seconds}}  other {{seconds}}}',`
### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.2.3|
| `npm ls react` | 16.2.0|
| `npm --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | chrome 64|
| --- | --- |
| NAME | VERSION |

**Comment by papasmile** [comment]
Hi, @palaniichukdmytro , I don't understand whether your formatting is supposed to support multiple languages... for example, you are using 'd.' in your output which is not global by any means.

You can get a lot more date format flexibility with a specialized library like moment.js (http://momentjs.com/) which also has its own internationalization (http://momentjs.com/docs/#/i18n/).

**Comment by palaniichukdmytro** [comment]
Now there is supported only en, but I found how to simplify it  : 
```
<FormattedMessage id='history.responseTime' values={{
                                days : responseTime.days,
                                hours: responseTime.hours.toString().padStart(2, '0'),
                                minutes: responseTime.minutes.toString().padStart(2, '0'),
                                seconds: responseTime.seconds.toString().padStart(2, '0'),
                            }}
                            />
```

`        'history.responseTime': '{days}d.  {hours}:{minutes}:{seconds}',
`

**Comment by papasmile** [comment]
Sure.  I suppose now you'd just need to translate that 'd' in your translations :)

Do you need anything else from this issue or can you close it?
