### ISSUE TITLE
Translations management

### ISSUE THREAD

**Issue by dmitry** [yahoo/react-intl#112]
How do you managing translations for the medium sized projects with more than 10 locales?

I know many services that are providing the management of the translations, but none of them are supporting `intl` format yet.

- http://docs.weblate.org/en/latest/formats.html
- https://webtranslateit.com/en/docs/file_formats/
- http://docs.transifex.com/formats/index
- http://docs.phraseapp.com/guides/formats/
- https://docs.smartling.com/display/docs/Supported+File+Types

More or less it's related to the https://github.com/yahoo/react-intl/issues/89

**Comment by ericf** [comment]
Are you asking about the file format, or the ICU Message syntax, or both?

**Comment by dmitry** [comment]
@ericf short question is how to manage translations on a medium size project?

**Comment by ericf** [comment]
That doesn't provide me with any more details about what you're asking. Are you wondering how to integrate with a translation service?

**Comment by dmitry** [comment]
What is the best practice to translate locales if there are more than 3 languages? 

For example, in rails projects I've used webtranslateit and phraseapp to manage translations. It's possible to push/pull translations from the service; services provides good interface for translators; with cli program it's very easy to import/export translation files. 
I can't imagine how to use translations without such service, if site at least have a 3 languages (because in this case you will need to find out a native speaker for the translations) or number of keys for translation are more than 500. 

Even if no proprietary services are yet exists, may be there are an open source software, than helps to manage translations?

**Comment by ericf** [comment]
> Even if no proprietary services are yet exists, may be there are an open source software, than helps to manage translations?

I am not sure, I haven't personally used any.

**Comment by g-p-g** [comment]
I've been experimenting with storing the locale files as JSON, which then allows you to use several different services. For instance, you can import it in crowdin (no association with it) and manage translations in there. Is that what you're looking for?

**Comment by LorbusChris** [comment]
an import/export feature for a format like XLIFF would be nice here! 

ICU seems to have a native Java converter http://icu-project.org/download/xliff2icuconverter.html

see also https://github.com/yahoo/intl-messageformat/issues/106

**Comment by dmitry** [comment]
@g-p-g crowdin (https://crowdin.com/page/tour/supported-formats) supports only simple JSON file, which is simply plain labels without pluralization and placeholders. Intl format have very complex placeholder mechanics. In my projects I'm using: https://github.com/fnando/i18n-js because it's much simplier and supported but most of the SaaS translation management tools.

**Comment by g-p-g** [comment]
@dmitry can you clarify what you mean? In the JSON file you will have keys mapping to text, where the text will be in ICU format which is free to contain whatever ICU supports. It seems this other tool you're mentioning uses YAML, but besides that can you clarify why it's simpler to use it? A quick look doesn't show how it simplifies managing the translations, which crowdin/oneskyapp/etc are about. Writing/generating the base translatable file was never an issue for me/the team, but managing translations is. Does that tool help in managing translations or generating a translatable file?

If it's only because of YAML instead of raw text, then sure that's fine.

**Comment by LorbusChris** [comment]
Maybe have a look at http://l10ns.org/ also. Works with ICU

**Comment by shawnhooper** [comment]
@dmitry I was trying to figure out how to get our content people and translators to work with the JSON files, and decided to write a quick web app to allow them to work with the different locales.  It's very rough, but does the trick.  

http://www.shawnhooper.ca/2016/02/react-intl-editor/

**Comment by ericf** [comment]
I think we should add techniques people are using to the [Wiki](https://github.com/yahoo/react-intl/wiki). If anyone here has more details on how they are interfacing with translation systems, please feel free to start a Wiki page!

@shawnhooper Cool that you've made this tool!

**Comment by jardakotesovec** [comment]
Wondering if anyone came across translation management tool that play nicely with react-intl format?

**Comment by M-ZubairAhmed** [comment]
> Wondering if anyone came across translation management tool that play nicely with react-intl format?

We use weblate with formatjs, works amazing

**Comment by b1rdex** [comment]
> We use weblate with formatjs, works amazing

Could you please share some details how to integrate formatjs with weblate? What format do you use from the list of supported (https://docs.weblate.org/en/weblate-5.0/formats.html) ?

**Comment by b1rdex** [comment]
> We use weblate with formatjs, works amazing

@M-ZubairAhmed Could you please share some details how to integrate formatjs with weblate? What format do you use from the list of supported (https://docs.weblate.org/en/weblate-5.0/formats.html) ?

**Comment by M-ZubairAhmed** [comment]
@b1rdex yes sure, our project is open source, you can take a look at https://translate.mattermost.com/
