### ISSUE TITLE
documenting what an array of multiple locales actually means

### ISSUE THREAD

**Issue by faassen** [yahoo/react-intl#113]
The mixin APIs allow you to pass in one locale or an array of locales. But what does FormatJS actually do when it gets more than one locale in an array? It doesn't appear to be documented anywhere, and I think it should.

The only thing I can think of that it could do is that if a locale in the list if not supported at all it will skip to the next one. Is this correct? Is the list of locales supported different for different things, i.e. things directly supported by Intl versus things supported only through FormatJS?

**Comment by slorber** [comment]
@faassen you may take a look here:
https://github.com/yahoo/intl-messageformat/issues/100

**Comment by ericf** [comment]
There's plans to improve this. tl;dr `locales` is plural to map to the underlying `locales` argument that the `Intl.*` constructors expect/support.
