### ISSUE TITLE
 Invariant Violation: [React Intl] An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by brendonco** [yahoo/react-intl#1134]
i'm getting an issue when testing using mountWithIntl method.

Invariant Violation: [React Intl] An `id` must be provided to format a message.

```
intl.formatMessage({
         |                         ^
      35 |         id: some.object.description,
      36 |         defaultMessage: some.object.description,
      37 |       }),
 at invariant (node_modules/invariant/invariant.js:42:15)
      at formatMessage (node_modules/react-intl/lib/index.js:677:3)
```

**Comment by papasmile** [comment]
Hi, @brendonco , is that your actual code?  `id` and `defaultMessage` should be strings, but they look like variables in your code.  Maybe `some.object == undefined`?

**Comment by brendonco** [comment]
Yes, you can close this since the object pass into formatMessage method doesnt have the id when deconstruct the object.
