### ISSUE TITLE
<FormattedRelative> is rendering english on the client side

### ISSUE THREAD

**Issue by geekyme** [yahoo/react-intl#114]
I am using a FormattedRelative component like this in an isomorphic app: 

<FormattedRelative value={ time_created } locales={['zh-Hant-TW']} />

I get this warning on the client side and I see my client side renders english instead of chinese. 

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 10:0.0.0.0.0.2.1.0">2 days ago</span></t
 (server) 10:0.0.0.0.0.2.1.0">前天</span></time><fig
```

**Comment by gpbl** [comment]
@geekyme are you sure the client is using the right locale?

**Comment by gpbl** [comment]
Maybe related https://github.com/yahoo/react-intl/issues/78

**Comment by geekyme** [comment]
issue is fixed now. All we need to do is to load up the appropriate locale files  on the client side before rendering the react-intl components - https://github.com/yahoo/react-intl/blob/master/dist/locale-data/zh.js

thanks to @gpbl for suggesting.
