### ISSUE TITLE
Support intl.formatMessage possible to be a string property?

### ISSUE THREAD

**Issue by SeamusY** [yahoo/react-intl#1142]
### Support
Is it possible to have a intl.formatMessage({id:'name of property'}) to be given as a property? instead of asking for a value?

### Expected behaviour
`<DropDownBox
                                    select={{
                                                  intl.formatMessage({id:"property value 1"}): defined value,
                                                  intl.formatMessage({id:"property value 1"}): defined value 2,
                                                  intl.formatMessage({id:"property value 1"}): defined value 3
                                     }}/>`

### Expect behaviour
`<some class requires 
                                    defaultColor
                                    defaultLabel
                                    select={{
                                                  "Hello": 1
                                                  "Word":2,
                                                  "Greetings": 3
                                     }}/>`

is it possible?

**Comment by papasmile** [comment]
Hi, @SeamusY, sorry don't really understand if you want a feature in `DropDownBox` or `formatMessage`... can you give an example of where would you define `defined value 2`?

**Comment by SeamusY** [comment]
Well the thing was that, i wanted to inject a string into the property before setting the value, since i am translating the "property string" to a different language. However, in any case when i have done inject or Format Text. It crashes the app.

**Comment by papasmile** [comment]
Still trying to get you... are you just trying to set object keys dyamically?  Using ES6 you have to use `[]` notation.  e.g.
```
<DropDownBox select={{ [intl.formatMessage({id:"property value 1"})]: defined value, [intl.formatMessage({id:"property value 1"})]: defined value 2, [intl.formatMessage({id:"property value 1"})]: defined value 3 }}/>
```
See "Computed Property Names" at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
