### ISSUE TITLE
FormattedNumber - Singapore Currency SGD10.00 >> S$10.00

### ISSUE THREAD

**Issue by kevinhylant** [yahoo/react-intl#1157]
### Expected behavior
- I'd expect that the internationally formatted currency for Singapore users read S$10.00 which is the local standard in Singapore ([see wikipedia](https://en.wikipedia.org/wiki/Singapore_dollar)) rather than SGD which is what is being returned when passing in the `sgd` currencyCode in the currency attribute (eg `<FormattedMessage currency="sgd" ...`)

### Current behavior
`FormattedMessage` returns SGD10.00

### Your Environment

| Executable | Version |
| ---: | :--- |
| `react-intl` | 2.4.0 |
| `react` | 16.2.0 |
| `npm --version` | 5.6.0 |
| `node --version` | 8.9.3 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by SavageWilliam** [comment]
Hey @kevinhylant what did you do to resolve this? Did you have to load specific localeData?

**Comment by arvinsim** [comment]
Still have the same issue

**Comment by longlho** [comment]
what's the locale that you set?
