### ISSUE TITLE
Is this project still being actively developed and maintained?

### ISSUE THREAD

**Issue by PutziSan** [yahoo/react-intl#1160]
It seems that the library is no longer being developed? [This comment](https://github.com/yahoo/react-intl/pull/612#issuecomment-321514487) even says it and for almost a year no one has contradicted? Moreover, [regular commits](https://github.com/yahoo/react-intl/commits/master) also seem to have been absent since September 2017.

Could one of the maintainers give a statement on whether and how this library will be maintained? 

If the development has been shut down, it would be useful to mention this in the documentation so that developers can adapt to it and may look for another option.

**Comment by papasmile** [comment]
Please see: https://github.com/yahoo/react-intl/pull/1141#issuecomment-403563027

**Comment by PutziSan** [comment]
Okay, in principle that means for me that the project will not be developed further.

I still think that a note should be attached in the README indicating that there are currently no active maintainers and possibly an e-mail address for someone who dares to take over the project.

**Comment by paulodiovani** [comment]
What about this fork? https://github.com/DragonRaider5/react-intl/tree/feature/new-context-api

**Comment by papasmile** [comment]
@paulodiovani Yea, we're making a small effort there to address https://github.com/yahoo/react-intl/issues/1106 specifically.  Contributions welcome.

**Comment by sourabh2k15** [comment]
I am interested in maintaining this project further. I recently interned @ Yahoo and came to learn about this project. Many people have found it useful in the past and thus it is of value to fix issues, review pending PRs and continue working on this project.

**Comment by tricoder42** [comment]
If anyone interested, I'm working on an alternative i18n library [jsLingui](https://github.com/lingui/js-lingui). The low-level API is very similar to react-intl (I migrated my projects more than a year ago). So far there's an [article](https://lingui.js.org/misc/react-intl.html) comparing both libs, but I could probably write a migration guide if enough people were interested.

**Comment by zbraniecki** [comment]
Hi all! My team at Mozilla is working on a library that aims to supersede `react-intl`. Similarly to @tricoder42 we build for the modern Web, but in contrast to `jsLingui` we also developed a foundational layer in place of `MessageFormat` that `react-intl` and `jsLingui` uses.

[Project Fluent](https://projectfluent.org/) is the result of 10+ years of experience of developing multilingual projects on the Web, and shortcomings of the 20 years old MessageFormat. We [documented the design choices and decisions](https://github.com/projectfluent/fluent/wiki) for the low-level data model and file format, and [differences between Fluent and MessageFormat](https://github.com/projectfluent/fluent/wiki/Fluent-and-ICU-MessageFormat).

On top of that, we are developing a set of libraries for [Vanilla DOM](https://github.com/projectfluent/fluent.js/tree/master/fluent-dom), [Python](https://github.com/projectfluent/python-fluent), [Rust](https://github.com/projectfluent/fluent-rs) and, what's most important for you, [fluent-react](https://github.com/projectfluent/fluent.js/tree/master/fluent-react).

Designing and developing a new localization system is a major effort that took us many years to get right, but now we're on the last stretch with all new Mozilla projects, especially react-based, using it in production and the system itself getting last tuneups before 1.0 release.

We're also developing low-level tooling in form of parser/ast/serializer, and web-based localization tool called [Pontoon](https://pontoon.mozilla.org/).

We'd love to hear you feedback [on the system itself](https://github.com/projectfluent/fluent/wiki), [RFC for 0.7](https://discourse.mozilla.org/c/fluent), and [fluent-react](https://github.com/projectfluent/fluent.js/tree/master/fluent-react) in particular.

**Comment by redonkulus** [comment]
@sourabh2k15 that sounds good to me. Please feel free to start reviewing PR's and issues. I can give you commit access to the repo as well.

I think the key part of maintaining is to balance the wants and needs of users, while also keeping the code base simple and light weight. We should be diligent in what gets added as any code merged becomes new code that you have to maintain forever :). 

Thank you for volunteering to help!

**Comment by jamuhl** [comment]
As an option for alternatives:

<img width="1140" alt="screen shot 2018-09-02 at 11 15 28" src="https://user-images.githubusercontent.com/977772/44954587-652b3480-aea4-11e8-9d87-f5dc2774c3ae.png">

https://github.com/i18next/react-i18next 

uses basically IntlMessageFormat for ICU: https://react.i18next.com/misc/using-with-icu-format

**Comment by bjankord** [comment]
It seems like maintenance fell off after @okuryu's last merge to master in [Dec 2017](https://github.com/yahoo/react-intl/commit/f8848df9493ded3f10c97f8dc817ca3a2f59433a), which was a 1 word typo fix. There's only been 1 commit to master since the one from @okuryu, that was from @redonkulus.

Prior to the 1 word typo fix commit, the last change was in [September 2017](https://github.com/yahoo/react-intl/commit/6d5c0f1f18b1a0ae62a0abdda59437d840aa1832), nearly a year ago.

The lack of commits on master over the last year, the amount of open PRs, the amount of logged issues that are unresolved, all these are signs the project is not maintained at a sustainable level. 

I'm not here to pass judgment, maintainer burnout is real. But I do want to give a warning to anyone who is considering using this library. If I was starting a new project, react-intl looks like the premiere solution for i18n in the react ecosystem. You'll find a lot of tutorials, it has a lot of downloads on npm, and there are a lot teams using it currently. However, if you look at the project closer, you'll discover the issues noted above.

**Comment by jamuhl** [comment]
@bjankord what i not understand that is that react-intl was not given to the community - so it would be able to take over (rights for npm, ...). Seems yahoo prefers it dying slowely - at least they should have killed it fast so some other lib eg. based on messageformat could take over.

**Comment by papasmile** [comment]
@jamuhl et all see https://github.com/yahoo/react-intl/pull/1141#issuecomment-403563027, new maintainers are being accepted!

**Comment by jamuhl** [comment]
@papasmile so hope dies last 🙏...hopefully they can make a turn...would be best.

**Comment by BenLloydPearson** [comment]
I work for Oath (Yahoo) and manage this repository. Unfortunately, we don't have internal resources to maintain this project. However, we're more than willing to hand maintainer responsibilities off to the community. If anyone here would like to take on this responsibility, please indicate so and we can work out a process to transition the responsibilities to you.

@sourabh2k15 has already volunteered to take on these responsibilities, but I'm sure additional participants would be welcome. @jamuhl, @PutziSan if you, or someone you know would be good candidates for this, let's talk. We recognize this is an important project to a lot of people and we'd like to do what we can to keep it alive.

**Comment by jamuhl** [comment]
@BenLloydPearson i guess we (@adrai and me @jamuhl) could take over and help building a community around react-intl / formatjs. There are two points i need to mention. I already lead the OSS i18n project https://i18next.com and both of us are founders of https://locize.com a continuous localization service. So we both got the needed knowhow plus are able to add the view of developers as of translators into the project. With locize we're also able to add a first financial contribution into the  upcoming work (we already support other projects like vue-i18n).

Our plan would be:
- setting up a council team
- search for community members willing to contribute
- plan for the future of react-intl / format js (council)
- setting up an open collective to financially aid the members willing to contribute (we personally would not take cash from the collective as we already get financed by locize)
- Change license to MIT or similar

But this also means Oath (Yahoo) needs to be willing to pass the project into new hands.

**Comment by BenLloydPearson** [comment]
Transferring control of all of formatjs to the community is a much bigger discussion than this issue, we have people internally who maintain npm and fix some issues with newer versions of React, etc., so unless there is a compelling reason to transfer everything to the community we're happy keeping those running. If there are other projects in the formatjs ecosystem that could use better community enablement, please let me know and I'll do what I can to help.

With that said, we welcome contributions to add improvements and bug fixes, and if people want to step up to close PR's we can grant them access. I've granted @sourabh2k15 write access to this repo so there's someone who can start work on merging outstanding PR's. I'm open to recommendations for others to invite.

**Comment by BenLloydPearson** [comment]
Thank you everyone for getting this discussion going. I'm going to close this ticket now since it is technically being maintained now. Feel free to re-open if this changes.

**Comment by indexzero** [comment]
> Thanks for all the cat herding @BenLloydPearson – the OSS maintainer struggle is real. 

Welcome new folks! We use `react-intl` @ GoDaddy and a small group has expressed a willingness to drive delivery for migrating to the `react@16` context API. Would this be useful? 

Seems like https://github.com/yahoo/react-intl/issues/1106 is has some traction, but needs help to drive it across the line. 

cc/ @redonkulus @sourabh2k15

**Comment by redonkulus** [comment]
@indexzero We will not have any resources to work on this from our end. So it makes sense to work with @DragonRaider5 and others to work on the existing PR (#1106) and make sure tests pass, documentation is updated and we do not break existing users (assuming we do not have to break the existing API).

**Comment by DragonRaider5** [comment]
@indexzero My PR for the new context API is ready to go. I just need somebody to fix the build process... See [here](https://github.com/DragonRaider5/react-intl/tree/feature/new-context-api) and my last post on #1106 !
