### ISSUE TITLE
Use React.Fragments to remove the requirement for injecting react-intl into components which need string-only translations

### ISSUE THREAD

**Issue by EliRobinson** [yahoo/react-intl#1169]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
Feature Request

### Expected behavior
With the implementation of `React.Fragments`, using the React.Intl components should be possible even in scenarios where you cannot use elements. Such as `placeholder` or `aria-labeledby`.

### Current behavior
In order to add localized text to placeholder, you must inject ReactIntl into the component, and use the `intl` prop.

### Proposal
With an attribute: (string for example)
```
<input
  placeholder={<FormattedMessage id="foo.bar.baz" string={true}/>}
/>
```

Instead it trying to return `<span>TextNode</span>`, it should return `<>TextNode</>`, which shouldn't count as an "element".

**Comment by lexanth** [comment]
Could be achieved by #1168 with `tagName` (or other prop) set to Fragment.

**Comment by EliRobinson** [comment]
Apparently `<FormattedMessage>` still returns a react component regardless of the contents of the component. So even setting `<FormattedMessage>` to return a React.Fragment won't work for any attributes that only support String.

Sad day 😭
