### ISSUE TITLE
Document why <Formatted*> components are better than the imperative API

### ISSUE THREAD

**Issue by slorber** [yahoo/react-intl#117]
Hi,

Just wanted you to be aware that we had in Paris a ReactJS Meetup about I18n and I asked a question nobody could answer: what's the advantage of using React components for formatting instead of using directly the - maybe deprecated - mixin API `this.format()`.

I think it should be clearly documented what are the advantages of a component over an imperative API

The only thing I guess so far is maybe the possibility to inject React components as template parameters, and maybe cacheability but I'm not sure at all :)

**Comment by ericf** [comment]
This is a good idea and I can add docs about this. That said, there will be an imperative API because it's still needed for certain types of formatting; e.g., an element's prop value, like `<input placeholder={someFormattedString} />`.

A major area where the components provide value is in composition of complex messages See: https://github.com/yahoo/react-intl/blob/master/src/components/message.js

And as we gain more guidance from React on `context` and `shouldComponentUpdate()`, the components can abstract away whether or not the relatively expensive `format()` methods need to be called during a re-render.

**Comment by export-mike** [comment]
Yes I'm trying to pass in placeholder values, I'm using 2.0.0-beta-2, I've looked a the code and can't see a way to do this?

**Comment by slorber** [comment]
@export-mike 

`var placeholder = this.props.intl.formatMessage({ id: "searchBar.searchPlaceholder" });`

**Comment by export-mike** [comment]
hmmm this is really troublesome for me as this introduces bad-parent, I'm using redux and can't see a good way to have this as my global state...

**Comment by slorber** [comment]
@export-mike be part of all props is like using react context, and decorator only extracts from the context.

What is your problem with the following I don't understand?

```javascript
var React = require("react");
var ReactIntl = require("react-intl");

var SearchBar = React.createClass({
	render() {
		var placeholder = this.props.intl.formatMessage({ id: "searchBar.searchPlaceholder" });
		var inputValue = this.input();
		return (
				<input
					value={inputValue}
					onChange={this.onInputChange}
					forceVisibility={this.isValid(inputValue)}
					placeholder={placeholder}
				/>
		);
	}
});

module.exports = ReactIntl.injectIntl(SearchBar);
```

**Comment by ericf** [comment]
@export-mike are you talking about `<input placeholder="">` or passing in values to fill placeholders inside of messages? For the former, what @slorber said, for the latter:

```js
<FormattedMessage
  id="greeting"
  defaultMessage="Hello, {name}!"
  values={{
    name: 'Eric'
  }}
/>
```

**Comment by export-mike** [comment]
It's to populate a property that expects a string such as placeholder. I'm
now using injectIntl on my components but being more aware/cautious on what
components should be coupled to InjectIntl.

**Comment by ericf** [comment]
@export-mike Here are some docs on the injection API: https://github.com/yahoo/react-intl/wiki/API#injection-api

**Comment by ericf** [comment]
Put some details on "Why Component?" on the Wiki:
https://github.com/yahoo/react-intl/wiki/Components#why-components

**Comment by export-mike** [comment]
@ericf thanks for your help.
