### ISSUE TITLE
Number formatting not changing after changing locale.

### ISSUE THREAD

**Issue by shockdesign** [yahoo/react-intl#1177]
### Expected behavior
When changing to the locale on an Android device to FR or DE I expect the number formatting to change the grouping of numbers to `123 345,67` and `123.345,67` respectively.

### Current behavior
Number stays formatted as it would for EN regions `123,345.67`.

### Step to reproduce for BUG REPORT
Easiest way to replicate the bug is to use the `formatNumber` function, and switch the locale on the device. Displaying the local via `intl.locale` displays the right locale however number formatting doesn't change.

### Your Environment
Developing on OSX 10.13.6

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.5.0 |
| `npm ls react-native` | 0.55.4 |
| `npm --version` | 6.4.1 |
| `node --version` | 10.10.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

React Native so browser version is N/A.

**Comment by redonkulus** [comment]
@shockdesign I believe this has been discussed in https://github.com/yahoo/react-intl/issues/234 and https://github.com/yahoo/react-intl/issues/1097, can you take a look at those conversations?

**Comment by DragonRaider5** [comment]
Might there be something in your component tree blocking the context update (f.e. a custom shouldComponentUpdate)?

**Comment by shockdesign** [comment]
@DragonRaider5 I don't think that is an issue, especially if the locale (which I added to display) is showing correctly. Also I'm not expecting dynamic changes. I'm killing the app and running it again after changing locale.

**Comment by shockdesign** [comment]
@redonkulus Even with a hardcoded `<IntlProvider locale="fr">` the formatting is still incorrect so I don't believe it's the same as the two discussions you pointed out.

`this.props.intl.locale` gets updated however .formatNumber still doesn't change.. Feels like I need to dig deeper into `Intl.NumberFormat`

**Comment by shockdesign** [comment]
Just an update to this, it looks like even though the locale has changed, when `formatNumber` gets called and looks through it's locale data, there is only English registered to it, even though for `formatMessage` everything gets picked up properly.

**Comment by shockdesign** [comment]
Okay... looking deeper it was to do with the IntlPolyfill.

And it looks like while we were adding all the locales from `react-intl` we also needed to add the locales imported from `intl` as well to ensure the Android Polyfill worked.

Doing this seems to have solved the issue.
