### ISSUE TITLE
FormattedDate always returns 'en' locale in server side

### ISSUE THREAD

**Issue by tranvansang** [yahoo/react-intl#1179]
### Is this a BUG REPORT or FEATURE REQUEST? (choose one)
BUG REPORT

### Expected behavior
`FormattedDate` returns formatted date string in required locale (`ja`) in both server and client as
e.g. 2018年9月14日(金) 午後10:16

### Current behavior

`FormattedDate` returns correct value in client, but in server side, it returns in `'en'` locale. Thus, browser generates warning `Warning: Text content did not match. Server: "Fri, September 14, 2018, 10:16 PM" Client: "2018年9月14日(金) 午後10:16"`

And obviously, produce wrong SEO preview.

### Step to reproduce for BUG REPORT

```javascript
//import locale
import en from 'react-intl/locale-data/en'
import ja from 'react-intl/locale-data/ja'
import {addLocaleData} from 'react-intl'
addLocaleData([...ja, ...en])

import {FormattedDate, IntlProvider} from 'react-intl'
import {renderToString} from 'react-dom/server'
console.log(renderToString(
  <IntlProvider
    locale="ja">
    <FormattedDate value={new Date()}
                   weekday="short"
                   year="numeric"
                   month="long"
                   day="numeric"
                   hour="numeric"
                   minute="2-digit"
                   hour12
    />
  </IntlProvider>
))
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.6.0 |
| `npm ls react` | 16.5.0 |
| `npm --version` | VERSION |
| `yarn --version` | 1.9.4 |
| `node --version` | v10.8.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Ubuntu | 18.04 |

| Browser | Version |
| --- | --- |
| NAME | VERSION |
| Chrome | Version 69.0.3497.92 (Official Build) (64-bit) |

**Comment by Wellington475** [comment]
I encountered the same problem in FormattedNumber

**Comment by roderickhsiao** [comment]
do you need to polyfill Intl locale in node?
https://formatjs.io/guides/runtime-environments/#server

by default it shipped only English Intl in Node

**Comment by ghostd** [comment]
Did you try to install the package `full-icu` and run your app with this?
```
NODE_ICU_DATA=node_modules/full-icu node index.js
```

**Comment by tranvansang** [comment]
@Wellington475 gosh, thank you very much. I tried and it worked like a charm.

I thought that [addlocaledata](https://github.com/yahoo/react-intl/wiki/API#addlocaledata) has done that job, thus, ignore this polyfill when setting up
