### ISSUE TITLE
injectIntl() breaks enzyme .dive() function.

### ISSUE THREAD

**Issue by danielesalvatore** [yahoo/react-intl#1180]
Dear all,
first of all thank you very much for your library!

I would like to kindly ask for your support in understanding how should I test a component that uses `react-intl` and in particular the decorator `injectIntl()`.

### Desired behaviour
I would like to test a connected component that uses both `redux` and `react-intl`. My test is just a `render without error` test and you can find the code below:

``` javascript
// Confirmation/test/index.test.js

import React from 'react';
import {shallowWithIntl} from 'enzyme-react-intl';
import Component from '../index'
import {findByTestAttr, storeFactory} from '../../../../test/utils';
import {DATA_TEST_COMPONENT} from '../constants'

/**
 * @function setup
 * @param {object} state - Redux state for this setup.
 * @returns {ShallowWrapper}
 */
const setup = (state = {}) => {
    const store = storeFactory(state);
    const wrapper = shallowWithIntl(<Component store={store}/>).dive();
    console.log(wrapper.debug())
    return wrapper;
};

describe("<Confirmation/>", () => {
    test('renders without error', () => {
        const wrapper = setup();
        const component = findByTestAttr(wrapper, DATA_TEST_COMPONENT);
        expect(component.length).toBe(1);
    });
});
```
where 
- `DATA_TEST_COMPONENT` is the value of the `data-test` attribute used in the component
- `findByTestAttr` is a helper function that find an element by `data-test` attribute
```javascript
export const findByTestAttr = (wrapper, val) => {
    return wrapper.find(`[data-test="${val}"]`);
};
```

This is the relevant part of the component I would like to test

```javascript

import React, {PureComponent} from "react";
// ...
import {FormattedMessage, injectIntl} from 'react-intl';
import {DATA_TEST_COMPONENT} from './constants';

class Confirmation extends PureComponent {

    render() {
        return (
            <div data-test={DATA_TEST_COMPONENT}>
              // ...
            </div>
        );
    }
}

const mapStateToProps = (state, props) => {
              // ...
};

const mapDispatchToProps = dispatch => bindActionCreators({
              // ...
}, dispatch);

Confirmation = connect(
    mapStateToProps,
    mapDispatchToProps
)(Confirmation);

Confirmation = injectIntl(Confirmation); // this is the important line!

export default Confirmation;

```

### Observed behaviour
The test fails if I `injectIntl()` is used on the component because it seems that it has implication of the `dive()` function of `enzyme`. The console log in the screenshots is the one you can find within the `setup()` fn of the test (`wrapper.debug()`).

Test fails if the decorator `injectIntl()` is used:

<img width="1209" alt="screen shot 2018-09-18 at 12 59 31" src="https://user-images.githubusercontent.com/6150475/45684060-7b442080-bb45-11e8-9856-45d73ee841ce.png">

Test pass if the decorator `injectIntl()` is commented:

<img width="1208" alt="screen shot 2018-09-18 at 12 59 53" src="https://user-images.githubusercontent.com/6150475/45684143-b181a000-bb45-11e8-96d4-62ea48efa74f.png">

Am i doing something wrong? 

### Libs versions
- "react": "16.5.1"
- "react-intl": "2.6.0",
- "redux": "4.0.0"
-  "react-scripts": "1.1.5"
- "enzyme": "^3.6.0"
-  "enzyme-adapter-react-16": "^1.5.0"
-  "enzyme-react-intl": "^2.0.1"

**Comment by redonkulus** [comment]
We have some docs on testing react-intl. Checkout the section on testing with injectIntl and Enzyme here: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#relativedate-advanced-uses-injectintl

**Comment by danielesalvatore** [comment]
Dear @redonkulus, thank you very much for your prompt reply. I finally sorted it out but with a slightly different approach. I use `enzyme` for my testing and I followed [this](https://github.com/airbnb/enzyme/issues/539#issuecomment-321638534) to render my component. Thank you again!
