### ISSUE TITLE
Feature Request: Pre-load currency data into IntlProvider

### ISSUE THREAD

**Issue by cmswalker** [yahoo/react-intl#1184]
### FEATURE REQUEST
It would be nice to pass currency data just once to `<IntlProvider/>` to avoid having to pass it around all the time. Basically pre-load the arguments so I don't have to pass them to `< FormattedNumber />`

### Expected behavior

```jsx
const formats = {
	currency: {
		code: 'JPY'
	}
};

<IntlProvider locale="ja" messages={translations} formats={formats} defaultFormats={formats}>
	< FormattedNumber value={100} /> // No currency Arg required!
</IntlProvider>
```

### Current behavior
Unfortunately, you need to keep on passing it around the app in order to provide it as a mandatory arg to formatted message.

```jsx
const formats = {
	currency: {
		code: 'JPY'
	}
};

<IntlProvider locale="ja" messages={translations} formats={formats} defaultFormats={formats}>
	< FormattedNumber value={100} currency="JPY" /> // This gets old
</IntlProvider>
```

**Comment by DragonRaider5** [comment]
I can have a look at this as soon as we fixed the build process for #1106 👍

**Comment by cmswalker** [comment]
Yes sorry. Basically looking for library support when it comes to partially
applying stuff at the Provider level!

**Comment by cmswalker** [comment]
Currently I do it on a page by page level which works but gets kinda
old/boilerplatey

**Comment by xiaomaini** [comment]
From personal usage, not all formatted numbers are currencies. This feels specific to your project needs, so you could consider using a [HOC](https://reactjs.org/docs/higher-order-components.html).

**Comment by cmswalker** [comment]
Fair, I think it would be nice to maybe provide some factory functions/components that could have some stuff pre-applied, but since this is easy to implement per user it doesn't necessarily need to be a feature

**Comment by MadaraUchiha-314** [comment]
I think this is a feature that's important. It doesn't make sense for an app to have and pass the currency information everywhere. Sure we can create a custom wrapper and an HOC around this. But isn't this a usecase that's important for the library itself to support ?

**Comment by longlho** [comment]
in your predefined top level `formats` object we allow basically everything in `Intl.NumberFormatOptions` which includes currency, isn't that what you're looking for?
