### ISSUE TITLE
How to display 1minute 30 seconds ago"

### ISSUE THREAD

**Issue by rumsky** [yahoo/react-intl#1187]
### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | VERSION |
| `npm ls react` | VERSION |
| `npm --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by StorytellerCZ** [comment]
Duplicate of #1188
