### ISSUE TITLE
(Question) Change title page

### ISSUE THREAD

**Issue by CMonjo** [yahoo/react-intl#1190]
Hey ! 
I'm sorry to post an issue for that but I can not find an answer to my question.
I am trying to use my website.

json files :
```
fr.json:
{
     "errorPage.title": Error 404 "
}
en.json:
{
     "errorPage.title": Error 404 "
}
```

I have this in my file:
```
const title = <FormattedMessage id = "errorPage.title" defaultMessage = "Error 404" />

document.title = title;
```
That return to my title page this [object Object]
How can I do? I start in React and I do not use Redux, should it? Thank's!

**Comment by oriSomething** [comment]
You should inject intl context, Something like that (didn't check):

```js
import React from "react";
import { injectIntl } from "react-intl";

class DocumentTitle extends React.Component {
  componentDidUpdate(prevProps) {
    if (prevProps.title !== this.props.title) {
      document.title = this.props.intl.formatMessage({ id: "your-id" });
    }
  }
}

DocumentTitle = injectInlt(DocumentTitle)
```

**Comment by mnogueron** [comment]
In your case `const title = <FormattedMessage ... />` is a React object, not a string. That's why you get `document.title` as `[object Object]`. 
You should apply @oriSomething's comment to get the translated text as a string.

**Comment by CMonjo** [comment]
Hey ! Thank you for your answers !
I'm sorry, I started on React and despite research I can not understand what you offer me as alternatives.
I show you my component which is a 404 page.
```
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import {FormattedMessage, injectIntl} from 'react-intl';
import './ErrorPage.css';
import Header from '../Headers/NormalHeader';

const DocumentTitle = () => (
	<FormattedMessage id='error.pageTitle' defaultMessage='Error 404'>
	{(message) => {
		if (document.title !== message) {
			document.title = message
		}
		return null
	}}
	</FormattedMessage>
)

class ErrorPage extends Component {
	render() {
		document.title = "viaTransit. - Erreur";
		let code = this.props.code;

		if (typeof code === 'undefined')
			code = "404";
		
		return (
			<main>
				<Header name={code}/>
				<section className="error-section">
					<h1>
						<FormattedMessage id="errorPage.sad"
						defaultMessage="oopsie :("/>
					</h1>
					<h2>
						<FormattedMessage id="errorPage.message"
						defaultMessage="Cette page n'existe pas !"/>
					</h2>
					<Link to="/" className="error-section-goback">
						<i className="material-icons">keyboard_arrow_left</i>
						<span>
							<FormattedMessage id="errorPage.btnBack"
							defaultMessage="Retour"/>
						</span>
					</Link>
				</section>
			</main>
		)
	}
}

export default ErrorPage;
```
I have tried both of the solutions you have proposed to me, @DragonRaider5 and @oriSomething, but I do not know where to put the code or how to use it.
Thank you for your answers !

**Comment by DragonRaider5** [comment]
Well, you'll actually have to render the `DocumentTitle` component.
Btw. also setting the title in your `ErrorPage`'s render method might overwrite your changed title...

**Comment by CMonjo** [comment]
@DragonRaider5 Ok it's working thank you so much !
