### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by markkelsall** [yahoo/react-intl#1193]
Hi all,

Not sure if I'm doing something fundamentally wrong or not but some guidance would be great.
I'm using server side react but I seem to be getting this "error" when I try this in a normal client side rendered app as well.
I've got the app running fine for any main stream language e.g. EN, FR, DE, ES etc where the dates are translating correctly, however when it comes to Arabic, I can't see to get the correct numbers to print and only prints normal ones e.g. 1234.50 

| Executable | Version |
| `npm ls react-intl` | 2.7.0 |
| `npm ls react` |16.3.2 |
| `npm --version` | 6.2.0 |
| `node --version` | 10.9.0 |

| OS | Version |
| macOS High Sierra | 10.13.4 |

| Browser | Version |
| Chrome | 69 |

I'm thinking that I'm missing something fundamental as I'm running out of ideas of what it could be that I'm missing so any help would be really appreciated!

Thanks

```import React from 'react';
import PropTypes from 'prop-types';
import { IntlProvider, addLocaleData, FormattedNumber } from 'react-intl';
import ar from 'react-intl/locale-data/ar';

addLocaleData(ar);

class App extends React.Component {

  render () {
    const { initialState } = this.props;
    const ltr = initialState.ltr ? 'ltr' : 'rtl';
    return (
      <div dir={ltr}>
        <IntlProvider locale="ar" messages={initialState.translations}>
          <div><FormattedNumber value={1000} /></div>
        </IntlProvider>
      </div>
    );
  }
}

App.propTypes = {
  initialState: PropTypes.shape({}).isRequired,
};

export default App;

**Comment by kumarharsh** [comment]
@markkelsall you need to use `ar-EG` or the extensions like `ar-u-nu-arab` for arabic numerals:

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation

```
new Intl.NumberFormat('ar-u-nu-arab').format(10000000)
> "١٠٬٠٠٠٬٠٠٠"
```

**Comment by markkelsall** [comment]
@kumarharsh thanks for your help and sorry for the late reply!

So I've managed to get it to work the way you suggested which is great and I understand it some extent but does that mean that `<FormattedNumber />` just doesn't support printing AR characters?

**Comment by kumarharsh** [comment]
It does. You just have to pass the correct locale. Try `ar-u-nu-arab`. FormattedNumber is just a wrapper around the browser's Intl API.

**Comment by markkelsall** [comment]
Thanks @kumarharsh 
Maybe this comes full circle back to my fundamental issue of trying to set this up using server side react. I've seen the other issue and thread bout SSR and seems that I'm doing everything as expected (using the IntlProvider)

In my App constructor I'm having to dynamically require the locale like so:
`
constructor (props) {
    super(props);
    const { initialState } = this.props;

    const localeData = require(`react-intl/locale-data/${initialState.locale}`); // eslint-disable-line import/no-dynamic-require
    addLocaleData(localeData);
  }
`
Bad I know!

However this is the only way I've been able to get the app to run and not hard coding the language I want to support.

Appreciate this is a separate topic to the first one raised so happy to close this and ask a new one?

What is the best approach for ensuring the locale is available for the client side app to render/check what the server sent is correct?

On the server side I'm doing this to polyfill:
`import areIntlLocalesSupported from 'intl-locales-supported';

export default (locale = 'en') => {
  if (global.Intl) {
    // Determine if the built-in `Intl` has the locale data we need.
    if (!areIntlLocalesSupported([locale])) {
      // `Intl` exists, but it doesn't have the data we need, so load the
      // polyfill and replace the constructors we need with the polyfill's.
      const IntlPolyfill = require('intl');
      Intl.NumberFormat = IntlPolyfill.NumberFormat;
      Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
    }
  } else {
    // No `Intl`, so use and load the polyfill.
    global.Intl = require('intl');
  }
};`

Thanks again

**Comment by kumarharsh** [comment]
Okay, I understand. I don't really have a good answer for this, but I think StackOverflow might be a better place to ask this question.

Personally, I'd throw in a bunch of if-else conditions for some locales (such as Arabic) to add the specific extensions required for displaying numerals in locale-specific formats. I haven't thought about how to check for availability of locales server-side - maybe SO would be better place to ask it.

**Comment by markkelsall** [comment]
@kumarharsh no problem. Thank you for putting me straight on some of my questions, much appreciated!
