### ISSUE TITLE
Using formatHTMLMessage is not parsing html inside messages.

### ISSUE THREAD

**Issue by sergioviniciuss** [yahoo/react-intl#1194]
### Expected behavior
Messages with html in it should  be parsed when using the imperative api e.g.: `intl.formatHTMLMessage('<b>foo</b>')`
should be rendered as **foo**
### Current behavior
when using _formatHTMLMessage_ , the html inside the labels is not being parsed and is rendering as <b>foo</b>

### Step to reproduce for BUG REPORT

I created this very basic project to allow you to reproduce the error: 
https://github.com/sergioviniciuss/react-intl-formatHTMLMessage-sample

just clone it and run `npm start` or check the code bellow:

```javascript
import React, { Component } from 'react';
import { injectIntl, defineMessages, FormattedHTMLMessage } from 'react-intl';
import logo from './logo.svg';
import './App.css';


const messages = defineMessages({
  htmlTest: {
    id: 'app.htmlTest',
    defaultMessage:'<b>Foo</b> bar'
  }
});

class App extends Component {
  render() {
    const { intl } = this.props;
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
           {intl.formatHTMLMessage(messages.htmlTest)}
          </p>
          <p>
           <FormattedHTMLMessage
            id="app.test2"
            defaultMessage="<b>Foo</b> bar 2"
          />
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default injectIntl(App);
```

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.0 |
| `npm ls react` | 16.5.2 |
| `npm --version` | 6.2.0 |
| `node --version` | 10.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.6 |

| Browser | Version |
| --- | --- |
| Chrome | 69.0.3497.100 |

**Comment by DragonRaider5** [comment]
Hey,

it is formatting the message containing html (it should return `<b>foo</b>`) but doesn't render it. To do that, you'd have to render the returned html like so:
```js
<p dangerouslySetInnerHTML={{ __html: intl.formatHTMLMessage(messages.htmlTest) }} />
```

But instead of doing so, I'd suggest directly using the `FormattedHTMLMessage` component, which does it for you:
```js
<FormattedHTMLMessage
  tagName='p'
  {...messages.htmlTest}
/>
```

**Comment by DragonRaider5** [comment]
You're welcome!
`FormattedHTMLMessage` actually uses `dangerouslySetInnerHTML` internally 😄 

Please close the issue if it now works or comment again, if it doesn't. Thanks!

**Comment by sergioviniciuss** [comment]
@DragonRaider5 I tested it and it works, but I also tested it with `formatMessage` and it also works, so, it makes me think: what's the point of using the `formatHTMLMessage`? Shouldn't this be also handled for it?
Thanks a lot, btw! This library is excellent!

**Comment by DragonRaider5** [comment]
Glad that it works and thanks a lot!

If I'm remembering correctly, there are some escaping mechanisms in `formatMessage` (to avoid code injection when using SSR), potentially breaking HTML - that's why there's a different function for formatting messages (`formatHTMLMessage`).
It doesn't do so, but using it is discouraged as it comes with some risks and is mostly there for legacy code.

**Comment by sergioviniciuss** [comment]
Makes sense! thanks! :D
