### ISSUE TITLE
FormattedNumber displays incorrect currency for CHF currency Code on Win 7 ie 11

### ISSUE THREAD

**Issue by lauterry** [yahoo/react-intl#1196]
### BUG REPORT
Running the following code :

console.log(new Intl.NumberFormat('de-CH', { style: 'currency', currency: 'CHF' }).format(123455));

outputs the wrong currency "fr." instead of "CHF" in IE 11 window 7.

capture d ecran 2018-10-05 a 11 58 51

This bug did not occurred in IE11 window 10 neither on safari, chrome nor firefox

Can your team reach the right team to report this bug please ? I don't know who to contact.

Best regards !

### Expected behavior
I expect the following code :

console.log(new Intl.NumberFormat('de-CH', { style: 'currency', currency: 'CHF' }).format(123455));

to output the right currency "CHF"

### Current behavior
Running the following code :

console.log(new Intl.NumberFormat('de-CH', { style: 'currency', currency: 'CHF' }).format(123455));

outputs the wrong currency "fr."

### Step to reproduce for BUG REPORT
```
<FormattedNumber
					value={123455}
					style="currency"
					currency="CHF"
					currencyDisplay="symbol"
					useGrouping={true}
					minimumFractionDigits={0}
					maximumFractionDigits={2}
				>
```

### Your Environment
| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 15.6.1 |
| `npm --version` | 6.4.1 |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| WINDOWS | 7 |

| Browser | Version |
| --- | --- |
| Internet Explorer | 11 |

**Comment by ghostd** [comment]
Did you add the Intl polyfill?

**Comment by lauterry** [comment]
Yes I did

**Comment by roderickhsiao** [comment]
Based on https://caniuse.com/#feat=internationalization IE 11 doesn't need Intl polyfills

it doesn't seem the data is coming from Intl polyfills nor react Intl.
I run on saucelab using different web pace and all can reproduce the issue so probably need to file ticket to Microsoft instead.

**Comment by lauterry** [comment]
Issue reported to Microsoft

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19243669/

**Comment by lauterry** [comment]
Microsoft says they won't fix this issue :(

**Comment by lauterry** [comment]
I posted an issue to the intl polyfill team

https://github.com/andyearnshaw/Intl.js/issues/317
