### ISSUE TITLE
Formatted Message options issue

### ISSUE THREAD

**Issue by SRIDHERKUMAR** [yahoo/react-intl#1199]
i am trying to get the translations for the select options.

example:
 availableCategories.map(field => <option value={field}
                                                                          key={field}><FormattedMessage id={field}/></option>)

I am not sure why it is showing all the options as [Object Object] . 

### Expected behavior
Expected to see the options.

### Current behavior
i am seeing all the options like [Object Object]

### Your Environment
Mac Os - Mac book pro 

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.1.5 |
| `npm ls react` | 16.2.0 |
| `npm --version` | 5.6.0 |
| `node --version` | 8.9.4 |

| OS | Version |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

| Browser | Version |
| NAME | VERSION |
| Chrome | 61.0.3163.71 |

**Comment by redonkulus** [comment]
@SRIDHERKUMAR Can you provide more code examples, its not clear from your current one what is happening. Maybe link to a gist or codesandbox URL that showcases the issue.

**Comment by SRIDHERKUMAR** [comment]
Just consider this simple example
import {FormattedMessage} from 'react-intl';

<select>
<option><FormattedMessage id={field}/></option>
</select>

In the same class it is working fine for the below example. 
 Example:
<Button ><FormattedMessage id='remove'/></Button>

**Comment by kumarharsh** [comment]
@SRIDHERKUMAR none of your code samples are visible. Try surrounding them in single quotes. 

I think you're trying to output FormattedMessage into a string. That's the reason you'd be getting an `[Object object]` output. Try `intl.formatMessage()` API instead.

**Comment by SRIDHERKUMAR** [comment]
I am trying to use this way.
import {FormattedMessage} from 'react-intl';
example1:
'<select>
<option><FormattedMessage id={field}/></option>
</select>

exampe 2:
availableCategories.map(field => <option value={field}
                                                                          key={field}><FormattedMessage id={field}/></option>)'

In the same class it is working fine for the below example. 
 Example:
'<Button ><FormattedMessage id='remove'/></Button>'

if i am supposed to use intl.formatMessage() can to help me how to use them for above examples.

**Comment by kumarharsh** [comment]
Yeah, I was guessing correctly. You can only use plain strings in the `<option>` component of select.

**Comment by SRIDHERKUMAR** [comment]
<img width="678" alt="screen shot 2018-10-16 at 1 41 03 pm" src="https://user-images.githubusercontent.com/22944940/47046102-3d88e680-d149-11e8-9a32-b3747b9d1b9c.png">
Thanks for the response

**Comment by kumarharsh** [comment]
https://github.com/yahoo/react-intl/wiki#formatting-data
