### ISSUE TITLE
Intl is not defined

### ISSUE THREAD

**Issue by nuragic** [yahoo/react-intl#120]
Hi,

I'm using react-intl from a node (v2.0) cli program and I get: *ReferenceError: Intl is not defined*

Seems that it's caused by: https://github.com/yahoo/react-intl/blob/master/src/mixin.js#L51-L52

When I import the Intl polyfill everything works correctly.
```javascript
import Intl from 'intl';
```
Is that the correct way to solve this issue?

Thanks!

**Comment by caridy** [comment]
Check the documentation on how to setup your environment:
http://formatjs.io/guides/runtime-environments/

**Comment by gpbl** [comment]
@nuragic is `Intl` installed with node? In my setup it wasn't (I installed node with brew) 
```
$ node
> console.log(Intl)
ReferenceError: Intl is not defined
```

**Comment by nuragic** [comment]
@caridy ok thanks!
@gpbl ciao! :) nope, I don't have the Intl object in my node runtime... Same for me, I installed node with brew...

**Comment by gpbl** [comment]
@nuragic I could get it working installing via `brew install node --with-icu4c` (bidere http://stackoverflow.com/questions/30410343/)

**Comment by nuragic** [comment]
@gpbl cool, thanks!

**Comment by nuragic** [comment]
@gpbl BTW, I just realized that I'm using iojs... :sweat_smile:
