### ISSUE TITLE
[Bug] HTML tags handling in FormattedMessage

### ISSUE THREAD

**Issue by Experiment8** [yahoo/react-intl#1206]
At the moment the HTML tags passed into the values are not parsed as HTML.
The solutions described in the [docs](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) is not suitable for many languages, because the tags position can vary a lot based on the language, is not a scalable solution.

Consider Arabic or Turkish, those languages are going to have the words inverted or split most of the times, and determine the position on code level is not a scalable enough solution.

### Expected behavior
Imagine we have a string as such:
```
{start_bold}Gift{end_bold} for {name}.
```
Which looks like this in the JSX code:
```
<FormattedMessage
          id="your_tag_id"
          values={{
            start_bold      : '<b>',
            end_bold        : '</b>',
            name              : 'Anthony'
          }}
        />
```
React Intl is correctly escaping the tag content, but it shouldn't do the same when the values are applied, because at this stage it should have already escaped any malicious code in the tag.

The generated string should be "**Gift** for Anthony.".

This phrase in Turkish, for example, would be conceptually swapped: "Anthony for **Gift**."

### Current behavior
The string is rendered escaped: "<b>Gift</b>for Anthony."

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.1 |
| `npm ls react` | 16.5.2 |
| `npm --version` | 5.6.0 |
| `node --version` | 8.11.4 |

I believe this should be addressed, I can MR if you believe this makes sense. Please let me know what you think.

**Comment by ghostd** [comment]
Dupplicate of #513
