### ISSUE TITLE
Plurals in complex grammars

### ISSUE THREAD

**Issue by dropfen** [yahoo/react-intl#121]
Hello, I saw the example with the plurals for `{num, plural, one {# item} other {# items}}``
You guys should know it, there are some languages where the pluralization is more complex:
for example in Russian when I would write *comments* it would be:

0 {# комментари*ЕВ*}
1 {# комментари*Й*}
2 {# комментари*Я*} 
.. 
4 {# комментари*Я*}
5 {# комментари*ЕВ*}
...
9 {# комментари*ЕВ*}

exception 
11 - 14 {# комментари*ЕВ*}

You see it gets really difficult with Russian grammar )) but there are some helping functions out there like this one (php):
```php
function getTermination ($num) {
    // Get the last two digits from the number
    $number = substr($num, -2);
     

    if($number > 10 and $number < 15) { // 11 - 14 the termination is 'ев'
        $term = "ев";
    }
    else {  // Otherwise get the termination by the last digit rule..            
        $number = substr($number, -1);
         
        if($number == 0) {$term = "ев";}
        if($number == 1 ) {$term = "й";}
        if($number > 1 ) {$term = "я";}
        if($number > 4 ) {$term = "ев";}
    }
    echo $term;
}

$termination = getTermination(523);
```

So, my question is, how can we apply those *rules* to this Component? Can we set this helper Function somewhere?
Thank you

**Comment by caridy** [comment]
@dropfen that is correct. while english only requires `one` and `other`, you can use `one`, `few`, `many` and `other` is some language and `ru` is one of them. This also is not something we have invented, we use CLDR pluralization rules, which (as today) is essentially this function:

```
function(n) {
        var i = Math.floor(Math.abs(n)),
            v = n.toString().replace(/^[^.]*\.?/, "").length;
        n = Math.floor(n);
        if (v === 0 && i % 10 === 1 && (i % 100 !== 11)) return "one";
        if (v === 0 && i % 10 === Math.floor(i % 10) && i % 10 >= 2 && i % 10 <= 4 && !(i % 100 >= 12 && i % 100 <= 14)) return "few";
        if (v === 0 && (i % 10 === 0 || v === 0 && (i % 10 === Math.floor(i % 10) && i % 10 >= 5 && i % 10 <= 9 || v === 0 && i % 100 === Math.floor(i % 100) && i % 100 >= 11 && i % 100 <= 14))) return "many";
        return "other";
    }
```

maybe we should update the documentation to reflect that `one` and `other` are not the only options. feel free to send a PR to update the docs.

**Comment by dropfen** [comment]
@caridy Oh, wow. Got it, thanks!
Could you please point me to the repo, where this function is declared?

**Comment by dropfen** [comment]
PR created #122

**Comment by caridy** [comment]
@dropfen thanks for the PR, we will check it soon.

As for the repo, it is just the CLDR json distro, as today, we are using version 26 and we will be accommodating things to start using the new distro thru: https://github.com/unicode-cldr
