### ISSUE TITLE
Enzyme helper functions not working

### ISSUE THREAD

**Issue by DavidUnzue** [yahoo/react-intl#1216]
I followed the [official docs](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#enzyme) for testing my components using Jest and Enzyme, but can't get them to work for even the simplest component.

### Expected behavior
Enzyme helper functions `shallowWithIntl` and `mountWithIntl` should inject the `intl` context to the tested components.

### Current behavior
The following error gets triggered when using those helper functions:
```js
TypeError: _reactIntl.IntlProvider is not a constructor
```

Seems like I'm not allow to instantiate react-intl's `IntlProvider` as proposed in the docs:
```js
const intlProvider = new IntlProvider({ locale: 'en-US', messages: flattenMessages(messages['en-US']) }, {});
```

### Step to reproduce
I created following helper file as stated in the docs:
```js
/**
 * Components using the react-intl module require access to the intl context.
 * This is not available when mounting single components in Enzyme.
 * These helper functions aim to address that and wrap a valid,
 * English-locale intl context around them.
 */

import React from 'react';
import { IntlProvider, intlShape } from 'react-intl';
import { mount, shallow } from 'enzyme';
import flattenMessages from './flattenMessages';
// You can pass your messages to the IntlProvider. Optional: remove if unneeded.
import messages from '../messages';

// Create the IntlProvider to retrieve context for wrapping around.
const intlProvider = new IntlProvider({ locale: 'en-US', messages: flattenMessages(messages['en-US']) }, {});
const { intl } = intlProvider.getChildContext();

/**
 * When using React-Intl `injectIntl` on components, props.intl is required.
 */
function nodeWithIntlProp(node) {
    return React.cloneElement(node, { intl });
}

export function shallowWithIntl(node, { context, ...additionalOptions } = {}) {
    return shallow(
        nodeWithIntlProp(node),
        {
            context: Object.assign({}, context, {intl}),
            ...additionalOptions,
        }
    );
}

export function mountWithIntl(node, { context, childContextTypes, ...additionalOptions } = {}) {
    return mount(
        nodeWithIntlProp(node),
        {
            context: Object.assign({}, context, {intl}),
            childContextTypes: Object.assign({}, { intl: intlShape }, childContextTypes),
            ...additionalOptions,
        }
    );
}
```

Then used the helper functions for snapshot testing my component:
```js
import React from 'react';
import toJson from 'enzyme-to-json';
import { shallowWithIntl } from '../../utils/intl-enzyme';


// Component to be tested
import Navbar from '../../components/Navbar';

function setup() {
  const props = {};

  const enzymeWrapper = shallowWithIntl(<Navbar {...props} />).first().shallow();

  return {
    props,
    enzymeWrapper
  };
}

describe('components', () => {
  describe('Navbar', () => {
    test('renders itself', () => {
      const { enzymeWrapper } = setup();
      const component = enzymeWrapper.dive();

      expect(toJson(component)).toMatchSnapshot();
    });
  });
});
```

When running it, the test fails with:
```js
TypeError: _reactIntl.IntlProvider is not a constructor
```

### My Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.7.2 |
| `npm ls react` | 16.5.0 |
| `npm --version` | 6.4.1 |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS High Sierra | 10.13.6 |

Any ideas on this?

**Comment by DavidUnzue** [comment]
I solved the issue.

Additionally to the other helper functions, I had also created a Jest Mock [as described in the docs](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#jest-mock) and although I had commented it out, Jest was creating an `IntlProvider` object set to `undefined`, which was then interfering with the instantiation in the helper functions (`new IntlProvider`), as the object existed already.

After deleting the mock file everything worked as expected.

**Comment by salagadoola** [comment]
For anyone who, like me, encounters the same issue (created a Jest Mock, which makes `IntlProvider` to be undefined):
- Solution 1: as mentioned above, deleting the mock file then everything works as expected.
- Solution 2: `const { IntlProvider } = jest.requireActual('react-intl');` to get the actual (not mocked) react-intl.
