### ISSUE TITLE
use react-intl with DocumentTitle requires string not object

### ISSUE THREAD

**Issue by dreamcog** [yahoo/react-intl#1217]
First, i need to say i just set the 

`      <IntlProvider key={locale} locale={locale} messages={localeMessage} textComponent={React.Fragment}>
        {children}
      </IntlProvider>`

it was works fine , but with DocumentTitle there still have a error says:

![image](https://user-images.githubusercontent.com/1401184/49131139-f8dc9780-f311-11e8-939a-586b616feefb.png)

the code is:

![image](https://user-images.githubusercontent.com/1401184/49131161-0db92b00-f312-11e8-9621-af6b31f25b21.png)

so , what should i do to fix it?

**Comment by dreamcog** [comment]
i am using the react-document-title

**Comment by dreamcog** [comment]
just fix this problem.

1.
`import { injectIntl, intlShape } from 'react-intl';`

2.
`module.exports = injectIntl(withRouter(connect(mapStateToProps,mapDispatchToProps)(OrderList)))
`
3.
`<DocumentTitle title={this.props.intl.formatMessage({id :'订单列表'})}>
`
>

**Comment by dreamcog** [comment]
please close this issue. thanks

**Comment by redeel** [comment]
You can close it yourself. There is a button under the comment form.
