### ISSUE TITLE
Placing Formatted* in HTML attributes

### ISSUE THREAD

**Issue by cyberthom** [yahoo/react-intl#125]
Apologies if this is documented somewhere but I can't find how `Formatted*` is supposed to be used inside HTML attributes.

e.g. The following outputs `[object Object]` as the title attribute is just a React component:
```
<img title={<FormattedMessage message="foo is {foo}" foo="bar" />} />
```

I am using ES6 syntax so don't have mixing available.

**Comment by ericf** [comment]
> I am using ES6 syntax so don't have mixing available.

You can use `React.createClass()` and then use the mixin; that's the best option for now until we get rid of the mixin.

**Comment by cyberthom** [comment]
I was hoping to be able to avoid that but fair enough. 
Thanks!

**Comment by gpbl** [comment]
@cyberthom what about using https://github.com/yahoo/intl-messageformat ?

**Comment by caridy** [comment]
@gpbl that will work, but you have to keep in mind that you might endup having duplication in the code if you include `react-intl` and `intl-messageformat` browser libraries unless you create a custom build for your app to dedupe them.

**Comment by gpbl** [comment]
@caridy sure! Module bundlers like webpack will take care of this, provided the package version is the same.

This raises another question: shouldn't `intl-*`modules being included as peer dependencies in react-intl?

**Comment by caridy** [comment]
@gpbl no. we do some funky stuff to bundle things together before producing the npm pkg, which means you endup with two copies of some internals, plus the data. This is a hard problem to tackle if you use ES6 modules today.

**Comment by gpbl** [comment]
Oh I see thanks. What's confusing, however, is that I can't see the duplicate code in webpack stats / mapped source. I'll investigate this further, since I'm using intl packages all around 😰
maybe is the dedupe plugin cleaning them up...
