### ISSUE TITLE
FormattedTime component isomorphic format issue

### ISSUE THREAD

**Issue by Ekhoo** [yahoo/react-intl#126]
https://gist.github.com/Ekhoo/a59a295dcabf2876c75e

**Comment by okuryu** [comment]
My guess that it's difference behavior between Intl.js polyfill and native implementation. Which implementation do you  use on the client side and server side?

**Comment by Ekhoo** [comment]
I use the polyfill version on both server and client side

**Comment by Ekhoo** [comment]
Ok on the server I use the polyfill version and on the client the native one

**Comment by caridy** [comment]
yes, this is polyfill specific. please, open the issue on https://github.com/andyearnshaw/Intl.js/issues/new, make sure you are trying the new version of the polyfill (1.0.0-rc-1)
