### ISSUE TITLE
Get a dummy msg if translation was not added yet

### ISSUE THREAD

**Issue by dropfen** [yahoo/react-intl#129]
Is it possible to implement something like a convention for not existing keys?

```
messages:  { 
  dummy: 'Noch keine Übersetzung für -->  ', // And output "Noch keine Übersetzung für 'nav.slogan'"
}
```
or for example:
```
dummy: {
  default: ['de'],
  prefix: '*** ' // Results in '*** Auf uns können Sie sich verlassen!' if path is 'nav.slogan' and german is provided as the first class language
}
````

Another option would be to have a hook provided by the IntlMixin with the actual element in wich the translation is sitting.. just an idea, maybe someone find it interesting..

**Comment by caridy** [comment]
@dropfen we are due on this topic. @ericf as done a lot of research in this area, and he will be providing some examples around the fallback concept.

also, there are a couple of good discussions around this topic in the issues... I think this one is the most prominent: https://github.com/yahoo/react-intl/issues/35

**Comment by dropfen** [comment]
Oh, yes, great! Just didn't searched for fallback, I was to deep in the dummy concept.. however, thanks!

**Comment by dropfen** [comment]
Hmm, the thread is closed.. So.. Just to add my 2 Cents to this.. Could you guys just call a fallbackHook, which is documented.. Just call it with some needfull variables like *path, currentLocale* and thats it.

Because everyone, wishes it, like he is used to it.. Java style, Microsoft style.. My crappy dummy style.. So with a hook, we would have the power to manage it ourself..
