### ISSUE TITLE
support for optional tag name instead of hardcoded span element

### ISSUE THREAD

**Issue by rsamec** [yahoo/react-intl#130]
I would like to suggested replacing

```js
return React.DOM.span(null, this.formatDate(value, options));
```
with support for optional tag 

```js
var tagName  = props.tagName || 'span';
return React.DOM[tagName](null, this.formatDate(value, options));
```

react-Intl components are usable than i svg <text>, that accepts only __tspan__ element.

**Comment by caridy** [comment]
We have discussed this in the past, but not in the context of svg, which brings something new to the table. I will discuss this again with @ericf soon.

**Comment by ericf** [comment]
Yeah I see the issue for SVG, so this makes sense to add.

**Comment by caridy** [comment]
awesome.
