### ISSUE TITLE
Currency format documentation lacking

### ISSUE THREAD

**Issue by Spookenator** [yahoo/react-intl#132]
Hi Guys,
I went to the documentation with regards overiding currency.

My react component is created for South Africa with locale code en-ZA the problem is that when i use ZAR as a currency code i get something that looks like ZAR25 000, this should read R25 00.

Could any assist me in getting this right.

**Comment by caridy** [comment]
CLDR solved that a while ago, you should be able to upgrade to the polyfill version 1.0.0-rc-4. Here is the new data: https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/en-ZA.json#L2193

**Comment by FinnWinchester** [comment]
Having the same issue and were not able to fix it after trying for several hours. Could you @caridy please provide further details on how to fix this?

Thanks.
