### ISSUE TITLE
Message composition creates parsing errors

### ISSUE THREAD

**Issue by sslotsky** [yahoo/react-intl#133]
Based on what I see here http://formatjs.io/react/#getIntlMessage#formatted-html-message

I should be able to use a ```FormattedMessage``` as one of the properties to another ```FormattedMessage```. For example:

```
var PageCountMessage = React.createClass({
  mixins: [IntlMixin],

  getDefaultProps: function() {
    return IntlData;
  },

  render: function() {
    var { messageKey, count, ...other } = this.props;
    var pageCountText = (
      <FormattedMessage
        message={this.getIntlMessage('snapshot.page_count')}
        count={this.props.count}
        {...IntlData} />
    );

    return (
      <FormattedMessage
        message={this.getIntlMessage(messageKey)}
        pageCountText={pageCountText}
        {...IntlData} />
    );
  }
});
```

However, attempting to do this results in a parsing error in ```parser.js```:

> Uncaught SyntaxError: Expected "=", "\\#", "\\u", "\\{", "\\}", "}" or [^{}\\\0-\x1F \t\n\r] but end of input found.

Using react v0.13, and no possibility of upgrading. Have I done something wrong or is there a bug?

**Comment by ericf** [comment]
This should work. Could you share the ICU Message strings for both of these messages?

**Comment by sslotsky** [comment]
Since we went with a different approach, I can't be sure what the strings were that I was testing with. If I get the chance I will test it out again but I'm on a new project now. Thanks for following up.
