### ISSUE TITLE
Localizing message containing HTML

### ISSUE THREAD

**Issue by alicoding** [yahoo/react-intl#137]
Hi,

I have a use case where I need to include partial HTML which is almost impossible to break it down because it will lose its context when doing the translation.

`router.jsx`
```
var intlData = {
    locales : ['en'],
    messages: {
        username: 'Username',
        join: '<p className="by-joining">By joining, I agree to Mozilla Webmaker&rsquo;s <Link external="https://webmaker.org/en-US/terms">Terms</Link> and <Link external="https://webmaker.org/en-US/privacy">Privacy Policy</Link></p>'
    }
};
```

So, I want to be able to just have the whole component be part of the intlData and when I use it with `getIntlMessage` method I could just call that and get the whole thing rendered correctly.

`component.jsx`
```
var React = require('react');

var Signup = React.createClass({
  mixins: [require('react-intl').IntlMixin],
  render: function() {
    return (
      <div>{this.getIntlMessage('join')}</div>
    );
  }

});
```

What is the best way to handle this? I was trying something similar with just simple component with text inside using `FormattedHTMLMessage` but it doesn't seem like it covers what I'm trying to do here?

I've read through this issue as well https://github.com/yahoo/react-intl/issues/68 but it doesn't seem to solve/work the way I want here?

**Comment by gpbl** [comment]
You should not include html tags into your messages. The way (not tested) I would do is:

```js

render() => {

  var linkToTerms = (
    <Link external="https://webmaker.org/en-US/terms">
      <FormattedMessage message="join_term_link" />
    </Link>
  )

  return (
    <div>
       <p className="by-joining">
          <FormattedMessage message="join" linkToTerms={linkToTerms} />
       </p>
    </div>
  );
}
```

and your messages:

```js
messages: {
  username: 'Username',
  join: 'By joining, I agree to Mozilla Webmaker’s {linkToTerms}',
  join_term_link: 'Terms'
}
```

**Comment by alicoding** [comment]
Hi @gpbl thanks for the respond! I've tried your approach before but the problem that we're encountered here is that if the string itself contain HTML partially it can be somewhat hard to separate them and it will lose the context of the message. Is there any other way you can recommend here?

**Comment by gpbl** [comment]
AFAIK there's no way to include HTML content in your strings without then applying audacious workarounds with `dangerouslySetInnerHTML`. 

Anyway, do you actually mean the *semantic* context? :-) I believe this is solved organizing better your messages, e.g.:
```js
{ 
 join: 'By joining, I agree to Mozilla Webmaker’s {linkToTerms}',
 linkToTerms: 'Terms' // clearly refers to the line above
}
```

**Comment by alicoding** [comment]
The thing is that we use (http://transifex.com/)[Transifex] to do the translation so, when we upload this `.json` file our translators not going to see the connection between `{linkToTerms}` and `{join}` strings there and what they'll see is just the string individually.

The example above might be a bit easy to reorganize or to make connection, but I'm more of looking at standard / correct way to localize such in React. I have done something similar for Angular and server-side templating but they have similar concept or easy to inject InnerHTML where it will be rerender and not display as string. This is what we've created for server [http://github.com/mozilla/node-webmaker-i18n](webmaker-i18n).

**Comment by alicoding** [comment]
So it seem `dangerouslySetInnerHTML` is enabled but it just doesn't work when it's React component?

I've tried something like this @gpbl :

```
{
  example: 'By joining, I agree to Mozilla Webmaker's <a href="http://somewhere.com">Terms</a> and <a href="http://somewhere.com">Privacy Policy</a>'
}
```

```
      <FormattedHTMLMessage message={this.getIntlMessage('example')} />

```

This will render correctly

but when I turn this to:

```
{
  example: 'By joining, I agree to Mozilla Webmaker's <Link external="http://somewhere.com">Terms</Link> and <Link external="http://somewhere.com">Privacy Policy</Link>'
}
```

it will render like this when I inspect the element.

```
<span data-reactid=".0.4.2.2.0">By joining, I agree to Mozilla Webmakers <link external="http://somewhere.com">Terms and <link external="http://somewhere.com">Privacy Policy</span>
```

**Comment by alicoding** [comment]
Now I see the reason here why I'm seeing `<link>` when it's a React component 

https://github.com/yahoo/react-intl/blob/master/src/components/html-message.js#L53-L57

I guess this is by design?

**Comment by caridy** [comment]
> Now I see the reason here why I'm seeing <link> when it's a React component

Can you elaborate more? The content of the message CANNOT be a react component, that part is not controlled by react, but just dumped into the DOM as HTML fragment.

**Comment by alicoding** [comment]
I think my use case we need to include React component in the string to
avoid and complications for our contributors who likes to help us translate
and we are trying to make it easy for them as much as possible.

**Comment by xmatthewx** [comment]
Thanks @gpbl and @caridy for any help you can offer. 

As you probably know, this has a big impact on translators and the quality of translations. A phrase out of context might be ambiguous and misinterpreted. Translated, it could become nonsense or worse when joined in a sentence. 

cc @k88hudson

**Comment by caridy** [comment]
@xmatthewx @alicoding I understand, and we have very similar requirements at yahoo, but the problem is that having dynamic react components in your translations means you're breaking the invariant of the react component that renders the translation. Imagine the translator makes a mistake, and types `<liink>` instead of `<link>`, there is no way you can catch that. Another issues is that your react component will be transpiled, transforming `<link>` tags into the corresponding imperative code, how do you plan to do that for the translations?

In the other hand, the ambiguity of the translation can be mitigated by introducing notes (comments) associated to the message itself, and the tool used for the translation can surface those comments. If you use a yaml file, those comments are no brainer, for json files, things are more complicated.

@ericf and I will be working on some tooling to extract messages from react components, at least it is an idea we have been playing with, and that will definitely have the ability to add comments for translators to avoid ambiguously or misinterpretation of the messages.

**Comment by alicoding** [comment]
Good point @caridy. I have been using [Chrome-i18n](https://developer.chrome.com/extensions/i18n) before switching to ReactJS. The nice thing about Chrome-i18n format at least we can use `description` for comment/instruction there and Transifex does parse that section for translators even though other format does it better but still better than key-value format.

So, that bring me to the question if it is possible to support different format here in react-intl? or we will have to build json from other format if that's the only and best way to do?

**Comment by caridy** [comment]
@alicoding we normally use js-yaml (https://www.npmjs.com/package/js-yaml), which is a nice parser for yaml format (http://yaml.org/), you can see an example here: https://github.com/yahoo/formatjs-site/blob/master/lib/messages.js, for translations defined here: https://github.com/yahoo/formatjs-site/tree/master/i18n

**Comment by alicoding** [comment]
I think this issue can be closed. I'm going to use how you guys suggested here.

I ended up doing it like this which I think it's good enough, but will have to either use `yaml` format to upload them to Transifex or Chrome-i18n which ever support better comment/instruction.

```
    var termsLink = (<Link external="https://webmaker.org/en-US/terms">{this.getIntlMessage("terms")}</Link>);
    var privacyLink = (<Link external="https://webmaker.org/en-US/privacy">{this.getIntlMessage("privacy_policy")}</Link>);
        <FormattedMessage
          message={this.getIntlMessage('by_joining')}
          linkTerms={termsLink}
          linkPrivacyPolicy={privacyLink} />
```

```
  {
        by_joining: 'By joining, I agree to Mozilla Webmakers {linkTerms} and {linkPrivacyPolicy}',
        privacy_policy: 'Privacy Policy',
        terms: 'Terms'
    }

**Comment by caridy** [comment]
that looks great.

**Comment by emmenko** [comment]
Hey guys, I'm using the `2.0.0-pr-1` version and this doesn't seem to work anymore.

```js
const termsLink = (<Link external="https://webmaker.org/en-US/terms">term</Link>)
const privacyLink = (<Link external="https://webmaker.org/en-US/privacy">privacy</Link>)

<FormattedMessage
  id="terms"
  defaultMessage="By joining, I agree to Mozilla Webmakers {linkTerms} and {linkPrivacyPolicy}"
  linkTerms={termsLink}
  linkPrivacyPolicy={privacyLink} />
```

This renders

```
By joining, I agree to Mozilla Webmakers {linkTerms} and {linkPrivacyPolicy}
```

Any idea how to fix it?

**Comment by emmenko** [comment]
Update: so I've found out that with `FormattedMessage` works, but not with `FormattedHTMLMessage`. 

Also the correct setup should be using `values`

```js
<FormattedMessage
  id="terms"
  defaultMessage="By joining, I agree to Mozilla Webmakers {termsLink} and {privacyLink}"
  values={{ termsLink, privacyLink }} />
```

If I use `FormattedHTMLMessage` it gets rendered like this

```
By joining, I agree to Mozilla Webmakers [object Object] and [object Object]
```

**Comment by ericf** [comment]
@emmenko this is working as expected, `<FormattedHTMLMessage>` is to support legacy messages that _contain_ HTML in them, but in order to protect the users and developer, all of the `values` are HTML escaped — this is how it works in v1 too.

**Comment by emmenko** [comment]
Hmm I see. So if I have let's say a `<Link>` and a HTML tag like `<code>` in the same message, how does it work? Or is this not possible?

**Comment by ericf** [comment]
That's not going to work out. My recommendation would be to move the `<code>` part into JSX and using React elements with `<FormattedMessage>`.

**Comment by Menci** [comment]
I write HTML directly in the message and I got this error:

```
Error: [React Intl Error FORMAT_ERROR] Error formatting message: "problem_judge_settings.auto_testcases" for locale: "zh-CN" 
Error: The intl string context variable "code" was not provided to the string "由数据文件自动检测测试点（自动匹配 <code>.in</code> 与 <code>.out</code> 文件）"
```

My solution is escape the message's url when loading them and wrap formatMessage to get unescaped HTML back.
