### ISSUE TITLE
Support object neutral path keys

### ISSUE THREAD

**Issue by mduvall** [yahoo/react-intl#138]
It's common for translation keys to be namespaced as `foo.bar.baz` and the resultant object to be:

```
{
  "foo.bar.baz": "foo"
}
```

With `react-intl`, this turns into a [path lookup](https://github.com/yahoo/react-intl/blob/master/src/mixin.js#L108-L121) on the `messages` object. I'd like to add an option for the context to support "object neutral path keys", whereby `foo.bar.baz` turns into the lookup `messages["foo.bar.baz"]`. If this is amenable I am happy to make the change.

**Comment by jasonmit** [comment]
This has already been discussed here https://github.com/yahoo/react-intl/issues/46

**Comment by mduvall** [comment]
@jasonmit Right, I should have mentioned I read over that ticket. The resolution is unclear there and the recommended solution of overriding `getIntlMessage` via another mixin is suboptimal for anybody taking on `react-intl` as a dependency. I'd suggest parameterization in the face of the ambiguity argument. Anyway it is fine, was just testing out the library. Thanks for the quick reply.

**Comment by jasonmit** [comment]
@mduvall this comment addresses how one might override it that method with your own, which treats the path as a string and not an object path https://github.com/yahoo/react-intl/issues/46#issuecomment-67502930
