### ISSUE TITLE
Per-message fallback for dynamically built tokens

### ISSUE THREAD

**Issue by glenjamin** [yahoo/react-intl#139]
I don't consider this the same as #35 - where we have multiple translations and some are incomplete.

The scenario is that a server API will return an error code, and we want to translate that on the UI. We have a set of error codes we can handle, and an open set of future error codes which for now should use some generic message.

It would be nice to have an API which supported a fallback to a different token, something like:

```js
this.getIntlMessageWithFallback("api.errors." + errorCode, "api.errors.generic")
```

**Comment by caridy** [comment]
you can simply have a custom lookup process that is responsible for trying to find a message for `"api.errors." + errorCode`, and if that message does not exists, it can fallback. All that should happen as part of the message resolution process, and a message should be provided into the actual format tag.

**Comment by ericf** [comment]
This is something that we're backing in support for in v2. You can see the current algorithm here: https://github.com/yahoo/react-intl/blob/v2-dev/src/format.js#L105

**Comment by glenjamin** [comment]
Looks sensible thanks!

**Comment by glenjamin** [comment]
Is there an overall summary issue for the v2 stuff? It looks like you're flattening messages earlier instead of at lookup time now, which is something I've been meaning to look into for a while - good stuff!

**Comment by ericf** [comment]
@glenjamin there's some stuff hanging around in the issues with the `fixed-by-v2` tag, and [this commit has an overview](https://github.com/yahoo/react-intl/commit/6210dd4919a9d8ce177ab040a7d1fe92329a73c0). But I plan to start working on a larger comprehensive set of changes along with the reasoning behind it, which I'll open an RFC issue for.

**Comment by ericf** [comment]
> It looks like you're flattening messages earlier instead of at lookup time now

The flattening of messages is something I hope to have a discussion around. Current on the branch it assumes a flat `id: message` collection, which means the `id` have to be unique per `<IntlProvider>` wrapper component.

Also one of the biggest changes for fallbacks is going against standard best practice of extracting your default English strings from your code. Instead with v2 you'll be able to author the default strings _inside_ the component where they are used. I wrote a [Babel plugin](https://github.com/yahoo/babel-plugin-react-intl) that will extract the messages from the components, but leave the source untouched. That way if there's a problem, the English strings are there in the source and can be formatted as the fallback — no worries about network issues, etc. with the translations.

You can checkout this [new example](https://github.com/yahoo/react-intl/tree/v2-dev/examples/translations) to see how the message extraction process works.

**Comment by ericf** [comment]
I will think more about your fallback use case, which is different than the one I'm describing above…

**Comment by glenjamin** [comment]
> The flattening of messages is something I hope to have a discussion around. 

As long as messages are still provided as an object, it's nice and easy to takes a nested object from v1 and flatten it at load or build time.


Babel plugin sounds good as a way to verify that tokens used == tokens defined - especially if it is smart enough to use some of babel's basic evaluation rules to allow simple dynamic / variable usage.

**Comment by ericf** [comment]
For what you're doing, with React Intl v2 I would imagine it would look something like this:

```js
import React, {Component, PropTypes} from 'react';
import {FormattedMessage} from 'react-intl';

class ErrorMessage extends Component {
    renderErrorMessge(errorCode) {
        
    }
    
    render() {
        switch (this.props.errorCode) {
            case 404:
                return (
                    <FormattedMessage
                        id="error.not_found"
                        defaultMessage="Not found."
                    />
                );
            
            case 500:
                return (
                    <FormattedMessage
                        id="error.interal_error"
                        defaultMessage="Internal Server error."
                    />
                );
            
            default:
                return (
                    <FormattedMessage
                        id="error.generic"
                        defaultMessage="There was a problem."
                    />
                );
        }
    }
};

ErrorMessage.propTypes = {
    errorCode: PropTypes.number.isRequired,
};

export default ErrorMessage;
```

**Comment by ericf** [comment]
> Babel plugin sounds good as a way to verify that tokens used == tokens defined - especially if it is smart enough to use some of babel's basic evaluation rules to allow simple dynamic / variable usage.

Yeah, adding variation would be great, but probably very hard to do since people will likely just pass `this.props` in as the values to the message. I'm currently using some of Babel's evaluation features, but it would be great to have you take a look at the plugin and let me know how I can make it better :)

**Comment by ericf** [comment]
See: #162
