### ISSUE TITLE
"US" prefixed when using currency on server

### ISSUE THREAD

**Issue by babsonmatt** [yahoo/react-intl#140]
Any ideas what might be prefixing "US" to the result? Right now it's causing an inconsistency between server/client in a universal (isomorphic) app.

Seems that Intl rc-4 works fine standalone, but when using react-intl FormattedNumber 'US' is prefixed.

Thanks!

**Comment by caridy** [comment]
what locale are you using?

**Comment by babsonmatt** [comment]
@caridy thanks for the quick response!

Just starting out with React-Intl (apologies ahead of time if we've made a mistake) so we attempted to run the following simple example universally (isomorphically):

`locales={['en-US']}`

```<FormattedNumber value={1000} style="currency" currency="USD" />```

This produced the following error in the browser:
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) =".161eec7de68.0.0">$1,000</span></div><
 (server) =".161eec7de68.0.0">US$1,000.00</span></ 
```

We then ran a simple test using Intl.js on the server:
```
Intl = require('intl');
var number = 1000;
console.log(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD'}).format(number));
```

Which outputted: `$1,000.00` (With 2 decimal places)

So it appears Intl.js rc-4 appends 2 decimal places while the React-intl example above does not.  It also appears that React-intl is prepending 'US' to the result on the server but not the client causing the error above.

Hope this is of some help, thanks!

**Comment by babsonmatt** [comment]
Update: Turns out locales wasn't being passed down, ugh.  Correcting this resolves the US being prepended on the server.  That being said, server still outputs 2 decimal places, while client does not.  Using `minimumFractionDigits={2}` corrects this.

**Comment by caridy** [comment]
@babsonmatt yeah, that what I was suspecting. As for the 2 decimals, that's a bug in V8. You can check FF, and you will see that it also adds the 2 digits. But your solution is the right thing to do, just be more specific, to force the right number of digits.

**Comment by babsonmatt** [comment]
@caridy Thanks for the help
