### ISSUE TITLE
Allow use react-intl to be used without a mixin. 

### ISSUE THREAD

**Issue by 3den** [yahoo/react-intl#141]
It would be nice if we could simplify the API to be able to use the react-intl without a requiring a mixing.

```js
var FormattedMessage  = ReactIntl.FormattedMessage;
var FormattedRelative = ReactIntl.FormattedRelative;

var PostMeta = React.createClass({
    render: function () {
        return (
            <FormattedMessage
                message="post.meta"
                num={this.props.post.comments.length}
                ago={<FormattedRelative value={this.props.post.date} />} />
        );
    }
});
```

In that case the messages and locale can be passed down as props or in the context.

**Comment by 3den** [comment]
cc: @ericf

**Comment by caridy** [comment]
Well, you could do that today, but you have to provide the right context.

In any case, @ericf is working on some refactor that will align better with the future React :)

**Comment by 3den** [comment]
@caridy thanks for the reply, we already have the right context, can you show me an example of how to get the translation without using the mixin?

**Comment by caridy** [comment]
ah, @3den, I was referencing to the fact that you can implement your own resolver for messages, using whatever technique you want, maybe a HOC, or a global registry, inheritance, etc, then you don't have to use `this.getIntlMessage()` at all, which means the mixin is not needed in your component. Of course, you will have to implement the resolver, which `getIntlMessage` already does for you in some degree, but in a very dummy way.

**Comment by ericf** [comment]
Yeah, today the `message` prop expects the string that should be formatted, you can provide that however you want and not need to use `this.getMessage()` that the Mixin provides.

**Comment by 3den** [comment]
IMHO the problem is because we need to use composition (through the component) and inheritance (through the mixing) at the same time. True, we can write our custom components that wraps both but it would be very nice to have that component provided by the `react-intl` itself. 

Also on the project I am working on we are trying to reduce the amount of mixins, and seems like in this case we could have a nice high level component that does the job out of the box. In that case I would expect all useless bellow to work.

```js
 // Gets the translation for "post.meta" passing the vars "num" and "ago"
 <FormattedMessage
           message="post.meta"
           num={this.props.post.comments.length}
           ago={<FormattedRelative value={this.props.post.date} />} 
 />

 // since there is no translation for the passed "message" it is used as it is
 // so this would return "My name is Frodo"
 <FormattedMessage
           message="My name is {name}"
           name="Frodo"
 />

var intlData = {
    locales : ['en-US'],
    messages: {
       hello: "Hi, {name}!"
    }
};

 // You can still pass custom Intl if you don't want to load it from "context"
 // this would return "Hi, Bilbo Baggins!"
 <FormattedMessage
           intl={intlData}
           message="hello"
           name="Bilbo Baggins"
 />
```

**Comment by chrismcv** [comment]
would something like `childContextTypes` not be able to provide something like this?

**Comment by caridy** [comment]
@3den right. The next generation of this pkg will facilitate this by using the concept of an ID for messages, we are still working out the details. The reason why we do not support what you're proposing is because it is ambiguous, how can you know if `foo.com` is a message of a path? and how `post.meta` should be resolved? For that reason, in the current version, we only accept messages, and any resolution should happen in userland or using the mixin.

**Comment by 3den** [comment]
@caridy In the example above I would always try to get the translation for message and if it does not exist use it as it is. 

```js
var intlData = {
    locales : ['en-US'],
    messages: {
       hello: "Hi, {name}!"
    }
};

 // this would return "Hi, Bilbo Baggins!"
 <FormattedMessage intl={intlData} message="hello" name="Bilbo Baggins" />

 // this would return "hi"
 <FormattedMessage intl={intlData} message="hi" />
```

An other way we can do it is by having 2 components one that is exactly what we have now, and an other that does the translation.

**Comment by caridy** [comment]
@3den again, we think about all these options, and made a decision for v1, specifically to protect developers for ambiguity and obscure behaviors, and we are actively working on v2 to provide more flexibility. we do not plan to patch the current behavior, you will have to workaround the current limitations until we release the next major release.

**Comment by 3den** [comment]
Sounds good, thanks for the feedback guys :+1:

**Comment by ericf** [comment]
You can checkout the updated code in the [`v2-dev` branch](https://github.com/yahoo/react-intl/tree/v2-dev).
