### ISSUE TITLE
`style` prop conflicts with standard HTML attribute

### ISSUE THREAD

**Issue by harlanlewis** [yahoo/react-intl#142]
`FormattedNumber`'s use of `style` as the prop to set currency/percent/etc conflicts with the standard HTML attribute used for CSS.

Reading through some of the other issues, it looks like the recommended approach to styling react-intl is to wrap `FormattedNumber` in another element, which I won't debate here.

However, this does cause problems with other tools expecting HTML standard usage of the `style` prop. For example, [babel-plugin-react-autoprefix](https://github.com/UXtemple/babel-plugin-react-autoprefix) autoprefixes react inline styles (as the name might suggest) by looking for `style` and then transforming the string, but fails when it runs into unexpected values (for example, an object) in the `style` prop. The autoprefixer plugin could certainly improve its error handling, but it seems that `style` (and other HTML standard attributes in general) would be safer if considered reserved and unavailable for component props.

**Comment by caridy** [comment]
@harlanlewis we will look into this.

**Comment by harlanlewis** [comment]
Great to hear, thank you!

**Comment by ericf** [comment]
It's not feasible to consider all HTML attribute names as reserved; e.g. `value`. `<FormattedNumber>` maps to the `Intl.NumberFormat` API on purpose and we don't want to change this. There's some who feel that you shouldn't pass `style` or `className` props to custom components, and I'm in that camp. My recommendation would be to switch the babel plugin to add an option to only consider HTML primitive components when extracting styles.
