### ISSUE TITLE
Currency Questions

### ISSUE THREAD

**Issue by chrismcv** [yahoo/react-intl#145]
Hi, 
I've 2 question on currency formatting.

1) Possible bug....
```
        <FormattedNumber
            value={45.90} 
            style="currency"
            currency="GBP"
             />
``` 
This is outputting `£45.9`, is there a way to get the second zero?

2) Our application is single currency, so if someone uses it with US locale it would show $45.90, or if UK £45.90... is there a way I can get "default" locale currency formatting? Do I just remove `currency="GBP"`?

Thanks, 
Chris

**Comment by caridy** [comment]
@chrismcv this is not a problem with the component, but with the underlaying infrastructure for format numbers. A quick test reveals that you're probably experimenting this in chrome only (or nodejs for the matter since they use the same engine: v8):

```
// Firefox
> new IntlPolyfill.NumberFormat('en-UK', {currency: "GBP", style: "currency"}).format(45.90)
"£945.90"
> new Intl.NumberFormat('en-UK', {currency: "GBP", style: "currency"}).format(45.90)
"£45.90"

// chrome
> new Intl.NumberFormat('en-UK', {currency: "GBP", style: "currency"}).format(45.90)
"£45.9"
> new IntlPolyfill.NumberFormat('en-UK', {currency: "GBP", style: "currency"}).format(45.90)
"£45.90"
```

 Feel free to open a bug for chrome.

**Comment by ericf** [comment]
Set the `minimumFractionDigits` and `maximumFractionDigits` props: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by jpierson** [comment]
@chrismcv wouldn't it be en-GB and not en-UK? (reference http://stackoverflow.com/questions/7296262/is-en-uk-an-illegal-locale)
