### ISSUE TITLE
Document the whole API...?

### ISSUE THREAD

**Issue by jhicken** [yahoo/react-intl#146]
So I have 2 concerns. First lets say I create a custom 'format'.  It should look something like the below code. I may have missed something but I didn't find any documentation on all the magic strings.
e.g. 'number', '2-digit', 'long'

```
date: {
  'short': {
    month: 'numeric',
    day  : 'numeric',
    year : '2-digit'
  }
}
```

It also looks like they change depending on what they are used with. (ex1 is valid. ex2 is invalid.) 
ex-1
```
<FormattedDate
  value={updated_at}
  day="numeric"
  month="long"/>
```
ex-2
```
<FormattedDate
  value={updated_at}
  day="long"
  month="long"/>
```

Me second question may be resolved by the first one.

How do I produce this?
'Jul 6th'
the above example ex-1 produces
'July 6'

**Comment by jhicken** [comment]
I found an answer to my first problem. I don't know if ya'll think its worthy to be in the documentation.

From the ecma-402 spec.
http://www.ecma-international.org/ecma-402/1.0/
<img width="514" alt="screen shot 2015-08-13 at 2 00 42 pm" src="https://cloud.githubusercontent.com/assets/5297942/9260255/df7efc36-41c3-11e5-825f-db97cbeb4364.png">

**Comment by caridy** [comment]
I think we have provided links to MDN, specifically https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat, which covers all this extensibly. But yes, maybe it will be easier to just bring some of that into formatjs website directly.

**Comment by jhicken** [comment]
Yeah they are there. I just missed them. I ended up digging through the different standards docs that the the project docs said it was built against. 

I personally would find it very helpful to have the some of this information put into the docs. Mostly for things like strings that I am am never going to remember.

**Comment by jhicken** [comment]
One other question on this I don't see anything about date ordinals in those docs. Am I missing something?
'6th'

**Comment by ericf** [comment]
The API is now documented on the wiki: https://github.com/yahoo/react-intl/wiki/API
