### ISSUE TITLE
Any plans to add parsing of dates/numbers?

### ISSUE THREAD

**Issue by box-turtle** [yahoo/react-intl#148]
It seems redundant to have to include something like globalize or moment.js to support parsing of form input.

**Comment by caridy** [comment]
this is part of the format.js umbrella of libraries, which is focused on formatting, for parsing, you will have to use a different library. IMO, parsing is more on the realm of the business logic rather than presentation.

**Comment by ericf** [comment]
There's not plan to add parsing support, other than what's already built into JavaScript.
