### ISSUE TITLE
Date formatting with safari

### ISSUE THREAD

**Issue by benzen** [yahoo/react-intl#149]
Doing this doesn't give always the same result on safari 8

When using the reactIntl mixin
````
let d = new Date();
d.setMonth(i);
this.formatDate(d, {month: 'long'})
````
On chrome it give me 'January' looks like normal.
On Safari it depends:
  sometimes i see 'january 2015' and somother i see 'janury'.

Is this related to https://github.com/andyearnshaw/Intl.js/issues/107

**Comment by benzen** [comment]
Please close this. it seems to be an issue with browser cache

**Comment by caridy** [comment]
@benzen yeah, the polyfill has that particular issue. We are tracking that issue here: https://github.com/andyearnshaw/Intl.js/issues/125
