### ISSUE TITLE
Problems with Browserify + (Safari / iOS )

### ISSUE THREAD

**Issue by lucasfeliciano** [yahoo/react-intl#150]
Hello there

I'm building a application using React + Flux + Browserify and on Chrome/Firefox works with no problems, but when I was trying to run it on Safari I got this error and my application did not render.

`ReferenceError: Can't find variable: Intl`

To fix it I had to install the intl module from npm and require in my code manually.

After fix that problem another one started to be thrown on console:

`ReferenceError: No locale data has been provided for this object yet.`

I'm stuck on this one, if some one know something about it I'll appreciate

**Comment by caridy** [comment]
https://github.com/andyearnshaw/Intl.js#getting-started
