### ISSUE TITLE
FormattedDate different behaviour on the server/client

### ISSUE THREAD

**Issue by latviancoder** [yahoo/react-intl#151]
I am building an isomorphic application and trying to understand following inconsistency.

I have a component with these two lines:

```javascript
<FormattedDate value="01.01.2015" day="numeric" month="long" year="numeric" />
<FormattedRelative value="01.01.2015" />
```

When I am rendering this component on the client with german locale, I get correct result:

*1. Januar 2015
vor 8 Monaten*

Then I am trying to render the same component on the server:

```javascript
React.renderToString(React.createElement(MyComponent, {locales: 'de'}))
```

This is what I get:

*January 1, 2015* <- **suddenly en-US**
*vor 8 Monaten*

**Comment by gpbl** [comment]
AFAIK `<FormatDate>` uses the locale-data available with `Intl`, while `<FormattedRelative>` include its own locales from [intl-relativeformat](https://github.com/yahoo/intl-relativeformat). `Intl` indeed does not provide any way to relative format a Date object. 

In your case, it seems that you are not polyfilling Intl on node with the german locale-data, as [explained here](http://formatjs.io/guides/runtime-environments/#polyfill-node), so `Intl` falls back to english. Perhaps this is your case?

**Comment by ericf** [comment]
Yup that's correct, the polyfilling Node link above is what you need.

**Comment by latviancoder** [comment]
it worked after some trying, thanks.

**Comment by ericf** [comment]
> it worked after some trying, thanks.

@latviancoder if there's something you had to do different than what's documented, let us know so we can update the docs for the next person. Thanks and glad to hear you got it working!

**Comment by latviancoder** [comment]
Well, I didn't do anything different, I just found that documentation could be a little bit more specific.

My first problem was I required some of react components *before* polyfilling intl. So in the following case date will remain english.

```javascript
require('intl');

var Hello = require('./src/components/Hello');

Intl.NumberFormat = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;

React.renderToString(React.createElement(Hello, {locales: 'de'}));
```

This will work:

```javascript
require('intl');

Intl.NumberFormat = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;

var Hello = require('./src/components/Hello');

React.renderToString(React.createElement(Hello, {locales: 'de'}));
```

Then I was doing stuff like `require('intl/locale-data/jsonp/de.js')`, although it wasn't necessary.
