### ISSUE TITLE
Allow className prop in components

### ISSUE THREAD

**Issue by laurentvd** [yahoo/react-intl#152]
The current components allow you to override the default `tagName` (`span`). Would it make sense to do the same with `className`? I often need to wrap my `FormattedMessage` components, just to add a class to them.

**Comment by ericf** [comment]
Wrapping them is intended. Think of React Intl's components are replacement for plain text — which you'd wrap to style.

On the [`v2-dev` branch](https://github.com/yahoo/react-intl/tree/v2-dev) I currently have support for function-as-child and an imperative API to return strings. I'm still up in the air with function-as-child, but I think it might be the official way to override the tagname for cases like SVG.

**Style `<Formatted*>` Component:**
```js
<span className="my-class-name">
    <FormattedNumber value={1000} />
</span>
```

**Render `<Formatted*>` Component in SVG:**
```js
<FormattedNumber value={1000}>
    {(formattedNumber) => <tspan>{formattedNumber}</tspan>}
</FormattedNumber>

```

**Comment by laurentvd** [comment]
Alright, I understand your reasoning, comparing a `<Formatted*>` to plain text. In that sense, it wouldn't be logical to be able to change the `tagName` either IMO. By the way, is there a changelog / breaking changes log for v2 somewhere?

**Comment by ericf** [comment]
Not yet. Still working on integrating into production apps to work out kinks and figure out the upgrade path.

**Comment by caccialdo** [comment]
Could we go as far as allowing any other attribute to be passed to the rendered element?

For e.g.: I want my `FormattedMessage` component to return an `<option selected disabled/>` in which case I would write, `<FormattedMessage tagName="option" selected disabled />`.

**Comment by ericf** [comment]
@caccialdo see my comment above: https://github.com/yahoo/react-intl/issues/152#issuecomment-134674213

There's no plan to make the `<Formatted*>` components support all possible props — [that's not a good design pattern](https://youtu.be/Zemce4Y1Y-A?t=2m14s). You'll be able to use the function-as-child pattern or the API that'll be at `this.context.intl.formatMessage()`, which will always return a string (instead of a React Element).

**Comment by ericf** [comment]
See: #162
