### ISSUE TITLE
v2-dev branch: package.json's browser location doesn't exist

### ISSUE THREAD

**Issue by ryan1234** [yahoo/react-intl#154]
I apologize for filing an issue on a branch as if it was something to be officially supported. :smile: 

https://github.com/yahoo/react-intl/blob/v2-dev/package.json#L26

```{javascript}
...
  },
  "main": "lib/react-intl-with-locales.js",
  "jsnext:main": "src/react-intl.js",
  "browser": "./lib/react-intl.js",
  "browserify-shim": {
    "react": "global:React"
  },
...
```
The `./lib` directory doesn't exist in the repository and it isn't created when I install the dependency, so I've had to go into `my_project/node_modules/react-int` and run `npm run build:lib` manually.

I'm wondering if there is something I'm missing or what the best way forward is to remove the manual step.

**Comment by ericf** [comment]
When the package is published to npm the `lib/` dir will be there. If you're trying to use it locally then you'll need to run the build. You should clone the Git repo and use `npm link`.
