### ISSUE TITLE
Jest testing and react-intl

### ISSUE THREAD

**Issue by dinodsaurus** [yahoo/react-intl#156]
Every time I add `react-intl` to a component my tests for that component fail and it says:
 `TypeError: Path must be a string. Received undefined`.
 I have `intl` package installed so I dont think that is the problem.
Did someone encounter similar problem and how would you suggest to solve it ?

**Comment by ericf** [comment]
Is this still an issue for you?

**Comment by dinodsaurus** [comment]
Nope, works like a charm now
