### ISSUE TITLE
react-intl v2-dev: Support for namespaced messages

### ISSUE THREAD

**Issue by bunkat** [yahoo/react-intl#159]
In the upcoming release, are namespaced messages no longer going to be supported? I see that the new message lookup is just:

````
let message = messages && messages[id];
````

Which causes something like this to fail even though it used to succeed.

````
const messages = { label: { active: 'Active' } };

<FormattedMessage id="label.active" />
````

Is it the expectation that the messages file should be converted to a flat namespace?

**Comment by ericf** [comment]
Yes, flat object. You'll be able to have multiple groups of messages though, just use multiple `<IntlProvider>` element.

**Comment by ericf** [comment]
An example on how to flatten is provided here: https://github.com/yahoo/react-intl/issues/193#issuecomment-152019363
