### ISSUE TITLE
Testing v2

### ISSUE THREAD

**Issue by kyleboyle** [yahoo/react-intl#160]
I am using babel/es6 in my project and am getting an error with 1.2.0:
```
ERROR in ./~/react-intl/src/react.js
Module parse failed: /node_modules/react-intl/src/react.js Line 7: Unexpected token
You may need an appropriate loader to handle this file type.
| // supports external modules. This is a hack for now that provides the local
| // modules a referece to React.
| export default React;
| 
 @ ./~/react-intl/index.js 6:15-31
```
Is it possible to test v2 yet? I switched my package.json dep to:

    "react-intl": "yahoo/react-intl#v2"

but webpack is now giving me an error when i try to include it:

    Module not found: Error: Cannot resolve module 'react-intl'

My /node_modules/react-intl does contain the code from the v2 branch.

**Comment by ericf** [comment]
We have a build and you're trying to run the code in src/, clone, build, and link if you want to try before a preview release is on npm.

**Comment by kyleboyle** [comment]
Ok cool, I have it running now. It seems that all of the child react components of IntlProvider are getting a blank context though.

**Comment by ericf** [comment]
See: #162

**Comment by kyleboyle** [comment]
thanks for your work on the preview release, everything is working
