### ISSUE TITLE
IntlRelativeFormat not working in npm build of react-intl@next

### ISSUE THREAD

**Issue by wuzzeb** [yahoo/react-intl#166]
Steps to see the bug:

~~~
npm install react-intl@next
~~~

Use a simple html file such as

~~~
<html>
  <head>
    <script src="node_modules/react/dist/react.js"></script>
    <script src="node_modules/react-intl/dist/react-intl.js"></script>
  </head>
  <body>
    <p>Hello world!</p>
  </body>
</html>
~~~

Disable javascript source maps (I use chrome, it is in the settings).  Then place a breakpoint on line 2787 in `react-intl.js`.  The relavent lines are

~~~
var _intlMessageformat = require(5);

var _intlMessageformat2 = _interopRequireDefault(_intlMessageformat);

var _intlRelativeformat = require(14);

var _intlRelativeformat2 = _interopRequireDefault(_intlRelativeformat);
~~~

where the last line is line number 2787.  When the breakpoint pauses at the last line, use the console to see that `_intlMessageFormat` and `_intlRelativeFormat` are identical and both equal to the MessageFormat class.  Somehow, the `require(14)` call is pulling in the MessageFormat class instead of the RelativeFormat.  Looking at `react-intl.js`, the RelativeFormat class seems to be in 15, not 14.  Since _intlRelativeformat variable contains MessageFormat, I get an error later when using the FormattedRelative element.  In particular, the MessageFormat class is passed the locale as the message to translate and an empty object for the locales.

Looks like some bug in browserfy during the dist step?  I looked through the source code and it seems that it imports intl-relativeformat correctly.

**Comment by ericf** [comment]
What version of Browserify are you using, this is a known Browserify bug, if you update to the latest it should go away. Reopen if that doesn't fix it.

**Comment by wuzzeb** [comment]
I wasn't using browserfy at all, it was exactly the file uploaded to npm, so whoever built and uploaded the package to npm will need to update browserfy.  For now I can rebuild using the latest browserfy.

**Comment by ericf** [comment]
Okay I see the issue now…

**Comment by ericf** [comment]
I traced this down to the `bundle-collapser` Browserify plugin not working correctly.
