### ISSUE TITLE
Testing: How to provide `this.context.intl` to child components in tests

### ISSUE THREAD

**Issue by okonet** [yahoo/react-intl#170]
I'm using v2 rc1 and wondering what is the strategy would be with testing? Right now all the `Formatted*` components require intl to be defined in the context. This is happening in a HOC `IntlProvider` which wraps my app, but not the component I'm testing resulting in errors like:

```
TypeError: Cannot read property 'formatPlural' of undefined
```

What approach would you suggest to work around this without rewriting all the tests?

**Comment by okonet** [comment]
I've found this https://github.com/karlbright/react-stub-context utility and using it for now but IMO it would be better to get a test helper.

**Comment by jopdeklein** [comment]
I am facing the same issue.

I might be misinterpreting, but the following description seems to hint that passing `intl` as a `prop` should be possible / desirable:
```
This function is used to wrap a component and will inject the intl context object created by the <IntlProvider> as a prop on the wrapped component. Using the HOC factory function alleviates the need for context to be a part of the public API.
``` 
(source: https://github.com/yahoo/react-intl/releases/tag/v2.0.0-pr-2)

But this seems to conflict with the way the `assertIntlContext` is currently implemented in the formatters:  https://github.com/yahoo/react-intl/blob/da28f2fdfd22c389225373be8f059571ee109646/src/components/number.js#L14

In any case, judging by the code , wouldn't it be possible to treat the `context` as a fallback when the intl `prop` is defined?

**Comment by ikhilko** [comment]
any progress here?

**Comment by ericf** [comment]
React's Test Utilities has [shallow rendering](http://facebook.github.io/react/docs/test-utils.html#shallow-rendering) support. You can pass `context` like this:

```js
shallowRenderer.render(<Component />, context);
```

I will provide more details as I fill out React Intl's test suite. The approach a few apps are using is a wrapper component which stubs out `context.intl` along with the flux stuff they have on context.

(Sorry I wrote something longer here two weekends ago, but forgot to submit it and lost what I had.)

**Comment by peeter-tomberg** [comment]
This is still a problem. I've currently started using the following approach:

```javascript
        view = ReactTestUtils.renderIntoDocument(
            <IntlProvider locale='en'>
                <NotificationList notifications={notifications}/>
            </IntlProvider>
        );
```

Where I wrap my component in an IntlProvider just so I can test them. Couldn't get react-stub-context to work.

**Comment by seriallos** [comment]
In case it's useful for anyone, I have a super quick hacky solution working with karma/mocha and the skin-deep helper lib.  This may also be applicable to the default shallow rendering helpers or another helper lib like enzyme.

I initially played with testing with `<IntlProvider>` but a) that seemed like a lot of overhead/boilerplate for any component which will use react-intl (which will be most) and b) karma using a phantomjs runner doesn't have `Intl` by default and I didn't want to muck with additional polyfills.

My component uses `injectIntl` to wrap my component in order to use `formatMessages` for attributes.

My test looks something like this:

```javascript
// import react, expect, etc from here
import WrappedComponent from './WrappedComponent';
import SkinDeep from 'skin-deep';

// this should be replaced with a stubbing/mocking library but i haven't gotten there yet
function noop() {};
const contextStub = {
    intl: {
        formatDate: noop,
        formatTime: noop,
        formatRelative: noop,
        formatNumber: noop,
        formatPlural: noop,
        formatMessage: noop,
        formatHTMLMessage: noop,
        now: noop,
    },
};

describe('WrappedComponent', () => {
  it('should render a WrappedComponent', () => {
    const tree = SkinDeep.shallowRender(<WrappedComponent />, contextStub);
    // This is the displayName of the wrapped component
    expect(tree.findNode('InjectIntl(Component)')).to.be.an('object');
  }
  it('should render a div in the original component', () => {
    const tree = SkinDeep.shallowRender(<WrappedComponent />, contextStub);
    // dive will render deeper children in skin-deep
    const component = tree.dive(['Component']);
    expect(component.findNode('div')).to.not.equal(false);
  }
});
```

**Comment by ericf** [comment]
Because of shallow rendering only going one level deep, I ended up using the `shallowRenderer.render(component, context)` signature and faking the `intl` context like this: https://github.com/yahoo/react-intl/blob/master/test/unit/components/date.js#L109-L129

**Comment by gregz67** [comment]
New to `react-intl` (and react for that matter).

I have a similar problem with rendering components in a styleguide (https://github.com/theogravity/react-styleguide-generator-alt) where `intl` will not be found on the context.  What is the best practice in a case like this?

Generally would it not be more appropriate for `react-intl` to handle such cases where it does not find `intl` on the context to return some (required) default value?  I would have assumed that was what `defaultMessage` is for on `<formattedMessage>`?

**Comment by ericf** [comment]
@gregz67 instead of polluting every component with `locale`, that information and the translated `messages` need to be passed into the some where, and that's what `<IntlProvider>` is for (along with many other i18n setup stuff.)

**Comment by christhomas** [comment]
I've got a component which is able to use FormattedMessage, but I don't have any methods or formatting functions on the component at all, but the normal, FormattedMessage component is there and functioning ok

**Comment by mirague** [comment]
Here's a handy helper function that will wrap the `intl` context around your tests, if you're using Enzyme. Something similar can be achieved for other frameworks I'm sure:

https://gist.github.com/mirague/c05f4da0d781a9b339b501f1d5d33c37

**Comment by ericf** [comment]
@mirague it would be great if you added these docs here: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#enzyme

**Comment by mirague** [comment]
@ericf Consider it done! Hope it's readable enough, feel free to run a grammar/text check.

**Comment by ericf** [comment]
@mirague thanks!
