### ISSUE TITLE
Changing locales does not change the FormattedRelative string value

### ISSUE THREAD

**Issue by gtoma4** [yahoo/react-intl#173]
I am trying to implement the samples provided on the formatjs.io react-intl page, but I'm having an issue with the FormattedRelative component.  I have a page that recreates the examples for FormattedDate, FormattedNumber, and FormattedRelative.  The FormattedDate and FormattedNumber behave as expected... when changing locales from "en-US" to "es-AR", the formatting is properly updated.  The strings in FormattedRelative however remain in English.  I am new to React and React-Intl.  Any help you can provide is appreciated.

I pass in props.name='Tom'  and props.locales='es-AR'

Here is my component:

import React  from 'react'
import ReactIntl from 'react-intl'

let IntlMixin = ReactIntl.IntlMixin;

export default React.createClass({
    mixins: [IntlMixin],

    render: function() {
        let myNum = 5600;
        let myPercent = 0.9562;
        let myCurrency = 19.95;
        let myDate = new Date();
        let past = Date.now() - (1000*60*60*25); //25 hrs ago
        let nearPresent = Date.now() - (1000*60*60*4); //4 hours ago
        let nearFuture = Date.now() + (1000*60*51); // in 51 minutes
        let future = Date.now() + (1000*60*60*48); // in two days
    
        return (
            <div>
                <p className="greeting">
                    Hello, {this.props.name}!
                </p>

                <p>Today is &nbsp;
                    <ReactIntl.FormattedDate
                        value={myDate}
                        day="numeric"
                        month="long"
                        year="numeric"
                    />
                    &nbsp;(formatted for US English)
                </p>

                <p>Here are some numbers formatted for US English</p>
                    <ul>
                        <li><ReactIntl.FormattedNumber value={myNum} /></li>
                        <li><ReactIntl.FormattedNumber value={myPercent} style="percent" /></li>
                        <li>
                            <ReactIntl.FormattedNumber
                                value={myCurrency}
                                style="currency"
                                currency="USD" />
                        </li>
                    </ul>

                <p> Here are some relative times in US English</p>
                <ul>
                    <li><ReactIntl.FormattedRelative value={past} units="hour"/></li>
                    <li><ReactIntl.FormattedRelative value={nearPresent} /></li>
                    <li><ReactIntl.FormattedRelative value={nearFuture} /></li>
                    <li><ReactIntl.FormattedRelative value={future} /></li>
                </ul>

            </div>
        );
    }
});

**Comment by caridy** [comment]
Are you loading the proper locale data?

**Comment by salagadoola** [comment]
This symptom sounds familiar (`FormattedDate` works, but `FormattedRelative` always in English).

If you are using v1, please take a look at #110 and #103 to see if the `ReactIntl.__addLocaleData(...)` solution helps.

**Comment by gtoma4** [comment]
@caridy - I thought I was loading the proper locale data (passing in locales="es-AR".  I am using webpack to build, so I think the issues referenced by salagadoola are relevant to my problem

@salagadoola - I am using v1.  I'll take a look and see if that helps resolve my problem.

@ericf - Is there an ETA for v2?  My company is just starting a project and it will be our first to include internationalization and I've been tasked with looking into how to do it.  I like whats coming out.  This library will do exactly what I need once I figure out how to use it.   Thanks!

**Comment by ericf** [comment]
@gtoma4 I haven't established a release date. In #162 there's a list of todos and I want to continue gathering feedback both internally (at Yahoo) and externally to make sure the design changes work out. I'd like to align with React 0.14 since it'll introduce braking changes for people, that way they can address React Intl's breaking changes at the same time.

**Comment by yloubry** [comment]
I have tested the same on the 2.0.0-pr-2 and 2.0.0-pr-3 and FormattedRelative remains in English but the other modules are using proper locale formats.

I am adding the locale-data as followed.
<script src="react-intl/dist/locale-data/fr.js"></script>

I see that the ReactIntlLocaleData.fr has all the info

<img width="321" alt="screen shot 2015-10-12 at 3 20 39 pm" src="https://cloud.githubusercontent.com/assets/13892147/10440527/d9a3a806-70f4-11e5-8e0f-370fffd10a00.png">

**Comment by ericf** [comment]
@yloubry We've changed how locale data works in 2.0, you need to explicitly add it to the library, whereas before the locale data modules would register themselves with the library.

```js
ReactIntl.addLocaleData(ReactIntlLocaleData.fr);
```

The reason for the `dist/` files using different global variables is to decouple them. This way both the library and locale data can be `<script async>`.

If you're using modules, the locale data files use UMD. Making these changes allowed us to have the locale data files _provide_ locale data instead of auto-registering it when loaded.

**Comment by yloubry** [comment]
Thanks @ericf for the clarification.

Here is what I had to do to make this work in v2

**In the template page:**
<img width="795" alt="screen shot 2015-10-13 at 2 15 39 pm" src="https://cloud.githubusercontent.com/assets/13892147/10468616/ecc1855a-71b4-11e5-8d47-49b420d0a045.png">

Note: The intl polyfill, React and the locale-data need to be loaded synchronously.
When I was testing with Safari, this would matter.

**In your app:**

import * as ReactIntl from 'react-intl';
ReactIntl.addLocaleData(ReactIntlLocaleData.fr);

Then don't forget to call your Root component with a locale

`<IntlProvider locale={window.App.locale} messages={window.App.messages}>`
   `<App locale />`
`</IntlProvider>`

In the release note, there is a mention that the locale can be added as followed but this did not work for me.

<img width="584" alt="screen shot 2015-10-13 at 2 29 06 pm" src="https://cloud.githubusercontent.com/assets/13892147/10468944/df21541e-71b6-11e5-90cc-1360e3da5148.png">
