### ISSUE TITLE
Object path notation

### ISSUE THREAD

**Issue by jonaswindey** [yahoo/react-intl#174]
I'm using 2.0.0-pr-1 and I'm trying to use objects in my language dictionary like this:

(en.js)

```
export default {
  'test': 'this is a test',
  'test2': {
    'field1': 'test 2 field 1'
  }
}
```

However, I can't access the translation with
`<FormattedMessage id="test2.field1" />`

Is this expected behaviour or can we use nested objects for this?

**Comment by ericf** [comment]
Yeah for v2 I would like to see if we can simplify the to a flat object data structure. You'd need to flatten this before passing it in to `<IntlProvider>`

**Comment by ericf** [comment]
Example on how to flatten the messages is provided here: https://github.com/yahoo/react-intl/issues/193#issuecomment-152019363

**Comment by marcosanfilippo** [comment]
Hi, we're using v2.
Does it mean we cannot use either in API?
The following doesn't work
```
const myDescriptor = { id: 'deep.level.translation' }; // nested structure
const myMessage = formatMessage(myDescriptor, { name });
```

Thanks
