### ISSUE TITLE
Node.js links, docs

### ISSUE THREAD

**Issue by srl295** [yahoo/react-intl#175]
re: http://formatjs.io/guides/runtime-environments/#server
* wiki link is wrong (as is node's README's) should be https://github.com/nodejs/node/wiki/Intl
* v.12.x and also ≥v3.1 have Intl by default. (iojs 1.0…3.0.x had it off).
* You don't have to recompile to get non-English, just pass the path to the full data. Details are in the above wiki link. Plan is for it to be as simple as [an npm install of the right module](https://github.com/nodejs/Intl/issues/11)

**Comment by caridy** [comment]
I have updated Intl.js readme with the corresponding notes from above as well. Thanks @srl295

**Comment by ericf** [comment]
This link has been updated on the website to point to the right Node wiki page.
