### ISSUE TITLE
Do something when message is not found.

### ISSUE THREAD

**Issue by ravloony** [yahoo/react-intl#176]
Is it possible to have some kind of callback fire when a translation is not found?

When I am developing, I would like to be able to call a url to automatically create the missing translation key in the database and simply fill it in later. All I need is some way to pass in a function that gets called with the key when a translation is not found by IntlMixin.getIntlMessage. Then I can use the id and the current locale to add the translation to the db.

Maybe this is possible already, but I couldn't see how.

Thanks!

**Comment by caridy** [comment]
@ravloony this use case is covered by https://github.com/yahoo/react-intl/issues/162

**Comment by ericf** [comment]
@caridy this _exact_ use case of calling a function is not handled in v2.

@ravloony [here's the current `formatMessage()` algorithm](https://github.com/yahoo/react-intl/blob/master/src/format.js#L111-L188) that's part of v2. It supports automatic fallbacks, but does not provide any hooks. Sort of using ES6 Proxies, there isn't currently a way to handle this. Would it help if there was warning message logged to the console?

**Comment by ravloony** [comment]
It would if the message is regexable, as I can override console.warn and parse out the message id. This is only going to happen in development so nasty hacks are not the end of the world I suppose.

**Comment by ericf** [comment]
If you know all your English message ids, and you have your current translated messages files, couldn't you compare each translated messages file against the English one to find the missing message ids that haven't been translated?

**Comment by ericf** [comment]
@ravloony any thoughts on my above question?

**Comment by ravloony** [comment]
In the end I went with declaring default messages in my react components. My translations are database backed so the tenant administrator can change them for that tenant.

So for a given translation
 - I call my translation function with a key and a default
 - The function checks the current translations collection (Backbone) for a match
 - If the key does not exist, it adds it, with the default and returns the default
 - Otherwise it returns the translation

Adding the translation consists of appending the save request to a promise. This way, even if the same key is inserted multiple times, it is eventually consistent in the database, with the latest key translation winning.

The administrator gets a list of keys, with their translations for the current language, which they can modify as they like, with their only constraint being that someone needs to load a given part of the interface once for the administrator to see the translations for that part.

So there are no files to compare.

**Comment by ericf** [comment]
@ravloony, okay cool. I glad you found a solution that works for you. Should I close this issue, or do you have any other feedback on things I can improve related to missing messages?

**Comment by ravloony** [comment]
@ericf No you can close the issue, thanks for the help!
