### ISSUE TITLE
Error with v2 in Safari 9.0

### ISSUE THREAD

**Issue by bartvde** [yahoo/react-intl#180]
Using 2.0.0-pr-2 and react 0.13.3, it works fine in Chrome or Firefox, does this error ring a bell for someone?

![screen shot 2015-10-05 at 11 39 16](https://cloud.githubusercontent.com/assets/319678/10277368/d30f9ba2-6b55-11e5-8b4e-67aaf9b7fa76.png)

**Comment by bartvde** [comment]
Ah I guess I simply need to use the polyfill

**Comment by zkirill** [comment]
For anyone else who stumbles on Safari compatibility issues:
https://github.com/andyearnshaw/Intl.js/#getting-started

Also, I wasn't seeing any errors in my case, it was just silently failing.
