### ISSUE TITLE
Pin version of React to 0.13 for react-intl 1.x

### ISSUE THREAD

**Issue by caccialdo** [yahoo/react-intl#182]
Currently `v1.2.0` is *very* loose with its React version dependency: https://github.com/yahoo/react-intl/blob/v1.2.0/package.json#L33

Problem is: react-intl breaks with React 0.14. An easy fix for v1 would be to just pin it `~0.13`

**Comment by ericf** [comment]
Okay, will do and release `v1.2.1`.
