### ISSUE TITLE
Not working on server side. "ReferenceError: Intl is not defined"

### ISSUE THREAD

**Issue by hackwaly** [yahoo/react-intl#183]
It's an implicitly using browser global variable.
https://github.com/yahoo/react-intl/blob/v2.0.0-pr-3/src/components/intl.js#L27

**Comment by okuryu** [comment]
You probably need to have the Intl Polyfill.
http://formatjs.io/guides/runtime-environments/

**Comment by hackwaly** [comment]
Thanks. I missed that.
