### ISSUE TITLE
A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by MintyAnt** [yahoo/react-intl#189]
While attempting to use the latest version of react and react-intl, I encounter the following error:

`Uncaught Error: Invariant Violation: App.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`

I'm using the `IntlMixin` and `FormattedNumber` according to how the getting started docs state I should use them.

My code is here:
https://bitbucket.org/MintyAnt/react_intl_test

Maybe i'm just using it wrong?

**Comment by claflamme** [comment]
This happens to me as well, with `FormattedMessage`. I get the above error in addition to:
`Warning: FormattedMessage(...): React component classes must extend React.Component.`

 I was using `1.2.0` without issue but I started getting the error with `1.2.1`.

**Comment by bluedaniel** [comment]
It's because `v1.2.1` does not support React `0.14`. I just had this too.

**Comment by ericf** [comment]
I was reported in #182 that React Intl doesn't work with React 0.14, and with 0.14 being such a massive change, the decision was to pin down 1.x to only work up to React 0.13.3.

**Comment by claflamme** [comment]
That's definitely reasonable, thanks for the replies.

**Comment by trevorbernard** [comment]
@ericf is there a timeline on when a version of react-intl will be support react 0.14?

**Comment by ericf** [comment]
@trevorbernard working on getting React Intl v2 finished up, which supports React 0.14. There have been 3 preview releases and you can track progress here: #162

**Comment by dennisroethig** [comment]
Are there any known issues using React 0.14 with react-intl 1.2.0?

I ran into the mentioned error above and tried pinning react-intl to 1.2.0 and everything seems to work fine (mostly `FormattedMessage` and `FormattedNumber` usage). I wasn't able to find any further information about what exactly is incompatible with the new React version.

```
"react": "^0.14.0",
"react-dom": "^0.14.0",
"react-intl": "1.2.0",
```

Thought I'd ask here before I wrap my head around the v2 updates.

Thanks in advance!

**Comment by trevorbernard** [comment]
Porting to react-intl@next was pretty painless. I was never a big fan of IntlMixin anyway. Good job guys

**Comment by ericf** [comment]
@dennisroethig there are many things that you can do in React 0.14 that aren't supported with React Intl v1 and my focus is working on v2 which is a much better. Feel free to ping me or create an issue if you have questions about upgrading to v2. Also there's #193 where I've detailed some things to look at when upgrading.

**Comment by ericf** [comment]
Closing this for now. People can peg to `v1.2.0` if it's working for them in a React 0.14 environment.
