### ISSUE TITLE
Bad pluralization with few keyword

### ISSUE THREAD

**Issue by alesculek** [yahoo/react-intl#190]
Hi,

I've tried 2.0.0-pr-3 and testing translations on czech language (based on your example)

I have this translation for czech:

```
'main.greeting': `
  Vítej {name}, {unreadCount, plural,
    =0 {nemáš žádnou novou zprávu}
    one {máš {formattedUnreadCount} novou zprávu}
    few {máš {formattedUnreadCount} nové zprávy}
    other {máš {formattedUnreadCount} nových zpráv}
  }.
`,
```

By CLDR link from README *few* is 2..4 but when I'm providing formattedUnreadCount in this range, translation still returning version from *other* (formattedUnreadCount > 5)

Just work-arounded by =2 .. =3 .. =4 .. but it's annoying :)
If I could help you somehow, provide more informations, test something, etc. feel free to reply.

Thanks.

**Comment by alesculek** [comment]
My render method:

```
render() {
  const {locale, messages} = this.getIntl();
  return (
    <IntlProvider locale={locale} messages={messages}>
      <TranslatedApp currentLanguage={this.state.currentLanguage} handleChangeLanguage={language => this.setLanguage(language)}>
        {this.props.children}
      </TranslatedApp>
    </IntlProvider>
  );
}
```
where locale is "cs-CZ"

**Comment by ericf** [comment]
@alesculek are you loading the `dist/locale-data-/cs.js` and adding it via `addLocaleData()`? This has changed from v1, and it's not fully documented yet…

**Comment by agat** [comment]
Hello, i have same issue with plurals. It looks as if the `addLocaleData` not work properly.

I load locale data and call `addLocaleData`. Example code:

````
import {IntlProvider, addLocaleData} from 'react-intl';
import ru from 'react-intl/dist/locale-data/ru';

addLocaleData(ru);

ReactDOM.render(
    <IntlProvider locale="ru">
        <App />
    </IntlProvider>,
    document.getElementById('app')
);
````

**Comment by alesculek** [comment]
@ericf Thanks! that worked for me. But as gulp suggest me, I'm importing cs from lib/locale-data
