### ISSUE TITLE
react-starter-kit

### ISSUE THREAD

**Issue by andreasi** [yahoo/react-intl#192]
Recently I started developing a new application using react-starter-kit (https://github.com/kriasoft/react-starter-kit). It works well and it fits my needs. I have problem though implementing internationalization/localization using yahoo's react-intl. It seems that I can't get access to the this.getIntlMessage method of the Intl provider. Additionally when I import the "Formatted..." components, I get an error saying the every component must extend React's Component class.Has anyone been able to combine the 2 libraries successfully? Thanks in advance.

**Comment by alesculek** [comment]
Which version of react-intl are you using? If you are using this.getIntlMessage(), then it looks like version with mixins. But in ES6 classes mixins are no longer available. But try look at example in this repository https://github.com/yahoo/react-intl/blob/master/examples/translations/src/client/index.js it might help you. I think that documentation on website is not up to date with new version, so this could point you how to implement translations.

For any further help will be great to provide versions and fragments of code that are you using.

**Comment by ericf** [comment]
@alesculek is corrected about the docs still being for v1. As part of the v2 RC process, I will update our staging website with v2's WIP docs.

**Comment by zkirill** [comment]
@ericf Is your staging website publicly accessible?

**Comment by ericf** [comment]
@zkirill it is, but currently shows the same thing as the production website: http://stage.formatjs.io/

**Comment by ericf** [comment]
Docs will be moving to the Wiki, I've started adding some: https://github.com/yahoo/react-intl/wiki
