### ISSUE TITLE
Wrong date format in Chinese

### ISSUE THREAD

**Issue by neversay** [yahoo/react-intl#194]
< FormattedDate value={new Date()} month="long" year="numeric" locales={'zh'} / >

I got something like:
2015年八月月

But it should be 
2015年八月

The character 月 (month) appears twice.

**Comment by ericf** [comment]
Which browser/runtime is this happening on? It's likely a bug either in the browser or the data in the Intl.js polyfill.

**Comment by mapmeld** [comment]
@ericf @neversay this is a known bug in the Intl.js polyfill https://github.com/andyearnshaw/Intl.js/issues/69

**Comment by salagadoola** [comment]
Latest commit https://github.com/yahoo/react-intl/commit/c05e63db38a8e8a163a9d64b557731a7deb7abb8 upgraded Intl.js version to 1.2.1 which has fixed this issue.
