### ISSUE TITLE
Make FormattedNumber shows "." in thousands and "," in decimals with locale

### ISSUE THREAD

**Issue by titanve** [yahoo/react-intl#199]
Hello!, where can I get support? I want to format a number with FormattedNumber so it shows "." in thousands and "," in decimals.

Thank you and sorry if this is not the support forum.

**Comment by ericf** [comment]
@titanve you'll have to provide more information for someone to be able to help. The thousands separator is related to the locale that you're using.

**Comment by titanve** [comment]
Hello @ericf,

I want to use the locale "es" (español - spanish) with webpack. I have implemented the InlProvider but I cannot make it work with the "es" locale.

Thank you

**Comment by ericf** [comment]
You must load the `locale-data/es` module as well. If you only need to support ES, then you can bundle it with your app code:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {addLocaleData, IntlProvider} from 'react-intl';
import esLocaleData from 'react-intl/locale-data/es';
import App from './app';

addLocaleData(esLocaleData);

ReactDOM.render(
    <IntlProvider locale="es">
        <App />
    </IntlProvider>,
    document.getElementById('container')
);
```

**Comment by titanve** [comment]
@ericf Thank you for your help. I'm gonna try that.

Have a good afternoon.

**Comment by titanve** [comment]
Dear @ericf 
Why are there differences between the way Firefox and Chrome show the numbers? I guess are because the JS engines they use, so, how can I get the same formatted number?

Thank you

**Comment by ericf** [comment]
Yes there are some browser variations as they implement things differently. But I'm surprised you're getting "43 966,00" without a decimal. What version of Firefox are you using?

**Comment by titanve** [comment]
@ericf I checked and it was Firefox ver. 41.0.2 because I noticed that there was an update and after the Firefox was updated to ver. 42.0 the bug was fixed, now Firefox shows 43.966,00 VEF. 

Why is it showing the Warning? it says critical dependencies.

Thank you

**Comment by ericf** [comment]
I'm not sure, what version of Node.js? If you're requiring the locale data from Node, you could use `lib/locale-data/es.js` instead.

**Comment by titanve** [comment]
@ericf My nodejs version is 5.0.0

`lib`?? I don't know how to use that...

Do I have to create a folder called `lib` ?

**Comment by ericf** [comment]
Yes, you should see it in your `node_modules/` dir.
