### ISSUE TITLE
Making formatMessage / getIntlMessage crash-safe?

### ISSUE THREAD

**Issue by Francoyy** [yahoo/react-intl#200]
Hello,

In many FE systems we dynamically apply translation methods to API values. Which means we can not be totally sure if the translation is in our Yala files or not.

For example: Yahoo Local has different providers (Yelp, TripAdvisor, Yahoo). If some day there is a new partner on API side, it will totally crash the FE and this is not appropriate.

Instead of using wrapper functions with try/catch, is it possible that react-intl directly handles such case?

- getIntlMessage:  If translation string missing > return original string
- formatMessage: If JSON parameters have too many variables, or too few, just do best effort and format what can be formatted, return the original string for the test.

Essentially I would like to understand why those functions currently crash easily, as no FE system wants to show a big stacktrace to the user.
Thanks!

**Comment by Francoyy** [comment]
I can see mentions of fallbacks in https://github.com/yahoo/react-intl/issues/162 but those seem to be language fallbacks or default string fallbacks?

I understand that we don't like silent errors. But say my translation key/value is "SUMMER_SALE": "Summer Sale". (The key comes from API, my scope is FE, I can not guarantee all the values that API will always return)

Do we:
- Want to show a huge stracktrace just because there was no translation found?
- Show the key instead of the value "SUMMER_SALE", which is ugly and deserves someone to create a ticket on my FE property, but at least doesn't crash to the user's face?

Any other suggestions or workarounds?

**Comment by ericf** [comment]
React Intl v2 has been rewritten to include graceful translation fallbacks. You can see the algorithm here:
https://github.com/yahoo/react-intl/blob/master/src/format.js#L117-L191

**Comment by ericf** [comment]
See: #35, #116, #139

**Comment by Francoyy** [comment]
Got it, will try the v2, thanks!
