### ISSUE TITLE
Cannot resolve module 'react-intl/locale-data/ru'

### ISSUE THREAD

**Issue by halt-hammerzeit** [yahoo/react-intl#203]
Webpack cannot resolve any `locale-data`

```
Module not found: Error: Cannot resolve module 'react-intl/locale-data/ru' in G:\work\webapp\code\client
resolve module react-intl/locale-data/ru in G:\work\webapp\code\client
  looking for modules in G:\work\webapp\node_modules
    resolve 'file' or 'directory' locale-data/ru in G:\work\webapp\node_modules\react-intl
      resolve file
        G:\work\webapp\node_modules\react-intl\locale-data\ru doesn't exist
        G:\work\webapp\node_modules\react-intl\locale-data\ru.json doesn't exist
        G:\work\webapp\node_modules\react-intl\locale-data\ru.js doesn't exist
      resolve directory
        G:\work\webapp\node_modules\react-intl\locale-data\ru doesn't exist (directory default file)
        G:\work\webapp\node_modules\react-intl\locale-data\ru\package.json doesn't exist (directory description file)
```

The reason is that there's no such folder.

The correct way would be `require('react-intl/lib/locale-data/ru')`.
You should update your documentation.

**Comment by ericf** [comment]
I'm using a `main` entry in the `package.json` file. It seems like you're having a problem with Webpack not respecting the proper Node.js `main` module resolution:

https://nodejs.org/docs/latest-v0.12.x/api/modules.html#modules_accessing_the_main_module

What version of Webpack are you using?

**Comment by halt-hammerzeit** [comment]
For anyone googling this
https://github.com/webpack/webpack/issues/800

Possibly Webpack doesn't support this module loading algorythm

**Comment by halt-hammerzeit** [comment]
I don't know why isn't it working.

**Comment by nmaves** [comment]
I am seeing this same issue with webpack@1.12.9.

```javascript
import en from 'react-intl/locale-data/en';
import fr from 'react-intl/locale-data/fr';

addLocaleData(en);
addLocaleData(fr);
```

```
ERROR in ./app/App.js
Module not found: Error: Cannot resolve module 'react-intl/locale-data/en' in /Users/nmaves/projects/.../app
 @ ./app/App.js 23:10-46

ERROR in ./app/App.js
Module not found: Error: Cannot resolve module 'react-intl/locale-data/fr' in /Users/nmaves/projects/.../app
 @ ./app/App.js 27:11-47
```

**Comment by nmaves** [comment]
Could the issue be with babel 6?

**Comment by ansonla3** [comment]
same issue + 1 , any ideas?

**Comment by afsanefda** [comment]
I have the same issue because after yarn add react-intl when I check the node module folder I cant find the locale-data folder! Do you know why?

**Comment by afsanefda** [comment]
Actually I added the 2.9.0 version and the problem solved! But Why in the latest verrsion this important folder has been removed ?????

**Comment by sinwailam193** [comment]
Got the same issue with the version 3.1.3 of react-intl

> Actually I added the 2.9.0 version and the problem solved! But Why in the latest verrsion this important folder has been removed ?????

Got the same issue with the version 3.1.3 of react-intl

**Comment by longlho** [comment]
We no longer distribute `locale-data`, please take a look at v3 Upgrade Guide https://formatjs.io/docs/react-intl/upgrade-guide-3x/

**Comment by naneziris** [comment]
> We no longer distribute `locale-data`, please take a look at v3 Upgrade Guide https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md

That is right guys, read the upgrade notes.
You have to do sth like that instead:

`import '@formatjs/intl-relativetimeformat/polyfill';`
`import '@formatjs/intl-relativetimeformat/dist/locale-data/en';`
`import '@formatjs/intl-relativetimeformat/dist/locale-data/fr'`

**Comment by Ivraie** [comment]
Hi, I have read the Upgrade Guide but I can't figure out how to include en-US. I see only '@formatjs/intl-relativetimeformat/dist/locale-data/en';
Does someone know how to do it ?

**Comment by longlho** [comment]
en has en-US
