### ISSUE TITLE
Missing locale data for: "en-US". Using default locale: "en" as fallback.

### ISSUE THREAD

**Issue by halt-hammerzeit** [yahoo/react-intl#204]
```
[React Intl] Missing locale data for: "en-US". Using default locale: "en" as fallback.
```

**Comment by halt-hammerzeit** [comment]
I found the cause of the error:

```
<IntlProvider locale={locale} messages={messages}>
```

It doesn't support a properly formatted `locale`.

A workaround:

```
function get_language(locale)
{
	const dash_index = locale.indexOf('-')
	if (dash_index >= 0)
	{
		return locale.substring(0, dash_index)
	}
	return locale
}

// not real locale
<IntlProvider locale={get_language(locale)} messages={messages}>
```

**Comment by ericf** [comment]
You'll need to load `locale-data/en.js` to get support for `en-US`. By default only the root, `en` locale data is provided.

> It doesn't support a properly formatted locale.

This is incorrect. The locale data files are provide per language, e.g. `en.js`, but they contain data for all locales in that language, e.g. `en-US`, `en-GB`, etc.

**Comment by SachaG** [comment]
I just ran into this issue. So just to clarify, in the following snippet `fr` works but `fr_FR` doesn't:

```
import fr from 'react-intl/locale-data/fr';
import { addLocaleData } from 'react-intl';
addLocaleData([...fr]);
...
<IntlProvider locale="fr" messages={myStrings}>
```

Is that the expected behavior? What would I need to do if I did want to use `fr_FR` or `fr_CA` instead?

**Comment by ericf** [comment]
@SachaG The locale needs to be a BCP-47 language tag. Replace `_` with `-`.

**Comment by mccrodp** [comment]
Hey @ericf, thanks for your answers. I am getting this in Gatsby w/ community i18n plugin. I have added the `locale-data` as you can see [here](https://github.com/mccrodp/gatsby-contentful-i18n/blob/master/src/layouts/index.js#L9), but I still get the below error. Any more specific ideas to what is missing? I have only `de` and `en-US` langs set, no `en` at the moment as it's not my repo.

> commons.js:77217 [React Intl] Missing message: "selectLanguage" for locale: "en-US"
> commons.js:77217 [React Intl] Missing message: "selectLanguage" for locale: "de"
> commons.js:77217 [React Intl] Missing message: "selectLanguage" for locale: "en"
