### ISSUE TITLE
Support nested messages-object

### ISSUE THREAD

**Issue by TN1ck** [yahoo/react-intl#207]
Currently the messages object has a format like this:
```
{
    app.title: "React Intl Translations Example",
    app.locales_menu_heading: "Locales:",
    greeting.welcome_message: "Welcome {name}, you have received {unreadCount, pl…t} new messages}} since {formattedLastLoginTime}.",
    menu.item_en_us_description: "The default locale of this example app.",
    menu.item_en_upper_description: "The fake, all uppercase "locale" for this example app."
}
```

I personally would much prefer a structure like this:
```
{
    app: {
        title: "React Intl Translations Example",
        locales_menu_heading: "Locales:"
    },
    greeting: {
        welcome_message: "Welcome {name}, you have received {unreadCount, pl…t} new messages}} since {formattedLastLoginTime}."
    },
    menu: {
        item_en_us_description: "The default locale of this example app.",
        item_en_upper_description: "The fake, all uppercase "locale" for this example app."
    }
}
```

I know that I could transform the second dictionary into a flat one, but what's the reasoning behind the default flat-one? It certaintly confused me.
It would be nice, if there is an option to give the `<IntlProvider>` how it should get the message from the id, maybe even a general approach and one can give it a function, like in my case:

```
// the _.get is a function from lodash
<IntlProvider locale='en' messages={messages} messageFn={(id, messages) => {_.get(messages, id)}}>
     <App />
</IntlProvider>
```

Would be awesome if something like this could be added.

**Comment by ericf** [comment]
Simplicity and flexibility is the main reason. With the flat object, people can write whatever message ids/keys they want and they won't be interpreted with special semantics.

The new focus is around the idea that people will author their messages _in_ their components and use [`babel-plugin-react-intl`](https://github.com/yahoo/babel-plugin-react-intl) to extract them. Once you have your messages in components, you're less likely to want a hierarchical object structure.

Like you said, you could write a transform, and that's my current suggestion. I'd be happy to publish [this](https://github.com/yahoo/react-intl/issues/193#issuecomment-152019363) as a generic transform for people to add to their build.

I think your idea of adding a `messageFn` would work, but adds more complexity that I am hoping to be able to avoid.

**Comment by zkirill** [comment]
@ericf Please publish your generic transform. It is very helpful!

**Comment by ericf** [comment]
Docs about the flat `messages` object structure have been added the the [Upgrade Guide](https://github.com/yahoo/react-intl/blob/master/UPGRADE.md#flatten-messages-object).

**Comment by crisu83** [comment]
Link to the upgrade guide is broken.

**Comment by ericf** [comment]
Check the wiki

**Comment by scazzy** [comment]
I do agree on nested translations as a need. Major MVC (non JS) frameworks use them because it helps keep all translations at one place, hence easier to manage (sending a list to the translator and Done!)

Where as keeping translations in FormatMessage component, I wouldn't really recommend besides the default text. You wouldn't wanna support 20 languages and find each component for every single text change. Secondly, it disallows maintaining a standard format for translations for readability and development.
Example: products: {}, app: {}, etc, app.greeting, email.heading

Infact, most MVCs (because they're frameworks), keep an easier folder structure

> ...
> lang/
>├─ en/
>├─ ├─ email.json
>├─ ├─ products.json
>├─ ├─ ...
>├─ fr/
>├─ ├─ email.json
>├─ ├─ products.json
>├─ ├─ ...

**Comment by Plorark** [comment]
For the ones who's facing the same issue, you can always flat your nested object with something like:
https://www.npmjs.com/package/flat
That's the way I've found to use my nested stuff.

**Comment by FlorianCassayre** [comment]
See [this thread](https://stackoverflow.com/q/45783677) for more information.
