### ISSUE TITLE
Error formatting the default message for

### ISSUE THREAD

**Issue by manuelmazzuola** [yahoo/react-intl#209]
Hello,
I'm using the **2.0.0-beta-1** version and I'm getting this issue.

```
[React Intl] Error formatting the default message for: "starting_from_budget_estimate"
Error: A value must be provided for: totalPrice
[React Intl] Using source fallback for message: "starting_from_budget_estimate"
```

Here the code
```
<FormattedMessage
  id="starting_from_budget_estimate"
  description="Base price string in the home page"
  defaultMessage="Starting from {totalPrice} {currency} per month"
  totalPrice="10"
  currency={game.budgetEstimate.currency} />
```

I'm not using it in the proper way ?

**Comment by manuelmazzuola** [comment]
Yes, I'm not using it in the proper way.
This is the proper way
```
<FormattedMessage
  id="starting_from_budget_estimate"
  description="Base price string in the home page"
  defaultMessage="Starting from {totalPrice} {currency} per month"
  values={{
    totalPrice: "10",
    currency: game.budgetEstimate.currency
  }} />
```

**Comment by ericf** [comment]
@manuelmazzuola I am glad you were able to recover form this. Sorry about the lack of docs for v2, but this is one of the breaking changes when upgrading from v1.

**Comment by vedmant** [comment]
If I use it with this.props.intl.formatMessage() where I put values? I tried formatMessage({link: <a/>}) and formatMessage({values: {link: <a/>{}) both not working?

**Comment by ericf** [comment]
@vedmant `values` are passed as the second argument. Note while the function takes four params, the `<IntlProvider>` curries the first two via `bind()`. https://github.com/yahoo/react-intl/blob/master/src/format.js#L102
