### ISSUE TITLE
Unit tests are not testing anything

### ISSUE THREAD

**Issue by 3den** [yahoo/react-intl#211]
I was trying to figure out how to get message translations without using `IntlMixin`, and when I checked the unit tests I notice that they are just checking if the functions are functions. If we replace all functions with a `Function.prototype` the tests would still pass... :disappointed: 

It would be nice if the test had real examples of what those functions output for given inputs, instead of just doing a type check.

**Comment by ericf** [comment]
Are you talking about what's on `master`? If so, see: #162's checklist. Tests will be added, but it was pointless to add them while building v2 when the API was in flux.
