### ISSUE TITLE
react-intl 2.0: FormattedMessage inside title tag is breaking after updating state

### ISSUE THREAD

**Issue by alansouzati** [yahoo/react-intl#212]
Hi guys,

 Thanks for working on react-int 2.0, I'm looking forward for the official release, in the meantime I'm using `next` version.

I have the following code that breaks after state is updated:

```
  ...
  _activateTab: function (index) {
    this.setState({activeIndex: index});
  },
  render: function () {
    <div ref="tabContent" tabIndex="0" aria-labelledby="content_description" role="tabpanel">
      <title id="content_description">
        <FormattedMessage id="Tab Contents" activeTitle={activeTitle}
          defaultMessage={activeTitle + " Tab Contents"} />
      </title>
      ...
    </div>
  }
```

The console log is:

```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.1.1.1.1.1:1:3.2.0.1.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

The weird thing is, if I remove `activeTitle` from `defaultMessage` everything works fine again.

Here is the code that works fine all the time:

```
  ...
  _activateTab: function (index) {
    this.setState({activeIndex: index});
  },
  render: function () {
    <div ref="tabContent" tabIndex="0" aria-labelledby="content_description" role="tabpanel">
      <title id="content_description">
        <FormattedMessage id="Tab Contents" activeTitle={activeTitle}
          defaultMessage={" Tab Contents"} />
      </title>
      ...
    </div>
  }
```

Also, if I replace `title` tag by a `div` tag everything works fine as well.

PS: I tried to create a jsFiddle to reproduce the issue but I could not find the minified react-intl for `next`version anywhere (hopefully you can deploy to cdnjs?).

**Comment by alansouzati** [comment]
Never mind, the issue was somewhere in own code.

**Comment by ericf** [comment]
This seems like incorrect usage of the `<title>` element which are only permitted in the `<head>`.

**Comment by alansouzati** [comment]
interesting. I've been using `<title>` for a11y and screen readers seem to get it. It was working in React 0.13, the issue started happening after I migrated to React 0.14. Anyways, thanks for the help.

**Comment by ericf** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title

**Comment by ericf** [comment]
React 0.14 might be correctly limited a `<title>`'s children to just text and not supporting any nested components since they have to return DOM elements.

**Comment by alansouzati** [comment]
Cool. Thanks again. This could be a very dumb question, what about `title` tag inside inline svg? I thought they were supposed to be valid. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title.

But I think you are right, all Title tags are supposed to be text only.

The issue is that it works the first time. It only fails after a state update, see this fiddle: https://jsfiddle.net/alansouzati/2f9p4ngp/
