### ISSUE TITLE
Hot swapping locale using v2

### ISSUE THREAD

**Issue by cayuu** [yahoo/react-intl#213]
How to hot-swap locale using v2 `<IntlProvider>`?

Basically how do you implement the example on the FormatJS.io homepage without reloading the app:

![FormatJS.io example](http://i.imgur.com/kYu36f6.png)

@ericf says ["hot-swapping locales will be possible"](https://github.com/yahoo/react-intl/issues/162#issuecomment-152832900) which _sounds_ like it's "still to come"? Hot-swapping _messages_ is easy (as this can be managed via whatever flux workflow you prefer) - you can then pass these `messages` directly to the intl components (`FormattedMessage` and its ilk). But for Numbers and Dates formatting is based on `locale` which is pulled via context or `injectIntl` decorator prop and can't be manually set on the components as far as I can tell (this is not necessarily a bad thing).

The [Translations Example](https://github.com/yahoo/react-intl/blob/master/examples/translations/src/client/components/locales-menu.js) currently reloads the entire app to change locale. 

To restate the question: when rendering an app using the canonical example, how do you **dynamically change** `locale` without hard-reloading the app?

```js
ReactDOM.render(
  <IntlProvider locale="en">
    <MyApp />
  </IntlProvider>,
  document.getElementById('container')
);
```

I suspect I'm missing something obvious. Sorry!

> Edit: Pushing `IntlProvider` into `MyApp` as the parent container (ie. `.render(<MyApp />)` with IntlProvider inside MyApp) obviously allows setting its props dynamically and "does the trick", but this seems non-canonical.

**Comment by ericf** [comment]
> Pushing IntlProvider into MyApp as the parent container (ie. .render(<MyApp>) with IntlProvider inside MyApp) obviously allows setting its props dynamically and "does the trick", but this seems non-canonical.

This works and is fine. The limitation is that your `<MyApp>` component won't have able to use the imperative API. The examples show `<IntlProvider>` wrapping the main `<App>` component to remove this limitation in the case that someone's root component is "fat" and doing number, date, or string formatting.

I think a better approach would be for you to create a `<HotSwappingIntlProvider>` component that's stateful (or hooks into your Flux system), handles fetching of translations (or does so via a Flux action) along with React Intl data for the new locale, and renders an `<IntlProvider>` internally.

This would probably be a good exercise for me to follow when I refactor the FormatJS website for React Intl v2. Right now the website loads all the locale data and translations it could possible need up front — which is not ideal for a real app with many strings and supporting many languages.

_Very rough_ sketch of `<HotSwappingIntlProvider>`:
```js
class HotSwappingIntlProvider extends Component {
    constructor({initialLocale: locale, initialMessages: messages}) {
        this.state = {locale, messages};
    }

    render() {
        return (
            <IntlProvider {...this.state}>
                {this.props.children}
            </IntlProvider>
        );
    }
}
```

Then your client render would look like:
```js
ReactDOM.render(
    <HotSwappingIntlProvider
        initialLocale='en'
        initialMessages={messages}
    >
        <App />
    </HotSwappingIntlProvider>
    document.getElementById('container')
);
```

**Comment by cayuu** [comment]
@ericf you are a legend and a credit to open source. Thank you for your detailed (and rapid) advice. The HotSwap HOC is a good solution and it's very helpful to know this is where your thoughts are inclined.

Much appreciated. :+1:

**Comment by mclemme** [comment]
@ericf thanks a lot for the sketch of the implementation, struggled with a hot swappable language selector until I found this :) I'll show my implementation of the HotSwappingIntlProvider for anyone else wondering how to do this, I'm relatively new at working in React, so it might be ugly, but it works for me :)

```js
import React from 'react';
import { IntlProvider } from 'react-intl';
import LocaleStore from '../stores/LocaleStore';

class HotSwappingIntlProvider extends React.Component {
    constructor(props) {
        super(props);
        const {initialLocale: locale, initialMessages: messages} = props;
        this.state = {locale, messages};
        this.changeListener = this._handleChange.bind(this);
    }

    _handleChange() {
        this.setState({
            locale: LocaleStore.getLanguage(),
            messages: LocaleStore.getMessages()
        });
    }

    componentWillMount() {
        LocaleStore.addChangeListener(this.changeListener);
    }

    componentWillUnmount() {
        LocaleStore.removeChangeListener(this.changeListener);
    }

    render() {
        return (
            <IntlProvider locale={this.state.locale} key={this.state.locale} messages={this.state.messages}>
                {this.props.children}
            </IntlProvider>
        );
    }
}

export default HotSwappingIntlProvider;
```

LocaleStore then holds the currently selected language and translated messages. LocaleStore is updated by a dropdown (material-ui).

**Comment by mowsmith** [comment]
@mclemme could you give me an example of your LocaleStore? I'm new to React too, and I'm trying get this working, but not quite sure how the two are wired together. Right now I'm using a query string to swap between the two, which works fine, but I was curious how to do it this way as well.
