### ISSUE TITLE
Another concat() issue

### ISSUE THREAD

**Issue by indeyets** [yahoo/react-intl#214]
I saw there were several similar issues in the past, but those happened long ago and are closed.

I get `TypeError: (locales || []).concat is not a function` error currently when using `<FormattedRelative>` component. I see that `locales` is an object.

I use react-intl 2.0.0-beta-1, browserify 12.0.1

**Comment by ericf** [comment]
Any way to create a simplified reproducible example?

**Comment by ericf** [comment]
I just tried building the examples with `browserify@12` and it's working correctly for me. I've had a problem when using the `bundle-collapser` plugin which I had to remove. Are you using that?

**Comment by indeyets** [comment]
code example would be complicated, but I think I found the offender. We use https://github.com/milankinen/livereactload for local development and it looks like it is in conflict with react-intl somehow.

might be related to outdated react-proxy dependency, which it uses

**Comment by ericf** [comment]
Closing this out…

**Comment by terinjokes** [comment]
@ericf I'm using `bundle-collapser` and can't remove it. Did you have any ideas why this would cause a difference?

**Comment by ericf** [comment]
@terinjokes for some reason bundle-collapser thinks that `intl-messageformat` and `intl-relativeformat` (which depends on `intl-messageformat` are the same package.

**Comment by terinjokes** [comment]
Good enough to get started. I'll take a look into why and hopefully get it
fixed.

**Comment by terinjokes** [comment]
@ericf how do you come to this conclusion? I see the requires for _intlMessageformat and _intlRelativeformat going to different bundle ids here.
