### ISSUE TITLE
[v2.0.0-pr-3] FormatNumber not reading defaultFormats

### ISSUE THREAD

**Issue by robhuzzey** [yahoo/react-intl#215]
Hey,

It looks like `FormatNumber` is not reading from the `defaultFormats` property.
https://github.com/yahoo/react-intl/blob/v2.0.0-pr-3/src/format.js#L92

Whereas `FormatMessage` is?
https://github.com/yahoo/react-intl/blob/v2.0.0-pr-3/src/format.js#L116-L117

**Comment by ericf** [comment]
`default*` config props on `<IntlProvider>` are intended to be for fallback cases. If you're using the same custom named formats for every locale, then just pass the same object to `formats` and `defaultFormats` prop when creating your `<IntlProvider>`.

**Comment by ericf** [comment]
See: https://github.com/yahoo/react-intl/blob/master/src/components/intl.js#L52-L77 from `2.0.0-beta-1`.

**Comment by robhuzzey** [comment]
Thanks @ericf although I'm trying to make my component re-usable without having to wrap with `<IntlProvider />`

In this example, I have the component's render method return my markup wrapped in `<IntlProvider />` but if this component is used in an app that already has `<IntlProvider />` at the parent, I'd like my component to take those settings... hence why I wanted to only set defaults as fallbacks.
https://gist.github.com/robhuzzey/e366d1d7b645f6e7a47e#file-example-js-L19

FYI, here is my PR for the real world project: https://github.com/holidayextras/ui-toolkit/pull/100 

I really appreciate your help on this :)
