### ISSUE TITLE
[v1.2.1] Why not accept React 0.14.0

### ISSUE THREAD

**Issue by Fenntasy** [yahoo/react-intl#216]
I recently made the shift and got some weird errors. Because the dependency "react": ">=0.11.2 <0.14.0" make npm install its own version of react 0.13.3.

Things is, removing the alternate react version, I don't have any problem running the lib wit react 0.14. 
Is there bugs that I don't know about in my use case or a compelling reason to do disallow this?

I would prefer staying on the 1.x branch for the moment as the newer version is still in beta (and I didn't find every change that I will need to to make to switch to the new version).

Thanks in advance

**Comment by ericf** [comment]
Pin to `1.2.0`.

**Comment by Fenntasy** [comment]
Thanks, but you changed it because you said it doesn't work with 0.14. As I didn't encounter any bug in my (alledgelly quick) checks, could you tell me what does not work?

Sorry to bother you with that.

**Comment by ericf** [comment]
There were other issues reported. I never tried it. But I don't anticipate another 1.x release.

**Comment by limpbrains** [comment]
@ericf 1.x version compatible with React 0.14 would be very helpfull. It would be easier to migrate to v2 if bouth versions will work on 0.14.
I have a project with about 500 translated messages and only react-intl stops me to upgrade to 0.14. When it will be out, I will have to upgrade all my libs at once, not one by one.

**Comment by ericf** [comment]
@limpbrains as explained above in this thread, you can pin to `1.2.0`.

**Comment by limpbrains** [comment]
@ericf Thanks, now I get it.
