### ISSUE TITLE
formatMessage in V2 outside a React component

### ISSUE THREAD

**Issue by BenNG** [yahoo/react-intl#218]
Hello! 

Is it possible to use the formatMessage method outside a react component ?

thank you !

**Comment by ericf** [comment]
Not exactly, but you could directly depend on the lower-level [`intl-messageformat`](https://github.com/yahoo/intl-messageformat) package which is used under the hood.

You can use `<FormattedMessage />` outside of a React component though; e.g., in a Flux store.

I'm curious, what you are doing to do?

**Comment by BenNG** [comment]
In my app,

I Generate some data to help the user discovering the features at the first use.
This generation data is not part of the application so I extracted the logic outside of a react component.
But in the generated data there are some descriptions.

so far, I successfully extract the messages with `defineMessages` but  I need to use `formatMessage` to use them

**Comment by ericf** [comment]
`defineMessages` is simply used as a hook of the extraction process and defining default messages doesn't require React, but formatting them does. Under the hook `formatMessage()` uses `intl-messageformat`.

**Comment by benmonro** [comment]
@ericf 

>You can use <FormattedMessage /> outside of a React component though; e.g., in a Flux store.

any chance you could provide an example of this?

**Comment by ruslanchek** [comment]
> I'm curious, what you are doing to do?
For example: 
Showing alert by browser's Notification API with localised string.

**Comment by benmonro** [comment]
we ended up rolling our own instead of using react-intl.  wasn't that hard actually.
