### ISSUE TITLE
Another hot swapping locale issue

### ISSUE THREAD

**Issue by antoinerey** [yahoo/react-intl#221]
Hey !

### My problem

Can't get hot swapping locale working. I looked for any solution in here, I didn't find any. That's why I'm posting in here. 

I'm using the v2 branch. (2.0.0-pr-3)

### What I did

As already said in #213 I made a custom wrapper which take a `lang` prop. This is an object similar to : `{ current: 'en' }`

``` javascript
const Lang = React.createClass({

  propTypes: {
    lang: PropTypes.object.isRequired,
    children: PropTypes.object.isRequired
  },

  render() {
    const { lang, children } = this.props;

    return (
      <IntlProvider locale={ lang.current } messages={ require(`../config/lang/${lang.current}.js`) }>
        { children }
      </IntlProvider>
    );
  }

});
```

And I'm using the `<FormattedMessage />` component like this.

``` javascript
<FormattedMessage id="HOME"/>
```

### So what ?

When hot swapping from any language to another, `locale` and `messages` props get the correct values. It actually updates like it should. But the `<FormattedMessage id="HOME" />` component does not update its text to the last locale. It keeps the previous one.

It keeps displaying 'Home' and not 'Accueil' for exemple. Quite anoying.

Any idea ?

**Comment by ericf** [comment]
Can you provide a simple runnable example showing the issue? It works as expected for me when I try something similar locally.

**Comment by antoinerey** [comment]
I just fixed this issue by moving the `<IntlProvider />` inside the router. 
My bad. Sorry for the issue !

Thank you !

**Comment by ericf** [comment]
@antoinerey glad you fixed it. Can you provide a rough sketch of how the code looks now? I bet lots of other people using react-router will run into something similar.

**Comment by antoinerey** [comment]
### Before

When I had my issue, my `<Root />` component was this, more or less :

``` jsx
// root.component.js

<Lang>
  <Router>
    <Route path="/" component={ require('../app/app.component.js') }>
       { ... }
    </Route>
  </Router>
</Lang>
```

The `<Lang />` component is just a simple wrapper, as I said, arround the `<IntlProvider />`.

``` jsx
// lang.component.js

<IntlProvider locale={ this.state.locale } messages={ require(`../lang/${this.state.locale}.js`) }>
  { this.props.children }
</IntlProvider>
```

### After

Then to solve my issue, I just moved the `<Lang />` component to the `<App />` component which is inside the router. 

``` jsx
// root.component.js

<Router>
  <Route path="/" component={ require('../app/app.component.js') }>
     { ... }
  </Route>
</Router>
```

```jsx
// app.component.js

<Lang>
  { this.props.children }
</Lang>
```

Now it is working as expected.

---

Notes :
1. I'm using a *Redux* architecture to manage stores and states.
2. To save my router state, I'm using *Redux Router* as a wrapper arround *React Router*. Maybe it is connected to my issue.

Hope this can help.
