### ISSUE TITLE
InjectIntl withRef isn't returning WrappedInstance

### ISSUE THREAD

**Issue by pushqin** [yahoo/react-intl#223]
When configuring injectIntl withRef = true.

like:

`export default injectIntl(DropDown, {withRef: true})`

when using: 
`<DropDown id="country" withRef ref="country" />`

source:
https://github.com/yahoo/react-intl/blob/master/src/inject.js#L38

in the source there is a return `return this.refs.wrappedInstance;`
this return is not included in the @next version

`$ npm install react-intl@next`

**Comment by ericf** [comment]
The bug fix already on `master` will be in the next release.

**Comment by skizzo** [comment]
In case this is is still happening to people, the workaround is to simply inject the `intl` property from the embedding component and not use `injectIntl` in the nested component at all. Then, `getWrappedInstance ()` works like a charm.
