### ISSUE TITLE
Unable to replace language at runtime

### ISSUE THREAD

**Issue by vslinko** [yahoo/react-intl#224]
I'm trying to connect my local state to `IntlProvider` using props.
But `IntlProvider.shouldComponentUpdate` is blocking all my changes.

**Comment by ericf** [comment]
Can you provide more information?

**Comment by vslinko** [comment]
I have a component that connecting `locale` and `messages` from the redux store to the `IntlProvider`:
https://github.com/vslinko/ripster/blob/master/src/frontend/bundles/common/components/ReduxIntl/ReduxIntlContainer.js

When locale will change, `IntlProvider` will receive new `locale` and new `messages`, but content on the page will not change.

Reason of it is `IntlProvider.shouldComponentUpdate` that blocking all changes.

**Comment by vslinko** [comment]
Please let me know if you need more information, and sorry for my English, it isn't good enough.

**Comment by ericf** [comment]
I don't understand how when the props passed to `<IntlProvider>` change its `shouldComponentUpdate` is blocking changes. It performs shallow compare of `props` and `state`.

**Comment by vslinko** [comment]
I don't know but it does.
If you want I could prepare example with the issue.

**Comment by quicksnap** [comment]
Related: #234

**Comment by Dindaleon** [comment]
I am about to post an example for server rendering. I will update this post.

**Comment by DWboutin** [comment]
I use 2.0.0 and it worked #1! 

Just wrapped my root component like this

```javascript
  render() {
    const { children, loggedIn, user, application } = this.props;

    const intlData = {
      locale: application.locale,
      messages: i18n[application.locale],
    };

    return (
      <IntlProvider key="intl" {...intlData}>
        <div id="application">
          <div className="page-wrap">
            <Header loggedIn={ loggedIn } user={ user } handleLogout={ this.handleLogout } handleLanguageChange={this.handleLanguageChange} />
            <MainNavigation />
            {children}
          </div>
          <Footer />
        </div>
      </IntlProvider>
    );
  }
```
