### ISSUE TITLE
Mismatch in server and client rendered currency

### ISSUE THREAD

**Issue by frankleng** [yahoo/react-intl#225]
using 2.0 beta-1, Node 4.2.1
<img width="556" alt="screen shot 2015-11-18 at 2 18 02 am" src="https://cloud.githubusercontent.com/assets/6145910/11238569/6d387e12-8d9b-11e5-8755-2f2febf4aae0.png">

```value = [0, 10]``` 
``` <FormattedNumber value={value[0]} style="currency" currency="USD"/> ```

Any idea why the client rendered version has decimal places?

**Comment by ericf** [comment]
This is a known V8 issue which has been fixed in the V8 version used by Node 5. You can add `minimumFractionDigits={2}` to force V8 to do the correct thing in Node < 5.

**Comment by frankleng** [comment]
:+1: thanks! @ericf
