### ISSUE TITLE
Uncaught Error on Chrome Canary (49)

### ISSUE THREAD

**Issue by vslinko** [yahoo/react-intl#228]
![screen shot 2015-11-21 at 10 47 23 pm](https://cloud.githubusercontent.com/assets/1966521/11321959/2bec8386-90a2-11e5-824b-e0f74c4b9072.png)
![screen shot 2015-11-21 at 10 48 23 pm](https://cloud.githubusercontent.com/assets/1966521/11321960/2bed8c7c-90a2-11e5-9817-9bc0aa6e19b7.png)

**Comment by vslinko** [comment]
Looks like problem in https://github.com/yahoo/intl-format-cache/blob/master/src/memoizer.js#L25 but I'm not sure.

It's working when I do this:
```diff
 function createFormatCache(FormatConstructor) {
     var cache = objCreate(null);

-    return function () {
+    return function (a, b, c, d, e, f) {
         var args    = Array.prototype.slice.call(arguments);
         var cacheId = getCacheId(args);
         var format  = cacheId && cache[cacheId];

         if (!format) {
-            format = objCreate(FormatConstructor.prototype);
-            format = FormatConstructor.apply(format, args);
+            format = new FormatConstructor(a, b, c, d, e, f);

             if (cacheId) {
                 cache[cacheId] = format;
             }
         }

         return format;
     };
 }
```

**Comment by bsr203** [comment]
This only happens in Canary. (Version 49.0.2571.0 canary (64-bit)) If I open the same page in chrome (Version 46.0.2490.86 (64-bit)), it works fine. I tried by disabling all extension but the result is same.

**Comment by ericf** [comment]
This has been addressed here: https://github.com/yahoo/intl-format-cache/pull/11
I will work on doing releases of all our intl-related packages soon.

**Comment by ericf** [comment]
I've released `intl-format-cache@2.0.5` which fixes https://github.com/yahoo/intl-format-cache/issues/9

**Comment by bsr203** [comment]
thanks..

**Comment by ericf** [comment]
I will update both 1.x and 2.x branches to use `intl-format-cache@2.0.5`, in the meantime the V8 team has rolled back this patch and it should be in a near future Canary update.

Details of the core, underlying issue here: https://github.com/tc39/ecma402/issues/57

**Comment by vslinko** [comment]
Thank you. We can't wait for `react-intl` release. :smile:
