### ISSUE TITLE
CLDR short numbers?

### ISSUE THREAD

**Issue by mwilliams-change** [yahoo/react-intl#229]
How can I use `FormattedNumber` to generate output formatted like CLDR short numbers? (see http://cldr.unicode.org/translation/number-patterns#TOC-Short-Numbers)

Seems like this isn't available out of the box, do I have to create a custom format for `IntlProvider`?

I'm using `2.0.0-pr-3`.

**Comment by ericf** [comment]
These unit/rule-based number formats are not supported. `<FormattedNumber>` uses [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) under the hood.
