### ISSUE TITLE
Currency representation for INR

### ISSUE THREAD

**Issue by seekshiva** [yahoo/react-intl#231]
Hi, when I give
```
  <FormattedNumber
    value={2344}
    style="currency"
    currency="INR"
  />
```

I get the output as `Rs.2,344.00`.

Is there a way to make it appear as `₹2,344.00` instead?

**Comment by seekshiva** [comment]
should I file an issue under formatjs parent project?

**Comment by ericf** [comment]
What locale is this running in?

**Comment by ericf** [comment]
I'm guessing you're seeing this in v8/Chrome, and I can confirm that even when using the `currencyDisplay` set to `'symbol'` (which is the default) `'Rs.'` is used in place of `'₹'`. Firefox is doing the correct thing and showing the symbol.

Would you want to file this as a bug against v8/Chrome for its `Intl.NumberFormat` implementation?

**Comment by seekshiva** [comment]
Thanks. Filed the issue at https://code.google.com/p/v8-i18n/issues/detail?id=35

**Comment by seekshiva** [comment]
Looks like v8-i18n project is no longer applicable as it was merged into v8. I've filed an issue in V8 at https://code.google.com/p/v8/issues/detail?id=4584
