### ISSUE TITLE
Shorthand for defineMessages

### ISSUE THREAD

**Issue by quicksnap** [yahoo/react-intl#236]
Would you accept a PR for shorthand API for `defineMessages`?

```js
defineMessages([
  [messageId, defaultMessage, messageDescription],
  [messageId, defaultMessage, messageDescription],
  // ...
]);
```
The babel plugin would need to be adjusted as well.

**Comment by ericf** [comment]
I don't think this is superior and is would be less ergonomic to use the messages have `"namespaced.ids"`. This also means that people always have to remember the order of the entries in the array.

Can you explain your concern with the current API?

**Comment by quicksnap** [comment]
It's just wordy:

```
const messages = defineMessages({
  'noCatalogSelected': {
    id: 'CATALOG_PICKER.noCatalogSelected',
    defaultMessage: 'No Catalog Selected',
  },
  'noCatalogsAvailable': {
    id: 'CATALOG_PICKER.noCatalogsAvailable',
    defaultMessage: 'No Catalogs Available',
  },
  'submit': {
    id: 'CATALOG_PICKER.submit',
    defaultMessage: 'No Catalogs Available',
  },
});
```

And API like this would be nice:

```
const messages = defineMessages('CATALOG_PICKER', [
  ['noCatalogSelected', 'No Catalog Selected'],
  ['submit', 'No Catalogs Available'],
  ['noCatalogsAvailable', 'No Catalogs Available'],
]);

// messages = { noCatalogsSelected: { id: 'CATALOG_PICKER.noCatalogsSelected' /*...*/ } }
```

**Comment by quicksnap** [comment]
I wouldn't be heartbroken if you decline this proposal--just my preference. Since some components may have a lot of messages, it makes adding messages less painful and takes up less space. The pattern would be so prevalent that developers will probably not forget the ordering.

**Comment by ericf** [comment]
I don't want to change this at this time, and I don't think using an array is this is way better or idiomatic. It might be worth trying to experiment with different Babel transforms that run before babel-plugin-react-intl and compile into the current format.
