### ISSUE TITLE
[v2] React component classes must extend React.Component. 

### ISSUE THREAD

**Issue by jithin1987** [yahoo/react-intl#237]
I am getting this warning on console whenever react-intl classes are used.

```
Warning: IntlProvider(...): React component classes must extend React.Component.
Warning: FormattedNumber(...): React component classes must extend React.Component.
```

**Comment by DWboutin** [comment]
+1

**Comment by ericf** [comment]
They do. Can you provide more information?

**Comment by jithin1987** [comment]
I am on `react-intl@2.0.0-pr-3.` and on react version `0.14.3`

![screen shot 2015-12-07 at 12 05 10 pm](https://cloud.githubusercontent.com/assets/193126/11638266/e7923c90-9cda-11e5-9c94-a9fe4b6171bb.png)

Let me know what else you need.

**Comment by samuelsantia** [comment]
Hi there,

I have the same issue using ```version 1.2.2``` on ```react 0.14.3```
I am using gulp with browserify and babelify to bundle the application.

I have done a mini project to test it.
This is my code

````json
// .babelrc
{
  "stage": 0,
  "ignore": "/node_modules/"
}

````

````json
// project dependencies
"dependencies": {
    "babel": "^5.8.34",
    "babel-polyfill": "^6.3.14",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-intl": "^1.2.2"
  },
  "devDependencies": {
    "babel": "^5.8.21",
    "babel-core": "^5.8.25",
    "babelify": "^6.3.0",
    "browser-sync": "^2.10.0",
    "browserify": "^12.0.1",
    "gulp": "^3.9.0",
    "run-sequence": "^1.1.5",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  }
````

````javascript
// gulp task
gulp.task('browserify', () => {
  browserify('index.js')
  .transform(babelify)
  .bundle()
  .pipe(source('app.js'))
  .pipe(buffer())
  .pipe(gulp.dest('public'));
});
````

````javascript
// index.js
import React from 'react';
import { render } from 'react-dom';
import { FormattedDate } from 'react-intl';

class Test extends React.Component {

  render() {
    return (
      <FormattedDate value={new Date()} day="numeric" month="long" year="numeric" />
    );
  }
}


window.onload = () => {
  render(<Test />, document.getElementById('app'));
}

````

Thanks in advance!!

**Comment by ericf** [comment]
@jithin1987 @samuelsantia what does it show it extending if not `React.Component`?

@jithin1987 I can't reproduce this locally. Could you try `2.0.0-beta-1` and see if the problem still exists, and if so create a very simple runnable example of the problem?

**Comment by samuelsantia** [comment]
Yes, this is the error on console browser

![captura de pantalla 2015-12-07 a las 22 26 20](https://cloud.githubusercontent.com/assets/891869/11640200/980cd25a-9d31-11e5-8a27-5400ede3a72d.png)

**Comment by jithin1987** [comment]
@ericf I think the problem is the version of `react` specified with `react-intl`. My project used `jspm` If I pin dependency of `react-intl` `react` version to `0.14.3` I don't see the warning. Default version jspm associates with `react-intl` is `0.14.0-rc1`

I see this in package.json for `react-intl`

```
  "peerDependencies": {
    "react": "^0.14.0 || 0.14.0-rc1"
  },
```
This for some reason is confusing `jspm`

**Comment by jithin1987** [comment]
@samuelsantia I think you need to update react-intl to `2.0.0-beta-1`, that should solve your warnings issue. I am closing this issue for now.

**Comment by ericf** [comment]
@jithin1987 cool, glad that fixed it. Yeah it seems jspm doesn't parse versions according to Semver.

**Comment by igorprado** [comment]
@ericf So isn't possible use `react-intl` *V1* with React > 0.14?
