### ISSUE TITLE
Server side rendering doesn't work.

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#238]
Hi! I try to use your package with my unviersal rendering app, but it won't work. 

```
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
```

My setup use React-Router and Redux, so i render it this way: 

```
<Provider store={store}>
  <IntlProvider locale="en">
    <RoutingContext {...renderProps} />
  </IntlProvider>
</Provider>
```

Any ideas or comment on how i can render it server side or what you plan about this?

Thank you

**Comment by ericf** [comment]
Server-side rendering does work. Are you sure you're importing modules properly? It seems like one of your components is undefined. You'd have to create a simplified working example of the problem for me to be able to help debug the issue.

**Comment by DWboutin** [comment]
With version 2.0 it's ok, not with 1.*

**Comment by ericf** [comment]
`<IntlProvider>` does not exist in 2.0: If you're using 1.x see: http://formatjs.io/react/ for the docs.

**Comment by DWboutin** [comment]
Do any good Docs will be out soon for version 2.0?

**Comment by ericf** [comment]
They'll be ready as part of the RC release, but it's not expected until after the new year (I'm the only one working on it).

**Comment by DWboutin** [comment]
It will be ok! If you got anything, juste let me know! Thank you very much

**Comment by ericf** [comment]
You can check the Releases page for notes, the UPGRADE.md guide, and #162

**Comment by DWboutin** [comment]
Thank you!
