### ISSUE TITLE
Adding external files for locales (Docs please)

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#239]
Hi! I use React 14.* + and i want to stock my locales messages in files to handle them well and let the translators do their work without getting into the code.

How can i do this? i'm very lost about using this package now. The Docs doesn't speak of this.

I'm trying to connect IntlProvider into this file (who is rendered client and server side) but it won't work.
https://github.com/DWboutin/Beverage/blob/master/src/components/App.react.js

I created a component called AppContainer to handle it. But it's not working.

```
class AppContainer extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <IntlProvider locale="en">
        <App></App>
      </IntlProvider>
    );
  }
}
```

Thank you

**Comment by ericf** [comment]
See the examples for getting started with v2. We're in the middle of rebuilding React Intl, so the docs on the website are still for v1.

https://github.com/yahoo/react-intl/tree/master/examples/translations
