### ISSUE TITLE
FormattedMessage causes React invariant violation error

### ISSUE THREAD

**Issue by ledsoft** [yahoo/react-intl#241]
Hi,

I'm using react 0.14.3 and react-intl 1.2.2. When showing localized message with FormattedMessage, I'm getting Invariant violation error.

Minimalistic example:

```javascript
var intlData = {
    locales: ['en'],
    messages: {
        'save': 'Save'
    }
};

var App = React.createClass({
    mixins: [IntlMixin],

    render: function () {
        return <div>
            <FormattedMessage message={this.getIntlMessage('save')}/>
        </div>
    }
});

ReactDOM.render(<App {...intlData}/>, document.getElementById('content'));
```
Causes a warning: *FormattedMessage(...): React component classes must extend React.Component.*
and an error: **Invariant Violation: FormattedMessage.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.**
I also tried passing message name directly to the 'message' parameter, but the result is the same.

Thanks

**Comment by ericf** [comment]
You can try `1.2.0` or `npm i react-intl@next`, but `1.2.1` and `1.2.2` don't work with React 0.14; you have duplicate copies of React in your app.

https://github.com/yahoo/react-intl/releases/tag/v1.2.1

**Comment by ledsoft** [comment]
Awesome, thanks a lot!
