### ISSUE TITLE
Is there a way to change <IntlProvider locale="***"> in Redux app? 

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#243]
Hi, 

I try to change the main language of my app with come buttons and not refreshing the app.

```javascript
let store = applyMiddleware(thunkMiddleware)(createStore)(reducers);
let { lang, messages } = store.getState().locales;

ReactDOM.render((
  <Provider store={store}>
    <IntlProvider locale={lang} messages={messages}>
      <Router history={createHistory()}>{routes}</Router>
    </IntlProvider>
  </Provider>
), document.getElementById( APP_DOM_CONTAINER ));
```

maybe a method like `IntlProvider.setLang('fr')`?

Thank you!

**Comment by ericf** [comment]
React components use `props` not setters. If you change the `locale` prop on `<IntlProvider>`, it will re-render that component.

See: #234

**Comment by DWboutin** [comment]
How can i change it correctly?

**Comment by benkeen** [comment]
I'm puzzled about this myself!

**Comment by jacortinas** [comment]
@DWboutin I don't see anything in the example you provided that indicates that the app would re-render after the locale has changed. The `IntlProvider` is a component like other components can be wrapped in a react-redux [connect](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) function.

**NOTE**: I haven't tested this code out directly, it should be either good enough or almost good enough.

```javascript
// ConnectedIntlProvider.js

import { connect } from 'react-redux';
import { IntlProvider } from 'react-intl';

// This function will map the current redux state to the props for the component that it is "connected" to.
// When the state of the redux store changes, this function will be called, if the props that come out of
// this function are different, then the component that is wrapped is re-rendered.
function mapStateToProps(state) {
  const { lang, messages } = state.locales;
  return { locale: lang, messages };
}

export default connect(mapStateToProps)(IntlProvider);
```

```javascript
// index.js (your top-level file)

import ConnectedIntlProvider from 'ConnectedIntlProvider';

let store = applyMiddleware(thunkMiddleware)(createStore)(reducers);
let { lang, messages } = store.getState().locales;

ReactDOM.render((
  <Provider store={store}>
    <ConnectedIntlProvider>
      <Router history={createHistory()}>{routes}</Router>
    </ConnectedIntlProvider>
  </Provider>
), document.getElementById( APP_DOM_CONTAINER ));
```

The place where I work is currently using react, redux, react-router and react-intl all together and have explored this exact solution for rendering of our localized strings.

**Comment by jacortinas** [comment]
Jeez nevermind I just saw #234 :(

We did end up exploring this and then going with a solution that refreshes the entire app on a locale change FYI.

**Comment by ericf** [comment]
@jacortinas did you try setting a `key={currentLocale}` on the `<IntlProvider>` to force React to create and new instance and re-render everything under it?

**Comment by jphilipstevens** [comment]
@ericf we had the issue mentioned above. using key={currentLocale} worked for us in out react-redux-intl app.

**Comment by xml** [comment]
I've added this to the [IntlProvider Doc](https://github.com/yahoo/react-intl/wiki/Components).

**Comment by ericf** [comment]
@xml thanks!

**Comment by AMongeEntytle** [comment]
I am currently working on a wrapper for IntlProvider that extracts the locale from the url path (/en/..., /es/..., etc) but I'm not able to make it work as they "locale" key is in this case a call to a function which extracts the current locale from the path. Any ideas how can I get it working? I tried the workarounds here but had no luck ...

**Comment by DWboutin** [comment]
You can check my repo https://github.com/DWboutin/react-webpack-startup maybe it can give you some ideas

**Comment by mbm56767** [comment]
add this in mapStateToProps  of ConnectedIntlProvider file: where lang is the currentLocale
return { key: lang, locale: lang, messages: messages };

**Comment by papasmile** [comment]
@xanderiel assuming you have other preconditions mentioned above (<IntlProfilder locale={locale} and key={locale}>) from your state, then, yea, it should force a full re-render.

**Comment by arturog** [comment]
I believe setting key={locale} will trigger a recreation of a *second* full tree and the removal of the first tree.  This is *not* a re-render, this is add/remove.  I don't think this is right.

Right now my whole app is flashing when changing locale, and I believe key={locale} is the reason.

**Comment by Yuripetusko** [comment]
@arturog having same issue, this triggers a lot of react lifecycle unmounts which is not desirable in many cases

**Comment by jedmao** [comment]
I hope this is helpful to anyone wishing to provide live locale switching. I personally don't think you should store locale settings in your Redux state, because you should have a single source of truth and the URL is a great place for that (e.g., http://example.com/zh/about is the Chinese version of the `/about` route). I look to http://nike.com as a good example of this, as they are a very global company.

That said, in order to support live theme switching, I started with some helper functions I created in `src/helpers/intl.ts` that look like this:

```ts
import { createIntl as _createIntl, createIntlCache } from 'react-intl'

import Locale from 'models/Locale' // typeof 'en' | 'zh'

let currentIntl = createDefaultIntl()

export function createDefaultIntl() {
  return _createIntl({ locale: 'en' }, createIntlCache())
}

export async function createIntl(locale: Locale) {
  return locale === 'en'
    ? createDefaultIntl()
    : _createIntl(
        {
          locale,
          messages: await import(`../translations/${locale}.json`),
        },
        createIntlCache(),
      )
}

export async function switchRootIntl(locale: Locale) {
  if (locale !== currentIntl.locale) {
    currentIntl = await createIntl(locale)
  }
  return currentIntl
}
```

Next, provide the default intl object to your root intl provider:

```tsx
<RawIntlProvider value={createDefaultIntl()}>
  <BrowserRouter>{children}</BrowserRouter>
</RawIntlProvider>
```

Finally, you can use `createIntl` to provide nested locales that don't affect the root (should you actually need this) or you can use `switchRootIntl` to affect the entire page, including the URL.

Happy to provide more details if that's not enough information.

**Comment by SeunghunSunmoonLee** [comment]
This doesn't update. intl object's default language hasn't changed from 'en'. messages have been updated tho. I wonder why. 
```
        const cache = createIntlCache();

        const intl = createIntl(
          {
            locale: locale,
            messages: keys
          },
          cache
        );

        this.setState({ intl });
```
```
    return (
      <RawIntlProvider value={this.state.intl}>
        {this.props.children}
      </RawIntlProvider>
  )
```

**Comment by longlho** [comment]
@SeunghunSunmoonLee can you create a codesandbox to demo this issue please?

**Comment by bertho-zero** [comment]
> I believe setting key={locale} will trigger a recreation of a _second_ full tree and the removal of the first tree. This is _not_ a re-render, this is add/remove. I don't think this is right.
> 
> Right now my whole app is flashing when changing locale, and I believe key={locale} is the reason.

Using `key` react will consider that it is a different node, if we replace `key=` with `otherKey=` it will reload the messages without flashing.

This could be put in the doc.

**Comment by blueyestar** [comment]
I took more than 2 days to figure out why my form values lost after language switch, eventually I found   it was caused by key prop.

I hope this is helpful for anyone who has same problem.

**Comment by flipcc** [comment]
@blueyestar And what happens when you use ´otherKey´ instead of ´key´ like bertho-zero suggested? Does this work?
