### ISSUE TITLE
IE10 support in 2.0

### ISSUE THREAD

**Issue by tad9ab** [yahoo/react-intl#244]
I was wondering if the plan is to have support for IE10 in version 2.0.  Currently, it does not appear to work in IE10.

**Comment by jongsue** [comment]
:+1:

**Comment by jongsue** [comment]
@tad9ab Check out Intl Polyfill
https://github.com/andyearnshaw/Intl.js
It seems working fine!

**Comment by tad9ab** [comment]
Thanks @jongsue.  We might end up using that if they won't be supporting it directly.  Just waiting to hear an official response.

**Comment by ericf** [comment]
Yes, React Intl v2, like v1 supports IE 10. React Intl does use the built-in `Intl` APIs which are not present in IE until IE 11, so you'll need to use a polyfill as @jongsue pointed out.

http://formatjs.io/guides/runtime-environments/

**Comment by tingwei628** [comment]
@ericf  May I ask why not add support with IE10 directly ? Thank you.

**Comment by ericf** [comment]
@tingwei628 I don't understand your question. IE 10 is supported, see my comment above.

**Comment by saidmoya12** [comment]
@ericf then why still this issue?

I have same issue and all my packages are up to date

Is necesary use some plugint on babel?


Thanks
