### ISSUE TITLE
format date/time in a specific timezone

### ISSUE THREAD

**Issue by andreafdaf** [yahoo/react-intl#245]
I'm having a hard time formatting dates/times in a specific timezone, I haven't developed the app I'm having to update, so it already uses this library heavily for date/time formatting.

Now I'm been asked to show times/dates in different timezones from that of the user, but since it is based on the native JS Date the only supported timezone is the one from the user's browser

For example, let's suppose I have three different events, one at 9:30PM PST (-8:00), one at 9:30PM CEST (+1:00) and one at 9:30PM JST (+9:00)
Now, I'm in Italy so I'm CEST, it's important that those date/times keep showing the local time in the timezone they are set to, since showing 13:30, 21:30 and 6:30 is pointless... the user must know that the event is always at 21:30 (how we format dates in Italy, so the correct i18n format) but on different zones, so 21:30PST, 21:30CEST and 21:30JST.
Showing times formatted in the user timezone is really misleading, or else the user might think that he is booking something for 1:30PM in Los Angeles and would see this time change if he moves around the world.

I'm using a stupid fix by now, removing the timezone suffix from the date and placing the user current timezone, so dates always show the same time... but this makes those dates useless when they must be compared, forcing me to always have a Date used for formatting and a Date used for comparing.

What do you think on adding timezone support? How you think this could be implemented? Thanks :)

**Comment by ericf** [comment]
You can use the `timeZone` option when using `<FormattedDate>` or `<FormattedTime>`.
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters

This will only work in runtimes that have built-in implementation of the `Intl` APIs as the `Intl.js` polyfill does not support timezones at this time.

**Comment by andreafdaf** [comment]
you are awesome, thanks :v:
