### ISSUE TITLE
Don't crash if Intl is not present.

### ISSUE THREAD

**Issue by dev-rkoshlyak** [yahoo/react-intl#252]
Currently it crash application and I see no easy way to fix it.
I think it will be better if warning logged and default language used.

**Comment by ericf** [comment]
Can you please provide more information. What do you expect to happen when the core underlying APIs aren't present in the runtime?

http://formatjs.io/guides/runtime-environments/
https://github.com/yahoo/react-intl/blob/master/examples/hello-world/index.html#L9

**Comment by dev-rkoshlyak** [comment]
WebView is not supported:( I think it is bug on polyfill side but who cares, if it crashing app:)

<img width="535" alt="screen shot 2015-12-17 at 3 17 03 pm" src="https://cloud.githubusercontent.com/assets/6261571/11884794/3fec4db0-a4d1-11e5-97a0-065d23e2a411.png">
For some reason,

**Comment by dev-rkoshlyak** [comment]
I expect, warning to be logged or even error and then default language used with whatever possible rendering. Not sure if it possible, but you can render date as date.toString(). It will not be beautiful, but it will work.
May there can be some simple interface to implement for such use cases.
ICustomIntl:
  renderDate()
  renderNumber()

**Comment by ericf** [comment]
You'll have to load the polyfill into the runtime if it doesn't have `Intl` built-in, it's a requirement of this library. 

There is an error thrown in 2.0.0-beta-2: https://github.com/yahoo/react-intl/commit/2c7ff6e6b09e4c4f876195f4d5842296b85d76a8
