### ISSUE TITLE
Strategies for using JSX in messages?

### ISSUE THREAD

**Issue by jbelcher** [yahoo/react-intl#26]
I've run into a few cases where my messages need inline JSX (like a link or presentational markup). I'm handling that now by chopping messages up around the JSX, but it's a bummer to lose the overall translation context. I'm curious if you have employed any other approaches to handle this situation?

**Comment by ericf** [comment]
I've been working on a way to allow React Elements to be passed as values when formatting messages, allowing for things like @kyleboyle's [example above](https://github.com/yahoo/react-intl/issues/26#issuecomment-63195693) to work.

See: https://github.com/yahoo/react-intl/issues/65#issuecomment-70592513

**Comment by kyleboyle** [comment]
:bananadance:
