### ISSUE TITLE
FormattedTime results in unexpected date values instead of time

### ISSUE THREAD

**Issue by jpierson** [yahoo/react-intl#263]
I'm evaluating _react-intl_ for a project and no matter what format configuration I try I get a short date format out of the FormattedTime component. So for example if I specify `<FormattedTime value={1450905938000} />` I will get `12/23/2015` as the output. I've also tried various format component property values including defining custom formats but I always get the same result.

I'm using `"react-intl": "^2.0.0-beta-1"` from npm.

**Comment by jpierson** [comment]
After updating to **2.0.0-beta-2** I'm still having the same issue. I'm also using _redux_ and ES6 without mixins if that matters. I'm completely new to the react-intl library so I may be overlooking something obvious. Is there a way to set a hard coded format for _FormattedTime_ just to verify that it works? Is it wrong for me to expect that the default format should out the time in some format as opposed to the date?

**Comment by ericf** [comment]
This brings up a good point! Currently, there isn't much difference between FormattedDate and FormattedTime, it's just which named formats collection it pulls from. I think it makes sense to set some default props on FormattedTime so that it renders a time, instead of a date when no options are passed.

**Comment by jpierson** [comment]
@ericf that is intuitively how I was attempting to use it at first. In the meantime. In the meantime is there a way to set format directly on the FormattedTime component. I'm looking at the source right now trying to determine how the props are handled. Looks like they are fed to [formatTime](https://github.com/yahoo/react-intl/blob/master/src/components/time.js#L25) which is just a renaming of [intl](https://github.com/yahoo/react-intl/blob/master/src/components/intl.js) but that's where I stopped following it, not sure where _.intl_ in the context comes from.

**Comment by jpierson** [comment]
Ok, I'm getting somewhere. By specifying formats directly on the FormattedTime component usage itself I am now getting a formatted time of _4:25 PM_.

```jsx
var intlData = {
        "time": {
            "hhmm": {
                "hour": "numeric",
                "minute": "numeric"
            }
        }
    }
};

return (<FormattedTime value={1450905938000} format="hhmm" {...intlData} />)
```

**Comment by jpierson** [comment]
Ok, so answering my question from above about setting the format value for FormattedTime component directly on the component I found that I can of the following.

```jsx
<FormattedTime value={1450905938000} hour="numeric" minute="numeric" />
```

This seems obvious now but initially I wasn't able to find any documentation on FormattedTime and the properties it accepts and looking the source it wasn't obvious either.

Ultimately what I wanted and found also works is the date and time together which likewise I found only through trial and error.

```jsx
<FormattedDate 
    value={1450905938000} 
    month="numeric" 
    day="numeric" 
    year="numeric" 
    hour="numeric" 
    minute="numeric" />
```

With respect to **B** above and after realizing that in the specification of the formats, either directly or though custom format aliases, the only thing that is specified is the nature of each component of the date or time value and not ordering of the parts or the separators involved. I'm assuming that this implies that these values are properly localized using the region information specified as part of a locale.

**Comment by jpierson** [comment]
Coming back to **A** it looks like after reading through _Components_ section of issue #162 I've ensured that I'm defining formats by setting the corresponding prop on _IntlProvider_.

```jsx
render(<IntlProvider locale="en" {...intlData}><AppRouter store={store} /></IntlProvider>, document.querySelector("#appContainer"));
```

I was also able to confirm that I am able to use the date formats I've specified. I thought I had the same exact setup when using the _FormattedTime_ component but I was having trouble getting my format to be recognized. Possible bug? It was most likely something different on my side and now I'm exclusively using FormattedDate to output date and time so It's not much of a concern for me right now unless anybody would like me to confirm.

I'll leave this issue open for now for the consideration that by default FormattedTime should output a time related format instead of the date.

**Comment by ericf** [comment]
The intlData object you have is the right shape for IntlProvider. For FormattedTime it takes a flat collection of props for its option, which map to [Intl.DateTimeFormat's options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters). These options are defined here as propTypes: https://github.com/yahoo/react-intl/blob/master/src/types.js#L42

**Comment by ericf** [comment]
@jpierson Here's a PR to resolve this issue with the default options: https://github.com/yahoo/react-intl/pull/264
