### ISSUE TITLE
How to remove warning fallback?

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/react-intl#265]
I dont know why I get this warning:

    [React Intl] Missing message: "home.helloWorld" for locale: "en", using default message as fallback.

The default translation (english) is inside the component where the message is needed. 

The second language is spanish and there is a translation  file for it. However, I dont want to write a translation file for the english language as this is the default language for my app. So how can I avoid that warning?

**Comment by ericf** [comment]
See: #251
