### ISSUE TITLE
How to setup react-intl v2 for server side rendering and locale swtich on runtime?

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/react-intl#266]
Hello,

I was able to set it up for an app without server side rendering without an issue; however, I am not able to do it for one that is rendered on the server side.

For a server side rendering app, I am able to load the language the user has selected, but only if the user refreshes the page. This means, that the language is not being replaced at runtime.

So, is there a tutorial/guide for implementing react-intl v2 on a universal/isomorphic app? The ones that I find on google are for version 1.

**Comment by Dindaleon** [comment]
Solved! I will soon post a demo.

**Comment by irrg** [comment]
@Dindaleon are you still planning on posting a demo?

**Comment by WellyShen** [comment]
@Dindaleon can you share your tutorial for us?

**Comment by TylorShin** [comment]
+1
need some advice :cry:

**Comment by Baldrani** [comment]
Up, if anybody has the solution
