### ISSUE TITLE
version 2.0.0-pr-3

### ISSUE THREAD

**Issue by enahum** [yahoo/react-intl#267]
I've been using version 2.0.0-beta-1 and it's been working great, but when I tried to update to version i get the following error (view image)
![screen shot 2015-12-26 at 15 41 17](https://cloud.githubusercontent.com/assets/6757047/12007680/c0022984-abed-11e5-80a4-7ad00b3f6533.png).

Any suggestions?

**Comment by ericf** [comment]
Use the latest version: `npm i react-intl@next`
