### ISSUE TITLE
getIntlMessage v2 Upgrade

### ISSUE THREAD

**Issue by alexander-schranz** [yahoo/react-intl#268]
isn't there something missing in the upgrade for getIntlMessage to v2. A Function call or something like that around the object?

https://github.com/yahoo/react-intl/blob/master/UPGRADE.md#replace-getintlmessage-calls-with-message-descriptors

tried to update the following code:

```jsx
<div>{this.getIntlMessage('test')}</div>
```

if i follow the upgrade it would just be:

```jsx
<div>{{id: 'test' }}</div>
```

But that did not work for me:  `Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {id}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of App.`

When I did change using instead the following it did work: 

```jsx
<FormattedMessage id="test" /> 
```

What is the right syntax for the getIntlMessage in v2?

**Comment by ericf** [comment]
There's an example right after where you linked to in the Upgrade Guide: https://github.com/yahoo/react-intl/blob/master/UPGRADE.md#update-formattedmessage-and-formattedhtmlmessage-instances

**Comment by alexander-schranz** [comment]
yeah the FormattedMessage works correcty but when I did replace my old getIntlMessage as shown in die UPGRADE.md I will get the error I posted.

**Comment by ericf** [comment]
What you did was not valid JSX, whether your using React Intl or not. The Upgrade Guide provides two examples, `<FormattedMessage>` and `formatMessage()`. Using a bare `getIntlMessage()` is not something that was ever documented.
