### ISSUE TITLE
How to access messages within component render method?

### ISSUE THREAD

**Issue by NGPixel** [yahoo/react-intl#269]
While I always use the standard `<FormattedMessage />` component to display localized text in my React app, I have to deal with a module which absolutely need a string to be provided. Is it possible to access the messages using a function or something, without having to use the `<FormattedMessage />` component? Note that I am in the render() method of the parent component.

I was able to get a workaround (but it's definitely not a good solution):
````
this._reactInternalInstance._context.intl.messages['new_request.fields.description.hint'];
````

Thanks,
Nick

**Comment by ericf** [comment]
You can use `injectIntl()` which will provide access to the lower-level: `props.intl.formatMessage()`. All the `format*()` methods return a string. There's an example in the Upgrade Guide: https://github.com/yahoo/react-intl/blob/master/UPGRADE.md#update-to-injectintl
