### ISSUE TITLE
 International Telephone Component

### ISSUE THREAD

**Issue by InSuperposition** [yahoo/react-intl#271]
Any thoughts on adding an International Telephone Component?

Something similar to http://jackocnr.com/intl-tel-input.html

**Comment by ericf** [comment]
Can you explain more of what you're thinking? This might be a good candidate for an external library to provide.

**Comment by InSuperposition** [comment]
I was inspired to open the issue after looking through the redux-form docs. Specifically this example:
http://erikras.github.io/redux-form/#/examples/normalizing

After thinking about it overnight, I agree with you about it as a standalone library. It is most likely out of the scope of FormatJS. I'm closing the issue.
