### ISSUE TITLE
how to just import zh-Hant?

### ISSUE THREAD

**Issue by nodegin** [yahoo/react-intl#275]
I already setup my own translation, but seems I must also add locale-data from react-intl

so I added

```
import en from 'react-intl/lib/locale-data/zh';
import zh from 'react-intl/lib/locale-data/zh';
addLocaleData(en);
addLocaleData(zh);
```

but zh returning non tranditional one, I saw react-intl/lib/locale-data/index.js contains zh-Hant

how can I add that?

**Comment by ericf** [comment]
`zh-Hant` is included in the `locale-data/zh.js` file. The files contain all locale data for the language for convenience, sorry for the confusion.

**Comment by nodegin** [comment]
ok thanks
