### ISSUE TITLE
FormattedNumber locale=en-AU currency=AUD - A$ is still being prepended to amount

### ISSUE THREAD

**Issue by AlistairB** [yahoo/react-intl#278]
Hi,

I have set locale set to en-AU and currency style to AUD but it still prepends A to the currency amount. The same does not occur with en-US and USD.

I am using 2.0.0 pr3

Cheers

**Comment by ericf** [comment]
Likely the same thing as #231 and #273. Feel free to reopen if it's not…

**Comment by AlistairB** [comment]
Thanks you are right. Added my specific case to https://bugs.chromium.org/p/v8/issues/detail?id=4584
