### ISSUE TITLE
Where's IntlProvider?

### ISSUE THREAD

**Issue by Ahrengot** [yahoo/react-intl#280]
Looking at the example in the readme file, the entire app is wrapped in `<LocationProvider />` but when I pull the latest version of react-intl on npm, I don't find that file anywhere. Neighter in the node_modules/react-intl/src or anywhere as a prop on the main ReactIntl object I get when I require it through webpack.

Am I missing something here, or has this method been deprecated?

**Comment by ericf** [comment]
npm install react-intl@next

**Comment by jamiehill** [comment]
I think this issue needs to be addressed.

The README on master clearly uses `IntlProvider` in the example, and references `1.2.2` as the current version.

This clearly is incorrect, and can lead to people barking up the wrong tree.

**Comment by ericf** [comment]
@jamiehill I'll fix it by setting the `@next` version to `@latest` in npm.
