### ISSUE TITLE
RangeError on FormattedNumber currency when maxDigits < 2

### ISSUE THREAD

**Issue by cayuu** [yahoo/react-intl#284]
v2.0.0-beta-2

Reporting this in case it's a real issue and not a localised/external-influence fail.

```js
<FormattedNumber
  style="currency"
  currency="EUR"
  value={10}
  maximumFractionDigits={0}
/>
```

(For me) when I add  `maximumFractionDigits` (all values less than `2`) to a currency style FormattedNumber it throws a `RangeError`.

**Comment by ericf** [comment]
What browser/runtime in which locale?

**Comment by ericf** [comment]
Based on this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

It seems you just need to make sure `maximumFractionDigits` ≥ `minimumFractionDigits`. So also set `minimumFractionDigits={0}`.

**Comment by cayuu** [comment]
Thanks Eric.
