### ISSUE TITLE
FormattedMessage in Select's options

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#286]
Hi,

I want to translate my Select dropdown choices. I did this: 

```javascript
<option key={option.value + '-' + index} value={option.value}><FormattedMessage {...messages[baseNameLabel + '_' + option.name]} /></option>
```

I think `FormattedMessage` render the string in a span. So i get this error message: 
`Warning: Only strings and numbers are supported as <option> children.`

**Comment by ericf** [comment]
Yup, in cases where you need a string, you can use the `injectIntl()` to wrap your component and create an HOC. This will then provide `this.props.intl.formatMessage()` and it will always return a string.

**Comment by DWboutin** [comment]
Is there any doc on this? Thank you for your answer!

**Comment by ericf** [comment]
There's some if you search `injectIntl`, look at #162, the UPGRADE.md, or the `examples/` dir.

**Comment by davidspiess** [comment]
I get around this issue using the following syntax
```jsx
<FormattedMessage id={option.name} key={option.value + '-' + index}>
  {(message) => <option value={option.value}>{message}</option>}
</FormattedMessage>
```

**Comment by jacksbox** [comment]
Just if someone is still looking for an "easy" solution for this
When you set `textComponent={React.Fragment}` on the `<IntlProvider>` component, you can do this:
`<option><FormattedMessage id={option.name} /></option>`
but you can't do this (concat a value outside of the message):
`<option>5 <FormattedMessage id={option.name} /></option>` 
nor this:
`<option>{`5 ${<FormattedMessage id={option.name} />}`}</option>`

But this will work: 
`<option><React.Fragment>5 <FormattedMessage id={option.name} /><React.Fragment></option>`

**Comment by kalwalt** [comment]
I followed the code suggestions by @davidspiess and worked perfectly in a gatsby project with react-intl: 4.6.9. For anyone interested go to this [commit](https://github.com/kalwalt/gatsby-starter-i18n-bulma/pull/128/commits/587a09bdb6adec41610b089bb027ad75b608d13d)
Happy coding! :slightly_smiling_face: :partying_face:
