### ISSUE TITLE
FormatMessage into a select box

### ISSUE THREAD

**Issue by juanda99** [yahoo/react-intl#288]
What I try:

```
        <select defaultValue={this.props.locale} onChange={(e) => this.handleChange(e)}>
          <option value='es'> {<FormattedMessage {...messages.spanish}/>} </option>
          <option value='fr'> {<FormattedMessage {...messages.french}/>}</option>
          <option value='en'> {<FormattedMessage {...messages.english}/>}</option>
        </select>
```

The warning: 
Warning: Only strings and numbers are supported as <option> children.

So the select options are empty at runtime. How do I manage to get the text?

My messages are quite simple: 

```
const messages = defineMessages({
  spanish: {
    id: 'home.spanish',
    description: 'Select language',
    defaultMessage: 'Spanish'
  },
  english: {
    id: 'home.english',
    description: 'Select language',
    defaultMessage: 'English'
  },
  french: {
    id: 'home.french',
    description: 'Select language',
    defaultMessage: 'French'
  }
})
```

I can't guess why you return createElement(tagName, null, ...nodes);
in the render method of FormattedMessage.

**Comment by ericf** [comment]
Using the imperative API with always returns strings `formatMessage()`. See: #286

**Comment by juanda99** [comment]
upps, I had a look the day before and #286 was not there. Thank you!

**Comment by ericf** [comment]
@juanda99 no worries, you guys posted the same issue a couple hours apart :)
