### ISSUE TITLE
Ship tool for extracting messages to .json file by default

### ISSUE THREAD

**Issue by haf** [yahoo/react-intl#289]
**EDIT: See last comment!**

Greetings,

I would like to [extract the messages](https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L156-L167) for the FormattedMessage-s, that the react-intl plugin inside webpack generates a hashmap of, for use inside the server-side system and not just for use inside the JS client-side system.

Put differently; with the changes to v2 I don't have to place all strings in en.json anymore, but I would still like to get access to them outside of JS. How?

Regards
Henrik

## I've tried:

 - new file `.babel.rc` from here: https://github.com/yahoo/babel-plugin-react-intl/issues/23 – probably misspelt name, should be `.babelrc`.
 - new file `.babelrc`:

``` json
{
  "extra": {
    "react-intl": {
      "messagesDir": "./i18n",
      "enforceDescriptions": true
    }
  }
}
```

With webpack config

``` text
// snip
-        { test: /\.js$/,
4          loader: 'babel-loader',
-          query: {
5            // react needed for JSX syntax
5            // es2015 needed for modules
5            // stage0 needed to do splats (...variable)
5            presets: ['react', 'es2015', 'stage-0'],
5            // react-intl extracts i18n messages to a shared file
5            // add-module-exports removes the need to do `require('a').default`
5            plugins: ['react-intl', 'add-module-exports'],
5            cacheDirectory: true
5          },
4          exclude: /node_modules|bower_components/
4        },
// snip
```

gives: "index.js: Unknown option: /.babelrc.extra" as the error message.

I've tried adding the above `extra` property to the webpack configuration above, too. It gives a very similar error message.

Versions:

```
✗ npm ls | grep "intl"
├─┬ babel-plugin-react-intl@2.0.0
│ └── intl-messageformat-parser@1.2.0
├── intl@1.0.1
├── intl-locales-supported@1.0.0
├── intl-messageformat@1.2.0
├─┬ react-intl@2.0.0-pr-3
│ ├── intl-format-cache@2.0.4
```

**Comment by haf** [comment]
Syntax is thus:

```
5            plugins: [
-              ['react-intl', {
6                'messagesDir': './i18n'
6              }], 'add-module-exports']
```

**Comment by haf** [comment]
This was not the solution; there seems to be a file `examples/translations/scripts/translate.js` that does what I want. Why is this not the default in the package? How are one supposed to internationalise easily when one has to code an extractor?

Wouldn't it be better to provide that by default as an option to the programmer through the options in my last comment?

**Comment by ericf** [comment]
No, because it's a lossy process. Running that process by default would remove the extracted descriptions and the file names/paths the messages were extracted from. The descriptions are very important for the translators and the file names/paths might be used to prefix the message ids.

You'll need to post-process the JSON files before sending them off for translation, likely in a specific format for each translation service, so you'll be writing a little bit code — like what's in the translations example app.

React Intl is an internationalization library, not a localization library or service. The idea is to extract the messages from the React components and provide all useful information that developers need for their localization pipeline.

**Comment by haf** [comment]
Thanks for the clarification. However, in my case I was looking to just serve the same key-value pairs from the server as well (and doing translation there), not to extend this library to do localisation. Besides that, if this just is well documented (which it's not at the moment) I don't think it will be an issue for anybody.

**Comment by ericf** [comment]
Docs aren't done. There's a checklist in #162 where you can track the progress of v2 development. Also there's info about the state of docs, tests, and tre final v2 release in the release notes for beta-2.
