### ISSUE TITLE
FormattedTime displays Date without options

### ISSUE THREAD

**Issue by flqw** [yahoo/react-intl#291]
The use of FormattedTime without options results in the Date being displayed.
```
// Displays the date
<FormattedTime value="2016-02-09T19:30:00Z" />

// Displays the time correctly
<FormattedTime value="2016-02-09T19:30:00Z" hour="numeric" minute="numeric" />
```

I am using ``2.0.0-beta-2``.

**Comment by ericf** [comment]
This has been reported and changed on `master`: https://github.com/yahoo/react-intl/issues/263
