### ISSUE TITLE
Language fallback

### ISSUE THREAD

**Issue by eflarup** [yahoo/react-intl#292]
Apologies in advance if I am rehashing known issues here. This may in fact be just a documentation question, and I may not have found the correct doc.

If I understand https://github.com/yahoo/react-intl/issues/162 correctly, the automated language fallback is only from the "requested locale" (e.g., da-DK) to the default message (I also read Issue 35, which was closed with a reference to Issue 162, but I admit I got lost trying to figure out what the outcome, if any, of Issue 35 was).

So, in an example with the requested message locale being da-DK, there is no lookup in the da message locale if the message is not found in the da-DK file. The fallback is just directly to the default message. In other words, a standard fallback lookup from the most specific to the most general (similar to the Java default) was not implemented. That also jibes with my testing:

If I have a da-DK.json file with 2 messages, and a da.json file with 3 messages, the message missing from the da-DK.json file is not read from the ja.json file. And if I run the app in the da-DK locale, with the da-DK.json file completely missing (but the da.json file present), I get the message that the locale is not supported.

So if I want to support all Spanish locales using just one translation, (contained in es.json), there is no way to do that without custom code? Would I have to create about 30 copies of the es.json file to support the Spanish locale variants, or alternatively write my own code to do the Java-type lookup?

**Comment by ericf** [comment]
In general this is correct. In a minor of major version after v2 I'll explore a more robust fallback strategy.

> If I have a da-DK.json file with 2 messages, and a da.json file with 3 messages, the message missing from the da-DK.json file is not read from the ja.json file.

Yup. One way to handle this would be a merge of the two where `da.json` provides defaults for `da-DK.json` which overrides any defaults with its specific strings.

> So if I want to support all Spanish locales using just one translation, (contained in es.json), there is no way to do that without custom code? Would I have to create about 30 copies of the es.json file to support the Spanish locale variants, or alternatively write my own code to do the Java-type lookup?

React Intl doesn't do any file loading, it's whatever you pass into `<IntlProvider locale={} messages={}>`, so you could choose to load `es.json` for all Spanish locales and pass it into `messages`.

Note that React Intl's locale data is currently organized per **language**, not locale. So `es.js` contains locale data for `es` and all `es-*` locales.
