### ISSUE TITLE
Error on react-intl@1.2.2 for FormattedNumber

### ISSUE THREAD

**Issue by n3ssi3** [yahoo/react-intl#294]
Hey,
I just installed react-intl@1.2.2 on my react-project
When I try to use FormattedNumber in my code I get following error:
```
Invariant Violation: FormattedNumber.render():
A valid ReactComponent must be returned. You may have returned undefined,
an array or some other invalid object
```

I use JSX with webpack babel loader 
My code you can find here:
https://gist.github.com/n3ssi3/350a0bb4018b92500d9c

Thanks for the help

**Comment by ericf** [comment]
@n3ssi3 I think you want to `npm install react-intl@next` to get `v2.0.0-beta-2`. I also recommend with these beta releases to **not** use `^` or `~` in the React Intl version string in your `package.json`.

**Comment by n3ssi3** [comment]
Thanks @ericf 

But sadly that didn't help...
I get this error, even after running `npm install` :
```
./~/react-intl/~/react/react.js
Module build failed: Error: ENOENT: no such file or directory, open 'myproject/node_modules/react-intl/node_modules/react/react.js'
    at Error (native)
 @ ./~/react-intl/index.js 6:15-31
```
(PS.  ./node_modules/react-intl/node_modules/react/react.js exists)

**Comment by ericf** [comment]
Hmm… one issue is that React Intl is getting its own copy of React. In v2 it's set as a `peerDependency` so there should only be one copy of React at the root of your `/node_modules/`. Maybe, remove the entire `node_modules` dir and reinstall everything now that you have v2 in your `package.json`?

**Comment by n3ssi3** [comment]
:+1: thanks that worked
