### ISSUE TITLE
Values with value zero (0) not being rendered in messages

### ISSUE THREAD

**Issue by kumarharsh** [yahoo/react-intl#295]
I have this code in my project, where the value of `level` is a number between 0 - 5.

```jsx
<span title={props.intl.formatMessage({
        id: 'ui.widget.level.title',
        defaultMessage: 'Level: {level}',
        description: 'Title for the Level meter'
      }, {level: props.level}
)}}/>
```

This renders only `Level: ` if the value of `props.level` is 0. I tried this with `<FormattedMessage/>` too, with the same result.

Is this a bug? or should I be coercing all values passed into the intl messages to be strings?

**Comment by ericf** [comment]
Use: `{level, number}`. Also please search the other issues before opening a duplicate one as this has been asked before.

**Comment by kumarharsh** [comment]
I had, mostly variations of `zero` , `zero render`, etc, but couldn't find anything close to this. Perhaps my search terms were wrong. Thank you for your answer.

**Comment by ericf** [comment]
If you had 1000 levels, using `number` will render it as "1,000" too.
