### ISSUE TITLE
Rename `defaultMessage` to `default` or `message``

### ISSUE THREAD

**Issue by prencher** [yahoo/react-intl#298]
Would it be possible to rename `defaultMessage` to either `default` or `message`? Using `<FormattedMessage>` and `formatMessage` both lead to very long statements, and this would help without losing any contextual information.

**Comment by ericf** [comment]
I want the API to be locked for v2, many people are already depending on it and this would be a major breaking change.

**Comment by monolithed** [comment]
@ericf, v2 has been already released. 
`defaultMessage` is really ugly name for typing every day. `message` is a good alternative and you can add such alias, why not?
