### ISSUE TITLE
Question: decimal separator or thousands in numberFormatPropTypes

### ISSUE THREAD

**Issue by ValeryG** [yahoo/react-intl#299]
Is it possible to override decimal separator  or thousand separator  or define the custom ones in  in numberFormatPropTypes so FormattedNumber for 'en' locale can be flexible enough to format as 1'000,00 ?

**Comment by ericf** [comment]
It's not possible to do in a clean way. Under the hood, [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) is used and it returns an opaque string.

However we have proposed a formatToParts() API for ECMAScript which would make this much clear to replace the thousands separator, but it's not implemented yet.

**Comment by johnwp** [comment]
Is this easier to do in 2019?
