### ISSUE TITLE
2.0: injectIntl(): merge contextTypes of WrappedComponent

### ISSUE THREAD

**Issue by Kosta-Github** [yahoo/react-intl#301]
shouldn't [this](https://github.com/yahoo/react-intl/blob/bda07341d032bfb69263762a9097f7c0ef0ab348/src/inject.js#L54-L56):
```JavaScript
    InjectIntl.contextTypes = {
        intl: intlShape,
    };
```
be better changed to merge with the `contextTypes` of the `WrappedComponent`?
```JavaScript
    InjectIntl.contextTypes = {
        intl: intlShape,
        ...WrappedComponent.contextTypes
    };
```

This is for the `2.0.0-beta-2` branch...

**Comment by ericf** [comment]
It doesn't need to because The Inject Intl wrapper component renders `<WrappedComponent>`. React provides `context` on a per-component basis, therefore there's no need to thread it through the component hierarchy.
