### ISSUE TITLE
Serving translated text on v2 with react-router

### ISSUE THREAD

**Issue by adam-26** [yahoo/react-intl#302]
Hi,

I have a working isomorphic application using react-intl (v2) with react-router, and I bundle the app using webpack. Currently, I include all translated text in the main app bundle, and on load assign the localized text to the <IntlProvider> that wraps the entire application. If the user changes language, I redirect the user so the page is refreshed. This is a simple approach, and it works. 

However, it requires all translations to be embedded in the main app bundle which increases it's size. The other disadvantage with this is that it can not take advantage of the webpack code-splitting that I am using with react-router. The "Dynamic Route" feature of react-router (https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md) provides split points throughout the application for webpack to bundle.

I have spent some time looking at various possibilities that allow react-intl to take advantage of code-splitting inline with react-router, however its complicated by the fact that the application is isomorphic and also rendered by a node server, and I have not been able to get this to work. I have looked at serving the text from an endpoint that is retrieved by the app and kept as state in the app, and this can be done but I dislike the fact that extra requests are required to retrieve the text before the page can be rendered. My preference would be to have the translated text included the javascript bundles to reduce unnecessary requests. However, this requires the use of `require` statements with dynamic (locale) parameters, and webpack does not know how to handle these.

Have you considered this (or a similar) scenario? And do you have any recommendations on how to approach this? Can this be done without needing to write a webpack plugin?

Let me know your thoughts, Adam.

**Comment by ericf** [comment]
I think it's best to think of the translated strings as *data* and not code. You can serialize the initial set of strings for the user's locale when rendering on the server, and when the user switches languages in the UI, fetch new strings and pass them into the `<IntlProvider>`.
