### ISSUE TITLE
Incorrect display of currency symbol for AUD

### ISSUE THREAD

**Issue by gtibbitts** [yahoo/react-intl#304]
We are using react-intl to format currency for five different countries, all currently using the en.js locale-data. NZ, CA, US seem to format correctly. When selecting en-nz and displaying USD, I get US$. When specifying en-us and NZD, I get NZ$. When specifying en-nz and NZD, I get $, so those locales/currencies seem to work correctly. The problem is with en-au and AUD. A$ is displayed regardless of the locale I specify. I've looked through the js files and can't find where this is being done, so can someone help? There are no javascript errors on page load.

**Comment by gtibbitts** [comment]
We're using beta 2, btw.

**Comment by ericf** [comment]
See #278
