### ISSUE TITLE
Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### ISSUE THREAD

**Issue by wzup** [yahoo/react-intl#307]
After getting these errors with default `1.2.2`:
```
Warning: FormattedNumber(...): React component classes must extend React.Component.
Error: Invariant Violation: FormattedNumber.render(): A valid ReactComponent must be returned.
```

I read issues and answers here and decided to try `react-intl@next`. Now I get this:

```
Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.
```

I use server side React rendering. This is inside my route.js:
```
        var html = ReactDOMServer.renderToString(React.createElement(components.ComponentBox, {
            data: data,
            locales: aLocales
        }));
        res.render('index', {
            html: html
        })
```

And for client side:
```
    ReactDOM.render(
        <ComponentBox data={window.data} />,
        document.getElementById('content')
    );
```

And this is how I use `<FormattedNumber>` that throws an error:
```
        return (
            <li className="option" style={bi}>
                <span className="PriceVal"><FormattedNumber value={this.props.price} style="currency" currency="USD" /></span>
            </li>
        );
```

This is an example from current `react-intl` about how to use `<IntlProvider>`:
```
ReactDOM.render(
    <IntlProvider locale="en">
        <App />
    </IntlProvider>,
    document.getElementById('container')
);
```

I did so but it didn't help, I still get the error:
```
    ReactDOM.render(
        <IntlProvider locale="en">
              <ComponentBox data={window.data} />
        </IntlProvider>,
        document.getElementById('content')
    );
```

How to use `react-intl@next` with server side rendering? Does it support server side rendering?

Also, explanation that is written in README here in Github is totally different from what is written here http://formatjs.io/react/#formatted-html-message. What is right source of information about how to use the plugin?

**Comment by tsironis** [comment]
I have a similar issue when I try testing my components with jsdom.

More info here: https://gist.github.com/tsironis/247a0a7f7a0132a37be1

**Comment by driesvancraen** [comment]
Is this an error in this release or am I trying to implement this wrong?

```
import {IntlProvider} from 'react-intl';
class App extends React.Component {
  render() {
    return (
      <IntlProvider locale="en">
        <div>{this.props.children}</div>
      </IntlProvider>
    )
  }
}
```

**Comment by tsironis** [comment]
Any updates on this one?

**Comment by ericf** [comment]
Not sure how to help. Might be useful to read the [upgrade guide](https://github.com/yahoo/react-intl/blob/master/UPGRADE.md), and look at the [examples](https://github.com/yahoo/react-intl/tree/master/examples).

I can tell you that v2.0.0-beta-2 works on both the server and client.

**Comment by tsironis** [comment]
For anyone looking for an answer and uses jsdom to test components, I neglected to render inside a ```IntlProvider``` component when running tests. How silly of me

```
...
describe('Component Test', function() {

  it('rendering', function() {
    const renderedComponent = renderIntoDocument(<IntlProvider locale="en"><Comp /></IntlProvider>);
    ...
  });
});
```

**Comment by raulra08** [comment]
Wrapping my <div> in a <IntlProvider> did the job.

`
import "babel-polyfill";
import React from "react";
import {IntlProvider} from 'react-intl';

class App extends React.Component {
    render() {
        return (
            <IntlProvider locale="en">
                <div className="wrapper">
                    <Header />
                    <Sidebar />
                    <Content/>
                    <Footer/>
                </div>
            </IntlProvider>
        );
}}
export default App;
`

**Comment by EdgarOrtegaRamirez** [comment]
You can also wrap your Router from `react-router` with `<IntlProvider>`:

Using `react-intl@2.1.5`

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { Router, Route, hashHistory } from 'react-router'
import { IntlProvider } from 'react-intl'

ReactDOM.render(
  <IntlProvider locale="en">
    <Router history={hashHistory}>
      <Route path="/" component={App} />
    </Router>
  </IntlProvider>,
  document.getElementById('root')
)
```

**Comment by joetidee** [comment]
Try this package [enzyme-react-intl](https://github.com/joetidee/enzyme-react-intl)

**Comment by xanderiel** [comment]
In case you haven't done so, wrap your entire app in an `IntlProvider`:
```
ReactDOM.render(
    <IntlProvider locale={locale} messages={messages}>
        <App />
    </IntlProvider>,
    document.getElementById('container')
);
```
Example from `react-intl`:
https://github.com/yahoo/react-intl/blob/master/examples/translations/src/client/index.js

**Comment by smakosh** [comment]
> Wrapping my div in a IntlProvider did the job.
> 
> ```
> import "babel-polyfill";
> import React from "react";
> import {IntlProvider} from 'react-intl';
> 
> class App extends React.Component {
>     render() {
>         return (
>             <IntlProvider locale="en">
>                 <div className="wrapper">
>                     <Header />
>                     <Sidebar />
>                     <Content/>
>                     <Footer/>
>                 </div>
>             </IntlProvider>
>         );
> }}
> export default App;
> ```

You could wrap it with a Fragment now 👍

**Comment by jinxin0112** [comment]
What causes it?

**Comment by GiuMagnani** [comment]
If someone is still facing this issue (like me today), I had the `IntlProvider` inside the **Layout** file that was inside `gatsby-browser.js`, so when I tried to build, the server couldn't find the Provider (https://github.com/gatsbyjs/gatsby/issues/688). 

I solved it moving **Layout** inside `IntlProvider`, then creating the `gatsby-ssr.js` file and adding the same behaviour using `wrapPageElement` API:

```
export const wrapPageElement = ({ props, element }) => {
  const locale = props.pageContext.locale;
  const pageLocale = locale || defaultLocale;

  return (
    <IntlProvider locale={locale} messages={messages[pageLocale]}>
      <Layout locale={locale} {...props}>
        {element}
      </Layout>
    </IntlProvider>
  );
};
```

My repository: https://github.com/GiuMagnani/giu-magnani-website

Issues related:
https://github.com/yahoo/react-intl/issues/865
https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/77

**Comment by eboutahir** [comment]
> Try this package [enzyme-react-intl](https://github.com/joetidee/enzyme-react-intl)

that solve my life :smile:  thanks @joetidee

**Comment by panasoniclam** [comment]
@wzup  thanks

**Comment by mdforhadsarker** [comment]
> Wrapping my div in a IntlProvider did the job.
> 
> ```
> import "babel-polyfill";
> import React from "react";
> import {IntlProvider} from 'react-intl';
> 
> class App extends React.Component {
>     render() {
>         return (
>             <IntlProvider locale="en">
>                 <div className="wrapper">
>                     <Header />
>                     <Sidebar />
>                     <Content/>
>                     <Footer/>
>                 </div>
>             </IntlProvider>
>         );
> }}
> export default App;
> ```

It worked

**Comment by menosprezzi** [comment]
Please help!

I dont understand WHY this error is popping to me:
```
"react": "^16.13.1",
"react-intl": "^5.9.4",
"@testing-library/react": "^9.5.0",
"jest": "^26.5.2",
```

and my test:

```ts
  it('should match snapshot', () => {
    const { asFragment } = render(
      <IntlProvider locale='en'>
        <UnavailabilityChartCard {...MOCK} />
      </IntlProvider>
    );
    expect(asFragment()).toMatchSnapshot();
  });
```

I did everything, but it still not working!
https://codesandbox.io/s/react-intl-and-react-testing-library-forked-zcnlc?file=/src/__tests__/FormatDateView.test.js
Here at codesandbox it worked!

**Comment by longlho** [comment]
If you cannot repro it in a sandbox it's prob something with your test setup.

**Comment by menosprezzi** [comment]
I found it! I'm using yarn workspaces and I have 2 versions of react-intl :( So I have 2 different contexts
So silly prob.

Thank you!

**Comment by azizmashkour** [comment]
I have followed the same logic and implemented it this way:

```
const locale =
  (navigator.languages ? navigator.languages[0].split(/[-_]/)[0] : false) ||
  navigator.language ||
  navigator.browserLanguage ||
  'en';

const messages = locales[`${locale}`];

ReactDOM.render(
  <Provider store={store}>
    <IntlProvider locale={locale} messages={messages}>
      <App />
    </IntlProvider>
  </Provider>,
  document.getElementById('app-container'),
);```
but unfortunately it's showing me this error I am not able to understand

Could someone please help?

**Comment by azizmashkour** [comment]
![Screen Shot 2021-04-07 at 1 58 10 PM](https://user-images.githubusercontent.com/10519310/113879797-2fb4f900-97bb-11eb-80f6-07c24f8b2db8.png)

**Comment by Baldrani** [comment]
Okay so in my case it was due to SSR.

In addition of the "locale" Provider which allow language switching.

I've added to my `_document.jsx` a Provider which get the locale from the router.

```jsx
 class MyDocument extends Document<TDocumentInitialProps> {
        static async getInitialProps(ctx: DocumentContext): Promise<TDocumentInitialProps> {
            const messages = (await importMessages(ctx.locale)) as Record<string, string> | Record<string, MessageFormatElement[]>;

            return {
                locale: ctx.locale,
                messages,
            };
        }

        render(): JSX.Element {
            const { locale, messages } = this.props;

            return (
            <IntlProvider locale={locale} messages={messages}>
                <Html lang={locale}>
                <Head>
                    <link rel="icon" href="/images/layout/favicon.png" />
                </Head>
                <body>
                    <Main />
                    <NextScript />
                </body>
                </Html>
            </IntlProvider>
            );
        }
    }

    export default MyDocument;
    ```
