### ISSUE TITLE
Importing react-intl from a jest spec fails

### ISSUE THREAD

**Issue by sri** [yahoo/react-intl#308]
I have a passing test. If I add `import ReactIntl from 'react-intl';` to it, it fails with the following error message (I've modified the paths and test name so that I can publish this publicly):

> TypeError
  /app/assets/javascripts/frontend/my_app/__tests__/My-test.js
  /app/assets/javascripts/frontend/jspm_packages/npm/react-intl@2.0.0-beta-1/lib/react-intl-with-locales.js
  /app/assets/javascripts/frontend/jspm_packages/npm/react-intl@2.0.0-beta-1/lib/react-intl.js
  /app/assets/javascripts/frontend/jspm_packages/npm/react-intl@2.0.0-beta-1/lib/locale-data-registry.js
  /app/assets/javascripts/frontend/jspm_packages/npm/intl-messageformat@1.2.0/index.js
  /app/assets/javascripts/frontend/jspm_packages/npm/intl-messageformat@1.2.0/lib/main.js
 src$core$$.default.__addLocaleData is not a function

What's actually happening is that some of the React components deep in the hierarchy import `react-intl` and that's where it fails. BTW, I'm using react-intl 2.0 beta. Any ideas on how to fix this?

Thanks!

**Comment by bmcconaghy** [comment]
This can be fixed by adding "<rootDir>/node_modules/intl-relativeformat" to the  unmockedModulePathPatterns list.

**Comment by ericf** [comment]
Try updating to 2.0.0-beta-2. Also there's no default export, only named exports, so at the very least you should update you're import statement to:

```js
import * as ReactIntl from 'react-intl';
```

**Comment by alejandroiglesias** [comment]
I'm having the same issue. I'm running `2.0.0-beta-2`.

@bmcconaghy i tried your solution but didn't worked. Same error.
@ericf i'm using that version and using named imports.

**Comment by bmcconaghy** [comment]
@alejandroiglesias you also need to add react-intl and intl-relativeformat.  Sorry, should have mentioned that in my initial comment.

**Comment by alejandroiglesias** [comment]
@bmcconaghy i did added both to `unmockedModulePathPatterns` but still fails.

**Comment by bmcconaghy** [comment]
@alejandroiglesias I would try just the module names without directory paths.  Jest figures it out without the actual paths in my experience.

**Comment by bmcconaghy** [comment]
@alejandroiglesias also add intl-messageformat.

**Comment by alejandroiglesias** [comment]
@bmcconaghy adding `react-intl`, `intl-relativeformat` and `intl-messageformat` seemed to work since now i'm getting different kinds of errors on my specs. I suppose i should open a different issue asking for those, right? Thanks.

**Comment by emj365** [comment]
@bmcconaghy Same problem here, did you fix it?
