### ISSUE TITLE
Trying to add locales from an ajax return

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#310]
How can i add locales from an object after an ajax call?

I tried this:

```javascript
addLocaleData({
    locale: 'en',
    messages: messageI18n,
  });
```

But it seems messages is not correct. `messageI18n` is built like any other locales in my app. How can i make it possible? Thank you!

**Comment by ericf** [comment]
`addLocaleData()` is specific for the locale data that React Intl needs internally to run, it includes pluralization rules and relative-time patterns. You shouldn't pass your translated strings into this method, you should pass them into `<IntlProvider>`, which can be nested.

**Comment by DWboutin** [comment]
I can i pass it trough `<IntlProvider>`? I got this to handle my base EN language.

```javascript
const messages = defineMessages({
  aboutDev: {
    id: 'about.dev',
    description: 'Welcome to the development version of the application',
    defaultMessage: 'Welcome to the development version of the application',
  },
  menuDashboard: {
    id: 'menu.dashboard',
    description: 'Dashboard',
    defaultMessage: 'Dashboard',
  },
...
```

After i pass it to my main app like this

```javascript
render() {
    const { children, loggedIn, user, application, location } = this.props;

    const intlData = {
      locale: application.locale,
      messages: i18n[application.locale],
    };

    const className = location.pathname.substr(1).replace('/', '-');

    return (
      <IntlProvider key="intl" {...intlData}>
        <div id="application" className={className}>
          <div className="page-wrap">
            <Header loggedIn={ loggedIn } user={ user } handleLogout={ this.handleLogout } handleLanguageChange={this.handleLanguageChange} />
            <MainNavigation />
            {children}
          </div>
          <Footer />
        </div>
      </IntlProvider>
    );
  }
```

Now i need to add some strings to intlData after an ajax call. How can i do this?

Thank you very much

**Comment by ericf** [comment]
Pass it into the `<IntlProvider>` as props after making the request to fetch updated translations.
