### ISSUE TITLE
Getting error: "Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by NikZar** [yahoo/react-intl#311]
Hi all, I am struggling integrating react-intl in my hobby [project](https://github.com/NikZar/Reactiwall) .

These are my current react-intl dependencies:

>     "babel-plugin-react-intl": "^2.0.0",
>     "react-intl": "^2.0.0-beta-2",

Lately I have started getting this error in the component that is using the FormattedMessage while starting webpack:

> ERROR in ./app/components/Home.js
> Module build failed: TypeError: /Users/niko/Sites/Reactiwall/app/components/Home.js: Path must be a string. Received undefined
>     at assertPath (path.js:8:11)
>     at Object.posix.join (path.js:479:5)
>     at PluginPass.exit (/Users/niko/Sites/Reactiwall/node_modules/babel-plugin-react-intl/lib/index.js:155:46)
>     at newFn (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/visitors.js:293:19)
>     at NodePath._call (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/path/context.js:74:18)
>     at NodePath.call (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/path/context.js:46:17)
>     at NodePath.visit (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/path/context.js:116:8)
>     at TraversalContext.visitQueue (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/context.js:153:16)
>     at TraversalContext.visitSingle (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/context.js:113:19)
>     at TraversalContext.visit (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/context.js:197:19)
>     at Function.traverse.node (/Users/niko/Sites/Reactiwall/node_modules/babel-traverse/lib/index.js:139:17)
>  @ ./app/containers/HomePage.js 25:12-41

Here it is the component code:

```
import React, { Component } from 'react';
import { Link } from 'react-router';
import styles from './Home.module.css';
import {FormattedMessage, defineMessages} from 'react-intl';
import LanguagePickerContainer from '../containers/LanguagePickerContainer';

export default class Home extends Component {
  render() {
    const messages = defineMessages({
        greeting: {
            id: 'greeting',
            description: 'Welcome greeting to the user',
            defaultMessage: 'Hello, {name}! How are you today?'
        }
    });
    return (
      <div className={styles.container}>
        <h2>Reactiwall</h2>
        <Link to="/counter">to Counter</Link>
        <br />
        <Link to="/message">to Message</Link>
        <h1>
          <FormattedMessage {...messages.greeting} values={{name: 'niko'}} />
        </h1>
        <LanguagePickerContainer />
      </div>
    );
  }
}
```
Anybody can help me understanding what am I doing wrong?
(This is my first attempt to learn how to use react, webpack, etc.  )

Thank you in advance!

**Comment by ericf** [comment]
This has been fixed in `babel-plugin-react-intl@2.1.1`: https://github.com/yahoo/babel-plugin-react-intl/issues/36
