### ISSUE TITLE
FormattedRelative - shows yesterday instead of today after setHours

### ISSUE THREAD

**Issue by WilliamHolmes** [yahoo/react-intl#312]
I'm see an issue after setting hours back to 0.
("react-intl": "2.0.0-beta-2")

new Date(1454976000000)
Tue Feb 09 2016 00:00:00 GMT+0000 (GMT Standard Time)

ISSUE (pseudo): ...
```
<IntlProvider locale={'en'}>

let time = (new Date().setHours(0, 0, 0, 0));

<FormattedRelative value={time} style={'best-fit'} units={'day'} />
```

RESULT:     YESTERDAY

EXPECTED:     TODAY

**Comment by ericf** [comment]
It's rounding according to [this](https://github.com/yahoo/intl-relativeformat/blob/master/src/core.js#L80-L92). So I think that means when it's the 0–2nd hour in the day, it will say "yesterday". These thresholds will likely be revisited in the future…

**Comment by WilliamHolmes** [comment]
Thanks for the info.

Can this be overridden, or can I set a custom property for RelativeFormat threshold?

**Comment by ericf** [comment]
Yeah, but it will affect all code importing `intl-relativeformat`.

```js
import IntlRelativeFormat from 'intl-relativeformat';
IntlRelativeFormat.thresholds.hour = 24;
```
