### ISSUE TITLE
format Number - currency - styles

### ISSUE THREAD

**Issue by lwelti** [yahoo/react-intl#313]
do you support only one style for the format Number Currency ?

so for the en-US user and currency USD will get $9.00 
so for the en-US user and currency MXN will get MX$9.00 
but for the es-MX user and currency MXN will get $9.00

is that the case?

**Comment by ericf** [comment]
It's what the browsers support. `<FormattedNumber>` calls: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by lwelti** [comment]
and the Intl polyfill supports all of those formats or just few?

**Comment by ericf** [comment]
I believe all forms for NumberFormat, and some forms for DateTimeFormat (e.g. it doesn't support tz).
