### ISSUE TITLE
v2 does not support falsy message values

### ISSUE THREAD

**Issue by Zemljoradnik** [yahoo/react-intl#314]
I have a message that looks like this `Found {count} items.`, and when I try to use it like this:

`<FormattedMessage
    {...messages.foundItems}
     values={{count: 0}}
/>`

The result is `Found items.`

The problem is in the compiler.js:
```
StringFormat.prototype.format = function (value) {
    if (!value) {
        return '';
    }

    return typeof value === 'string' ? value : String(value);
};
```

**Comment by petersendidit** [comment]
Think you want your message to really be `Found {count, number} items.`

**Comment by Zemljoradnik** [comment]
Sorry, I wasn't clear enough: this was only an example why I think this is inconsistent behavior. If the value doesn't have to bi string (and it is being coersed to string anyway), I think 0 should be valid value like any other number.
