### ISSUE TITLE
zh-HK locale is resolved to "zh" instead of "zh-Hant-HK"

### ISSUE THREAD

**Issue by drmcdev** [yahoo/react-intl#317]
In intl.js, "zh-HK" is equal to "zh-Hant-HK" which is traditional Chinese . However in react-intl, it is resolved to "zh" which is simplified Chinese.

**Comment by ericf** [comment]
Please provide an example.

**Comment by drmcdev** [comment]
> new IntlRelativeFormat('zh-HK').format(new Date(1526271670524))
'2年后'
> new IntlRelativeFormat('zh-Hant-HK').format(new Date(1526271670524))
'2 年後'
> new IntlRelativeFormat('zh-Hans-HK').format(new Date(1526271670524))
'2年后'

It means zh-HK is interpreted as 'zh' instead of 'zh-Hant-HK'.

However in intl.js, zh-HK is the same as zh-Hant-HK.

**Comment by ericf** [comment]
zh-HK is not a valid locale, use zh-Hant-HK.
