### ISSUE TITLE
Get pure format function

### ISSUE THREAD

**Issue by Bloomca** [yahoo/react-intl#318]
Hello!

Thanks for the library, it works great, but I want to have a pure function exports as well.

My problem is that I want to get just a string (but with interface to handle my price objects), and I don't want to use context in every component.

Do you have any ideas?

**Comment by ericf** [comment]
If you don't want to use the components or API that's provided via injectIntl(), then you could just use the built-in Intl APIs directly; e.g. Intl.DateTimeFormat.
