### ISSUE TITLE
Beta 2 does not work in Mac Safari

### ISSUE THREAD

**Issue by Sinistralis** [yahoo/react-intl#320]
Attempting to use this module in safari causes the following JS error:

[Error] ReferenceError: Can't find variable: Intl

I'll try to track this down and see exactly where this is happening.

**Comment by Sinistralis** [comment]
It looks like this is caused by Safari not implementing the Intl spec. It can be pollyfilled via https://www.npmjs.com/package/intl.

I'm trying this now. If it fixes the problem, this should probably be documented somewhere.

**Comment by caridy** [comment]
That's correct, just polyfill that using the npm pkg or the FT polyfill service: https://github.com/andyearnshaw/Intl.js#getting-started

**Comment by Sinistralis** [comment]
My bad, didn't notice that. Thanks for the prompt reply.
