### ISSUE TITLE
Importing localeData does not work as described

### ISSUE THREAD

**Issue by c089** [yahoo/react-intl#323]
Examples and #162 mention to import locales from `react-intl/locale-data/de`. Turns out I have to use `react-intl/lib/locale-data/de` instead (note the extra `/lib/` in there). The project I tested this in runs on node 5.5 and bundles for the client using browserify 13.

**Comment by ericf** [comment]
This is fixed on master

**Comment by c089** [comment]
:+1: thanks for the quick response
