### ISSUE TITLE
Give more explanation about `=0 { No comments yet }` in Readme

### ISSUE THREAD

**Issue by kidwm** [yahoo/react-intl#324]
In README.md:
```
Note: You could also write `=0 { No comments yet }`
```
As a newbie to FormatJS, I did not understand what does this line means, where should it be inserted to take effect?

**Comment by ericf** [comment]
http://formatjs.io/guides/message-syntax/#plural-format

**Comment by kidwm** [comment]
@ericf Thanks, but why not add a reference link to it ?

**Comment by ericf** [comment]
There are many links to the website in the README and at the top of the /react/ page it links to it.
