### ISSUE TITLE
v2.0.0-beta-2: Setting locale and defaultLocale to the same value still produces warning "[React Intl] Missing message"

### ISSUE THREAD

**Issue by bwhitty** [yahoo/react-intl#326]
Example:

```js
<IntlProvider locale="en_US" defaultLocale="en_US">
  ...
</IntlProvider>
```

If I then using a string (for example with id 'home.greeting') a warning will be produced like the following 
`[React Intl] Missing message: "home.greeting" for locale: "en_US", using default message as fallback.`

I would expect the fact that locale === defaultLocale would mean falling back to the default message is expected and therefore should not throw a warning.

Am I missing something?

**Comment by ericf** [comment]
See #251

**Comment by bwhitty** [comment]
Sorry about that, thanks!
