### ISSUE TITLE
 IntlProvider component not updating when props change for the first time

### ISSUE THREAD

**Issue by aoshi321** [yahoo/react-intl#329]
Hi

I have the following code
```
  <IntlProvider locale={ this.props.locale } messages={ this.props.translations }>
      <div>
        <div>
          {children}
        </div>
      </div>
  </IntlProvider>
```

When the props are updated for the locale and the messages, its not updating the messages the first time they change in the children. It then precedes to use the previously updated props. If I use the IntlProvider as the parent for a child I don't have this problem

**Comment by ericf** [comment]
`<IntlProvider>` needs to wrap any usage of the `<Formatted*>` components, most people use it at the root. See the `/examples/` dir in this repo.
