### ISSUE TITLE
How to use without mixins [ES6]

### ISSUE THREAD

**Issue by alexmngn** [yahoo/react-intl#330]
Hi there,
I'm interested to use this module for my react application, but I cannot find a way to use it without the mixin. As ES6 classes doesn't has any support for mixins, I'm wondering what would be the best way to do it?
Thanks.

**Comment by aoshi321** [comment]
Hi 

If you look at the example on the main page you you can use the IntlProvider component as the parent container of your application. You need to download the latest version  react-intl@next

**Comment by alexmngn** [comment]
Can you explain what the `addLocale` method does and if I have to use it?

**Comment by aoshi321** [comment]
The 'en' locale you get by default. For other non english languages  like french for instance you need to add the the locale as follows:
import { addLocale} from 'react-intl';
import fr from 'react-intl/lib/locale-data/fr';

addLocale(fr);

**Comment by alexmngn** [comment]
So I've added the following to my code above but it still doesn't work.

```
import { IntlProvider, addLocaleData } from 'react-intl';
import enLocaleData from 'react-intl/lib/locale-data/en';

addLocaleData(enLocaleData);
addLocaleData({
  locale: 'en-US',
  parentLocale: 'en'
});

```

What is wrong ?

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/wiki/Upgrade-Guide
https://github.com/yahoo/react-intl/issues/203
