### ISSUE TITLE
Uglify output has all languages but I only want 10

### ISSUE THREAD

**Issue by adriaanbalt** [yahoo/react-intl#331]
I'm having difficulty reducing the size of my minified JavaScript output and it's due to React Intl loading all country's locale data.  I want to include only a subset of all the languages and I had assumed to do so I would do the following:
```js
let enabledLanguages = [
	'en',
	'ar',
	'es',
	'fr',
	'fr-CA',
	'po',
	'pt-BR',
	'ru',
	'th',
	'tr',
	'zh'
];

if (!window.Intl) {
	window.Intl = require('intl');
	window.Intl.polyFill = true;
}

let localizations = {};
enabledLanguages.forEach((val) => {
	localizations[val] = require(`../../localization/${val}`); 
	window.Intl.polyFill && require(`intl/locale-data/jsonp/${localizations[val].locale}`);
	localizations[val].messages = flattenMessages(localizations[val].messages);
	addLocaleData(require(`react-intl/lib/locale-data/${localizations[val].locale}`));
});
```
But regardless, my output JS has every country's localization data.  Am I missing a step?  I see that it does correctly grab my custom localization data and the app still works perfectly.  At the root of my app, in `App.js`, I have `<IntlProvider {...this.state.intlContent || {locales: this.state.currentLocale, messages:{}}}>` so I can correct get the correct local data and the messages.

Thanks

**Comment by ericf** [comment]
What build system are you using? I have the `browser` field in `package.json` set to ignore the `lib/locale-data/index.js` file which contains all of the locale data. I've tested this with Browserify and Webpack, but maybe there's a recent change to these tools that's not respecting the `browser` field anymore?

**Comment by adriaanbalt** [comment]
Hi Eric,
It seems that if I do not dynamically require the locales, which I'm doing within the `ForEach` over `enabledLanguages` array, it will load all locales.
But if I separately require each locale individually, it works, like this:
```
window.Intl.polyFill && require('intl/locale-data/jsonp/en')
addLocaleData(require('react-intl/lib/locale-data/en'))

window.Intl.polyFill && require('intl/locale-data/jsonp/ar')
addLocaleData(require('react-intl/lib/locale-data/ar'))

window.Intl.polyFill && require('intl/locale-data/jsonp/es')
addLocaleData(require('react-intl/lib/locale-data/es'))

window.Intl.polyFill && require('intl/locale-data/jsonp/fr')
addLocaleData(require('react-intl/lib/locale-data/fr'))

window.Intl.polyFill && require('intl/locale-data/jsonp/fr-CA')
addLocaleData(require('react-intl/lib/locale-data/fr'))

window.Intl.polyFill && require('intl/locale-data/jsonp/pl')
addLocaleData(require('react-intl/lib/locale-data/pl'))

window.Intl.polyFill && require('intl/locale-data/jsonp/pt')
addLocaleData(require('react-intl/lib/locale-data/pt'))

window.Intl.polyFill && require('intl/locale-data/jsonp/ru')
addLocaleData(require('react-intl/lib/locale-data/ru'))

window.Intl.polyFill && require('intl/locale-data/jsonp/th')
addLocaleData(require('react-intl/lib/locale-data/th'))

window.Intl.polyFill && require('intl/locale-data/jsonp/tr')
addLocaleData(require('react-intl/lib/locale-data/tr'))

window.Intl.polyFill && require('intl/locale-data/jsonp/zh')
addLocaleData(require('react-intl/lib/locale-data/zh'))
```
I'm surprised but do you know if there is anyway to make this dynamic and not force React Intl to load all locales up front?  Thanks

**Comment by ericf** [comment]
I generally recommend loading only the language data you need on the page. You can do this by having the HTML document only load the locale data scripts for the current language.

Not sure why Webpack would be including _all_ of the locale data, but maybe it's `require()` heuristics don't like your dynamic string.

**Comment by maxguzenski** [comment]
When you use variable into require, webpack will import all folder files because it dont know what you will need at runtime level. Webpack call this "context":

https://github.com/webpack/docs/wiki/context

You have to use ContextReplacementPlugin
https://webpack.github.io/docs/list-of-plugins.html#contextreplacementplugin
