### ISSUE TITLE
after add IntlProvider setState do not work with test JEST

### ISSUE THREAD

**Issue by emj365** [yahoo/react-intl#332]
```
describe('Quotation', () => {
  let component, renderedDOM;
  // Quotation.prototype.loadFromServer = jest.genMockFunction();

  beforeEach(() => {
    component = TestUtils.renderIntoDocument(
      <IntlProvider locale='en'>
        <Quotation />
      </IntlProvider>
    );
  });

  it('quotation loaded', () => {
    let lastPrice;
    component.setState({last: 1100, prevClose: 1000})
    lastPrice = TestUtils.findRenderedDOMComponentWithClass(
      component, 'last-price'
    );
    console.log(component.state.last); // => 1100
    expect(lastPrice.textContent).toEqual('1100'); // => failed
  });
}
```

```
  render() {
    return (
      <div className="quotation">
        <div className="title">{this.props.children}</div>
        <div className="last-price">
          this.state.last // => undefine
        </div>
      </div>
    );
  }
```

After `setState`, `component.state.last` return a number but `this.state.last` is `undefined` in `render`.
It only happen when I use `IntlProvider`.
I've tried add `component.forceUpdate();` before `expect`. Doesn't help.

**Comment by ericf** [comment]
You're calling `setState()` on the `<IntlProvider>` component. Not sure what you're expecting, but that's not going to result in anything. Maybe you want to set a `ref` on `<Quotation>` so you can access it, and call `setState()` on **it**.

**Comment by emj365** [comment]
@ericf thank you so much. I made a mistake. It's not a bug of `react-intl`.
I spent lot of time to figure out how to solve that problem. But I'm beginner for reactJS unit test.
Could you tell me how to `ref` to help me? Thank you very much.

**Comment by ericf** [comment]
> Could you tell me how to ref to help me? Thank you very much.

There are many resources on the web that provide help with React and would do a better job than me, start with the React docs.

**Comment by emj365** [comment]
Thank you.

**Comment by emj365** [comment]
https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl
@ericf but I feel test demo is not enough for me.
Now I got Quotation component by use 
```
    let quotation = TestUtils.findRenderedComponentWithType(
      component, Quotation
    );
```
but got 

```
  - TypeError: state.getNumberFormat is not a function
        at formatNumber (node_modules/react-intl/lib/format.js:115:18)
        at FormattedNumber.render (node_modules/react-intl/lib/components/number.js:62:35)
        at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
        at ReactCompositeComponentMixin._renderValidatedComponent (node_modules/react/lib/ReactCompositeComponent.js:607:32)
        at wrapper [as _renderValidatedComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:220:30)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
```
when I 
```
quotation.setState({last: 1100, prevClose: 1000});
```

could you help to create more test demo? I couldn't do every test with shallow rendering.

**Comment by emj365** [comment]
@ericf more detail here http://stackoverflow.com/questions/35649687/reactjs-how-can-i-setstate-with-inner-component
