### ISSUE TITLE
Formatted number not rendering correctly

### ISSUE THREAD

**Issue by aoshi321** [yahoo/react-intl#333]
Hi

Im using the latest beta version and when I use the 'FormatNumber' as follows:
```
 <FormattedNumber value={1000} style="currency" currency="USD" />
```
It renders

1 000,00 $US

thanks

**Comment by ericf** [comment]
What's the locale and browser, also what were you expecting?

You should try your combination of configuration options with [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) and if you get the same result, then it's not a bug in this lib.

**Comment by ericf** [comment]
Closing this for lack of information.
