### ISSUE TITLE
how to write jest test with state change?

### ISSUE THREAD

**Issue by emj365** [yahoo/react-intl#334]
https://github.com/yahoo/react-intl/issues/332

I couldn't aways write test with shallow render like https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl

I need to change state. could you create some demo? please.

**Comment by ericf** [comment]
Please don't ask for support like this.

**Comment by emj365** [comment]
Sorry I mean shallow render don't support test with `setState`. 
Why not create more demos other than shallow render?
