### ISSUE TITLE
formatMessage is weird with Number zero

### ISSUE THREAD

**Issue by carystanley** [yahoo/react-intl#335]
formatMessage seems to handle excepting numbers as params, but does nor seem to handle the zero value correctly.

Example:

lang/strings.json:
{
   "PROGRESS": "Progress ({count}/{total})",
}

code:
var count = 0;
var total = 25;
var str = this.context.intl.formatMessage({id: 'PROGRESS'}, {count: count, total: total});

Expected: str === "Progress (0/25)"
Actual: str === "Progress (/25)"

**Comment by ericf** [comment]
Use `{count, number}`

**Comment by esquevin** [comment]
Why are falsy values not displayed to begin with ? I keep forgetting to add `, number` especially in plural messages.
