### ISSUE TITLE
<FormattedRelative/> is too resolving

### ISSUE THREAD

**Issue by halt-hammerzeit** [yahoo/react-intl#337]
I'm using `<FormattedRelative/>` and first it shows `now`, then it shows `1 second earlier`, `2 seconds earlier`, `3 seconds earlier`, etc.
I would like to implement my own resolution scale.
For example: "recently (< 5 min)", "X minutes earlier", "half an hour", etc.
Is it possible with this tag or should I write my own tag?

**Comment by ericf** [comment]
The actual strings comes from CLDR and cannot currently be customized. You can set the [`updateInterval`](https://github.com/yahoo/react-intl/blob/master/src/components/relative.js#L137) which defaults to 10 seconds to something longer.

I don't recommend trying to write your own custom component, `<FormattedRelative>` does work under the hood to extend its re-renders to the longest interval possible before the next "interesting moment" based on delta and the configured `updateInterval`.
