### ISSUE TITLE
Conflicting information on pre-defined date formats

### ISSUE THREAD

**Issue by alanhogan** [yahoo/react-intl#34]
According to formatjs.io/guide, formatjs comes with 4 pre-defined date formats:

![screen shot 2014-11-24 at 1 58 00 pm](https://cloud.githubusercontent.com/assets/6808/5174128/60d156e4-73e3-11e4-82af-08b1eb1aa611.png)

However, the React integration docs eventually make it clear (although this [escaped my notice](http://stackoverflow.com/questions/27010990/with-react-intl-how-do-i-fix-error-uncaught-referenceerror-no-date-format-nam/27062814?iemail=1&noredirect=1#27062814)), and my experience agrees, that it doesn’t actually ship with these pre-defined.

![react makes you define date formats](https://cloud.githubusercontent.com/assets/6808/5174127/60b18314-73e3-11e4-92ba-23459c0a2811.png)

**Please either include these 4 useful pre-defined formats in react-intl, or update the main /guide to alleviate this confusion.**

**Comment by ericf** [comment]
Closing this as it's now outdated with v2.
