### ISSUE TITLE
Custom Formatting in FormattedDate

### ISSUE THREAD

**Issue by ravi-tj** [yahoo/react-intl#340]
@ericf 
According to this doc : http://formatjs.io/react/#formatted-date

the date format output is `March 1, 2016`,  but what if I need my custom format, lets say 
`11 Aug 2016 at 12.30 PM`
where the format is like DD SHORTENED MNTH NAME - YYYY at HR.MIN AM/PM

**Comment by ericf** [comment]
All of the options here are supported: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters

See: https://github.com/yahoo/react-intl/blob/master/src/types.js

**Comment by santosguilherme** [comment]
@ravi-tj how to resolve it?

**Comment by okovpashko** [comment]
@santosguilherme I suppose that it's not a thing `react-intl` created for. Under the hood, it uses browsers `Intl` object that doesn't provide an ability to use a custom format.

**Comment by santosguilherme** [comment]
Thanks, @okovpashko. I have already solved by combining the FormattedDate and FormattedTime elements.

**Comment by okovpashko** [comment]
@santosguilherme I wrote about custom formatting using only `FormattedDate`. Did you combine them using `FormattedMessage`, or just write something like `<FormattedDate ... /> at <FormattedTime/>`?

**Comment by okovpashko** [comment]
@santosguilherme it's a good way.The message format is flexible and can be easily changed by translators according to target language.
