### ISSUE TITLE
Access to defineMessages by string  - not only by key

### ISSUE THREAD

**Issue by Shachar16290** [yahoo/react-intl#343]
Hi,

I'm using react-intl and I wish to have the option to write defineMessages this way: 

```javascript
const messages = defineMessages({
 "my.namespaced.id": { 
      defaultMessage: "My message", 
      description: "My description" 
  }
}
```

And then do : 

```javascript
 {...messages["my.namespace.id"]}
```

I notice other people asked for it in here:  #162 

For now, I use only external messages file and pass it to IntlProvider and then access the messages by string id with InjectIntl -  formatMessage.
I want the option to use defineMessages inside each component and not in external file.

Thank you.

**Comment by ericf** [comment]
The decoupling between the property name on the `messages` object from the message's unique `id` is an explicit design decision. This way shorter "local" names/bindings can be given while not changing the message's `id` which could result in the translation system charging for re-translation.

> I want the option to use defineMessages inside each component and not in external file.

I don't understand what you're asking for which isn't already possible today.

**Comment by Shachar16290** [comment]
> I don't understand what you're asking for which isn't already possible today.

I think you did not understand me.
I would like to access my messages by string and not by key. I'm trying to map types generically. For example: 
One of my component props is type('sms', 'call' etc..) - `this.props.type` . I want to map it to message from `messages`:

```javascript
const messages = defineMessages({
 "sms": { 
      defaultMessage: "My SMS message", 
      description: "My description" 
  },
 "call": { 
      defaultMessage: "My CALL message", 
      description: "My description" 
  }
}
```
and then to access it in my component :

```javascript
 {...messages[this.props.type]}
```
This way I wont need to check which message I need to present. 
Hope it is more informative now.

**Comment by ericf** [comment]
This works today:

```js
<FormattedMessage {...messages[this.props.type]} />
```

**Comment by Shachar16290** [comment]
I want to to use InjectIntl.formatMessge() function. I don't want to use `<FormattedMessage {...messages[this.props.type]} />`  because it limits me.
Is there a way to use it  like this:
` InjectIntl.formatMessge( {...messages[this.props.type]}) ` ?
I tried it and i got an exception : 
> Invariant Violation: [React Intl] An `id` must be provided to format a message.

Another thing, I tried to use babel-plugin-react-intl to extract all the messages from my components and I realized it creates a json file to each component and not one total json file. I don't understand how does it helps me? do I need to merge all these json files to one?

Thank you so much for your help.

**Comment by ericf** [comment]
> I don't want to use:
> `<FormattedMessage {...messages[this.props.type]} />` because it limits me.

Limits you how? It actually provide more advanced features.

> Is there a way to use it like this:
> `InjectIntl.formatMessge( {...messages[this.props.type]})` ?

There's no `InjectIntl.formatMessage`, you could use [`injectIntl(MyComponent)`](https://github.com/yahoo/react-intl/wiki/API#injection-api) to wrap your component with another component which will provide the imperative API via `props.intl` to `MyComponent`.

But yes, you can do:
```js
props.intl.formatMessage(messages[this.props.type]);
```

> I tried it and i got an exception :
>> Invariant Violation: [React Intl] An id must be provided to format a message.

Like [I said above](https://github.com/yahoo/react-intl/issues/343#issuecomment-191894245), you need to provide an `id`.

> Another thing, I tried to use babel-plugin-react-intl to extract all the messages from my components and I realized it creates a json file to each component and not one total json file. I don't understand how does it helps me? do I need to merge all these json files to one?

It helps you by creating JSON files that contain your default message definitions which can then be provided to a translator. Did you look at the [Translations Example](https://github.com/yahoo/react-intl/tree/master/examples/translations)?

**Comment by Shachar16290** [comment]
> There's no InjectIntl.formatMessage, you could use injectIntl(MyComponent) to wrap your component with another component which will provide the imperative API via props.intl to MyComponent.

Yes, I know. I meant this way.

> Like I said above, you need to provide an id. An id is required because that's how translations passed into <IntlProvider> via its messages prop are looked up and used. When a translation is missing for a certain, id, then the defaultMessage is used as a fallback.

Thank you. My syntax was wrong. Its difficult without documentation. 

> It helps you by creating JSON files that contain your default message definitions which can then be provided to a translator. Did you look at the Translations Example?

Thank you for the example. Still, I think the json files "merge" should be done by the plugin or something. Its a bit annoying we should do it separately and that the plugin creates so many files for nothing.

**Comment by ericf** [comment]
> Thank you for the example. Still, I think the json files "merge" should be done by the plugin or something. Its a bit annoying we should do it separately and that the plugin creates so many files for nothing.

I've responded to other issues about this. tl;dr merging is lossy which is why the plugin doesn't do it by default. I think it's fair to say that people have to write a few lines of code to merge the messages if they wish to, since this is likely one very minor aspect of building a translation pipeline.

**Comment by Shachar16290** [comment]
Ok.
Again, Thank you so much for all the information :)
