### ISSUE TITLE
Passing nested objects as arguments to `formatMessage`?

### ISSUE THREAD

**Issue by hedgeday** [yahoo/react-intl#344]
I was wondering whether the `formatMessage` function that we get through IntlMixin accepts nested objects as the second argument.

For example, I want to do something like: 
```js
var content = this.formatMessage('My name is {data.firstName.value}', 
{
    data: { 
        firstName: {
            value: 'hedgeday'
        }
    }
});
``` 

for the output message of 'My name is hedgeday'.

Namespacing the argument in the message results in the following error: `Uncaught SyntaxError: Expected ",", "}" or [^ \t\n\r,.+={}#] but "." found.`

Is this currently supported? Is there another way I can represent nesting within the argument object without using the `.` character?

**Comment by ericf** [comment]
There's no plan to support this. You'll need to make your values object flat.

**Comment by hedgeday** [comment]
Is there a reason why not? Just curious.

**Comment by brunops** [comment]
+1
I have interest in this feature as well, seems like a common use case. 
What is the philosophy behind the decision of not supporting it? Any known work around to support this?

thanks

**Comment by ericf** [comment]
It's not valid ICU Message syntax. Extending the syntax to support this might confuse translators who wouldn't be familiar with it.

This change also inverses the ownership of the message variables. By making them require some arbitrary nested data structure, it means the message is no longer the owner of its own placeholder variables.
