### ISSUE TITLE
[NPM] Errors littering console

### ISSUE THREAD

**Issue by zacbarton** [yahoo/react-intl#351]
While developing with v2 I've noticed loads of the below errors;

`[React Intl] Missing message: {id} for locale: {locale} using default message as fallback.`

From what I can tell the version I installed from npm (react-intl@2.0.0-beta-2) appears to be missing the below [lines](https://github.com/yahoo/react-intl/blob/master/src/format.js#L147) found in `src`;

```
// This prevents warnings from littering the console in development
// when no `messages` are passed into the <IntlProvider> for the
// default locale, and a default message is in the source.
if (!defaultMessage ||
(locale && locale.toLowerCase() !== defaultLocale.toLowerCase())) {
/// and so on ...
```

The missing code is exactly what I'm looking for to remove these console errors while developing - I want to use the messages I've defined in my components.

**Comment by ericf** [comment]
This change will be out in the next release since it's on master.

**Comment by joncursi** [comment]
@ericf has this been released? I'm still getting errors on `2.1.3`, and the problem is unfortunately worse for react-native development since console.error messages flash the entire screen. Thanks!

<img width="376" alt="screen shot 2016-07-17 at 4 32 35 am" src="https://cloud.githubusercontent.com/assets/4974609/16899595/8e92c59a-4bd7-11e6-9f89-a62aa94d16e8.png">

**Comment by ericf** [comment]
@joncursi yes it was released. Is this not a valid error? Maybe you should try setting `<IntlProvider defaultLocale='en-US'>`.

**Comment by joncursi** [comment]
@ericf that solved the problem, thanks! The way that error was worded led me to believe that it was an issue with the messages, not the locale

**Comment by ericf** [comment]
@joncursi I guess it could be updated to output _what_ the default locale is.
