### ISSUE TITLE
Error using IntlProvider with Router

### ISSUE THREAD

**Issue by mafrosis** [yahoo/react-intl#352]
Hello, please forgive any obvious oversights: I'm new to React (but not JS!)

When I wrap my `<Router>` from `react-router` with `IntlProvider`, I receive an error. Code:

    ReactDOM.render(
        <IntlProvider locale='en'>
            <Router history={browserHistory}>{routes}</Router>
        </IntlProvider>,
        document.getElementById('app')
    );

Errors:

    Warning: React.createElement: type should not be null, undefined, boolean, or number.
    It should be a string (for DOM elements) or a ReactClass (for composite components).
    
    Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) 
    or a class/function (for composite components) but got: undefined.

**Comment by baer** [comment]
I'm also having an issue possibly related to react-router. For me I get: 

`[React Intl] Could not find required `intl` object. needs to exist in the component ancestry.`

I'll update this issue as I work through the possible issues.

**Comment by ericf** [comment]
When you guys figure out, we should add it to the [Wiki](https://github.com/yahoo/react-intl/wiki)

**Comment by MartijnHols** [comment]
I had the same issue because I was using `import IntlProvider from 'react-intl';` instead of `import { IntlProvider } from 'react-intl';`. Easy oversight as a resullt of converting the line `var IntlMixin         = ReactIntl.IntlMixin;` from the docs into `import IntlMixin from 'react-intl';`, which, surprisingly, didn't throw any messages when applied as a mixin.

**Comment by mafrosis** [comment]
I didn't realise there was any difference between those two statements!

**Comment by ericf** [comment]
@magrosis was the import statement the issue for you?

**Comment by mafrosis** [comment]
Yes! It did. How strange. Can anyone explain why that might be? I think the curly brackets notation was only used for multiple imports on the same line..

**Comment by ericf** [comment]
```js
export default 42;
export const named = 'foo';
```

```js
import defaultExport from 'mod'; // 42
import {named} from 'mod'; // 'foo'
```

ES2015 has named and default exports. React Intl only has named exports, therefore trying to import the package's default export will be `undefined`. Ideally the tooling gets better to throw a compile error.

**Comment by baer** [comment]
@ericf The React-Router manipulates context so unless you define an intl provider for each route there is some trickery you need to do to make everything work. I'm trying to get this work done today but I think it's probably worth leaving as a docs/recipes task.

Also, congrats on rc1! Thanks for your awesome contributions to the JavaScript community and for the very clean code that makes my debugging easier :).

**Comment by baer** [comment]
To be more specific - this does not work. [This line](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L18) calls `invariant` with a null context. which throws the `[React Intl] Could not find required intl object. needs to exist in the component ancestry.` error.

```jsx
  <IntlProvider
    locale="en"
    defaultLocale="en">
    <Route path={Config.fullPath()} component={Page}>
      <IndexRoute component={Home}/>
    </Route>
  </IntlProvider>
```

```js
class Home extends React.Component {
  render() {
    return (
      <Button>
        <FormattedMessage {...defaultMessages["greeting-button"]}/>
      </Button>
    );
  }
}
```

I've never used react router for much until recently but I do know there is a `<RenderContext>` component in their API. I'll be looking into how

**Comment by ericf** [comment]
@baer which version of React Router are you using?

Also, the React Intl components are expecting to be created by React, which provides both a `props` and `context` arguments to the component's constructor/function.

**Comment by baer** [comment]
I'm on 1.x right now but a 2.x conversion would be in the cards if it facilitated react-intl.

**Comment by ericf** [comment]
@baer I created a simple example app using React Intl + React Router and it works for me: https://github.com/yahoo/react-intl/pull/354
