### ISSUE TITLE
Why defaultMessage?

### ISSUE THREAD

**Issue by steida** [yahoo/react-intl#355]
I don't see a reason why `message` prop name isn't good enough. Did I overlook something?

**Comment by ericf** [comment]
Because the message comes from the `messages` collection passed to `<IntlProvider>` based on the Message Descriptor's `id`, and this may be a translated message. To avoid this confusion, `defaultMessage` is used to signify it's the default/fallback for the main message at the `id`.

**Comment by steida** [comment]
Make sense. Thank you.
