### ISSUE TITLE
maximumFractionDigits set to 0 crashes React in Safari/iPhones

### ISSUE THREAD

**Issue by mycroft11** [yahoo/react-intl#360]
Hi, I'm using 2.0.0-beta-2 and FormattedNumber fails if maximumFractionDigits is set to 0 or 1. For some reason, setting it to 2 is fine, but I need to format the numbers with no decimals.

Any ideeas?

**Comment by ericf** [comment]
@mycroft11 thanks for reporting this, but I need some more info to take any action:

- What _exact_ version of the Intl polyfill are you using?
- What version of Safari? 
- Does it crash on Safari on OS X?
- Do you have a simple reproducible test case to show the problem?
- Does it crash when you try `2.0.0-rc-1`?

**Comment by mycroft11** [comment]
Hi Eric, it's fixed in rc-1! :)
