### ISSUE TITLE
I want to use FormattedRelative with an UTC date

### ISSUE THREAD

**Issue by miracle2k** [yahoo/react-intl#361]
Right now, I am using moment.js to convert it, FormattedRelative to display.

Is it feasable that FormattedRelative could support this use case directly?

**Comment by ericf** [comment]
Can you explain how this isn't working today?

**Comment by miracle2k** [comment]
I wasn't thinking about this right. My real problem is that the timestamp I have is UTC but without timezon information attached. It really should't be react-intl's concern to do that sort of conversion.

**Comment by ericf** [comment]
Ideally you can get the time in ms since those are all relative to UTC, otherwise you can set the timezone offset on the `Date` instance you create to UTC before passing it to `<FormattedRelative>`.
