### ISSUE TITLE
Changing locale dynamically

### ISSUE THREAD

**Issue by julien-f** [yahoo/react-intl#365]
*Disclaimer: completely new to React/Redux, therefore I am probably asking a lot of silly questions :laughing:*

I am trying to implement dynamically change the the locale of my React/Redux based application, here is what I ended up doing:

```js
import React, { Component } from 'react'
import { connect, Provider } from 'react-redux'
import { IntlProvider } from 'react-intl'
import { render } from 'react-dom'
import { Router } from 'react-router'

import actions from './actions'
import localizedMessages from './localized-messages'
import store from './store'

@connect(
  ({ lang }) => ({ lang }),
  actions
)
class IntlWrapper extends Component {
  render () {
    const { children, lang } = this.props

    return <IntlProvider
      locale={lang}
      messages={localizedMessages[lang]}
    >
      {children}
    </IntlProvider>
  }
}

render(
  <Provider store={store}>
    <IntlWrapper>
      <Router>
        // My application...
      </Router>
    </IntlWrapper>
  </Provider>,
  document.getElementsByTagName('app')[0]
)
```

My problem is that when the `lang` state value is changed, I get the following warning: `[react-router] You cannot change <Router routes>; it will be ignored`.

My guess is that the router is recreated at each render which looks like a bad idea, what would be the correct approach here?

**Comment by ericf** [comment]
I'm not sure. It seems odd to me that React Router doesn't support being re-rendered since that's not very aligned with how React works. I'd have to build an example myself to figure out an approach to doing this.

One thing you could try is making your [route config static and defined as a plain object](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#configuration-with-plain-routes) which that same object is always passed in to `<Router routes={routeConfig}>`.

**Comment by jmurzy** [comment]
@julien-f I have a similar setup but I cannot reproduce your issue. Are you doing any hot loading by any chance? That's not supported, reactjs/react-router#2704.

Can you put together a sample repo that illustrates the problem?

**Comment by julien-f** [comment]
No, I am not doing hot loading.

> Can you put together a sample repo that illustrates the problem?
Will do.

**Comment by TomiS** [comment]
I was able to implement connection between React-Intl locale and Redux store. However I experience a weird behaviour when I cold reload the app. On initial reload, the language is not correctly updated to match the state. I researched a little and found out that after preparing the redux store with English as default language and loading state from local storage (that contains Finnish "fi" as current user locale) the `IntlProvider`'s locale property is correctly updated but this information does not trickle down to `FormattedMessage` elements. See picture. 
![react-intl-example](https://cloud.githubusercontent.com/assets/33161/14427741/bc9fcf84-fffe-11e5-8027-035fb6c18708.png)

I do not even try to update `intl` in context manually. Should I? Is it even possible? Is this a bug or am I just a noob? :)

**Comment by julien-f** [comment]
@ericf, @jmurzy: Sorry I did not create a repo to illustrate, in my project I switched from `<Route />` elements to plain routes and I no longer see this issue.

**Comment by ericf** [comment]
@TomiS I'm guessing it's the issue with `context` and `shouldComponentUpdate`: https://github.com/facebook/react/issues/2517

**Comment by TomiS** [comment]
@ericf Seems like a very probable reason so thank for pointing me to right direction.

**Comment by julien-f** [comment]
Since I am not encountering this problem, I am closing this issue.

Thanks for your help.

**Comment by xml** [comment]
I'm could use clarfification on this: should we expect dynamic updating of the locale through the redux store to work properly and rerender our '<FormattedMessage>`s, or do we need to re-render the entire application on changes, a la: https://github.com/gpbl/react-locale-hot-switch ???

**Comment by ericf** [comment]
@xml is it the issue in React with `context` and `shouldComponentUpdate` that I linked to above?

**Comment by bitcloud** [comment]
The problem is that you have a connected redux component in the tree. This is kind of a pure component which blocks rendering if not the passed props to the wrapped component or the props that are mapped via the store have changed.

To work around that just use `injectIntl`.

e.g.:
```
import { injectIntl } from 'react-intl';
import { connect } from 'react-redux';

...

injectIntl(connect(mapStateToProps, mapDispatchToProps)(SignUpForm));

```
`injectIntl` is picking up the changed context and is adding them as props to the connected component which triggers the rerender of its subtree.

**Comment by randomcatgamer** [comment]
was up
