### ISSUE TITLE
Output plural numbers with correct language script

### ISSUE THREAD

**Issue by miracle2k** [yahoo/react-intl#366]
I have an app with Persian localization (i.e. essentially Arabic script). If I have a plural in my ``FormattedMessage``, I'd like the number itself to be printed using the Arabic numbering system, i.e. ۱, ۲ etc.

I cannot pass a string as the variable, as then, the correct plural form can not be determined. 

Is this already supported? If not, I'd have a look at it.

**Comment by ericf** [comment]
This is supported via the ICU Message syntax.

```
You have {unreadCount, plural,
  one {{unreadCount, number} unread message}
  other {{unreadCount, number} unread messages}
}.
```

By using the `number` argument types, the value will pass through `Intl.NumberFormat` which for Arabic will use Arabic's numbering system.
