### ISSUE TITLE
How to define the messages?

### ISSUE THREAD

**Issue by Vadorequest** [yahoo/react-intl#368]
I really don't get how this lib works. When I use an I18n library I usually define a locale key like `en` with an object containing all locales. I'm using the `2.0.0-rc1` version.

By reading the API at https://github.com/yahoo/react-intl/wiki/API#definemessages I have the feeling that I first must define the locales and somehow define the messages afterwards.

 So, I tried the following:

```cjsx
React = require 'react'
ReactDOM = require 'react-dom'
{ createStore, applyMiddleware } = require 'redux'
{ Provider }  = require 'react-redux'
{ IntlProvider, addLocaleData, defineMessages } = require 'react-intl'
thunk = require 'redux-thunk'
App = require './components/App'
docApp = require './reducers/'
middlewares = require './middlewares/'

store = createStore docApp, applyMiddleware(
    # middlewares.stateChangeLogger
    thunk.default
)

addLocaleData require '../../../../node_modules/react-intl/locale-data/fr', require './locales/fr'
addLocaleData require '../../../../node_modules/react-intl/locale-data/en', require './locales/en'

ReactDOM.render(
    <IntlProvider locale='fr'>
        <Provider store={store}>
            <App />
        </Provider>
    </IntlProvider>,
    document.getElementById('app-container')
)
```

And in my `App.cjsx` file I have the following:

```cjsx
React = require 'react'
# XXX We must require each package one by one. Do not use the ./index.cjsx file here or you'll get destroyed by circular dependencies. :)
Wysiwyg = require './wysiwyg/Wysiwyg'
Page = require './page/Page'
Screen = require './screen/Screen'
PageContainer = require '../containers/PageContainer'
{ injectIntl } = require 'react-intl'

class App extends React.Component

    render: ->
        console.log JSON.stringify @props.intl.messages
        console.log @props.intl
        <div className="adl-app">
            <Wysiwyg />
            <Screen>
                <PageContainer />
            </Screen>
        </div>

module.exports = injectIntl App
```

When I load my page, I get the following:
```
{}
Object {formats: Object, messages: Object, defaultLocale: "en", defaultFormats: Object, locale: "fr"}
```

So, my `@props.intl.messages` is empty, but I do have a `@props.intl`.
What am I doing wrong?

**Comment by Vadorequest** [comment]
I found a workaround, but still not a proper solution.

```cjsx
React = require 'react'
ReactDOM = require 'react-dom'
{ createStore, applyMiddleware } = require 'redux'
{ Provider }  = require 'react-redux'
{ IntlProvider, addLocaleData, defineMessages } = require 'react-intl'
thunk = require 'redux-thunk'
App = require './components/App'
docApp = require './reducers/'
middlewares = require './middlewares/'

store = createStore docApp, applyMiddleware(
    # middlewares.stateChangeLogger
    thunk.default
)

addLocaleData require '../../../../node_modules/react-intl/locale-data/fr'
addLocaleData require '../../../../node_modules/react-intl/locale-data/en'

locale = 'fr'
messages =
    fr: require './locales/fr'
    en: require './locales/en'

# Monkey Patch for wrong warnings.
originalConsoleError = console.error
if (console.error is originalConsoleError)
    console.error = =>
        if (arguments[0].indexOf('[React Intl] Missing message:') is 0)
            return

        originalConsoleError.call(console, arguments)

ReactDOM.render(
    <IntlProvider locale={locale} messages={messages[locale]}>
        <Provider store={store}>
            <App />
        </Provider>
    </IntlProvider>,
    document.getElementById('app-container')
)
```

`App.cjsx`
```cjsx
React = require 'react'
# XXX We must require each package one by one. Do not use the ./index.cjsx file here or you'll get destroyed by circular dependencies. :)
Wysiwyg = require './wysiwyg/Wysiwyg'
Page = require './page/Page'
Screen = require './screen/Screen'
PageContainer = require '../containers/PageContainer'
{ injectIntl, FormattedMessage } = require 'react-intl'

class App extends React.Component

    render: ->
        <div className="adl-app">
            <FormattedMessage {...@props.intl.messages.hello} /> # Displays "Hello"
            <Wysiwyg />
            <Screen>
                <PageContainer />
            </Screen>
        </div>

module.exports = injectIntl App
```

`fr.coffee`
```coffee
module.exports =
    hello:
        id: 'app.commons.hello'
        defaultMessage: 'Bonjour'
```

I had to monkey patch the errors (https://github.com/yahoo/react-intl/issues/251#issuecomment-166077090). Basically I don't get how I'm supposed to link a locale with a set of messages. Here I just define the locale and the messages, but they don't seem to be linked.

**Comment by maxs15** [comment]
Same problem on my side, the ``messages`` property of the ``IntlProvider`` was working on ``2.0.0-pr-3``but since I updated to ``2.0.0-rc-1`` it doesn't work anymore..
Did something changed in the new version ?

Thanks

**Comment by ericf** [comment]
> Did something changed in the new version ?

@maxs15 you can check here: https://github.com/yahoo/react-intl/releases

> Basically I don't get how I'm supposed to link a locale with a set of messages.

@Vadorequest `<IntlProvider locale="fr" messages={frTranslations}>`. Not much docs for 2.0 yet, you'll have to look in the Wiki, `examples/` and `src/` dir for now.

**Comment by maxs15** [comment]
Thanks @ericf,
I've finally found the issue, I wasn't calling ``addLocaleData`` for the languages I support.
It looks like the language configuration file is mostly for Dates support no ?
Maybe it would nice to consider translating without ``addLocaleData`` in order to support basic translations.

I don't see why something like that wouldn't work:
``
<IntlProvider locale="fr" messages={{"test1": "Text 1", "test2": "Text 2"}}>
   <FormattedMessage id="test1"/>
   <FormattedMessage id="test2"/>
</IntlProvider>
``

Components like ``FormattedMessage``would work and components like ``FormattedDate``would display an error that the config file of the language is needed.
It would allow people only using basic translation to reduce the size of the bundle even more !

**Comment by ericf** [comment]
Adding the locale data to React Intl is required for it to function properly. Locale data for number and date formatting are build into browsers (expect Safari). React Intl expands on this by adding plural and relative-time formatting for which the locale data is needed to back the APIs.
