### ISSUE TITLE
Relative date in formatted message

### ISSUE THREAD

**Issue by julien-f** [yahoo/react-intl#370]
I did not find in [the documentation](http://formatjs.io/guides/message-syntax/) how to format a relative date in the message syntax.

How can I do that?

**Comment by ericf** [comment]
The best way is to use a simple placeholder argument and pass in the formatted relative-time value or `<FormattedRelative>` element.

```js
<FormattedMessage
  id="posted"
  defaultMessage="posted {ago}"
  values={{
    ago: <FormattedRelative value={datePosted} />
  }}
/>
```

**Comment by julien-f** [comment]
I would have expected a dedicated syntax just like the `date` operator but this will do, thanks!

**Comment by ericf** [comment]
There isn't, and if there was, you'd still want to use the way I provided above because using the component will allow the relative times to "tick" as time progresses.
