### ISSUE TITLE
<FormattedNumber style="currency"/> does not render in v2

### ISSUE THREAD

**Issue by mycroft11** [yahoo/react-intl#380]
Hi,
The number format does not format the passed value at all, it just shows the original value, without any formatting.

Any ideas?

**Comment by ericf** [comment]
Check you're console, there's likely an error telling you that you need to also pass a `currency` prop:
```
[React Intl] Error formatting number.
TypeError: Currency code is required with currency style.
```

Once you add something like `currency='USD'` it will format the number.

**Comment by mycroft11** [comment]
Hi ericf,

This seems to happen on firefox and safari only. Chrome is ok, and the error is this:

[React Intl] Error formatting number.
RangeError: invalid digits value: 0

Here's how i set it:

<FormattedNumber value={344.33} style="currency" currency="GBP" maximumFractionDigits={0}/>

**Comment by mycroft11** [comment]
FormattedNumber value="3434.44" style="currency" currency="GBP" maximumFractionDigits={0}

**Comment by ericf** [comment]
You likely also need to set minimumFractionDigits to 0:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat
