### ISSUE TITLE
site not working on Safari

### ISSUE THREAD

**Issue by alansouzati** [yahoo/react-intl#381]
Hi guys,
 
Is there anything special I need to do in order to make sure http://formatjs.io/react/ works in Safari ?

I know Safari does not ship Intl library, shouldn't the site include the polyfill?
![screen shot 2016-03-31 at 1 29 04 pm](https://cloud.githubusercontent.com/assets/1207250/14189928/ca49daca-f744-11e5-8169-2c32ee24fc54.png)

**Comment by l0gicgate** [comment]
Here is the repo for the Intl polyfill.

You will also need to load the locale-data asynchronously as well as the Intl.js library.

https://github.com/andyearnshaw/Intl.js/

**Comment by alansouzati** [comment]
Well, I'm not trying to load the polyfill, sorry if I was not clear on my issue. I'm trying to access http://formatjs.io/react/ and if I check the browser console I see the Intl issue.

**Comment by l0gicgate** [comment]
I apologize, I misread your post. That is pretty ironic that they don't load the polyfill on the site!

**Comment by ericf** [comment]
Maybe it's intermitted? I don't see the error.

**Comment by alansouzati** [comment]
Clearing my cache did the trick. sorry for the inconvenience
