### ISSUE TITLE
Using react-intl in the browser

### ISSUE THREAD

**Issue by alansouzati** [yahoo/react-intl#382]
Not sure if this issue makes sense, feel free to close if you think this should not be supported.

I'm trying to use react-intl directly in the browser for testing purposes. Do you guys provide either a bower distribution or a CDN with content that is browser-friendly?

**Comment by ericf** [comment]
Use https://npmcdn.com
https://npmcdn.com/react-intl@next/dist/react-intl.min.js

**Comment by alansouzati** [comment]
thanks! :)
