### ISSUE TITLE
Short Formatted Relative format

### ISSUE THREAD

**Issue by LarsOL** [yahoo/react-intl#393]
Our designer would like to have the option to have the <FormattedRelative> output shorted versions
e.i 5h ago, 1m ago etc.

How would we go about implementing this? 

Thanks, and great library.

**Comment by ericf** [comment]
We'd need to update a few of things:

1. Update [`formatjs-extract-cldr-data`](https://github.com/yahoo/formatjs-extract-cldr-data) to extract the additional data from CLDR.
2. Update [`intl-relativeformat`](https://github.com/yahoo/intl-relativeformat) to support a new option for short/narrow relative times using the CLDR.
3. Update this package to start passing this extra CLDR data to `intl-relativeformat` and the option when creating an instance.

**Comment by ericf** [comment]
Looking at the CLDR data, I don't see "1m ago", there is data for "1 mo. ago". I'll have to dig around to see if there's a more abbreviated set of data for relative dates.

**Comment by vielmetti** [comment]
Updating this for @hoodiek as the same issue has been identified in Mastodon at  https://github.com/tootsuite/mastodon/issues/857

**Comment by dtm5011** [comment]
I opened a [pull request](](https://github.com/yahoo/formatjs-extract-cldr-data/pull/15)) with `formatjs-extract-cldr-data` to include the short formats. 
If that get's approved `intl-relativeformat` uses a grunt plugin to wrap it, so `https://github.com/yahoo/grunt-extract-cldr-data` will need to be updated as well.

**Comment by okuryu** [comment]
merged https://github.com/yahoo/formatjs-extract-cldr-data/pull/15 and published `formatjs-extract-cldr-data@4.1.0`.

**Comment by Soreine** [comment]
This is almost complete. I think we are just missing an option to tell to `FormattedRelative` to use the `best-fit` unit in its short form.

**Comment by papasmile** [comment]
@Soreine I opened a PR for short format options.  But I actually didn't get what you mean by 'use the best-fit unit in its short form'... doesn't it do that by default?
