### ISSUE TITLE
Getting translation out of React component

### ISSUE THREAD

**Issue by tomitrescak** [yahoo/react-intl#400]
I'm sorry to ask here, but I really tried to find a way of how to get a translated string out of the React component and I could not. Is it even possible?

I need to translate some strings in .js file with helper functions and I have no idea how. Thanks.

**Comment by ChrisFan** [comment]
The basic idea is using all the messages generated by `babel-plugin-react-intl`.
Take a look at [translate.js](https://github.com/ant-design/intl-example/blob/master/scripts/translate.js), the code needs to be improved, but it works.

**Comment by tomitrescak** [comment]
HMMM, I'm very new in this so I'm not sure how the code you posted will solve my problem. How will even babel know about my translation string if it exists only in js file? And how do I even call the translation? Thanks

**Comment by tomitrescak** [comment]
Ok, after some playing with it, I understand the process now. The messages are defined via defineMessages and obtaining them is done via custom function, nothing inbuilt exists for this.

**Comment by ericf** [comment]
@tomitrescak The [Babel plugin](https://github.com/yahoo/babel-plugin-react-intl) will statically analyze your modules that `import` the `"react-intl"` module and look for uses of `defineMessages` or `<FormattedMessage>` and extract their contents into [Message Descriptors](https://github.com/yahoo/react-intl/wiki/Components#message-descriptor). The Babel plugin will create one `.json` file per `.js` file which contains messages that were extracted.

From there you can look at the example @ChrisFan linked to and see how to aggregate and process these `.json` files into a structure that you'd need for your translators or translation system.

So far everything I mentioned happens at built-time. During runtime, you'll want to feed translated messages in the simple form: `{"messageId": "translated message"}` into the [`<IntlProvider>` component](https://github.com/yahoo/react-intl/wiki/Components#intlprovider).
