### ISSUE TITLE
Object.assign undefined is not a function

### ISSUE THREAD

**Issue by andrewho83** [yahoo/react-intl#403]
I was getting undefined is not a function when using FormattedRelative.  Unsure if I should file this here as it is babel related. 

It was related to Object.assign not being defined.  Had to update babel-core (^6.2.x to 6.7.x) to fix.

In lib/index.js,

    babelHelpers.extends = Object.assign || function (target) {
      for (var i = 1; i < arguments.length; i++) {
        var source = arguments[i];

    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) {
        target[key] = source[key];
      }
    }
    }

    return target;
    };

Line 489:

    Object.assign(IntlRelativeFormat.thresholds, {
        second: 60, // seconds to minute
        minute: 60, // minutes to hour
        hour: 24, // hours to day
        day: 30, // days to month
        month: 12 });

and 506:

    Object.assign(IntlRelativeFormat.thresholds, thresholds);

**Comment by ericf** [comment]
Okay, thanks for reporting! I'll make sure it doesn't use `Object.assign` directly without using/including a polyfill.

**Comment by taion** [comment]
You may want to consider using `babel-runtime` instead of a polyfill, to avoid setting stuff up in the global environment.

**Comment by ericf** [comment]
`babel-runtime` is too heavy and has too much overhead. This is an internal operation where I control both objects, so I'll just write a simple shim that falls back to `Object.assign` when available.
