### ISSUE TITLE
Keep a Changelog so users can easily find out what's changed.

### ISSUE THREAD

**Issue by ericlathrop** [yahoo/react-intl#404]
A nice changelog format is here:
http://keepachangelog.com/

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/releases

**Comment by ericlathrop** [comment]
Woah, I never thought to look there. I'm used to looking for a CHANGELOG file in the repo.

**Comment by ericf** [comment]
If you want to call it out better, feel free to open a PR with links to the releases page where you see fit so others can find it.
