### ISSUE TITLE
please add more examples, e.g. for plural. How to use formatPlural?

### ISSUE THREAD

**Issue by plandem** [yahoo/react-intl#406]
It's not clear how to use formatPlural. E.g. for formatMessage i use like this:
```
const { value, intl: { formatMessage, formatPlural } } = this.props;
...
<Form.Item label={formatMessage(messages.of)} labelCol={{ span:24 }}><span/></Form.Item>
```

but how to use formatPlural? I have next messages defined as:
```
const messages = defineMessages({
  of: {
    id: 'sort-input.of',
    defaultMessage: 'of'
  },
  values: {
    id: 'sort-input.values',
    defaultMessage: 'values',
    zero: 'values',
    one: 'value',
    two: 'values',
    few: 'values',
    many: 'values',
    // other: 'values'
  },
....
```

this one is not working like supposed:
```
<Form.Item label={formatPlural(value, messages.values)} labelCol={{ span:24 }}><span/></Form.Item>
```

**Comment by ericf** [comment]
Use `<FormattedPlural>` if your app is only one language, otherwise use `<FormattedMessage>`.

- https://github.com/yahoo/react-intl/tree/master/examples
- https://github.com/yahoo/react-intl/wiki
- http://formatjs.io/guides/message-syntax/#plural-format

**Comment by plandem** [comment]
So it's the only way? I don't want to use < FormattedPlural/> or < FormattedMessage/>. It would be better to use same way as at other parts of application - via defineMessage + format*

**Comment by ericf** [comment]
Checkout the examples and docs, `defineMessages()` doesn't work how your example is.

**Comment by plandem** [comment]
I already tried to search - the only use case FormattedPlural. That's why i asked about **formatPlural** and **defineMessage**.

**Comment by plandem** [comment]
It's quite critical for us, because we use separate files for all i18n. And **FormattedPlural** requires to hardcode messages into components. Of course, we can use babel custom utils to grab messages, but it's against our workflow - i18n at separate file, constants at separate files and etc.

**Comment by sagannotcarl** [comment]
Putting this here in case anyone else was like me and still confused on how to use `formatMessage` to make a plural string.

```
const messages = defineMessages({
  'items': {
    id: 'items',
    defaultMessage: '{itemCount, plural, one {Item} other {Items}}',
  },
});

const pluralString = formatMessage(messages.items, { itemCount: itemCount });
```

**Comment by jessepinho** [comment]
For future ref, docs on how to format `defaultMessage` for plural (and other cases) are here: https://formatjs.io/docs/core-concepts/icu-syntax/
