### ISSUE TITLE
Lost space from template after parsing

### ISSUE THREAD

**Issue by denova** [yahoo/react-intl#408]
Hello!

Based on 'Nested' example [added](https://github.com/denova/react-intl/blob/parsing-template-issue-2/examples/nested/src/client/components/widgets/greeting.js#L10) two following messages:

1. `'I have bought'`
2. `' fruits'`

Expected `I have bought fruits` line but space lost:

![d9b41f10bf](https://cloud.githubusercontent.com/assets/1096682/14466534/ec972458-00df-11e6-842a-5284df8775c3.png)
Also space is lost in more complicated templates like `'I use{browser, select, chrome{ Google Chrome} firefox { Mozilla Firefox}}'`:

![7779898fce](https://cloud.githubusercontent.com/assets/1096682/14466703/acc13412-00e0-11e6-9ae4-4a164590b277.png)
Seems it's a bug.

p.s. for me works way of adding variable with one space:
```
<FormattedMessage
  id="msg"
  defaultMessage={`I use{browser, select, chrome{{space}Google Chrome} firefox {{space}Mozilla Firefox}}`}
  values={{
    browser: 'chrome',
    space: ' '
  }}
/>
```

Thanks.

**Comment by ericf** [comment]
It's treated as insignificant whitespace. Use the unicode escape character for space `\u0020`

**Comment by windok** [comment]
Looks like `\u0020` is no longer supported. You can use `\u2000` whitespace that is 1/2 of font size.
