### ISSUE TITLE
FormattedDate not rendering in Safari and iOS

### ISSUE THREAD

**Issue by Gerarddp** [yahoo/react-intl#409]
When running our react application in Safari 9.1 and any version of Safari for iOS we are seeing this error:

```
[React Intl] Error formatting date.
ReferenceError: No locale data has been provided for this object yet.
```

and the date is not displayed properly, like
`Mon Apr 11 2016 00:00:00 GMT+0200 (CEST)`

It works in Safari 9.1.1 Preview, which supports Intl natively. Which make us thing it may not be an issue with react-intl but with intl.js. I tried digging into it a bit and found out that `'[[availableLocales]]'` is an empty array when the error occurs.

**Comment by ericf** [comment]
Can you provide the simplest, plain HTML example that reproduces this problem?

**Comment by Gerarddp** [comment]
I made a simple project https://github.com/Gerarddp/react-intl-bug while doing that I realised that I'm loading intl in a weird way, so maybe that's the culprit.

**Comment by Gerarddp** [comment]
Yeah, the problem was the way I loaded Intl, I didn't know better because the documentation wasn't finished when I started implementing it :stuck_out_tongue_closed_eyes: I'll leave the project open if you want to look at it, and maybe add it to the documentation for others.

**Comment by ericf** [comment]
If you think there's stuff in the docs that should be expanded on for loading the polyfill you can edit this docs section on the wiki: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

**Comment by efkan** [comment]
People who use `React-Intl` on `React-Native` might visit this issue for the same issue.

When `formatDate`, `formatNumber `etc. are being used, the same error could be thrown and format attempting would not be success. **Related lacale data must be imported** as directed by _Gerarddp_ .

For instance:
```
import 'intl' // is a MUST!
import 'intl/locale-data/jsonp/en.js' // is a MUST when DEVELOPING!
```

However, on the phone the error is not thrown and the app works properly. So importing needs only in development process.

**Comment by mananarora** [comment]
To make the internationalization functions visible in all our components we have to wrap the App component with IntlProvider.
<IntlProvider locale='en'>
        <App/>
 </IntlProvider>
In IntlProvider you
