### ISSUE TITLE
FormattedNumber doesn't work

### ISSUE THREAD

**Issue by alexmngn** [yahoo/react-intl#410]
Hi,
I am trying to use the component `FormattedNumber`, but it doesn't work. Looks like a bug to me.

```
	<IntlProvider
		locale="en-US"
		messages={locales['en-US']}
	>
		<div>
			<FormattedNumber style="currency" currency="USD" value={123456} />
			<FormattedNumber style="currency" currency="USD" value="123456" />
			<FormattedMessage id="myMessage" />
		</div>
	</IntlProvider>
```

This only returns the value the way I passed it to the component, wrapped with a span, but it doesn't format the number.

The `FormattedMessage` component works fine for all my translations, 
the locale is set to `en-US`, so I don't think the issue comes from the `IntlProvider` or something else.

I am using the latest version of the library, `2.0.1`

Any idea?

**Comment by ericf** [comment]
Is there an error logged to the console? If so what does it say?

**Comment by alexmngn** [comment]
No there isn't any error.

**Comment by ericf** [comment]
Can you create a simple HTML page that makes the problem reproducible and tell me what browser to try?

Are you using Safari and not loading the Intl polyfill?

**Comment by ericf** [comment]
Also if you're using the .min.js version you won't get errors. Use the non-minified version to get errors in development.

**Comment by alexmngn** [comment]
@ericf Oh actually I have an error, sorry I never noticed it!
It says that:
```
[React Intl] Error formatting number.
TypeError: Bind must be called on a function
```
Any suggestion?

**Comment by ericf** [comment]
You'll need to provide the simplest, runnable, example that I could use to reproduce the error in the same browser you're seeing the issue in.

**Comment by alexmngn** [comment]
I tried to create a separate small project and tried to reproduce and I can't find a way to isolate the problem. Looks like the issue seems to come from somewhere in my large project.

**Comment by alexmngn** [comment]
OK I was able to isolate the problem. It seems like the FormatNumber doesn't work when I load the intl polyfill.

```
window.Intl = require('intl/dist/Intl');
```
Find attached a test where I was able to reproduce the issue.

run:

`npm install`
`gulp`

Then open index.html

[ui.zip](https://github.com/yahoo/react-intl/files/219736/ui.zip)

**Comment by ericf** [comment]
Yes, so you're overriding Chrome's default `Intl` implementation, I'd suggesting conditionally loading the polyfill: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

This is not an issue with React Intl. You can focus on properly loading the Intl polyfill to resolve this.

**Comment by alexmngn** [comment]
@ericf Safari needs the polyfill, and it doesn't work with the polyfill either!

**Comment by ericf** [comment]
This example works in Safari and Chrome: https://github.com/yahoo/react-intl/tree/master/examples/hello-world

**Comment by alexmngn** [comment]
Can you tell me in which case the library needs the polyfill?

**Comment by ericf** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Browser_compatibility

Please start with the examples. It works, we've been using it for years.

**Comment by alexmngn** [comment]
Why do I get the Intl polyfill error on Safari when I don't load it?

**Comment by ericf** [comment]
Please look at the example. It uses the polyfill. I pointed you to all the docs we have on this, all the details are important. 

- https://github.com/yahoo/react-intl/wiki#i18n-in-javascript
- http://formatjs.io/guides/runtime-environments/#client
- http://cdn.polyfill.io/v2/docs/
- https://github.com/andyearnshaw/Intl.js/blob/master/README.md
- https://github.com/yahoo/react-intl/blob/master/examples/hello-world/index.html#L9
