### ISSUE TITLE
Change linting rules

### ISSUE THREAD

**Issue by ev1stensberg** [yahoo/react-intl#412]
I know this is a matter of what you prefer, but would it be a good thing to change things around considering unnecessary semi-colons and/or other eslint rules, for example Airbnb?

**Comment by langpavel** [comment]
I like current setup. You can soften rules in your fork but this project and contributions should have same code style.

**Comment by ev1stensberg** [comment]
Another thing I noticed was the use of `renderer.render(something)` should we try remove `renderer` so we only could use `render(something)` ? It's just importing a specific part of the module we´re taking it from, in this use case we import `renderer` so we could only use render. Dunno how this fits with ReactDOM render method though.

**Comment by ericf** [comment]
I don't understand this. But these changes don't result in anything being different about this lib.

**Comment by ev1stensberg** [comment]
It's for minor optimization, we don't need all those semi-colons :smile:
