### ISSUE TITLE
Testing: How to get wrapped or inject mock context

### ISSUE THREAD

**Issue by omichelsen** [yahoo/react-intl#420]
Hi, I have now spend several days trying to wrap my head around the docs, and trawling through the issues here, so now I have to ask: 

How do I test my components using, _not_ Shallow Rendering, but `renderIntoDocument`?

Do I have to wrap every component in my tests like this - and if so, how do I access the wrapped component? `view.getWrappedInstance()` doesn't seem to work, neither does any prop of `view` that I could find.

```js
view = ReactTestUtils.renderIntoDocument(
    <IntlProvider locale='en'>
        <NotificationList notifications={notifications}/>
    </IntlProvider>
);
```

Or even better - is there a way where I don't have to wrap all my tests like this, but can instead inject a dummy `Intl` context? I am not really testing my translations, so just want my component to run?

PS. Shallow rendering is fine for tiny components, but I have several that are more than 1 level deep, plus I want to test my click handling etc.

Thanks very much in advance.

**Comment by ericf** [comment]
What we do is create a wrapper component that configures an `<IntlProvider>` for the tests. You can run into a similar situation if you're using a Flux framework.
```js
const render= element => ReactTestUtils.renderIntoDocument(
    <IntlProvider locale='en'>
        {element}
    </IntlProvider>
);

view = render(<NotificationList notifications={notifications}/>);
```

**Comment by omichelsen** [comment]
Thanks, but how do I access the `NotificationList` element afterwards? `view` will be pointing to `IntlProvider`?

**Comment by ericf** [comment]
You should be able to use a `ref`

**Comment by omichelsen** [comment]
Could you give a quick example, so far my feeble attempts have not been working :/

**Comment by omichelsen** [comment]
I think I have found out how to solve this. It requires combining quite a few things, so leaving this as an example I hope could be added to the docs to help others in the future:

In your component, remember to add `{withRef: true}` when calling `injectIntl()`:

```js
class AddContact extends React.Component {
  ...
}
export default injectIntl(MyComponent, {withRef: true});
```

In your test, add a "ref" to extract the reference to your tested component:

```js
let element;
let root = TestUtils.renderIntoDocument(
  <IntlProvider><MyComponent ref={(c) => element = c.refs.wrappedInstance} /></IntlProvider>
);
```

You can now access the wrapped component instance from `element`, e.g. like this:

```js
element.myStaticFn('yay')
```

Since you will have to do this in all your unit tests, you should probably wrap that setup in a `render` function like @ericf suggests above.

**Comment by ericf** [comment]
@omichelsen cool that you were able to figure out a solution. The Wiki is open so feel free to add a _DOM Rendering_ section to the Testing docs about this: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl

**Comment by omichelsen** [comment]
@ericf I added a section to the docs. Feel free to edit/correct.

**Comment by ericf** [comment]
@omichelsen thanks! 🎉
