### ISSUE TITLE
Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.

### ISSUE THREAD

**Issue by tomitrescak** [yahoo/react-intl#422]
Hi, I'm getting this error in Safari, but not in Firefox or Chrome.
Do you have any idea what may be causing this? I did everything by the book.

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/wiki#getting-started

**Comment by tomitrescak** [comment]
@ericf ... I'm sorry, but what kind of answer is that. I understand you guys are busy people, but to close the ticket this way is just ridiculous. Obviously, if this works in all browsers but Safari, the problem is somewhere out there. I even wrote an article on Medium about this to introduce your library to Meteor/Mantra community ...  

This is my layout page (by the book):

```javascript
import React from "react";
import Alert from "react-s-alert";

import { addLocaleData, IntlProvider } from "react-intl";
import UnsupportedBrowser from "./unsupported_browser_view";
import HeaderView from "../../header/components/header_view";
import AuthContainer from "../containers/auth_container";
import { Grid, Column } from "../../semanticui/components/semantic_ui";

const Header = AuthContainer(HeaderView);

interface IProps {
  content?: any;
  context?: IContext;
}

// possibly do this for different languages
const enLocaleData = require("react-intl/locale-data/en");
const messages = require("../../../../../lib/i18n/lang/en-US.json");

// add info on the current locale
addLocaleData([...enLocaleData]);

export class Layout extends React.Component<IProps, {}> {
  render() {
    const { Utils } = this.props.context;
    if (!Utils.Ui.checkBrowser()) {
      return (
        <UnsupportedBrowser />
      );
    }
    return (
      <IntlProvider locale="en" messages={messages}>
        <main id="home">
          <Header />

          <Grid classes="page">
            <Column>
              <div id="main">{ this.props.content ? this.props.content() : null }</div>
            </Column>
          </Grid>
          <Alert />
        </main>
      </IntlProvider>
    );
  }

  componentWillMount() {
    const { Utils } = this.props.context;
    Utils.Ui.pageTransition();
  }

  componentWillUpdate() {
    const { Utils } = this.props.context;
    Utils.Ui.pageTransition();
  }
};


export default Layout;
```

**Comment by tomitrescak** [comment]
Am getting the same error with your hello-world example ...

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {IntlProvider, FormattedNumber, FormattedPlural} from 'react-intl';

export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            name       : 'Eric',
            unreadCount: 1000,
        };
    } 

    render() {
        const {name, unreadCount} = this.state;

        return (
          <IntlProvider locale="en">
            <p>
                Hello <b>{name}</b>, you have {' '}
                <FormattedNumber value={unreadCount} /> {' '}
                <FormattedPlural value={unreadCount}
                    one="message"
                    other="messages"
                />.
            </p>
            </IntlProvider>
        );
    }
}
```

**Comment by GertjanReynaert** [comment]
The answer might have been brief, but the answer to your issue is literally describes in the getting started:

For older browsers and Node you might need to polyfill the Intl APIs. The Runtime Environments guide provides an overview of doing this, and here's some specific info:

For older browsers (and current Safari) we recommend using the intl package on npm. Which can be used via npmcdn or polyfill.io.

**Comment by ericf** [comment]
@tomitrescak I just wanted to link you directly to the answer, much faster than me re-typing what's already there. Sorry, but that's all the time I had today to dedicate to your question. Feel free to update the Wiki docs to make it more clear for the next person and Safari currently requires the polyfill to be loaded.

**Comment by tomitrescak** [comment]
I apologise if I've been harsh, actually before responding I checked the page and found nothing related to my problem ... I must have overlooked it and I apologise. I'll check out your answers. Thanks for your help.

**Comment by simPod** [comment]
Did you solve it? I have no idea how to fix it using "Getting started" guide

**Comment by tomitrescak** [comment]
Nope, sorry. I abandoned this project because of this. Instead I wrote my own i18n text extractor plugin for Atom and I'm using MessageFormat to format the messages.

**Comment by ericf** [comment]
> Did you solve it? I have no idea how to fix it using "Getting started" guide

You're loading an Intl polyfill?

**Comment by simPod** [comment]
@ericf thank you for your response. My developer did a wombo-combo and somehow fixed it. Don't know how exactly :( But polyfill figures in that solution

**Comment by rvetere** [comment]
I just had the same error in a server-side-rendering setup, and like described [here](http://formatjs.io/guides/runtime-environments/#server), i just added this line of code now before i execute the render function:

```
global.Intl = require('intl');
```

and this already fixed the bug, SSR working again, thanks! 👍 

PS: that link written was also mentioned nicely in the getting-started guide

**Comment by bmatto** [comment]
We're running into this error in a rails capybara test - we are using the capybara-webkit driver ... however have not been successful in polyfilling for the capybara test env.  Any suggestions?

**Comment by bmatto** [comment]
We're running into this error in a rails capybara test - we are using the capybara-webkit driver ... however have not been successful in polyfilling for the capybara test env.  Any suggestions?

**Comment by SebLambla** [comment]
I had the same issue, I ended up by calling this polyfill: https://github.com/andyearnshaw/Intl.js#getting-started

**Comment by brotzky** [comment]
I've added the polyfill to our app header, but still Safari still crashes.

**Comment by sl-wsiiz** [comment]
@brotzky it works for me. You can see how it's done on 'pull/1236/head:ssr' branch [here](https://github.com/react-boilerplate/react-boilerplate/pull/1236)

```
export default function ensureIntlSupport() {
  if (window.Intl) return Promise.resolve();
  return new Promise((resolve) => {
    resolve(require('intl'));
  })
  .then(() => Promise.all([
		require('intl/locale-data/jsonp/en.js'),
  ]));
}

// client/index.js
import 'babel-polyfill'
// ...
ensureIntlSupport()
	.then(renderApp)
```

**Comment by sleva13** [comment]
@brotzky it works for me. You can see how it's done on 'pull/1236/head:ssr' branch [here](https://github.com/react-boilerplate/react-boilerplate/pull/1236).

```
export default function ensureIntlSupport() {
  if (window.Intl) return Promise.resolve();
  return new Promise((resolve) => {
    resolve(require('intl'));
  })
  .then(() => Promise.all([
    require('intl/locale-data/jsonp/en.js'),
  ]));
}

// client/index.js
import 'babel-polyfill'
// ...
ensureIntlSupport().then(renderApp)
```

**Comment by brotzky** [comment]
@sleva13 My issue turned out to be Safari's lower case return of navigator.language

```JavaScript
// Safari
navigator.language === "en-us"

// Chrome, others
navigator.language === "en-US"
```

I was using the navigator.language to dynamically fetch language files, but since I had named the files to follow the upper case convention it failed for me.

So in the end the solution you said did work, but my issue turned out to be unrelated to what I originally thought was the cause.

**Comment by bf** [comment]
So how can I fix this specifically for mac users? What kind of code should I paste into my project?

**Comment by bf** [comment]
Answer from https://github.com/andyearnshaw/Intl.js:

``` 

Intl.js and Browserify/webpack

If you build your application using browserify or webpack, you will install intl npm package as a dependency of your application. Ideally, you will avoid loading this library if the browser supports the built-in Intl. An example of conditional usage using webpack might look like this:

function runMyApp() {
    var nf = new Intl.NumberFormat(undefined, {style:'currency', currency:'GBP'});
    document.getElementById('price').textContent = nf.format(100);
}
if (!global.Intl) {
    require.ensure([
        'intl',
        'intl/locale-data/jsonp/en.js'
    ], function (require) {
        require('intl');
        require('intl/locale-data/jsonp/en.js');
        runMyApp()
    });
} else {
    runMyApp()
}
note: a similar approach can be implemented with browserify, althought it does not support require.ensure.

note: the locale data is required for the polyfill to function when using it in a browser environment, in the example above, the english (en) locale is being required along with the polyfill itself.

```

**Comment by saadaouad** [comment]
Thanks @rvetere 👍

**Comment by maciejtatol** [comment]
I had that issue using Intl along with *webpacker + react_on_rails + SSR* . Instead of adding it to `global`, I've provided it in Webpack configuration (in webpack/environment.js):
```
const { environment } = require('@rails/webpacker')

/// This block provides Intl (required for Server Side Rendering)
//////////////////////////////////////
const webpack = require('webpack');

environment.plugins.set(
  'Provide',
  new webpack.ProvidePlugin({
    Intl: 'intl',
  })
)
//////////////////////////////////////

module.exports = environment;

```

**Comment by wellenzhong** [comment]
thanks @rvetere 
after i add the follow two lines,it works:
`global.Intl = require('intl');
window.Intl = require('intl);`
