### ISSUE TITLE
Resolve messages recursiveley 

### ISSUE THREAD

**Issue by muuki88** [yahoo/react-intl#426]
Hi,

I want to create a message with placeholder values, where the placeholder values in turn must be internationalized. Consider the following example

```jsx
<FormattedHTMLMessage id="my.message" values={{
   name: 'John Doe',
   countryCode: 'country.en' // <-- this should be resolved to England
}}>
</FormattedHTMLMessage>
```

You can solve this by nesting multiple `FormattedMessage` items, but this gets messy.

```jsx
<FormattedMessage id="country.en">{ country =>
  <FormattedHTMLMessage id="my.message" values={{
     name: 'John Doe',
     countryCode: country
  }}>
}</FormattedHTMLMessage>
</FormattedMessage>
```

Is there a feature in `react-intl` version `2.x` to solve this? I also posted a [question on SO](http://stackoverflow.com/questions/36746149/use-intl-key-in-html-and-resolve-messages-recursiveley)

thanks,
Muki

**Comment by ericf** [comment]
You can pass React Elements as values:
```js
<FormattedMessage id="my.message" values={{
    name: 'John Doe',
    countryCode: <FormattedMessage id="country.en"/>
  }}
/>
```

Assuming the message is something like: `{name} lives in {countryCode}`

**Comment by muuki88** [comment]
Thanks for you very fast reply. But hits doesn't seem to work. If I use the message `{name lives in {countryCode}`. The out put is

```
Johne Doe lives in [object object]
```

which may be a nice place to be, but not England ;)

**Comment by muuki88** [comment]
Confirmed. The `FormattedHTMLMessage` is the root cause for this.

```jsx
// works: John Doe lives in England
<FormattedMessage id="my.message" values={{
    name: 'John Doe',
    countryCode: <FormattedMessage id="country.en"/>
  }}
/>

// not working: John Doe lives in [object object]
<FormattedHTMLMessage id="my.message" values={{
    name: 'John Doe',
    countryCode: <FormattedMessage id="country.en"/>
  }}
/>

// not working: John Doe lives in [object object]
<FormattedHTMLMessage id="my.message" values={{
    name: 'John Doe',
    countryCode: <FormattedHTMLMessage id="country.en"/>
  }}
/>
```

Is this a bug or a feature in `FormattedHTMLMessage`?

**Comment by ericf** [comment]
Yeah, it'll only work with `<FormattedMessage>`: https://github.com/yahoo/react-intl/wiki/Components#formattedmessage

Not really a bug, but more of how it kind of has to work with using `dangerouslySetInnerHTML`. What's your message text? It can likely be converted to move the HTML out and move it to the `values` of `<FormattedMessage>` which can accept React elements.

**Comment by muuki88** [comment]
Thanks for the deprecation hint. We will try to workaround this. The message bascially contains some `<br/>` tags. I'll try without `FormattedHTMLMessage`.
