### ISSUE TITLE
Cant pass 0 (number) to FormatMessage

### ISSUE THREAD

**Issue by otbe** [yahoo/react-intl#428]
Hi everyone,

Im using a simple message like the following:
```
{
    'myId': 'Account balance: {balance}' 
}
```

and Im using it like this:
```
<FormattedMessage id='myId' values={{ balance: 0 }}}/>
```

Expected result is:
```Account balance: 0```

But what I get is:
```Account balance: ```

Is this correct?
Thanks.

P.S.: I know I can use a more complex message, but this is only a simple example.

**Comment by wrwrwr** [comment]
How about:

```javascript
{
    'myId': 'Account balance: {balance, number}'
}
```

Format docs: http://formatjs.io/guides/message-syntax/#number-type.

**Comment by ericf** [comment]
@otbe this has been brought up before, the recommendation it what @wrwrwr said.

**Comment by sethimcclaine** [comment]
An alternate is to convert ints to strings

<FormattedMessage id='myId' values={{ balance: (0).toString() }}}/>

<FormattedMessage id='myId' values={{ balance: value.toString() }}}/>
