### ISSUE TITLE
Components: pass through dom props

### ISSUE THREAD

**Issue by Guria** [yahoo/react-intl#432]
It' very easy to redefine `tagName` with components to render `button` or `a`, but it's impossible to set `onClick` or `href` on it. Even `className` couldn't be set to default `span`. :(
Would be great if components would pass through general dom props to rendered element to avoid extra usage of `injectIntl`.

**Comment by langpavel** [comment]
@Guria You mean `injectIntl`, didn't you? But absolutely agree, at least `className` is just annoying, but other props can be passed as well.

**Comment by Guria** [comment]
Of course. Thanks, fixed.

**Comment by langpavel** [comment]
See PR #434

**Comment by ericf** [comment]
This issue has been brought up many times before. Can you review the other discussions first, then provide any new feedback here?

**Comment by ericf** [comment]
Here are my thoughts the last time this was brought up: https://github.com/yahoo/react-intl/pull/255#issuecomment-166628628
