### ISSUE TITLE
intl props not available

### ISSUE THREAD

**Issue by benzen** [yahoo/react-intl#439]
I'm using starting my app like this:

`````js
import {IntlProvider, addLocaleData} from 'react-intl'
import enLocaleData from 'react-intl/locale-data/en'
import frLocaleData from 'react-intl/locale-data/fr'

...
addLocaleData(enLocaleData)
addLocaleData(frLocaleData)

...
const App = () => {
  return <IntlProvider locale="en">
    <Provider store={store}>
      <RoutedApp/>
    </Provider>
  </IntlProvider>
}

`````

All seams ok.
But i don't have an intl field in the props or in the context of my components.

Any idea on what i did wrong?

**Comment by ericf** [comment]
See: [Injection API](https://github.com/yahoo/react-intl/wiki/API#injection-api)

**Comment by benzen** [comment]
So injectIntl is required even when using IntlProvider ?

**Comment by ericf** [comment]
If you want this:
> But i don't have an intl field in the props or in the context of my components.
