### ISSUE TITLE
FormattedNumber formatting

### ISSUE THREAD

**Issue by mycroft11** [yahoo/react-intl#440]
Hi,

Currently there's no way to format currency with two significant digits -> 
10.5 should be 10.50 while keeping the format of 10 to just 10, instead of 10.00.

Any thoughts on this?

**Comment by ericf** [comment]
It's going to round up, but it is possible:

```js
<FormattedNumber
  value={10.5}
  style='currency'
  currency='USD'
  minimumFractionDigits={0}
  maximumFractionDigits={0}
/>
```

See: https://github.com/yahoo/react-intl/wiki/Components#number-formatting-components

**Comment by ErikMartensson** [comment]
I don't think this answers the question.

Is it possible to show a max of two decimals, when the value contains decimals. And then not show any fractions when the value contains no decimals?

**Comment by jwineman** [comment]
I was able to solve this with the following code:
```
<FormattedNumber
            style='currency'
            currency='USD'
            minimumFractionDigits={price % 1 === 0 ? 0 : 2}
            maximumFractionDigits={price % 1 === 0 ? 0 : 2}
            value={price}
          />
```

**Comment by white112** [comment]
You are right.
Thanks. @jwineman
