### ISSUE TITLE
Per message fallback

### ISSUE THREAD

**Issue by rafaelsales** [yahoo/react-intl#442]
I'm trying to implement per-message fallback. E.g:

```javascript
// en.json (default locale)
{ 
  "user": {
    "name": "Name",
    "email": "E-mail"
  }
}

// ja.json
{ 
  "user": {
    "name": "名前"
  }
}
```

When using Japanese locale I would expect:
`messages.user.name => "名前"`
`messages.user.email => "E-mail"`

Couldn't find support for this in the docs and the codebase.
Is there support for this already or plans to implement?

**Comment by ericf** [comment]
`defaultMessage` fallbacks are already supported. via `defineMessages` and `<FormattedMessage>`. Also at build time just merge the two collections, where `en.json` serves as the defaults for `ja.json` so any missing messages in `ja.json` are `en`'s. Pass the merged collection in `<IntlProvider>`.
