### ISSUE TITLE
Simple string translation is not simple.

### ISSUE THREAD

**Issue by nkudo** [yahoo/react-intl#450]
I have an app which is already built in English and I'm trying to localize it for German. 
I already built out a small library and to translate text I simply  call it like a function thus:
`{Intl.t('hello_word')}` passing the right keys returns the translation in a JSON file.

Right now I want to integrate this plugin, do I have to add `<FormattedMessage>` to every single text I have to translate? Note my app already has more than 100 words, is there no simple function in the API to just fetch a string from a JSON file using keys? what happened to simple abstraction?

**Comment by ericf** [comment]
> is there no simple function in the API to just fetch a string from a JSON file using keys?

Nope, this package won't perform any I/O.

> what happened to simple abstraction?

I dunno, maybe I'm too in the weeds with solving the more complex use cases with this library?
