### ISSUE TITLE
IntlProvider component in tests are not letting other components render.

### ISSUE THREAD

**Issue by SamAmiri** [yahoo/react-intl#451]
I wrote a series of tests with Karma + Mocha + Chai and when testing the individual components I kept getting an error that I needed to add the following to the individual components tests:

`Chrome 50.0.2661 (Mac OS X 10.10.5) Filters when the more filters drawer is open has drawer component FAILED
	Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.`

When I did wrap the `<IntlProvider />` component around the `<Filter />` component, it won't render the children components of `<Filter />`. Is this known?

**Comment by ericf** [comment]
Please review these docs on testing with React Intl: https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl

**Comment by SamAmiri** [comment]
Thanks for the link! I do have a question in regards to DOM rendering. If we are not using the `injectIntl`in the component(i.e. `<Filter />`) and using `<FormattedTime />` component, do we still have to wrap it like this `explort default injectIntl(Filter, { withRef: true});`? And lastly in the example given, what does `myClassFn() { ... }` do? We only use the `render()` function to display the children components.
