### ISSUE TITLE
docs need addLocaleData explanation

### ISSUE THREAD

**Issue by limscoder** [yahoo/react-intl#452]
I'm following the upgrade guide from v1 to v2.

In v2 I get an error about not calling `addLocaleData`, which was not required in v1. The docs don't clearly explain what I'm supposed to pass as an argument to this call or what it does.

If I call `addLocaleData({locale: 'fr'})` I get an error about not having a `pluralizationRuleFunction`, which wasn't needed in v1. If I supply an empty function, all of my `Formatted*` components appear to continue to work correctly. I also see the supplied "locale data" from the `fr` locale in the guide contains calendar data, but isn't that already included with the `Intl` interface (or the `Intl` polyfill I'm already applying for runtimes without it)?

Since my components appear to work without the data, I am unsure if I need this data or what it's used for.

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/wiki#loading-locale-data

**Comment by kostyaostapuk** [comment]
@ericf @limscoder Hi guys. Can you suggest me any reasons why
I should use method addLocaleData in my project? I using react-intl v2.x

Looks like I can work without adding the locale data through the method ‘addLocaleData’

UPD: addLocaleData is necessary for old browser (e.g. Safari 12- & IE11)
I think answer here: https://formatjs.io/docs/react-intl/upgrade-guide-3x/#migrate-to-using-native-intl-apis
