### ISSUE TITLE
addLocaleData with an array doesn't work

### ISSUE THREAD

**Issue by steida** [yahoo/react-intl#456]
This works: `[cs, de, es, en, fr, no, pt, ro].forEach(addLocaleData)`

This doesn't work: `addLocaleData([cs, de, es, en, fr, no, pt, ro])`

![screen shot 2016-05-11 at 23 57 45](https://cloud.githubusercontent.com/assets/66249/15197883/32c824ee-17d4-11e6-9426-cfe775edd722.png)

Btw, I don't understand why in `addLocaleData([...en, ...fr, ...es]);` items must be ...ed.

**Comment by Zephir77167** [comment]
Hello,

Accord to the [documentation](https://github.com/yahoo/react-intl/wiki#locale-data-in-browsers), `addLocaleData([...cs, ...de, ...es, ...en, ...fr, ...no, ...pt, ...ro])` should work.

**Comment by steida** [comment]
But why such weird verbose syntax?

**Comment by ericf** [comment]
It's because `en`, `es`, etc. are arrays, so the spread operator makes it into one array.

Generally, you're only adding one language's locale data.

**Comment by steida** [comment]
The array is an implementation detail. The developer should not be forced to ... ... ... ... everything I suppose. But I understand the decision was made and it's hard to fix it without breaking changes.

**Comment by ericf** [comment]
You can use concat, or open a PR to make it work.
