### ISSUE TITLE
Does react-intl support dynamic data translation?

### ISSUE THREAD

**Issue by agile116** [yahoo/react-intl#460]
As far as I know, react-intl needs id, defaultMessage defined in code, so it is impossible to translate keys included in dynamic loaded data. Do I miss anything? Or are there any other ways to handle it?

**Comment by steida** [comment]
Yes, it does. Check https://este.firebaseapp.com/intl

**Comment by ericf** [comment]
This sounds similar to the question in #463. I responded there: https://github.com/yahoo/react-intl/issues/463#issuecomment-219257449
