### ISSUE TITLE
Opting out of the "[React Intl] Missing message" in developement

### ISSUE THREAD

**Issue by m4nuC** [yahoo/react-intl#465]
We are not using the defaultMessage property because we don't want a fallback language. So the console ends up being cluttered by these: 

**[React Intl] Missing message: "USD" for locale: "en"**

Is there a way to disable these in development ?

**Comment by ericf** [comment]
If you're not providing any `defaultMessage` values and not passing in English messages to `<IntlProvider>`, what do you want displayed during development? Just the literal message ids?

**Comment by m4nuC** [comment]
Yes we just want to display literal message IDs.

**Comment by ericf** [comment]
Can you explain a bit more why? I'm trying to understand why this is a good idea and wouldn't lead to deploys of an app with missing strings.

**Comment by m4nuC** [comment]
The idea is that letting the ID as the default message makes it easier for translators (who dont' work with the console) to find what ID needs to be translated. 
Also this way I created a special language with no translation that translater can use to find out which ID is behind a string (they can switch to this language to display all strings on the app as IDs)
Maybe there is a better way to go about this ?

**Comment by ericf** [comment]
Okay, this makes more sense now.

If you want the warnings then, can you pass in your messages collection to `<IntlProvider>` for this special language where the keys and values are the same for the missing messages that need translation? e.g.:

```json
{
  "GREETING": "Hello, {name}",
  "AMOUNT_LABEL": "AMOUNT_LABEL"
}
```

This way the translator would see that the `AMOUNT_LABEL` string is missing it translation.

**Comment by m4nuC** [comment]
Thanks. That would work but given our workflow there would be a few downsides: 

- developers just deal with strings IDs and never use any specific language. Having them maintaining `defaultMessage` props is a bit cumbersome. 
- It could get pretty hairy when dealing with nested translation objects (only translators maintain the translation file and the less they deal with raw JSON the better ).

So overall using an empty language file and not filling in the defaultMessage props give all this for free. Would it be complicated to either:

- have the missing message warning be only an info message (this way they can be filtered out of the console) 
- allow to opt-out of these waring all together.

**Comment by ericf** [comment]
The JSON example I posted above would be generated by your build system.

I think it's a bad idea to disable this message. It's very extremely helpful for us when catching missing strings in the UI. It being noisy is likely temporary until the majority of your app's strings have been localized.

**Comment by m4nuC** [comment]
Actaully my issue was with the missing `defaultMessage`. But I see that in the latest version the message has been disabled? So now the only warning are for the missing translation strings which is fine.

**Comment by m4nuC** [comment]
How about adding a check for an environment variable such as: REACT_INTL_SILENT.

The idea is that there might be long period of time during the development process where translation strings haven't been added yet and right now all these error messages (that really aren't errors) render the console barely usable.

**Comment by ericf** [comment]
@m4nuC I think I've provided you with some examples of a few small things you can to do to handle this. I'm not in favor of adding an option to silence warnings, because I think it'll be abused and a bad idea in the end.

**Comment by m4nuC** [comment]
Ok. Thank you for your help. We will try to work that out another way.

**Comment by Rouby** [comment]
https://github.com/keyanzhang/identity-obj-proxy

It should be possible to hook this up in development as a message proxy.

**Comment by tkvw** [comment]
I don't understand the arguments against giving the developer an option to opt out of the debugging messages. In a situation where development cycle is 
```
-> developer defines messages using defineMessages 
-> messages are extracted and pushed to translation service 
-> translated files are pulled into the app. 
```
Than it does not make sense to warn me about missing messages, because I know they get translated later. It's intentional and now my console is cluttered with React Intl error messages. 
Currently I use the filter `/^(?!\[React Intl]).*$/` in console.log filter.

**Comment by mschipperheyn** [comment]
Another argument is that on React-Native, Missing messages actually create full on blocking errors. So, every message id you add cannot wait till later and has to be added to the resource file right away. 

I don't understand why this has to be such a discussion (it has been for years now) and not be solved by a simple startup option. Default can be the error, but at least you can opt out. Not everyone works the same way.

**Comment by serhiipalash** [comment]
We need this option in React-Native. It is not possible to work if you see red error screen always when someone forgot to add translations.

**Comment by karl** [comment]
We had the same need to hide missing translation errors (as we knew translations would be added by another team at a later time) and ended up using the following code:

```
// Disable missing translation message as translations will be added later.
// We can add a toggle for this later when we have most translations.

// eslint-disable-next-line
const consoleError = console.error.bind(console);
// eslint-disable-next-line
console.error = (message, ...args) => {
  if (
    typeof message === 'string' &&
    message.startsWith('[React Intl] Missing message:')
  ) {
    return;
  }
  consoleError(message, ...args);
};
```

**Comment by serhiipalash** [comment]
@karl great fix! Thanks!

**Comment by jurvi** [comment]
It's a stupid decision to not give this option during development. In almost all major projects the translations will come at a later stage, not during development, and for sure not by the developer. This warning spam is a pain in the ass and actually takes a lot of resources from browser as well.

**Comment by ybelenko** [comment]
How about add an option to set log level for this messages? I don't have all final texts during development so my console is filled up with `[React Intl] Missing...` errors. Right after application start my console error counter is up to 50 and it's really hard to find real execution errors.  I would change them to `warning` or `info` level to separate from real problems.

Ok, we got it, you don't want to disable errors displaying. But you can't force me to look at the console. If I get frustrated I will close the console at all, which is even worse for development.

**Comment by sorahn** [comment]
I'm also looking to opt-out of this for development.  Often when creating new things I don't even know what I'm going to be writing for the messages yet, so I just want the strings to come through without filling up the console with errors.

I've created a lot of base components that assume when we're done that the value passed in will be an `id`.  It would be great to just be able to pass in an option to the provider to turn these errors off.

**Comment by Lelith** [comment]
just commenting here that it is still an issue in 2019 and we still would love to be able to opt-out of error messages.

**Comment by m4nuC** [comment]
@ericf This is obviously not an isolated use case.  Maybe take a minute to reconsider?

**Comment by kopax** [comment]
I am in favor of it, @ericf why can't we add a single `if` test at the appropriate place to make everybody happy?

**Comment by melissammbeff** [comment]
Why was this issue closed if it was not solved?

**Comment by Lelith** [comment]
@melissammbeff i agree, its very sad that the maintainers of the package have such a strong opinion on several topics.
i m in discussion with my other frontend engineers in our company and we are activily looking for a alternative where the maintainers are more open. This package has several major issues for us (e.g. bad / low support on html encoded translations).

**Comment by sorahn** [comment]
I ended up using @karl's suggestion [here](https://github.com/yahoo/react-intl/issues/465#issuecomment-369566628) with a `.env` variable.  Works pretty well, but it really should just be part of the library.

At my last office we had pretty good success with i18next.

**Comment by JTLiberis** [comment]
Just wanted to keep the thread alive. Can we at least have an option to disable the messages during automated testing? My console is literally clogged with error messages... 🙏

**Comment by tinacious** [comment]
Custom error support was added as of [v2.7.0](https://github.com/formatjs/react-intl/pull/880) to `intl.formatMessage` and later, as of [v2.7.1](https://github.com/formatjs/react-intl/releases/tag/v2.7.1), this was exposed as the prop `onError` for `IntlProvider`, e.g.

```jsx
<IntlProvider onError={myCustomErrorFunction} />
```

The function will be passed the error string [as per the source code](https://github.com/formatjs/react-intl/blob/master/src/components/provider.tsx#L120-L125).

It's also been added to [the documentation](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#intlprovider).

You should be able to accomplish this with the existing API by implementing your own error handler.

**Comment by JTLiberis** [comment]
Thank you so much @tinacious

**Comment by AKedar21** [comment]
> We had the same need to hide missing translation errors (as we knew translations would be added by another team at a later time) and ended up using the following code:
> 
> ```js
> // Disable missing translation message as translations will be added later.
> // We can add a toggle for this later when we have most translations.
> 
> // eslint-disable-next-line
> const consoleError = console.error.bind(console);
> // eslint-disable-next-line
> console.error = (message, ...args) => {
>   if (
>     typeof message === 'string' &&
>     message.startsWith('[React Intl] Missing message:')
>   ) {
>     return;
>   }
>   consoleError(message, ...args);
> };
> ```

@karl Thanks for the hack

**Comment by longlho** [comment]
In the future we might expose err code that makes filtering easier.

**Comment by javaDeveloperKid** [comment]
It does not work for me in production build. Using v2.7.2 and callback is not called.
`<IntlProvider locale={language} messages={language && messages[language]} onError={this.onError}>`.

**Comment by bakakaba** [comment]
Based on @tinacious comment:

```javascript
<IntlProvider
  onError={(err) => {
    if (err.code === "MISSING_TRANSLATION") {
      console.warn("Missing translation", err.message);
      return;
    }
    throw err;
  }}
>
  {children}
</IntlProvider>
```
This should really be the default instead of the full blown error.

**Comment by longlho** [comment]
This is only in v4, not v2.

**Comment by tinacious** [comment]
> It does not work for me in production build. Using v2.7.2 and callback is not called.
> `<IntlProvider locale={language} messages={language && messages[language]} onError={this.onError}>`.

@javaDeveloperKid, without seeing the parent component, I'm not able to see what `this.onError` looks like.

Please note that this was a problem I needed to solve for myself and decided to contribute it to this thread to help others. **I am not a react-intl or formatjs contributor**. I noticed the original links I provided that link to the documentation and source code are now broken as it looks like the project owners have changed the project name and directories around since my initial comment.

Another quick search of their source code shows that `IntlProvider` tests reference `onError` and this should be working. My guess is you have another error somewhere else in your code. 

- you may be pointing to a previous version that does not offer support for a custom `onError` prop. Check your `package-lock.json` or `yarn.lock` file to confirm the version
- you may not be properly referencing your error handler correctly, i.e. it may be undefined. If you're using ES6 class components (which it looks like you may be from your syntax), you may have forgotten to bind the `this` context. I am leaning more towards this possibility.

You can read the `IntlProvider` source code if you wanted to see how it works: https://github.com/formatjs/formatjs/blob/master/packages/react-intl/src/components/provider.tsx

According to the source code, at least at a quick glance, it seems like [my suggestion](https://github.com/formatjs/formatjs/issues/465#issuecomment-527634135) should still work.

**Comment by timwuhaotian** [comment]
> We had the same need to hide missing translation errors (as we knew translations would be added by another team at a later time) and ended up using the following code:
> 
> ```js
> // Disable missing translation message as translations will be added later.
> // We can add a toggle for this later when we have most translations.
> 
> // eslint-disable-next-line
> const consoleError = console.error.bind(console);
> // eslint-disable-next-line
> console.error = (message, ...args) => {
>   if (
>     typeof message === 'string' &&
>     message.startsWith('[React Intl] Missing message:')
>   ) {
>     return;
>   }
>   consoleError(message, ...args);
> };
> ```

:0 also need to add 

`|| message.startsWith('[React Intl] Cannot format message')`

**Comment by keijop** [comment]
If you're using `intl` also outside of React and use `RawIntlProvider` instead of `IntlProvider` you can pass the above mentioned function to `createIntl`

```
const intl = createIntl({
  locale: 'fr-FR',
  messages: {},
  onError: <custom err handling>
}, cache)
```

**Comment by albertofrzara** [comment]
> We had the same need to hide missing translation errors (as we knew translations would be added by another team at a later time) and ended up using the following code:
> 
> ```js
> // Disable missing translation message as translations will be added later.
> // We can add a toggle for this later when we have most translations.
> 
> // eslint-disable-next-line
> const consoleError = console.error.bind(console);
> // eslint-disable-next-line
> console.error = (message, ...args) => {
>   if (
>     typeof message === 'string' &&
>     message.startsWith('[React Intl] Missing message:')
>   ) {
>     return;
>   }
>   consoleError(message, ...args);
> };
> ```

Thanks for hacks. 
Another solution may be to use the IntlProvider onError with this hack
```
const ignoreDefaulMessageError = (error) => {
    if (typeof error.message === "string" && error.message.includes("[@formatjs/intl Error MISSING_TRANSLATION]")) {
      return;
    }
  };

  return (
    <IntlProvider
      locale={locale}
      messages={messages}
      defaultLocale={defaultLocale}
      key={key}
      onError={ignoreDefaulMessageError}
    >
      {children}
    </IntlProvider>
```

**Comment by pmioduszewski** [comment]
The simplest possible workaround is using a browser's console filter.
Type `-MISSING_MESSAGE` in the console search input, and every log with the `MISSING_MESSAGE` string will be hidden.

<img width="644" alt="image" src="https://github.com/user-attachments/assets/ab687b34-7b87-4185-9cd0-28419c5868f6">

**Comment by vekinox** [comment]
As have been pointed out by others above, using a custom Intlprovider is an easy way to handle this

```js
// src/i18n/IntlProvider.jsx

import React from 'react';
import PropTypes from 'prop-types';
import { IntlProvider as Provider } from 'react-intl';

const IntlProvider = (props) => {
  const { children, lang, messages } = props;

  return (
    <Provider
      locale={lang}
      messages={messages}
      textComponent={React.Fragment}
      onError={(error) => {
        if (error.code === 'MISSING_TRANSLATION') return;
        console.error(error); // Log other types of errors
      }}
    >
      {children}
    </Provider>
  );k
};

IntlProvider.propTypes = {
  children: PropTypes.node,
  lang: PropTypes.oneOf(LANGUAGES),
  messages: PropTypes.object,
};

export default IntlProvider;
```

**Comment by Dari4sho** [comment]
None of the mentioned solutions in this issue worked for me on a basic react19 project. It's quite annoying. For example, my workflow is to add translations as the very last step before a launch. Until then, the console is rendered useless when placing dummy translations.

As many have recommened, the only thing that helps is adding a filter to the browser console, as of the latest version as of writing 
`-MISSING_TRANSLATION`.

The annoying part here is that on every page refresh the filter has to be "renewed" (e.g. removing a letter and adding it again), as it for some reason is not respected out of the box.

It's a valid situation developers find themselves in for at least 9 years now, just looking at this issue. There should be an option.
