### ISSUE TITLE
How to use particular locale in formatMessage method?

### ISSUE THREAD

**Issue by vdzundza** [yahoo/react-intl#467]
I've found https://github.com/yahoo/react-intl/blob/88ef46a7f530d143734ed8e8e6d510dc9d7b8136/src/format.js#L181 this. How can I force to use my locale in the formatMessage method?

**Comment by ericf** [comment]
This is set through the `locale` prop on the `<IntlProvider>`: https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context
