### ISSUE TITLE
About region code [en-US]

### ISSUE THREAD

**Issue by efkan** [yahoo/react-intl#468]
When I assign `en` value to the `locale` prop in the provider component it works. But I get the console warning below when I use `en-US` in the provider component like `<IntlProvider locale="en-US" messages={messagesEN}>`
   `[React Intl] Missing message: "home.greeting" for locale: "en-US", using default message as fallback.`
   It shouldn't evaluate the region code US? Am I wrong?

**Comment by efkan** [comment]
According to https://blog.johnphoto.se/2016/03/21/react-intl-v2/ , I have to create a translation file.

**Comment by ericf** [comment]
See: https://github.com/yahoo/react-intl/wiki#loading-locale-data
