### ISSUE TITLE
Getting translations from nested paths

### ISSUE THREAD

**Issue by kosz** [yahoo/react-intl#470]
```
export default {
  hello: 'Hello',
  world: 'World',
  user: {
    login: 'Login' 
  }
};
```

works:
```
<FormattedMessage id="hello" />
```

doesn't work: 
```
<FormattedMessage id="user.login" />
```

I see in this example that they do use this approach : https://github.com/gpbl/isomorphic500/blob/master/src/intl/en.js, but I get the feeling that they massaged the library quite a bit, not sure if that's `react-intl` or the external example's monkey patching providing that feature. 

Is this supposed to work out of the box ? The translation examples don't seem to cover it.

**Comment by ericf** [comment]
The messages collection must be flat in v2. See here how you could flatten the structure you have just before you pass it to the `<IntlProvider>`: https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object
