### ISSUE TITLE
SyntaxError when assigning JSON string to defaultMessage

### ISSUE THREAD

**Issue by efkan** [yahoo/react-intl#476]
Hello,

I've been try to use an array message - _which has 24 occupational group items_ - as `defaultMessage`. Actually I can use the below code. It works perfectly. But I get this error: `TypeError: A message must be provided as a String or AST.`. 

	occupationalGroups: {
		id: 'register.occupationalGroups',
		description: '',
		defaultMessage: [{"_id":"000000000000000000000001","name":"Private sector employee"}]
	}

Then I decided to convert JSON to string by using `JSON.stringify()`. Thus I can convert the string to a JSON by using JSON.parse easily. However when trying a string I get the below error:
```
[React Intl] Error formatting the default message for: "register.occupationalGroups"
SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "\"" found.
```

The JSON string I use;
`defaultMessage: '[{"_id":"000000000000000000000001","name":"Private sector employee"}]'`

In fact both of code parts work properly.

Is there any chance to use or to pass an object without an error?

(Able to assign an object to `defaultMessage` without an error would be great!)

**Comment by langpavel** [comment]
? defaultMessage should be ICU string

**Comment by ericf** [comment]
See: https://github.com/yahoo/react-intl/wiki/Components#string-formatting-components

**Comment by efkan** [comment]
Thanks @ericf . I've tried with `FormattedMessage` component.

It works with the same error though I use `<FormattedMessage {...messages.occupationalGroups} />`. Just like in code of `intl.formatMessage(messages.occupationalGroups)`, it works (translates successfully) with the same error.

I want to give more information about what I do; I use `react-intl` together with `React-Native`. It works great as expected. However if I try to translate an object it throws error. 

I've tested `FormattedMessage` by using the below code. 

```
<Intl.FormattedMessage {...messages.occupationalGroups}>
	{
		(...nodes) => {
			nodes.map((node) => {
				console.log('node: ', node)
			})
		}
	}
</Intl.FormattedMessage>
```



The console output (note that _translation is success_ with _errors_):
```
[React Intl] Error formatting message: "occupationalGroups" for locale: "de-DE", using default message as fallback.
SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "\"" found.

[React Intl] Error formatting the default message for: "occupationalGroups"
SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "\"" found.

[React Intl] Cannot format message: "occupationalGroups", using message source as fallback.

node:  [{"_id":"000000000000000000000001","name":"Arbeitnehmer im Privatsektor"}...]
```


Message descriptor:
```
occupationalGroups: {
	id: 'register.occupationalGroups',
	description: '',
	defaultMessage: JSON.stringify([
		{
			'_id' : '000000000000000000000001',
			'name' : 'Private sector empolyee'
		},
		...
}
```

Translation:
```
'occupationalGroups': JSON.stringify([
	{
		'_id' : '000000000000000000000001',
		'name' : 'Arbeitnehmer im Privatsektor'
	},
	...
])
```

Sorry for taking your time. Have a good night..

**Comment by ericf** [comment]
It must be an a string that's compatible with ICU message syntax. It cannot be an object or JSON string. See the docs that I linked to.
