### ISSUE TITLE
DateFormat Issue with Safari browser 

### ISSUE THREAD

**Issue by chsanthosh** [yahoo/react-intl#477]
Eg:
Date:
May 27, 2016

HK Lang (zh-hant-hk):
Chrome:
2016年5月27日

in Safari:
2016年5月月27日

Duplicate "月" shows only on safari .. ? 
Any options to resolve the same or is it specific safari issue?

**Comment by ericf** [comment]
What version of the Intl polyfill package are you using? Can you try the latest version?

**Comment by ericf** [comment]
Using `intl@1.2.x` this issue has been resolved: `'1969年12月31日'`
