### ISSUE TITLE
Provide ES5 examples as well as ES6 examples.

### ISSUE THREAD

**Issue by wirehead** [yahoo/react-intl#480]
I'm porting some ES5 React code from react-intl 1.x to 2.x and I'm pretty sure I've got the entire injectIntl thing wrong but all of the examples in the wiki are ES6, not ES5.

**Comment by ericf** [comment]
There's no plan to re-write the examples using only ES5 syntax, but here's a quick overview of using `injectIntl()` using ES5 + CommonJS:

```js
var React = require('react');
var ReactIntl = require('react-intl');
var Component = React.createClass({ /* ... */ });
module.exports = ReactIntl.injectIntl(Component);
```
