### ISSUE TITLE
FormattedMessage values don't show '0' as a value

### ISSUE THREAD

**Issue by iamsaksham** [yahoo/react-intl#482]
<FormattedMessage
          id = 'active-users'
          description = 'ACTIVE USERS'
          defaultMessage = 'ACTIVE USERS({userList})'
          values = {{
            userList: this.props.list.get('users').size
          }}
      />

In above case when value of userList is not 0 then it shows in the defaultMessage correctly as ACTIVE USERS(2), but when it is 0, then it donot display 0 as the value. It is displayed as ACTIVE USERS()

**Comment by ericf** [comment]
If you want to format this argument as a number use `'ACTIVE USERS({userList, number})'`. You can search through the other issues that have been brought up on this topic for more details.

**Comment by aaronbeall** [comment]
@ericf Is there any documentation on how FormatJS interpolates values? It seems will take any value and turn it into a string, how does it handle null, undefined, NaN, etc?

**Comment by papasmile** [comment]
Documentation simply states:
> A value must be supplied for every argument in the message pattern the instance was constructed with.
https://github.com/yahoo/intl-messageformat/tree/v2.2.0#formatvalues-method

But I do see that method that produces what is "a value" or not (ie blank resulting in 'Cannot format message' error) as of latest release (2.2.0): https://github.com/yahoo/intl-messageformat/blob/03e0f1d3aeb313fb5ecf607d3697446c2c367e24/src/compiler.js#L159
