### ISSUE TITLE
Date format problems when using Intl.js polyfill

### ISSUE THREAD

**Issue by pselden** [yahoo/react-intl#49]
Very sorry to open this here since it's not directly related to react-intl but since you guys have probably already encountered this in your use at scale I figured I would bring it up here.

Everything seems to be working fine for browsers that support Intl.js natively -- but there are a few differences when using the polyfill that I was wondering how you have overcome.

1) No support for timezone formatting except UTC -- the polyfill will throw an error if you try to supply a timezone that isn't 'UTC'
2) Differences in date formatting -- specifically this one: https://github.com/andyearnshaw/Intl.js/issues/68

Do you have products that use the Intl.js polyfill version with date or timezone formatting -- and if so, how do you get around this issue?

Also, is there a newsgroup or IRC something where I could ask questions like this instead of polluting the github issue tracker?

Thanks!

**Comment by Tin-Nguyen** [comment]
Is there any updates to fix the issue for timezone on polyfill @andyearnshaw ? I'm facing the issue on my app running on Safari browser.

**Comment by caridy** [comment]
@Tin-Nguyen we haven't look at the timezone feature just yet. You can follow up the progress here: https://github.com/andyearnshaw/Intl.js/issues/19

**Comment by Tin-Nguyen** [comment]
Thanks @caridy , I did with `moment-timezone` component

**Comment by ericf** [comment]
@caridy has done work to improve the Intl.js polyfill recently. Still no timezone support, but it should be easier to add, and the discussion to add it should take place on its repo.
