### ISSUE TITLE
How to handle less than and greater than in the plural form?

### ISSUE THREAD

**Issue by jeantimex** [yahoo/react-intl#493]
The plural form doesn't support forms like less than and greater than, so the following code will always show "50+ users" when `numUsers` is `2`:

```javascript
<FormattedMessage
  defaultMessage='{numUsers, plural, =0 {0 users} one {1 user} <50 {# users} other {50+ users}}'
  values={{ numUsers }}
/>
```

What will be the best way to handle the above formatted message if I want to have a less than or greater than logic. Thanks!

**Comment by ericf** [comment]
You should use two messages:
```js
{numUsers < 50 ? 
    <FormattedMessage
        id='less_than_50_users'
        defaultMessage='{numUsers, plural, =0 {0 users} one {1 user} other {# users}}'
        values={{ numUsers }}
    /> :
    <FormattedMessage
        id='50_or_more_users'
        defaultMessage='50+ users'
    />
}
```

**Comment by jeantimex** [comment]
Thanks @ericf! I see you added the support label, does that mean react-intl will support that feature in future release?

**Comment by ericf** [comment]
No it means that this was an issue that's really a user-support ticket 😄

**Comment by jeantimex** [comment]
Cool, thanks mate!
