### ISSUE TITLE
Format number currency should not be based on locale but on currency props

### ISSUE THREAD

**Issue by lauterry** [yahoo/react-intl#494]
Hi

I want to display an amount with euro currency while having my app displayed in english.

I use `FormattedNumber` : 

```
 <FormattedNumber
                    value={ 1234 }
                    style="currency"
                    currency="EUR"
                    currencyDisplay="symbol"
                    useGrouping={ true }
                    maximumFractionDigits={ 0 }
/>
```

I expected the result to be `1 234 €` but it outputs `€1,234`.

My actual thought is that the result of `FormattedNumber` should not be based on locale but on the currency props.

I can then display amount in euro in the right format while having my app displayed in english.

What do you think ?

Best regards

**Comment by ericf** [comment]
Displaying Euros in English, `€1,234` is correct. It wouldn't make sense to an English user to see a space for the thousands separator.

**Comment by lauterry** [comment]
Thanks @ericf for your input
