### ISSUE TITLE
2.1.3 throws exception (addLocaleData).. 

### ISSUE THREAD

**Issue by chriscartlidge** [yahoo/react-intl#499]
When importing react-intl we get the following exception:

```javascript

import reactIntl from 'react-intl';

reactIntl.addLocaleData(........);
````

"TypeError: Cannot read property 'addLocaleData"

**Comment by ericf** [comment]
Was this working before 2.1.3?

In any case there's no default export so you need to do one of the following:

```js
import * as ReactIntl from 'react-intl';
ReactIntl.addLocaleData(...);
```
or
```js
import {addLocaleData} from 'react-intl';
addLocaleData(...);
```

**Comment by chriscartlidge** [comment]
@ericf It was working before 2.1.3.

I'll do the second option you suggested but I think it maybe breaking a lot of peaks projects with people auto upgrading minor versions. 

Cheers :)

**Comment by ericf** [comment]
> I think it maybe breaking a lot of peoples projects.

You're the only one that reported this, and all of the functional tests pass. Maybe you updated your transpiler and now it's working with ES6 module imports correctly?

Did you try downgrading to 2.1.2 to see if you get the same error?

**Comment by chriscartlidge** [comment]
Downgrading to 2.1.2 fixed the issue. We have had no transpiler updates only this. It's just an FYI, maybe how we were using it was odd compared to the general use case.

**Comment by ericf** [comment]
After you update your `import` statement to be correct, if the issue is still there, please reopen with a reproducible example of the issue.
