### ISSUE TITLE
FormattedRelative format options?

### ISSUE THREAD

**Issue by reintroducing** [yahoo/react-intl#500]
This is a question but I wasn't sure where else to put it.  I'm formatting my date using FormattedRelative and it outputs "4 minutes ago". Great. However, I'd like to shorten that to "4 mins ago" if possible.  I tried `<FormattedRelative value={dateTime} format="short" />` but got an error saying short is not a valid format. I'm wondering what the possible values are for formatting the relative time and in the future, where can I find this in the documentation? I tried going through the docs but I must have missed it.

**Comment by ericf** [comment]
You can see the docs on `<FormattedRelative>` here: https://github.com/yahoo/react-intl/wiki/Components#formattedrelative

The `format` prop is used to create custom named formats that correspond to setting defaults for options. In the case of `<FormattedRelative>` it can be used to set the `units` and `style` options. You define these `formats` on `<IntlProvider>`; e.g.:
```js
<IntlProvider
    locale='en'
    formats={{
        relative: {
            hours: {
                units: 'hour',
                style: 'numeric',
            },
        },
    }}
>
    <FormattedRelative value={date} format='hours'/>
</IntlProvider>
```

In terms of using short-hand like `min`, that's not currently supported.

**Comment by reintroducing** [comment]
Got it, thanks @ericf. Is there any planned support for doing what I'm trying to accomplish or am I just left with string manipulation to achieve that?

**Comment by ericf** [comment]
There's work happening to standardize the API into JavaScript: https://github.com/caridy/intl-relative-time-spec which will include the short forms; e.g. `2 min. ago`

**Comment by ericf** [comment]
Closing this out… this is a feature for the underlying `IntlRelativeFormat` or web platform to solve.

**Comment by aaronbeall** [comment]
@ericf I see the spec you referred to has a "short" style like `2 min. ago` but the docs for `formatRelative` still only show `'best fit' | 'numeric'`. Is there a way to achieve the "short" version?

**Comment by papasmile** [comment]
Hi, @aaronbeall, there is a PR out.  Feel free to add a +1 and/or just use those changes: https://github.com/yahoo/react-intl/pull/1145
