### ISSUE TITLE
FormattedMessage inside of custom Button component throws error

### ISSUE THREAD

**Issue by reintroducing** [yahoo/react-intl#501]
I'm using FormattedMessage inside of a custom Button component like so:
```
<Button className="Messages-compose-btn" icon="pencil">
    <FormattedMessage id="messages.compose" />
</Button>
```
All Button is is a wrapper for a button element that has some custom styling in it.  The `children` prop of Button is set to accept any prop as such:
```
PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.element,
    PropTypes.node,
    PropTypes.arrayOf(PropTypes.element),
    PropTypes.arrayOf(PropTypes.node)
])
```
In the console I'm seeing `Uncaught TypeError: ReactDOM.findDOMNode is not a function`.  If I put the FormattedMessage right above the Button component it shows up just fine.

Am I doing something wrong or is this a bug?

**Comment by ericf** [comment]
I couldn't say, seems like your `<Button>` might be doing something with ReactDOM. Not a bug here.

**Comment by reintroducing** [comment]
The button is not doing anything crazy, here is its render method:
```
return (
    <button
        className={classes}
        type={type}
        onClick={evt => {
            if (route) {
                browserHistory.push(route);
            }

            if (onClick) {
                onClick();
            }
        }}
        disabled={disabled}
    >
        {icon && iconPosition === 'left' && <Icon id={icon} />}
        {children}
        {icon && iconPosition === 'right' && <Icon id={icon} />}
    </button>
);
```

**Comment by reintroducing** [comment]
Quick follow up, I'm actually able to re-create it by doing the following as well:
`<button><FormattedMessage id="messages.compose" /></button>`

**Comment by reintroducing** [comment]
And one last quick follow up: I thought that maybe something was re-rendering multiple times or that particular parent component had an issue with it.  I transferred the following to its own route and I'm still getting the error with only one render of the Community component.
```
import React, {Component} from 'react';
import {FormattedMessage} from 'react-intl';

class Community extends Component {
    render() {
        console.log('render');
        return (
            <section className="Community Page">
                <h1 className="heading-md">Community</h1>
                <button><FormattedMessage id="messages.compose" /></button>
            </section>
        );
    }
}

export default Community;
```

**Comment by reintroducing** [comment]
Sorry, I don't mean to keep spamming this thread, but I keep finding new things with this issue.  If I wrap the FormattedMessage in a span I have no issues.  Why would this be?

Doesn't work: `<button><FormattedMessage id="messages.compose" /></button>`

Works: `<button><span><FormattedMessage id="messages.compose" /></span></button>`

**Comment by reintroducing** [comment]
Aaaaand last but not least, I figured it out :)

For anyone else who may ever run into this, I am using react-a11y during local dev.  When initializing react-a11y you have to pass in ReactDOM as such:
```
if (process.env.NODE_ENV === 'development') {
    const a11y = require('react-a11y');
    const ReactDOM = require('react-dom');

    a11y(React, {ReactDOM});
}
```
Apologies for the noise.

**Comment by polise** [comment]
I spent 100 years trying to solve this problem. Thank you @reintroducing !
