### ISSUE TITLE
Question: example that shows conditional loading of Intl.js

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#51]
Hi,

The examples provided don't offer sufficient support to get started without questions. It just gives you enough information to almost understand how to set it up in a real world scenario, but not quite. And struggles follow.

I find myself with the following questions

* I'm looking for an example that shows the conditional loading of Intl.js both in the browser and in node.js. This, in the context of creating a distribution.js for my application with gulp. I want to avoid including Intl.js there in the distribution when during packaging Intl.js will obviously not be there.
* Can I specify a normal properties style text file as a source for messages?
* I work w global message files (as opposed to component level message files). What's the best way to only load the correct one? I can load based on the applied locale, but if that's not available it should revert back to the default and load only that.
* The library seems to use either props or context to reference a message bundle. How do I work with a globally available language file in order not to have to pass this through each and every time.
* is it possible to set the library up so that any message that is not found will just return the provided message key? In a dev scenario, you may not want to have to supply all the correct messages up front. and imho a non-available messages file should not result follow this scenario and provide a warning in stead of throwing an exception.

My suggestion: provide a small complete scenario that is set up for production and development.

**Comment by caridy** [comment]
> I'm looking for an example that shows the conditional loading of Intl.js both in the browser and in node.js. This, in the context of creating a distribution.js for my application with gulp. I want to avoid including Intl.js there in the distribution when during packaging Intl.js will obviously not be there.

we don't have such example, we are waiting for polyfill.io to include intl.js to do so (we are working with them to get that in soon)

> Can I specify a normal properties style text file as a source for messages?



> I work w global message files (as opposed to component level message files). What's the best way to only load the correct one? I can load based on the applied locale, but if that's not available it should revert back to the default and load only that.

`getIntlMessage()` is optional, you can replace it with `window.Foo`, or you can implement your own method to resolve a message. This library only provides a simple mechanism to render the top level component by passing all messages available in the app thru props, and it will try to use that information to resolve messages by path, but this is completely optional.

> The library seems to use either props or context to reference a message bundle. How do I work with a globally available language file in order not to have to pass this through each and every time.

same as above, ultimate a message is just a reference to a string value, do what you have to provide the right string value, that's all.

> is it possible to set the library up so that any message that is not found will just return the provided message key? In a dev scenario, you may not want to have to supply all the correct messages up front. and imho a non-available messages file should not result follow this scenario and provide a warning in stead of throwing an exception.

you can implement a resolver method, maybe thru a mixin that you add to all components with intl requirements, and that method can simply try to resolve the global message, or apply the fallback mechanism.

**Comment by ericf** [comment]
Instead documenting all the possible ways to use this package, I think the better thing to do is for us to create an example app that embodies all our recommendations and docs from the website.
