### ISSUE TITLE
Formatting constant numbers

### ISSUE THREAD

**Issue by vysinsky** [yahoo/react-intl#510]
Hi,

is it somehow possible to format number in message like `{1000, number}`? It is constant number so I don't want to pass it as variable. Also I want to use power of react-intl to properly format number in certain locale. Now it complains that value for `1000` was not passed.

**Comment by ericf** [comment]
Are you formatting this message in multiple places? If it's just in one place, then you could do:

```js
const num = 1000;
// ...
<FormattedMessage
  id='some_msg'
  defaultMessage='{num, number}'
  values={{num}}
/>
```

**Comment by ericf** [comment]
Closing…
