### ISSUE TITLE
Nested json

### ISSUE THREAD

**Issue by dmoskovsov** [yahoo/react-intl#512]
Hey guys. 

I'm trying to set up react-intl and currently experiencing problems with using nested json: 
{
    "account": {
        "forgotPassword": {
            "header": "Forgot Password"
        }
    }
}

This will give me index.js:939 [React Intl] Missing message: "account.forgotPassword.header" for locale: "sg"

While this json would work: 

{
    "account.forgotPassword.header": "hello world"
}

Isn't first option supposed to work? 

Thanks!

**Comment by ericf** [comment]
Nested `messages` is not supported.

**Comment by meni-cherbakovsky** [comment]
@ericf, I went over the upgrade guide and over some other comments on issues and your answer regarding nested messages support was negative.

Actually, in larger applications, developers might use message ids that will help them to organize the translations in their application. It means that they will choose message ids that represent their translations that relate to the components.

For example, here is how a translation file might look like eventually:
 
"app.toolbar.addData": "Add Data",
"app.toolbar.remove": "Remove",
"app.toolbar.undo": "Undo",
"app.toolbar.redo": "Redo",
"app.tooltip.table": "Table",
"app.tooltip.name": "Name",
"app.tooltip.location": "Location",

Using the prefix app.toolbar.* or app.tooltip.* will help us identifying the toolbar or tooltip component in the whole translation file. But using this approach the file size increases without any reason. If we would have used a nested version of messages it will be easier to maintain, plus, the file size will be smaller (no need to add the prefixes at all):

"app" : {
	"toolbar": {
		...
	},
	"tooltip": {
		...
	}
}

I would like to understand why did you choose the flattened massage id as the right approach in terms of order, organization and file size?

Thanks
