### ISSUE TITLE
FormattedNumber printed twice on Safari iOS 

### ISSUE THREAD

**Issue by shprink** [yahoo/react-intl#520]
Hi,

Every numbers used with FormattedNumber on safari iOS 9 are printed twice. Here is how it look everywhere:

![image](https://cloud.githubusercontent.com/assets/1388706/16590535/43cfce98-42d8-11e6-9e1e-c8f106c89c45.png)

Here is on iOS:

![image](https://cloud.githubusercontent.com/assets/1388706/16590523/3a642d54-42d8-11e6-98fd-96a1e688ff78.png)

code:

```
 <div className="row">
        <div className="column followers-count">
          <FormattedMessage {...messages.followers} />
          <FormattedNumber value={user.followers} />
        </div>
        <div className="column followers-count">
          <FormattedMessage {...messages.following} />
          <FormattedNumber value={user.following} />
        </div>
      </div>
```

**Comment by ericf** [comment]
Please provide a link or reproducible example app that shows the issue.

**Comment by shprink** [comment]
Do you have any jsfiddle all setup (react, reactDom, intl) that I could fork to demonstrate that?

**Comment by ericf** [comment]
Nope, sorry. If you run the examples in this repo do you see the issue in Safari?

**Comment by shprink** [comment]
ok it seems to be related to some of our project config.

If I run `new Intl.NumberFormat('en', {}).format(999)`:

on chrome: 

![image](https://cloud.githubusercontent.com/assets/1388706/16648571/11c97530-4435-11e6-8a69-3c1438b05e8d.png)

on safari:

![image](https://cloud.githubusercontent.com/assets/1388706/16648589/1b9fe5e4-4435-11e6-8a80-9bba01f0247e.png)

If I run the same command on your hello world example of yours:

![image](https://cloud.githubusercontent.com/assets/1388706/16648607/3609fc80-4435-11e6-8658-64acc712211a.png)

anyway closing this, sorry for the trouble. Thanks

**Comment by shprink** [comment]
FYI I had to upgrade `intl` polyfill from 1.1.x to 1.2.x and it now works :)

**Comment by ericf** [comment]
Okay, I'm glad you were able to figure it out. Now I recall this being an issuing in 1.1.x of the `Intl` polyfill.
