### ISSUE TITLE
looking for intl in props along with context

### ISSUE THREAD

**Issue by salzhrani** [yahoo/react-intl#523]
something similar to what `react-redux` does [here](https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L83). It eliminates the need to recreate a provider for some nesting cases, `intl` could be passed to a child component.

**Comment by ericf** [comment]
I'm not sure I understand what you're asking. Could you explain more — maybe with some sample code — as to what you're looking to do?

**Comment by salzhrani** [comment]
it is basically useful when using `cloneElement` and with enzyme
for example
```
class Alert extends React.Component{

  getHtml() {
    // !!this.props.intl === true
    const newChild = React.cloneElement(Children.only(this.props.children), {...this.props});
    return React.renderToStaticMarkup(newChild);
  }
}


<Alert>
  <FormattedMessage
    id='app.greeting'
    description='Greeting to welcome the user to the app'
    defaultMessage='Hello, {name}!'
    values={{
        name: 'Eric'
    }}
  />
</Alert>
```
`getHtml` would fail because context doesn't have `intl` even though it exists in props.

I hope this makes sense

**Comment by ericf** [comment]
You need to wrap the `newChild` with an `<IntlProvider>` since you're doing a new render.

```js
  getHtml() {
    // !!this.props.intl === true
    const newChild = React.cloneElement(Children.only(this.props.children), {...this.props});
    return React.renderToStaticMarkup(
      <IntlProvider {...this.props.intl}>
        newChild
      </IntlProvider>
    );
  }
```
