### ISSUE TITLE
error when define the variable of locale to zh，

### ISSUE THREAD

**Issue by Pines-Cheng** [yahoo/react-intl#524]
when I define the variable of locale to zh，which the language I use is simply chinese ,

```
import zh_CN from '../language/zh_CN';
import en_US from '../language/en_US';
<IntlProvider
                locale={"zh"}
                messages={zh_CN}
            >
```
I meet a error:
```
[React Intl] Missing locale data for locale: "zh". Using default locale: "en" as fallback.
```
and the  file loading of is still en-US.js,I don't know why,can someone help me ?

**Comment by ericf** [comment]
You need to load the locale data that React Intl needs to operate. This is done via [`addLocaleData()`](https://github.com/yahoo/react-intl/wiki/API#addlocaledata), there's details on the Wiki here: https://github.com/yahoo/react-intl/wiki#loading-locale-data

This locale data is separate from your apps translated strings that you're passing to `<IntlProvider>`.

**Comment by Pines-Cheng** [comment]
Thank you very much , you really help me much !

**Comment by Pines-Cheng** [comment]
I very sorry to trouble  you ,But I met another problem after use `addLocaleData()` to load the local data ,the error is : 
```
index.js:919 [React Intl] Missing message: "hello" for locale: "zh", using default message as fallback.
```
But I have import the message by `import zh_CN from '../language/zh_CN';`
I don't know why.
@ericf

**Comment by Pines-Cheng** [comment]
I have found the solution. It is just the problem of the module export , sorry to ask such a stupid question.
