### ISSUE TITLE
Hour and minute format are not applied

### ISSUE THREAD

**Issue by muuki88** [yahoo/react-intl#529]
Hi,

We are trying to format a datetime value, but the settings for `hour` and `minute` get read put not applied.

<details>
 <summary>formats definition</summary>
```js
export const deFormats = {
  date: {
    medium: {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    },
    year: {
      year: 'numeric'
    }
  },
  time: {
    week: {
      hour: '2-digit',
      minute: '2-digit',
      weekday: 'long'
    },
    short: {
      hour: '2-digit',
      minute: '2-digit'
    },
    medium: {
      hour: '2-digit',
      minute: '2-digit',
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    }
  }
};
```
</details>

<details>
 <summary>jasmine test</summary>
```jsx
  beforeEach(() => {
     addLocaleData(de);
  });

  const render = (value) => {
    const component = renderIntoDocument((
      <IntlProvider locale="de" formats={deFormats}>
        {/* this is actually a component, which generates this content */}
        <FormattedTime value={value} format="medium">
           { (mediumFormat) => {
              <span title={mediumFormat}>
                <FormattedRelative value={value} />, <FormattedTime value={value} format="short" />
              </span>
             }
           }
        </FormattedTime>
      </IntlProvider>
    ));
    const spans = scryRenderedDOMComponentsWithTag(component, 'span');
    expect(spans.length).toBeGreaterThan(0);

    return spans[0].textContent;
  };
```
</details>

Our production code looks exactly the one in the test

```jsx
<FormattedTime value={value} format="medium">
 { (mediumFormat) => {
  <span title={mediumFormat}>
    <FormattedRelative value={value} />, <FormattedTime value={value} format="short" />
  </span>
 }}
</FormattedTime>
```

The outputs for both code blocks differ:

```
# production output
vor 2 Stunden, 01:24
# jasmine test output
vor 2 Stunden, 1:24
```

Changing the settings

```js
short: {
   hour: '2-digit', // changing this in numeric has no effect. 
   minute: '2-digit'
}
```

However if I use an invalid value for the `hour` setting, it will render the complete date time and print a warning.

I'm not sure if this has something to do with the nested formatted values?

We are using version `2.1.3`, assemble the application with webpack and use jasmine `2.4.1` for tests.

**Comment by ericf** [comment]
Can you provide more details on your test environment. Is this running in a browser or node? What which version?

My guess based on what you provided is that this is related to the Intl polyfill. If you're using it in the test environment can you provide the version?

**Comment by muuki88** [comment]
We use `phantomjs`, `karma` and `jasmine` to run our tests. The bundle gets packaged by webpack.

<details>
<summary>package.json excerpt</summary>
```js
    // polyfill stuff
    "babel-core": "^6.9.0",
    "babel-eslint": "~6.0.2",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-1": "^6.5.0",

    // testing libs
    "karma": "^0.13.9",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-ajax": "^0.1.13",
    "karma-junit-reporter": "^1.0.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "^1.7.0",
    "phantomjs-prebuilt": "^2.1.4",
    "react-addons-test-utils": "^15.0.2",
    // build with
    "webpack": "^1.12.14"
```
</details>

<details>
<summary>karma.conf.js excerpt</summary>
```js
    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine-ajax', 'jasmine'],


    // list of files / patterns to load in the browser
    files: [
      'node_modules/babel-polyfill/dist/polyfill.js',
      'app/test/tests.webpack.jsx'
    ],

    preprocessors: {
      'app/test/tests.webpack.jsx': ['webpack']
    },
    browsers: ['PhantomJS'],

    webpack: {
      module: {
        loaders: [
          {
            test: /.jsx?$/,
            loader: 'babel-loader',
            exclude: /node_modules/,
            query: {
              presets: ['es2015', 'react', 'stage-1']
            }
          },
          {
            test: /\.svg$/,
            loader: 'svg-inline'
          },
          {
            test: /\.s?css$/,
            loader: 'style!css!sass'
          }
        ]
      },
      resolve: {
        root: path.resolve('./app/main'),
        extensions: ['', '.js', '.jsx', '.css', '.scss']
      }
    },
```
</details>

The interesting part is, that this seems to happen on _test_ and on the _live_ page.

**Comment by ericf** [comment]
> The interesting part is, that this seems to happen on test and on the live page.

I confused. I thought you were saying the production page was correct and the test page was wrong?

> # production output
> vor 2 Stunden, 01:24
> # jasmine test output
> vor 2 Stunden, 1:24

**Comment by muuki88** [comment]
It's correct in production by accident. If I change the settings from `2-digit` to `numeric` is has no effect. So there seems to be some browser behavior that overrides the settings for `hour` and `minutes`. Not sure if other settings affected as well. Tested on Chrome / Firefox

**Comment by andi5** [comment]
We are using https://github.com/andyearnshaw/Intl.js as intl polyfill.

**Comment by andi5** [comment]
Firefox und Chrome seem to render hour 5 as "05", regardless of 2-digit or numeric. At least Firefox uses ICU to find a good skeleton and it appears to be {{HH}}. The intl polyfill instead decides on {{h a}}, where {{a}} does not seem to be printed as hour12 is not specified(?). Anyways, the options seem to be passed to the intl implementation, so this bug in this project appears to be invalid.

I would argue that having a format {H} for german would be nice, but as long as all implementations do the same, it is ok.

The intl polyfill issue looks like https://github.com/andyearnshaw/Intl.js/issues/190

**Comment by ericf** [comment]
An approach I've used for assertions in unit tests is to not directly test that the platform is working correctly, but rather that the component is, so you could test it against using the `Intl.DateTimeFormat` API directly. [Here's an example](https://github.com/yahoo/react-intl/blob/f3398e265971748d461a4aa669924ff6ed2603f1/test/unit/components/time.js#L95-L106).

This way it covers the case of some of the browser inconsistencies. That said, I understand that's not an ideal answer, but we are working in ECMA TC39 to try to standardize the output of these APIs better across browser and environment.

**Comment by muuki88** [comment]
Thanks a lot @ericf That solves our testing issues ( we are kind of new in the React ecosystem). Time is always a tough issue on any platform and language. We appreciate you took the time helping investigate this.

I'll close this.
