### ISSUE TITLE
Provide option to ignore unfound message exceptions.

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#53]
In development it often makes sense to create a message key to be processed later. E.g. given when message files are auto generated or provided by a different process you can't control. In such a case, you don't want everything to grind to a halt just because a message key is not there. 

I suggest adding an option, similar to what I use developing against similar APIs in Java to ignore unfound messages. If turned on, simply the message key itself should be printed in case the item is not found

**Comment by mweibel** [comment]
:+1:

**Comment by gpbl** [comment]
+1!

**Comment by caridy** [comment]
as we described here: https://github.com/yahoo/react-intl/issues/35, there are few mechanism that you can apply to change the default behavior of this library:

* shim, or do not use the built-in `getIntlMessage`, instead, provide your own resolver.
* add a build step to complete missing keys based on the default language definition and validate entries as well.

**Comment by ericf** [comment]
Closing as dup of #35
