### ISSUE TITLE
Changing locales dynamically doesn't work

### ISSUE THREAD

**Issue by z-ax** [yahoo/react-intl#531]
Hi. I know you might mark as a duplicate, but I've checked the issues, docs for [Dynamic Language Selection](https://github.com/yahoo/react-intl/wiki/Components#dynamic-language-selection), but still it doesn't work.

What am I doing:

- have locales dir, where messages are in JSON format, like `./locales/appName_en-US.json`.
- load JSON with messages via `require('./locales/appName_en-US.json')` (Electron app).
- render app with this locale and messages, like this:

```jsx
const LOCALE_PATH = './locale/appName_';
let loadLocaleMessages = (intlLocale) => {
        return require(LOCALE_PATH + intlLocale.toUpperCase() + '.json');
    },
    renderApp = () => {
        // ...

        try {
            intlMessages = loadLocaleMessages(intlLocale);
        } catch (e) {
            Log(`Locale "${intlLocale}" can\'t be loaded, using default (${DEFAULT_LOCALE}).`);
            intlLocale = DEFAULT_LOCALE;
            intlMessages = loadLocaleMessages(DEFAULT_LOCALE);
        }

        ReactDOM.render(
            <IntlProvider locale={intlLocale} messages={intlMessages}>
                <Main locale={intlLocale} />
            </IntlProvider>,
            appElement
        );
```

It re-renders just fine when new locale comes, but anyways get **error** like this when trying to load `ru-RU`: `[React Intl] Missing locale data for locale: "ru-RU". Using default locale: "en" as fallback.` and then `[React Intl] Missing message: "menu.devices" for locale: "en"`.

Any ideas? Seems like after new render I have no EN messages, nor RU messages.
Of course, I checked if messages are loaded finely, there's a correct JSON with all required messages.

**Comment by ericf** [comment]
Yes, React Intl requires locale data for it to perform its functions, this is separate from your translated messages. See: https://github.com/yahoo/react-intl/wiki#loading-locale-data
