### ISSUE TITLE
how to do ? eg:placeholder

### ISSUE THREAD

**Issue by mtsee** [yahoo/react-intl#532]
placeholder can not use FormattedMessage, how to do this?

**Comment by ericf** [comment]
Using the imperative API which can be accessed by wrapping a component with [`injectIntl()`](https://github.com/yahoo/react-intl/wiki/API#injection-api). [Here's an example](https://github.com/yahoo/react-intl/blob/5d25ea3ffb63aeab210e923e98304afb87c7b7c9/examples/translations/src/client/components/locales-menu.js).
