### ISSUE TITLE
<FormattedNumber> for german Currency and percentage

### ISSUE THREAD

**Issue by pheolink** [yahoo/react-intl#534]
Hi,

Is it possible to use de-DE instead of EUR. I want to have the following expected result. I want to have commas instead of decimal and decimal instead of comma and the euro sign should be placed at the end of the currency with the space in between the value and the currency symbol.

Expected Result:- 
Currency - 123.456,79 € 
Percentage - 12,3 %

**Comment by ericf** [comment]
Yes. Please see the Getting Started guide:
https://github.com/yahoo/react-intl/wiki#loading-locale-data
