### ISSUE TITLE
how get date back

### ISSUE THREAD

**Issue by ElfenLiedGH** [yahoo/react-intl#536]
`<Input type='text' value = {this.props.intl.formatDate(date, DATE_DDMMYYY_LOCALE)} />
`
then **User** change value from keyboard and how can i get this date with new Date(value)?

like moment(value, DATE_FORMAT).toDate(), i don't know **DATE_FORMAT**

**Comment by ericf** [comment]
This library doesn't do date parsing beyond what the build in `new Date()` constructor provides. If you're formatting the date, then you must have a value that can be passed to `new Date()`.
