### ISSUE TITLE
Rich text within FormattedMessage

### ISSUE THREAD

**Issue by amannn** [yahoo/react-intl#540]
What's the correct way to format a string like "Today is a **great** day."?

I see that formatting like this is possible if the bold part of the string should be a variable, but how can you do this if this isn't the case?

**Comment by ericf** [comment]
Today, you can use [`<FormattedHTMLMessage>`](https://github.com/yahoo/react-intl/wiki/Components#formattedhtmlmessage). Please see the other issues on this topic: #455, #504, and #513.
