### ISSUE TITLE
Override currency formatting

### ISSUE THREAD

**Issue by amannn** [yahoo/react-intl#541]
A `de` currency is currently formatted like `12,123.00 €`. Is it possible to change the position of the euro symbol like `€ 12,123.00`?

It's a quite common formatting in German speaking countries. However, [`Intl.NumberFormat`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) doesn't seem to provide such an option.

The [locale data of the polyfill](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/de.json#L2168) seems to specify this. However, overriding this doesn't seem to have any effect.

**Comment by ericf** [comment]
You'll need to use a more specific German locale where they common currency form is what you're looking for: [de-AT](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/de-AT/numbers.json#L110), [de-CH](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/de-CH/numbers.json#L110), or [de-LI](https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/de-LI/numbers.json#L110). (The `Intl` implementations in JS engines and the Intl polyfill source their data from [CLDR](http://cldr.unicode.org).)
