### ISSUE TITLE
Language doesn't change in Material UI Dialog

### ISSUE THREAD

**Issue by JakeLin1024** [yahoo/react-intl#542]
I noticed that Material UI Dialog was at the top layer same as the Root Element(weird???). When I changed locale, language changed in the main page, but when I opened the dialog, language remained the same. Is there something I need to add to the Dialog?

![Image of d](https://cloud.githubusercontent.com/assets/18651962/17019994/d7abaa2e-4f71-11e6-8fe7-eefa102c8c25.png)

**Comment by ericf** [comment]
You have two React roots. If the props you pass to `<IntlProvider>` are in the store, then you can wrap the contents of your modal with an `<IntlProvider>`. Or look to a modal solution that maintains the React component hierarchy.

See: https://github.com/yahoo/react-intl/issues/504#issuecomment-227495917

**Comment by JakeLin1024** [comment]
Thanks. And you mentioned unstable_renderSubtreeIntoContainer.
 It turned out it was a react bug. Updating to the latest version solves this issues.
