### ISSUE TITLE
Elements different from the span.

### ISSUE THREAD

**Issue by kirillkostko** [yahoo/react-intl#543]
Hello,

I'd like to add a possibility to choose other elements instead of default `span`. It's possible by adding a property `component` to all `<Formatted* />` components.

My case is format currency values inside SVG tree. It means that I have to use `text` or `tspan`.

Please let know what do you think. Thank you!

**Comment by langpavel** [comment]
You can do this by using callback instead of child

**Comment by ericf** [comment]
You can always create a custom component that wraps `<FormattedNumber>` and passes a function as the child as @langpavel points out.

**Comment by kirillkostko** [comment]
@langpavel @ericf thank you guys for the quick reply! However, I don't understand what do you mean. Could you please give me a small example? Thank you in advance!

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/blob/422866da63dbafdca16402f15ea76033b38b0bbf/test/unit/components/number.js#L141-L145

**Comment by kirillkostko** [comment]
@ericf Thank you!
