### ISSUE TITLE
How to set Id's for Formatted* components when you're rendering a list of components

### ISSUE THREAD

**Issue by iam-peekay** [yahoo/react-intl#544]
Hi. I have a list of todos that I'm rendering in my app. I want the text of the Todo's to be translated. If I try to use `FormattedMessage` such that the id is based on the to-do id:
```
              <FormattedMessage
                id={ `${todo.id}` }
                defaultMessage={ '{text}' }
                values={{ text }}
              />
```

I get a syntax error saying `React Intl] Messages must be statically evaluate-able for extraction.` I am not sure how to handle this case where I need to format the message in the todo component based on the single todo, and I need to set unique id's for each of these formatted messages.

Any help would be appreciated.

**Comment by ericf** [comment]
Where is the data from your list of todos coming from?

If it's dynamic data, then it probably doesn't make sense to try to have the Babel plugin extract. Instead you'd get the collection of todos from your database and you can provide the translations at runtime. If that's the case, then simply remove `defaultMessage` from here and passing in the collection of `messages` to `<IntlProvider>`.

**Comment by iam-peekay** [comment]
The data is pre-defined (not coming from database.)

**Comment by ericf** [comment]
In that case, it needs to be local to the file where it's being referenced. Babel can do some basic static evaluate of code, e.g. (`const foo = 2+2;` can evaluate the `foo` binding as having the numeric value `4`), but anything complex and dynamic it won't be able to resolve statically.

**Comment by ericf** [comment]
Closing this out… feel free to continue discussing, but at this point there's no actionable item.

**Comment by VenkyKicku** [comment]
const messagesObj = ({
  Title: {
    id: 'app.Title',
    defaultMessage: 'Tiltle',
  },
});

export default messagesObj;

<FormattedMessage
id={MessagesObj.Title.id}
 defaultMessage={MessagesObj.Title.defaultMessage}
 />

its giving me warining how to solve it

**Comment by harole** [comment]
@iam-peekay Have you done to the problem, would you mind share you method?
