### ISSUE TITLE
Add 'module' entry point for webpack 2 support

### ISSUE THREAD

**Issue by taion** [yahoo/react-intl#548]
It should just be a copy of `jsnext:main`, but named `module`. See e.g. https://github.com/reactjs/react-router/pull/3672.

webpack 2 prefers "module" instead of "jsnext:main" as the entry point for ES module builds.

Ideally at some point Rollup will move to "module" as well.

**Comment by ericf** [comment]
@taion I haven't had a chance to try out Webpack 2 yet. It would be great if you could open an PR to make this change and also if you event wanted to add an example to `examples/` which uses Webpack 2 to show people how, it would be much appreciated. I alway manually run through the example apps before doing a release to make sure they work correctly.
