### ISSUE TITLE
Please export all library propTypes

### ISSUE THREAD

**Issue by steida** [yahoo/react-intl#549]
https://github.com/yahoo/react-intl/blob/master/src/types.js
For example, I need messageDescriptorPropTypes.

Thank you.

**Comment by ericf** [comment]
I curious about the use case. Right now `intlShape` is the only public propTypes that are exposed. In the particular case of `messageDescriptorPropTypes`, it's fairly simple to redefine.

**Comment by steida** [comment]
That's what I did, but I would rather avoid reimplementation. You can close this issue, it's not critical of course :-)

**Comment by ericf** [comment]
Well I am interested in how you were using the prop types definition. Of all of the possible ones to expose from `types.js` this would be at the top of the list.

**Comment by steida** [comment]
Check Alert component, it takes message as a prop. https://github.com/este/este/blob/master/src/native/app/components/Alert.react.js#L39

**Comment by paulyoung** [comment]
I also would like to use `messageDescriptorPropTypes`.

**Comment by steida** [comment]
PropTyped are dead. Or at least, I don't need them.

**Comment by fikriauliya** [comment]
@steida Why is it dead?

**Comment by steida** [comment]
Because flowtype.

**Comment by kusmierz** [comment]
see flowtype/flow-typed#1280
