### ISSUE TITLE
Avoid duplicating id's

### ISSUE THREAD

**Issue by tyv** [yahoo/react-intl#550]
Imagine I have

```jsx
<FormattedMessage id="hello" defaultMessage="Hello">
```

and in another component

```jsx
const messages = defineMessages({
  placeholder: {
    id: 'hello',
    defaultMessage: 'Hello'
  }
})
// ...
<input placeholder={formatMessage(messages.placeholder)} />
```

in this case, how to avoid duplicating `id` or duplicating messages?
if it would be both `<FormattedMessage />` I can create `<Hello />` component, but how about this case?

**Comment by ericf** [comment]
There's a small example app [here](https://github.com/yahoo/react-intl/blob/master/examples/translations/scripts/translate.js#L13) which has a script that processes the messages extracted from `babel-plugin-react-intl` and will throw an error on duplicate ids. You could use something like that.

**Comment by tyv** [comment]
I am laready using, but in this case I will have twe equal strings with different id's what I wish to avoid.--Sent from Yandex.Mail for mobile28.07.2016, 20:11, "Eric Ferraiuolo" <notifications@github.com>:There's a small example app here which has a script that processes the messages extracted from babel-plugin-react-intl and will throw an error on duplicate ids. You could use something like that.

**Comment by ericf** [comment]
Okay, so does processing the extracted strings in the way that I linked to above work?

**Comment by tyv** [comment]
yes, but it would be id conflict, if I use it like that.. so dilemma is — I have to use different id's for same string

**Comment by tyv** [comment]
any ideas?

**Comment by kof** [comment]
@ericf why do you throw exception when 2 messages have identical id+defaultMessage? Why not just ignore the second one?

**Comment by ericf** [comment]
@kof that's up to your app's business logic whether you consider it an error or not.
