### ISSUE TITLE
FormattedMessage using an id?

### ISSUE THREAD

**Issue by Phyks** [yahoo/react-intl#551]
Hi,

In the message descriptor, there is an `id` field, which is to be filled. However, I am not sure I see real use case for this field.

My typical setup (as far as I understand how this library works) is to define my message descriptors in an external file, import it in my component JSX file and use `defineMessages` from this include.

Then, I have basically this in my JSX file:
```javascript
import { Component } from "react";
import { defineMessages, FormattedMessage } from "react-intl";
import messages from "./locales/Foobar";

defineMessages(messages);

export default class Foobar extends Component {
    render () {
        return (
            <div><FormattedMessage {...messages["app.Foobar.someID"]}/></div>
        );
    }
}
```

and in `locales/Foobar`:
```javascript
const messages = {
     "app.Foobar.someID": {
        id: "app.Foobar.someID",
        description: "Foobar description",
        defaultMessage: "Foobar"
    }
};
export default messages;
```

Why not letting letting the user pass an array of messages descriptors (instead of a map) and let `FormattedMessage` make use of the provided `id` field?

Thanks!

**Comment by ericf** [comment]
To `id` is so the messages can be provided via `<IntlProvider>` and looked up on the `context.intl` object.

**Comment by Phyks** [comment]
Ok, but then it is mostly a backend feature and is not meant to be used directly by the user?

Why not letting the user pass a message array (rather than a map) in `defineMessages` and return a map with id associated to message?

**Comment by ericf** [comment]
Looking an item up in an array would be O(n), compared to O(1) in a hash. The intention is that you're passing **translated** messages to `<IntlProvider>` therefore there's no need to pass a `description` for the translator and `defaultMessage` doesn't make sense. This is why it's a simple key/value pair from `id` to translated message string.

**Comment by Phyks** [comment]
Sure for the `<IntlProvider>`, but as far as I understood, `defineMessages` does not act on directly on the `<IntlProvider>`?

I mean, when we `defineMessages(someMessages)`, we have typically this structure:
```
const someMessages = {
     "anID": {
        id: "app.Foobar.someID",
        description: "Foobar description",
        defaultMessage: "Foobar"
    }
};
```

My point is that I do not understand why we need two (potentially) different IDs there (`anID` and `someMessages.anID.id == "app.Foobar.someID"`).

I'm sorry, I think I misunderstood something about the use of `defineMessages` because to me it would seems easier to do
```
const definedMessages = [
    {
        id: "app.Foobar.someID",
        description: "Foobar description",
        defaultMessage: "Foobar"
    }
];
const messagesHash = defineMessages(messages);
```

where `messagesHash` would be at the end of the above snippet
```
{
    "app.Foobar.someID": {
        id: "app.Foobar.someID",
        description: "Foobar description",
        defaultMessage: "Foobar"
    }
}
```

**Comment by ericf** [comment]
defineMessages is simply there for the Babel plugin to hook into. You can name the property whatever you want locally and it doesn't have to match the id. `foo: {id: 'some.long.namespace.foo'}`

**Comment by Phyks** [comment]
Ok. So the `id` is more for internal purpose and a user almost never access it?

I mean, `<FormatMessage>` and `formatMessage` calls expects a message argument, not an `id`.

**Comment by ericf** [comment]
`id` is meant to provide you a place to put in a message id that's constant between the message definition and your translation system/service. Locally you may want to use something shorter.
