### ISSUE TITLE
Letting FormattedMessage use a rendering function to apply after translation

### ISSUE THREAD

**Issue by Phyks** [yahoo/react-intl#552]
Hi,

Sometimes there are duplicate translations in an app, typically capitalized and uncapitalized. Then, it is useful to be able to apply a function to the resulting translation.

It seems to be feasible using the API:
```
const t = formatMessage(someMessage).capitalize()
```
(assuming you have a `String.capitalize` available) and then outputting `t` in your render.

But it does not seem to be feasible with the `FormattedMessage` structure. This component could take an extra prop with a function to apply on the resulting string for instance.

What do you think?

Thanks

**Comment by ericf** [comment]
I'm not totally sure I follow, but there are many ways for you to handle this. The simplest would be:

```js
const CapitalizedMessage = (props) => (
  <span style={{textTransform: 'capitalize'}}>
    <FormattedMessage {...props}/>
  </span>
);
```

**Comment by Phyks** [comment]
Indeed, sorry my example was a bad one as it is doable easily in CSS and enclosing it in a style `span` actually is a really easy way to do it.

By `capitalize`, I was meaning "setting the first letter to uppercase" whereas the `text-transform: capitalize` transforms the first letter of any word to uppercase.

This could be actually any formatting function which is locale-independent and cannot necessarily be reproduced in plain CSS.

**Comment by ericf** [comment]
The CSS `text-transform: capitalize` does take into account issues with different locales. I don't really understand what you're after. But you can always use the function-as-child pattern to pass a function to `<FormattedMesage>`.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#capitalize_(General)

**Comment by Phyks** [comment]
Hmm, imagine you have strings like "Lorem ipsum", "lorem ipsum", "LOREM IPSUM", and "Lorem Ipsum" in your app. I think the best way to store them in your app is to store only one of them (say "lorem ipsum") and derive the others from this one.

Both "LOREM IPSUM" and "Lorem Ipsum" can be achieved by CSS `text-transform` (resp. `uppercase` and `capitalize`), as discussed before.

But "Lorem ipsum" has only the first letter capitalized, and cannot be done in plain CSS (as far as I know). For this typical case, wrapping `FormatMessage` in another component and styling it won't work.

Still, I was not aware of the function-as-child pattern for `FormatMessage` and I think that would do the trick indeed.

Thanks

**Comment by ericf** [comment]
Ah, sorry, yeah. If you were styling with CSS classes you could do:

```css
.capitalized-message::first-letter {
  text-transform: capitalize;
}
```

**Comment by Phyks** [comment]
Indeed. Thanks for the CSS tip! :)

**Comment by kud** [comment]
https://github.com/yahoo/react-intl/issues/552#issuecomment-236041143

This is interesting but I'd like to do it in javascript, not in css, because I'd like that my source is already good and not handling by css. But maybe it's too much for nothing.

**Comment by kud** [comment]
I'm probably sure I miss lots of things of the power of react-intl but for the moment, this suits me:


```javascript
import _ from "lodash"
import React from "react"
import {
  FormattedMessage as RiFormattedMessage,
  injectIntl
} from "react-intl"

class FormattedMessage extends React.Component {
  static defaultProps = {
    mode: ''
  }

  render() {
    if(this.props.mode === 'capitalize') {
      return <span>{_.capitalize(this.props.intl.messages[this.props.id])}</span>
    }

    return (
      <RiFormattedMessage {...this.props} />
    )
  }
}

export default injectIntl(FormattedMessage)
```

Yes, I don't support yet the placeholder.
