### ISSUE TITLE
Defining messages for plural form?

### ISSUE THREAD

**Issue by Phyks** [yahoo/react-intl#553]
Hi,

The [doc on `<FormattedPlural>`](https://github.com/yahoo/react-intl/wiki/Components#formattedplural) is quite succinct and there are no examples provided with `<FormattedPlural>` and handling multiple locales.

From the example
```javascript
<FormattedPlural
    value={10}
    one='message'
    other='messages'
/>
```
it seems that one has to pass explicit values to each prop. Then, how to handle multiple localizations as is done through `formatMessage` and `defineMessage` and passing `messages` prop to main React component?

Thanks

**Comment by glosee** [comment]
I was wondering the exact same thing.

**Comment by glosee** [comment]
Probably we could wrap the component with `injectIntl` and then call `this.props.formatMessage()` to get the localized version of that string. I'm going to try that now.

**Comment by glosee** [comment]
Yep this works:

```
// en.js
{
  "bananas.one": "banana",
  "bananas.many": "bananas"
}

// fr.js
{
  "bananas.one": "banane",
  "bananas.many": "bananes"
}

// SomeComponent.jsx
import { injectIntl, intlShape, FormattedPlural } from 'react-intl';

const MyComponent = props => {
  const { formatMessage } = this.props.intl;
  <div>
    <FormattedPlural one={formatMessage({ id: 'messages.one' })} other={formatMessage({ id: 'messages.many' }) />
  </div>
);

MyComponent.propTypes = {
  intl: intlShape.isRequired,
};

export default injectIntl(MyComponent);
```

**Comment by ericf** [comment]
Yeah it's intended to be used for apps that **only** need to support one language. It should probably be removed because it confuses people. You'll likely want to use `<FormattedMessage>` with a plural argument: http://formatjs.io/guides/message-syntax/#plural-format

**Comment by Phyks** [comment]
Something like
```
const messages = {
    "app.common.album": "{itemCount, plural, one {Album} other {Albums}}"
}
```
works great! Thanks

Indeed,the `FormattedPlural` thing is confusing. Maybe just adding a pluralization example under `FormattedMessage` doc in the wiki would help a lot.


One last question about plural handling: is there a way to force it to use a specific pluralization?

I mean, with the above `messages`, I can `<FormatMessage {...messages["app.common.album"]} values={{itemCount: 42}}/>` but it does not seem to be possible to do `<FormatMessage {...messages["app.common.album"]} values={{itemCount: "other"}}/>` (actually this one works, but replacing `other` by `one` does not work, I guess it just selects `other` whenever it does not match with anything expected).

Thanks

**Comment by glosee** [comment]
Oh wow that is a much better solution. Thanks @ericf

**Comment by ericf** [comment]
Closing this as the example in the README has been updated to use `<FormattedMessage>`.

**Comment by Phyks** [comment]
Thanks!

**Comment by FreaKzero** [comment]
Im using the "Nested JSON" Export from Phraseapp and have written an own little PluralComponent for this - maybe also helpful for others.

`
import React, {PropTypes} from 'react';
import {injectIntl, FormattedPlural, formatMessage} from 'react-intl';

const Component = ({id, value, intl}) => (
    <span>
      <FormattedPlural 
        one={intl.messages[id].one} 
        other={intl.messages[id].other} 
        zero={intl.messages[id].zero} 
        value={value} 
      />
    </span>
);

Component.propTypes = {
    value: PropTypes.number.isRequired,
    id: PropTypes.any.isRequired
};

export default injectIntl(Component);`
