### ISSUE TITLE
Exporting Translations + Webpack Dev Mode

### ISSUE THREAD

**Issue by maniax89** [yahoo/react-intl#554]
Just wanted to start by saying this is a great tool and after a bit of learning I have been able to integrate it into my project with almost everything I need.

I have been stuck on an issue that may or may not be a desire for other developers - I tried looking through the issues on here and didn't find exactly what I am looking for yet. Basically I have a webpack configuration that has a custom plugin (https://github.com/maniax89/react-intl-aggregate-webpack-plugin) that takes the output from https://github.com/yahoo/babel-plugin-react-intl and puts it into one file. I also have a second webpack plugin (https://github.com/maniax89/react-intl-flatten-webpack-plugin) that runs through all the aggregate files and converts them into a flattened structure as required by react-intl v2

The issue I am having is that I don't really understand how I can generate these files with webpack and include them in my application at the same time. Either:

1. I write the flattened translation file to disk with webpack and webpack sees it as a new/changed file in dev mode and goes into an infinite loop or
2. I load the file too late and I cannot `import` it because it hasn't been generated yet.

I have resorted to just doing a asynchronous `fetch` that falls back to the default locale (english) - but that doesn't reload the new file anytime I make a change in development...I was hoping I could find a better way to statically include it. What I want to do is:

- have my messages defined in a file:
```javascript
import {defineMessages} from 'react-intl';

const messages = defineMessages({
  copyright :{
    id: 'footer.copyright',
    defaultMessage: 'copyright {year}',
    description: 'the copyright displayed at the bottom of the page'
  }
});

export default messages;
```
- use those messages in a file:
```javascript
import messages from './messages.js';
import React from 'react';
import {injectIntl, intlShape} from 'react-intl';

class Footer extends React.Component {
  render() {
    const intl = this.props.intl;
    const t = intl.formatMessage;
    return (
        <div>
          {t(messages.copyright, {year: '2016'})}
        </div>
    );
  }
}

Footer.propTypes = {
  intl: intlShape.isRequired
};

export default injectIntl(Footer);
```

- use the IntlProvider with messages included that were generated by webpack and part of the assets
```javascript
import { IntlProvider } from 'react-intl';
import en_messages from '../public/i18n/en.json';
import es_messages from '../public/i18n/es.json';
...
let supportedLocales = {
  "en" : en_messages,
  "es" : es_messages
}
let selectedLocale = "en";

<IntlProvider locale={selectedLocale} messages={supportedLocales[selectedLocale]}>
  <App />
</IntlProvider>
```

Based on what I have gathered with my knowledge of webpack and looking at other projects, people seem to be doing the generation of the files outside of webpack and then loading it up - which is fine for production but cumbersome for the hot-reloading feature of webpack in development. 

Has anyone had experience using webpack to generate these flattened translation files and then utilize them in both development and production environments?

**Comment by ericf** [comment]
You could just avoid extracting the default messages during development and it'll automatically fallback to the one defined in the source. There was also a change a bit ago [to **not** warn when the `locale` and `defaultLocale` are the same in development](https://github.com/yahoo/react-intl/blob/795c3cfa6d7e0636b5ae3b1b416b34610cf7e371/src/format.js#L224-L236); this way your console won't be littered up with noise when taking this approach.

Then in your `.babelrc`, you could specify to only extract translations during the `BABEL_ENV` or `NODE_ENV` is `production`:

```json
{
  "presets": ["es2015"],
  "env": {
    "production": {
      "plugins": ["react-intl"]
    }
  }
}
```

**Comment by maniax89** [comment]
So you think the best way to load up translations in index.js then is something like this?:

```javascript 
fetch('/i18n/en.json').then(function(response) {
  return response.ok ? response.json() : {};
}).then(function(messages){
  render((
    <IntlProvider
      locale="en"
      messages={messages}>
      <App />
    </IntProvider>
  ), document.getElementById('app'));
});
```

This makes it fall back to `{}` when translation files don't exist (in dev) but uses the files when they exist (in prod). The alternative would be to move the generation of those translation files outside of webpack like other projects I have seen so that I can statically import them, not sure what other drawbacks I might see with this approach I have so far though.

Setting the messages to empty seems to work well enough though (and it doesn't litter the console with errors). Thanks for your feedback.

**Comment by ericf** [comment]
There are many different approaches to loading the translations files at runtime. You'll have to figure out the best way for your app.
