### ISSUE TITLE
Differences between polyfill and native Intl cause problems in isomorphic apps

### ISSUE THREAD

**Issue by gpbl** [yahoo/react-intl#57]
I'm working on an isomorphic app and I get different outputs for a component rendered server-side and then mounted on the browser, i.e. Chrome. This causes React to warn about invalid checksum when rendering on browser and invalidate the server-rendering :(

In particular, the EUR currency format is different in Chrome (€100) and in node (€100.00). This does not happen in Safari since it also uses the same node polyfill and it outputs €100.00 as well.

**Comment by gpbl** [comment]
A temporary solution is to not use the currency format, but I wonder if this happens for other formats as well. How can we ensure that the browsers implements the same Intl formats as the node polyfill?

As alternative, I'd use the polyfill for Intl-enabled browser as well – but being a global object Chrome won't let me overwrite it. Maybe enabling the polyfill to use an alternative name to `Intl`?

**Comment by caridy** [comment]
@gpbl I'm not so sure what the checksum error is, can you elaborate more?

As for the errors with the polyfill, feel free to open an issue for the polyfill itself: https://github.com/andyearnshaw/Intl.js/issues/new, a PR will be welcome there since we are short on people working on that project.

As for patching Intl in Chrome, you just need to load the polyfill and add this line into your program: 

```
Intl = IntlPolyfill;
```

that will guarantee that you always use the polyfill, of course, you will have to pay the penalty of always using the polyfill :)

**Comment by gpbl** [comment]
I meant in an isomorphic app, where React uses a checksum to render the components client-side over a server-rendered HTML. If the content is different, the app loses the isomorphic benefits.

I can `Intl = IntlPolyfill;`, good idea. I'll try to contribute to Intl.js as well :-)

Thanks for the answer.

**Comment by caridy** [comment]
@ericf did you know about the checksum?

**Comment by gpbl** [comment]
I mean this warning from React:

> React attempted to use reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

If node.js (polyfill) renders `100.00` but chrome (no polyfils) render `100.0000` the checksum is "invalid" and react has to render the thing again. If they are the same, react will just attach event handlers.

**Comment by ericf** [comment]
@gpbl so Chrome's rendering of `$100` is actually the odd ball out here, the other browsers render it as `$100.00` like the Polyfill. I'd file a bug with Chrome on this one.

**Comment by gpbl** [comment]
@ericf thanks, you are right: it is a chrome issue (it is just for the EUR btw). I'll add a test for server rendering.

**Comment by x1a0** [comment]
I think i just had same problem in my app. For me it's the problem of `FormattedDate` component. Chrome native `Intl` and `locale-data` output differently from nodejs on server side.

I guess the solution is to polyfill on client side anyway? (on server side i am using `node 0.12.5` which only has english built-in so it loads polyfill for other locales I need).

**Comment by caridy** [comment]
@x1a0 what version of the polyfill are you using? rc4 should solve most of those problems, if not, feel free to open an issue in the polyfill repo

**Comment by rtymchyk** [comment]
The problem is all browsers are not up to date with the latest CLDR and they all implement the spec differently. This means if you use the polyfill on the server, you can expect a non-safari client to render and function differently.
