### ISSUE TITLE
how to clear cache of plugin? 

### ISSUE THREAD

**Issue by e-gnat** [yahoo/react-intl#574]
Hi,
While testing with Mocha and Enzyme I get multiple errors from Intl like this: 
[React Intl] Error formatting message: "REGULAR" for locale: "en", using default message as fallback.
TypeError: A message must be provided as a String or AST.

As far as I understand it happens after you change id of existing message. In debugging I see that in function createFormatCache it gets wrong id from function getCacheId(args). For some reason it returns whole object like this: 

cacheId = "[[{"defaultMessage":"Regular numbers"},{"description":"Regular numbers"},{"id":"REGULAR"}],"en",[]]"

 So after it it can't create format and returns undefined

But it happens only if there was changes in a local machine in a file with messages.

So my question is: What I do wrong? or How I can clean cache of plugin npm cache clear is not help

**Comment by ericf** [comment]
> As far as I understand it happens after you change id of existing message.

Can you explain this more? I don't really understand what you're saying.

**Comment by ericf** [comment]
Closing this. Feel free to open when more information has been provided to make this actionable.
