### ISSUE TITLE
Usage of invariant module

### ISSUE THREAD

**Issue by Swaagie** [yahoo/react-intl#579]
Nitpicking here, but why is `react-intl` depending on a fork of the `invariant` module (https://www.npmjs.com/package/invariant), while React uses https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/__forks__/invariant.js

This will inevitably lead to including the same script twice, since the hash will be different due to the minor difference in comments. I'm aware most builders provide features to prevent this from happening, but I don't expect everyone to scrutinize their bundle output.

**Comment by ericf** [comment]
I'm not worried about this as the module is so small.
