### ISSUE TITLE
How to implement shouldComponentUpdate when using ReactIntl

### ISSUE THREAD

**Issue by pselden** [yahoo/react-intl#58]
I'm not clear on how a component that uses ReactIntl.Mixin (or any of the new components) can implement shoulComponentUpdate. Am I able to get at the messages/locale/formats properties from inside a subcomponent of my app so that when I switch languages I can re-render the components that use these? When using PureRenderMixin it just never re-renders the components that use it at all.

Is this just a fundamental problem when passing down the locale props down with context or is there a way to solve it?

**Comment by caridy** [comment]
TL;DR: do not use the context, be explicit thru props:
check this for more details: https://github.com/yahoo/react-intl/issues/39#issuecomment-69790732

**Comment by slorber** [comment]
@caridy this is not manageable for a very large app :(

**Comment by ericf** [comment]
Related to this, we should also implement `shouldComponentUpdate()` _within_ each of the React Intl components.

**Comment by ericf** [comment]
See: #162
