### ISSUE TITLE
Improve examples scripts with watch

### ISSUE THREAD

**Issue by jiayihu** [yahoo/react-intl#582]
It's tedious to run `npm run build` every time I make a change to test the examples, so I suggest adding a `watch` script with [watchify](https://www.npmjs.com/package/watchify).
For instance this work perfectly in *hello-world* example:
```
"build": "../../node_modules/.bin/mkdirp build && ../../node_modules/.bin/browserify index.js -d -t babelify -t browserify-shim > build/bundle.js",
"watch": "../../node_modules/.bin/mkdirp build && ../../node_modules/.bin/watchify index.js -d -t babelify -t browserify-shim -o build/bundle.js -v",
```

**Comment by ericf** [comment]
Feel free to raise a PR for this.
