### ISSUE TITLE
Browserify/requiring react-intl in IE8 breaks

### ISSUE THREAD

**Issue by wardsng** [yahoo/react-intl#59]
Awesome library! I've been using browserify and requiring modules as needed, which was working well until I decided to mess around in IE8. It seems that the react-intl module (and its integrations: intl-relativeformat, intl-messageformat, intl-messageformat-parser, and intl-format-cache) make use of default (e.g. index.js: require('./lib/main'/).default), a keyword in IE. Would it be possible to change instances of key-value access via .default to ['default']?

In the meantime I've moved all my react dependencies into script tags in the HTML page, along with react-intl. It'd be nice to be able to manage them all via browserify again though!

**Comment by caridy** [comment]
related to https://github.com/yahoo/intl-messageformat/issues/90, we will fix it soon.

**Comment by mderazon** [comment]
Hey, not exactly related to this issue, but how do you conditionally load the polyfill with browserify ?

**Comment by ericf** [comment]
I've upgraded the underlying packages that were accessing `default` properties by dot-notation to use dereferencing. These issues should be fixed in the next release. Since [React requires es5-shim/sham](http://facebook.github.io/react/docs/working-with-the-browser.html#polyfills-needed-to-support-older-browsers) this package also assumes the APIs provided by the shim+sham are polyfilled in the runtime.

**Comment by roderickhsiao** [comment]
@ericf @caridy would you mind to check the build? the ``rc-3`` build for this fix is failing.

Thanks!

**Comment by ericf** [comment]
@roderickhsiao can you provide some more details? Do you have an error and stack trace?

**Comment by roderickhsiao** [comment]
oh sorry, I mean the travis CI 
https://travis-ci.org/yahoo/react-intl

**Comment by ericf** [comment]
rc-3 is on npm, it looks like the tests are failing because Sauce Labs is being flaky. I restarted them and will investigate more in the morning. There currently aren't any tests for the Browserify/Webpack bundling, but that would be a great thing to add if anyone was feeling up for it :wink:

**Comment by roderickhsiao** [comment]
Thanks @ericf
