### ISSUE TITLE
FormattedMessage by "id"

### ISSUE THREAD

**Issue by Odol** [yahoo/react-intl#598]
it's possible work with this format?:

`<FormattedMessage
                    id={'any.options.opOne'}
                    description="spanel selection reference text"
                    defaultMessage={'algo.test'}
                    values={{
                        name: "hola"
                    }}
                    />`

example of "en.json" 
I tried this but it does not work

`{
 any: {
   options: {
      opOne: "test"
    }
  }
}`

only works if you use this form 
I do not think a good way!

`{
 "any.options.opOne": "test"
}`

**Comment by ericf** [comment]
Yes, it only works with a flat message map. If you want to structure your messages as nested objects in source, then just flatten them before passing them into `<IntlProvider>`: https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object

**Comment by Odol** [comment]
Perfect thanks for your fast response!
