### ISSUE TITLE
Support React Native easily

### ISSUE THREAD

**Issue by steida** [yahoo/react-intl#600]
The only problem with usage in React Native is span inside components. React Native needs Text. We can fix it easily.  Add textElement into intlConfigPropTypes.

``` jsx
// In React Native
<IntlProvider
  textElement={Text}
  // ...
/>
```

Then all components can use textElement from the context if available.

**Comment by jrylan** [comment]
100% agree with this approach.

**Comment by ericf** [comment]
Sure, want to PR this? also s/Element/Component/

**Comment by steida** [comment]
I would rather not, but if you merge my PR quickly, it can.

**Comment by steida** [comment]
Sorry for my English. I will do it if you promise me PR will be reviewed in week at least ;)

**Comment by ericf** [comment]
The other thing this approach can help with is using the `<Formatted*>` components within SVGs. Since a nested `<IntlProvider>` inherits from its parent, it would be a cheap easy way to solve the issue of `<span>`s not being allowed in SVGs.

**Comment by steida** [comment]
It's safe to write only `<IntlProvider textElement={Foo} />`?

**Comment by steida** [comment]
There are two another issues for universal react-intl:
- All components must accept `style` prop to allow inline styles. Why? That's because style inheritance is not safe nor explicit, so style prop is the must.
- All components must provide setNativeProps method http://facebook.github.io/react-native/releases/0.31/docs/direct-manipulation.html#setnativeprops-shouldcomponentupdate React Native can be runtime detected very cheaply. It's the must http://facebook.github.io/react-native/releases/0.31/docs/direct-manipulation.html#setnativeprops-shouldcomponentupdate
https://github.com/este/este/issues/1046

**Comment by steida** [comment]
Hmm, I am not sure about `style` prop. React Native inherits text, and browser as well. Hmm.

**Comment by ericf** [comment]
> That's because style inheritance is not safe nor explicit, so style prop is the must.

This sort of sucks as it breaks the abstraction.

> All components must provide setNativeProps method

Can it just be a function that forwards the call onto the `<Text>` child?

**Comment by steida** [comment]
Which abstraction it breaks?
Yes, it's just a forward https://github.com/este/este/blob/master/src/native/app/components/Text.react.js#L34

**Comment by steida** [comment]
As for style inheritance. I think I was wrong. A browser can inherit them and the Text component in React Native inherits as well. http://facebook.github.io/react-native/releases/0.31/docs/text.html#nested-text

I had some issues with that, but I need to investigate it more.

**Comment by ericf** [comment]
> Which abstraction it breaks?

Sebastian has a good talk on this: https://www.youtube.com/watch?v=Zemce4Y1Y-A

> A browser can inherit them and the Text component in React Native inherits as well.

Okay that's much better and matches what I remember about React Native. I don't want to introduce a `style` prop on all of the React Intl components.

**Comment by steida** [comment]
I see, still, the text styles seem to be universal among React and React native. But you are right, it could be abstracted. Have you read this awesome article?

> Notice how none of the elements have a className or style prop. Using className or style props at this level could be considered a code smell.

http://jxnblk.com/writing/posts/patterns-for-style-composition-in-react/ 

I think we can reconsider style attribute later, if we will need it.

**Comment by steida** [comment]
Btw, I asked Sebastian Markbåge about that and he promised to respond after a weekend vacation.

**Comment by AlessandroCorradini** [comment]
@ericf You could detect if is react-native or not like so:
https://github.com/erikras/redux-form/blob/master/src/isReactNative.js

if is react-native, set the "defaultComponent" to <text>, else to <span>.

**Comment by jrylan** [comment]
@AlessandroCorradini that's a decent approach, but we still end up with the issue on needing to specify the use of <text> within an SVG element. <span> does not work within an SVG.

**Comment by AlessandroCorradini** [comment]
`<Text>` is the react-native component, it doesn't need a SVG element

**Comment by jrylan** [comment]
@AlessandroCorradini `<text>` (lowercase t) is for SVG:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text

`<Text>` (uppercase T) is for react-native.

**Comment by AlessandroCorradini** [comment]
It's my mistake sorry :D I was in a hurry to write. I meant Text component.

**Comment by AlessandroCorradini** [comment]
I thought..my approach need dependency with `react-native` and this isn't good for react (not react-native) users. 
Instead, you could add a component prop (not required). If it is provided, render this component like so, else render a regular `span`:

`<Component {...this.props}>{this.props.value}</Component> `
I don't know the exact prop than contains the translated value, `this.props.value` is "placeholder"

**Comment by jrylan** [comment]
@AlessandroCorradini I don't believe the prop idea is a good approach, because if you intend to create universal apps (using something like react-native-web), you would need to specify the prop every single time you used a react-intl component. It's really best to define the text element to use at the IntlProvider level.

The approach that @steida outlined in the first post is the perfect solution, and can easily be adjusted to accommodate SVGs as well, you would just wrap an SVG in another instance of IntlProvider, with textElement='text' or something along those lines.

**Comment by AlessandroCorradini** [comment]
I'm agree with you.

**Comment by steida** [comment]
@AlessandroCorradini Remember that browser code can import anything from Native and vice versa. And no, `require` isn't a solution because dependencies must be statically analyzable.

**Comment by mschipperheyn** [comment]
+1 @steida

**Comment by mschipperheyn** [comment]
To augment my +1: it's preferable to NOT detect RN vs ReactJS and automatically decide on the tag to use. RN Docs state that Text formatting is not passed through the tree like in HTML/css and recommends using a customized Text component to guarantee your fonts etc are correct. So, it might be preferable to create AText component that renders the Text with your font preferences, in which case you want AText to be the rendering component for react-intl.

**Comment by mschipperheyn** [comment]
Any ETA on this one? Is it on the radar or one of those "maybe, if we find some spare time,  but probably not"

**Comment by antoinerousseau** [comment]
You can already use it very easily in React Native, as explained in https://github.com/yahoo/react-intl/issues/119#issuecomment-216093163

**Comment by ericf** [comment]
> Any ETA on this one? Is it on the radar or one of those "maybe, if we find some spare time, but probably not"

@mschipperheyn, @steida said he could do a PR for it but I'm not sure if he's still planning to. I'd be happy to review one.

**Comment by steida** [comment]
@ericf No time for that, sorry :(

**Comment by antoinerousseau** [comment]
I'll see what I can do based on @steida's proposal :)

**Comment by brentvatne** [comment]
@antoinerousseau - any update?

**Comment by steida** [comment]
@brentvatne I just reimplemented common components in Este. Not ideal, but it works. https://github.com/este/este/blob/master/src/native/app/components/formatted.js

**Comment by antoinerousseau** [comment]
didn't have the time to work on a PR, just made my own HoCs
see `Formatted*.js` files in https://github.com/antoinerousseau/tribeez/tree/master/src/mobile/components

**Comment by brentvatne** [comment]
Long-term, this might be a solution: https://github.com/lelandrichardson/react-primitives

It aims to provide interop between common primitives, regardless of platform

**Comment by ericf** [comment]
@brentvatne React Fiber should allow a component's `render()` method to return a string, not sure how React Native will handle this, but it would be ideal for React Intl to use.

**Comment by mschipperheyn** [comment]
I wonder why we're veering of into conceptual idea territory when the initial post in this thread offers a perfect solution.

**Comment by ericf** [comment]
@mschipperheyn if you're eager to get the short-term solution in, would you mind opening a PR for it?

**Comment by mschipperheyn** [comment]
Hi @ericf , I don't have a lot of time but I'll give it a go and see where I end up

**Comment by mschipperheyn** [comment]
Ok, have a look and tell me what you think: https://github.com/mschipperheyn/react-intl

**Comment by ericf** [comment]
@mschipperheyn can you open a PR, even if it's a WIP one?

**Comment by mschipperheyn** [comment]
https://github.com/yahoo/react-intl/pull/738

**Comment by mschipperheyn** [comment]
Can someone help me test this? Should I deploy as tmp on npm to facilitate?

**Comment by mschipperheyn** [comment]
I haven't had the time to test this in RN yet and write specific tests for it yet, (I prob will have time over the holidays) but since the changes make the react-intl more generically applicable (not depending on span), without requiring code changes, would it be better if I remove the React Native specific documentation updates, so it can be merged and as such can receive some testing in the wild for RN?

**Comment by mschipperheyn** [comment]
Ok, so I removed the react-native references from the pull request. My hope is that this makes react-intl usable in React-Native without advertising as such and hopefully generate some useful input from testing in the wild. Also, I hope this will make this merge request acceptable to be applied now instead of later. 

Basically, the pull request is now "just" a change that eliminates the dependency on 'span' and makes the tag used to encompass the text configurable by specifying a `textComponent` attribute on the provider tag which defaults to 'span' but can also be set as textComponent={Text}.

**Comment by mschipperheyn** [comment]
@ericf can you give me feedback, please? Would love to see this implemented

**Comment by ericf** [comment]
This is now in `react-intl@2.2.0` 🎉

**Comment by ericf** [comment]
I added a note about `<IntlProvider textComponent>` on the Wiki:
https://github.com/yahoo/react-intl/wiki/Components#intlprovider

It would be great if someone wanted to add more comprehensive docs to the Wiki about using with React Native and even including an example app in the repo at `/examples` ❤️

**Comment by mschipperheyn** [comment]
I already have this ready. I just removed it from the deploy to expedite its release. I will add some stuff

**Comment by oun** [comment]
Hi. I got warning "Failed prop type: invalid prop textComponent supplied to IntlProvider, expected a ReactNode"

**Comment by steida** [comment]
As a creator of this issue, I changed my mind now. Now I think injectIntl should be used everywhere. It's nice with flowtype checking and auto-complete and definitely less verbose. <FormatWhatever seems to be the unnecessary abstraction for me. Feel free to correct me.

**Comment by ericf** [comment]
> <FormatWhatever seems to be the unnecessary abstraction for me. Feel free to correct me.

@steida React Intl's components provide an optimization for re-renders, and a component like `<FormattedRelative>` does auto-ticking, and `<FormattedMessage>` supports rich-text formatting — and this feature is about to be dramatically improved: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by RobertSheaO** [comment]
For me, I worked around the issue by calling the `formatMessage` function which returns just the string, no html tags like `FormattedMessage` does. Here's an example:

```
// Add intl to contextTypes, so it can be access with this.intl
MyComponentName.contextTypes = {
  intl: PropTypes.object.isRequired,
};

// Inside my compontent
class MyComponentName extends React.PureComponent {
  render() {
    <Text>{ this.context.intl.formatMessage({ ...messages.home }) }</Text>
  }
}
```

The object passed into `formatMessage` is the same that you would pass into `FormattedMessage`

`<FormattedMessage {...messages.home } />`

**Comment by steida** [comment]
> @steida React Intl's components provide an optimization for re-renders, and a component like <FormattedRelative> does auto-ticking, and <FormattedMessage> supports rich-text formatting — and this feature is about to be dramatically improved: #513 (comment)

I see your points, still. An optimization for re-renders is nice, but it's task for my view component I suppose. Yep, FormattedRelative does sense. FormattedMessage will not work for React Native I guess, feel free to correct me. 

The reason why I prefer (maybe I am wrong) intl is flow typing. I would love to have typed messages.
I will show the code soon.

**Comment by 39otrebla** [comment]
It seems `FormattedMessage` does not support other react-native components as values. For example, the following code produces only `Hello`, everything after the first `{` gets lost:

```javascript
const messages = {
  "HelloAll": "Hello{all}!"
};

[...]

const allText = <Text>, world</Text>;

[...]

render() {
  return <FormattedMessage id="HelloAll" values={{ all: allText }} />;
}
```

It's quite annoying since we have tons of custom `Text` components to highlight text around the app. 

Does anyone know if there's another way to achieve this in react-native?

**EDIT**
`intl.formatMessage()` doesn't work either, it would print: `Hello[object Object]!`.

**Comment by longlho** [comment]
@39otrebla can u create a separate issue for tracking? This sounds like a bug.

**Comment by 39otrebla** [comment]
I'm not sure this is a bug, `react-intl` is not explicitly developed for react-native.. isn't it? Indeed, it seems that `FormattedMessage` doesn't recognize native tags because they are objects rather than strings, as well as `formatMessage()` (indeed, the latter returns `Hello[object Object]!` as native tags most likely do not implement `toString()`).

It sounds more like a feature request to me. Let me know.

**Comment by longlho** [comment]
We do support passing arbitrary objects in (there's no explicit check if it's a React component or anything) so this is a bug to me.

Are you using latest react-intl version btw?

**Comment by antoinerousseau** [comment]
@39otrebla RN is supported: https://github.com/formatjs/react-intl/blob/master/docs/Components.md#using-react-intl-with-react-native

So it looks like a bug (if you are using a recent version of `react-intl`), because it should work:
https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting

**Comment by 39otrebla** [comment]
@antoinerousseau @longlho #1430 . Thanks.
