### ISSUE TITLE
Failed to parse SourceMap (xxx/main.js.map)

### ISSUE THREAD

**Issue by Bezdekm** [yahoo/react-intl#604]
Hello,

when I want to run application with react-int I got error message in console - Failed to parse SourceMap: http://localhost:3000/main.js.map.

Can you help me please? 

Thanks, Martin

**Comment by ericf** [comment]
This would be very hard to debug unless you create the simplest possible, runnable, open source, example that shows the issue. If you do so, then feel free to reopen the issue.
