### ISSUE TITLE
Overriding/augmenting named format properties

### ISSUE THREAD

**Issue by pselden** [yahoo/react-intl#61]
Currently named formats are an either/or proposition -- if you use a named format you cannot pass additional format arguments to it to either add new format args or override named ones. It would be useful to be able to do this in cases where you know some of the specifiers you want at build time but others at run time.

Example:

```js
/*
{
  "formats": {
    "number": {
      "currency": {
        "style": "currency",
        "minimumFractionDigits": 2
      }
    }
  }
}
*/
var price = { value: 42000, currency: 'USD' } ; // assume this comes from some api and is not hard coded
  
return <IntlNumber format="currency" currency={price.currency}>{price.value}</IntlNumber>;
```

This will always render it using the current locale's currency specifier because the currency code is ignored.

**Comment by ericf** [comment]
Makes sense. Is your feeling that `format` prop and its associated named format config values have lower precedence than the other prop values if there's conflicts?

**Comment by pselden** [comment]
@ericf Yes, I would think so.

**Comment by caridy** [comment]
:+1: my only concern will be the perf implications of this merging operation, but I guess we can optimize that part and we can also short-circuit it in case of no argument provided.
