### ISSUE TITLE
[minimumFractionDigits] doesn't work

### ISSUE THREAD

**Issue by wzup** [yahoo/react-intl#614]
`minimumFractionDigits` option doesn't work.

config:
```
const formatter = new Intl.NumberFormat('en-US', {
    minimumFractionDigits: 2,
});
```

Output:
```
{formatter.format(1350.70 * .85)}
1,148.095 // three digits!
```

Why does it give three digits instead of two?

**Comment by ericf** [comment]
It's working correctly.

You've configured the formatter to have a minimum of two fractional digits, 3 >= 2. If you'd like to set a **maximum** number of fractional digits, then also set `maximumFractionalDigits`.
