### ISSUE TITLE
Node Intl only supports english by default

### ISSUE THREAD

**Issue by pbazydlo** [yahoo/react-intl#615]
By default Node Intl package only supports english which can result in different results when server-side rendering react page.

Running `Intl.NumberFormat('fr-CA').format(2151)` in browser will return `2 151` whereas in Node the result will be `2,151` (fallback to english format).

This cannot be fixed in this package, but could be included in documentation so that it's easier to find when somebody runs into related issues.

**Comment by ericf** [comment]
It's in the docs, at the top of _Getting Started_, but feel free to make changes to the Wiki to make it more clear: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

**Comment by fabb** [comment]
@pbazydlo how do you fix that? I‘m using next.js and stumbled across this curious issue, and now I‘m trying to polyfill `Intl` only on the server, without much luck so far. Any hints?
