### ISSUE TITLE
Problem in loading appropriate locale data

### ISSUE THREAD

**Issue by mahyarmobilab** [yahoo/react-intl#616]
Hi there,
I recently got familiar with your lib and first of all I want to thank you for your great work.
I have a problem in loading appropriate locale data base on user locale. In our react application which is using webpack as build tool, the locale is being provided from server-side as a global variable. then I am using exactly what documentation says:
```
<script src="https://npmcdn.com/react-intl@latest/dist/react-intl.min.js"></script>
<script src="https://npmcdn.com/react-intl@latest/locale-data/fr.js"></script>
<script>
    ReactIntl.addLocaleData(ReactIntlLocaleData.fr);
</script>
```
in my index.html before including application `bundle.js`. 
I am getting these errors in console and react-intl cannot switch to target locale

```
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
Uncaught ReferenceError: ReactIntl is not defined
```
I cannot see what's wrong? am I missing something?

**Comment by ericf** [comment]
This is caused because `React` hasn't been loaded on the page. I've updated the docs to mention this and I'll look into providing a helpful error message for this case: https://github.com/yahoo/react-intl/wiki#loading-locale-data

**Comment by mahyarmobilab** [comment]
thanks a lot for your help. now I added `react` and `react-dom` and do not have that problem. the problem now is although I have these lines in my `index.html`:
```
<script src="/react/dist/react.js"></script>
<script src="/react-dom/dist/react-dom.js"></script>
<script src="/react-intl/dist/react-intl.min.js"></script>
<script src="/react-intl/locale-data/fr.js"></script>
<script type="text/javascript">ReactIntl.addLocaleData(ReactIntlLocaleData.fr);</script>
```
but I get the error:

`[React Intl] Missing locale data for locale: "fr". Using default locale: "en" as fallback.`

this is my index.js where I create an I18n Context.

```
render(
  <Provider store={store}>
    <IntlProvider
      locale='fr'
    >
      <div style={{ height: '100%' }}>
        <Router history={history} routes={routes} />
      </div>
    </IntlProvider>
  </Provider>,
  document.getElementById('app')
);

```

what do you think the problem is? what am I missing?

**Comment by ericf** [comment]
This looks correct to me, assuming that your `index.js` comes after…
```js
ReactIntl.addLocaleData(ReactIntlLocaleData.fr);
```

You'd have to put a simplified example up somewhere that I could see it.

**Comment by mahyarmobilab** [comment]
> assuming that your index.js comes after

yeah it comes after that. just one thing that I can imagine is happening is that the instance which I am adding the locale to is different than what index.js is using.

>You'd have to put a simplified example up somewhere that I could see it.

I will try to

**Comment by bojandragojevic** [comment]
I have same problem. Did you figure out why this is happening?

**Comment by steida** [comment]
Me too, it looks like something was changed.

**Comment by bojandragojevic** [comment]
Just ensure to add language you will use and it will work. You can add it in heigh level component or where you create store if you use redux.

```
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import de from 'react-intl/locale-data/de';

addLocaleData([...en, ...de]);
```

**Comment by jlteran** [comment]
@bojandragojevic  I tried importing like you said, but I am using Typescript and I get an error with the following line:
import en from 'react-intl/locale-data/en';

the error is: error TS1192: Module '"react-intl/locale-data/en"' has no default export.

Do you have any idea how to fix this. I've tried looking up the error but haven't been able to find a solution.

**Comment by steida** [comment]
@jlteran Check how it's implemented in https://github.com/este/este

**Comment by yohsuzuki** [comment]
@jlteran you can do:

    import * as en from 'react-intl/locale-data/en';
