### ISSUE TITLE
What is the browser support of react-intl

### ISSUE THREAD

**Issue by HadrienPierart** [yahoo/react-intl#618]
This is not very clear when reading the wiki or the readme.
Do you have the same min target browser as the underlying API Intl or is it better / worse ?

I can see this on the Mozilla MDN page : 

> Feature	Chrome	Firefox (Gecko)	Internet Explorer	Opera	Safari (WebKit)
> Basic support	24	29 (29)	11	15	No support

Meaning that safari is not supported at all, and IE only from v11 onward...

Could you consider adding a browser support table on the readme page ?

Thank you !

**Comment by HadrienPierart** [comment]
ok, found it while reading the wiki, my bad. => https://github.com/yahoo/react-intl/wiki#i18n-in-javascript
Closing...

**Comment by ericf** [comment]
@HadrienPierart Technically IE6+, but that's limited by what React supports.

**Comment by HadrienPierart** [comment]
Arent you limited by the Intl API ?
Or you mean the support when you include the polyfill + the locale data you need to add when not already provided by the browser ?

**Comment by ericf** [comment]
Yeah with the `Intl` polyfill.

**Comment by HadrienPierart** [comment]
ok then, thank you !
