### ISSUE TITLE
Option to disable "using default message as fallback." warning

### ISSUE THREAD

**Issue by MoOx** [yahoo/react-intl#619]
Hi,

First of all, thanks for this awesome library. More than useful, it's a must have.

I have a request (and didn't find a way to handle this)

We decided to put the main language of the app we work in the `defaultMessage` (s) (in order to avoid the pain of maintaining a translation file during development).

Our main language is english and we plan to add support for others (french, german etc).

But currently, by using defaultMessages everywhere, we get a TONS of warnings.
Those warnings WILL make sense in a near future, when we will start working on the translations. But for now it's more a noise we would like to hide _for a specific language_ (in our case "en").

The especially annoying part is that a warning is not unique for a given key: when I type in our login form, we get as many warnings as I type a key, cause the way react works, the form is getting re-rendered for each key pressed, and react-intl re-output the warning.

We cannot use NODE_ENV to skip those message, cause we are in development, and want to have other dev behavior.

The thing we should do here is add a whitelist (or maybe more JUST ONE (cause defaultMessage can only cover one language!) language key to say "this language is the one used un defaultMessage, so warnings about defaultMessage will be hidden).

Thoughts?

**Comment by ericf** [comment]
@MoOx there are other issues on this topic, please check out those for more details. The tldr is either leave `locale` undefined on `<IntlProvider>`, or make sure `locale` and `defaultLocale` have the same value. In this case, [this code path](https://github.com/yahoo/react-intl/blob/cc50a9806859cfddab5ff24bb9df46c6e72cd88b/src/format.js#L220-L233) will apply and the errors won't be outputted to the console.
