### ISSUE TITLE
Requiring unknown module "../locale-data/index.js"

### ISSUE THREAD

**Issue by jpaas** [yahoo/react-intl#620]
When I add:

```javascript
import {IntlProvider} from 'react-intl';
```
to a component in my React Native app, I get an error that its requiring unknown module "../locale-data/index.js".

Am I doing something wrong?

I'm using:
    "react": "15.3.1",
    "react-intl": "2.1.4",
    "react-native": "0.32.0",

**Comment by ericf** [comment]
React Native is not officially supported or tested. I haven't tried using React Intl within React Native, so it's hard for me to say.

My best guess is that it's related to React Native's custom module bundler (I'm assuming here RN still has its own custom bundler.) In [`package.json`](https://github.com/yahoo/react-intl/blob/cc50a9806859cfddab5ff24bb9df46c6e72cd88b/package.json#L35-L38) there's a `browser` field which tells bundlers like Browserify, Webpack, and Rollup to **ignore** `locale-data/index.js` from the browser builds. So many this has an adverse reaction with RN's module bundler?

**Comment by jpaas** [comment]
Oh. Based on some of the other issues, it seemed that some other people were using it with RN. If it isn't supported, feel free to close I suppose.

**Comment by ericf** [comment]
You're free to try getting it working 😄 I'm saying that it's not _officially_ supported because we've done zero testing in React Native.

**Comment by jgkim** [comment]
This issue is related to facebook/react-native#9518, and `intl-messageformat` has also the same issue with RN 0.32.

**Comment by jgkim** [comment]
I guess adding a `react-native` field to `package.json` may solve this issue on RN 0.32.

**Comment by jgkim** [comment]
If you use `react-intl` with `react-native` `0.32`, four packages have this problem. A workaround for this is to add `react-native` field to each `package.json` of those packages. WIthout the `react-native` field, `react-native` use the `browser` field as fallback.

### **`react-intl`**
```json
  "react-native": {
    "./locale-data/index.js": "./locale-data/index.js"
  },
```

### **`intl-messageformat`**
```json
  "react-native": {
    "./lib/locales": "./lib/locales.js"
  },
```

### **`intl-relativeformat`**
```json
  "react-native": {
    "./lib/locales": "./lib/locales.js"
  },
```

### **`intl`**
```json
  "react-native": {
    "./locale-data/complete.js": "./locale-data/complete.js"
  },
```

**Comment by ericf** [comment]
Definitely not planning to add react-native specific entries to package.json files for projects that have nothing to do with React, that's absurd. 

This sounds like a bug in how react native is interpreting the "browser" field in package.json.

**Comment by steida** [comment]
> Definitely not planning to add react-native specific entries

I am not sure I got it. How has React Native nothing to do with React?
It's basically yet another React platform. react-intl already supports two platforms, the browser, and the server, and the native is another which should and can be easily supported.

What I am overlooking? browser or react-native, where is the difference? Sorry if it is obvious. Thank you very much for react-intl. It's really well designed.

**Comment by steida** [comment]
https://github.com/este/este/blob/master/gulp/native-fix.js

**Comment by ericf** [comment]
I'm saying that React Native should fix how it's handling the "browser" field – which it currently has a bug in handling `"some-package": false`.

**Comment by tuckerconnelly** [comment]
@ericf Can you please add the react-native fields as a *temporary* fix, while react-native gets their stuff together?

**Comment by tuckerconnelly** [comment]
Or @jgkim can you run npm build in each of your forks and commit them to github, so I can use them? 🙃

**Comment by steida** [comment]
@ericf React Native is not a browser so I don't see why it should support setting for browser.

**Comment by jgkim** [comment]
@tuckerconnelly I already did what you said. Look at the react-native branch of each package.

**Comment by ericf** [comment]
@steida agreed. But it is, which is why people are seeing this issue. And it's reading it incorrectly. Note how this isn't an issue in Node and the module exists in the package.

**Comment by gitim** [comment]
Have the same issue, but I agree with @ericf 

> I'm saying that React Native should fix how it's handling the "browser" field – which it currently has a bug in handling "some-package": false.

for me it looks like RN bug too. I started investigating packager’s work, but have not finished yet.

**Comment by antoinerousseau** [comment]
any update on this?

**Comment by kompot** [comment]
Thanks @steida for a useful script mentioned in
https://github.com/yahoo/react-intl/issues/620#issuecomment-242948214
ended up using it (as one needs to remove `.babelrc`s anyway)

**Comment by gitim** [comment]
fyi: @davidaurelio merged a fix https://github.com/facebook/react-native/commit/5710b230a2a0f2b29553fbf94af5147a2e030f44

**Comment by ericf** [comment]
@gitim Cool, thanks for letting us know! Closing this now…

**Comment by steida** [comment]
Still broken in RN 0.39

**Comment by sharnik** [comment]
The fix in the react-native repo is tagged with v0.40.0-rc.3, so it didn't go in yet.

**Comment by antoinerousseau** [comment]
it's first tagged `v0.35.0`... so yes it's live since that version

@steida try again with fresh node_modules maybe

**Comment by steida** [comment]
Sure I trashed that dir

**Comment by jgkim** [comment]
The fix cannot raise the error anymore, but it cannot actually fix the issue, since it makes the module imports an empty object instead of actual locale data. Thus, to use `react-intl` with `react-native`, we need to import each locale manually.

**Comment by davidaurelio** [comment]
> Still broken in RN 0.39

> The fix makes it not raise the error anymore, but it cannot actually fix the issue, since it makes the module import an empty object instead of the actual locale data.

Is there anything that has to be implemented in RN Packager? Would somebody take the time to describe it in a few words to me, please? I would have capacities to give it another go.

**Comment by Zyphrax** [comment]
I have a magic post-install script, but I'm not sure if it is still necessary :)

```javascript
const fs = require('fs');
const packages = [
  { name: 'react-intl', patch: './locale-data/index.js' },
  { name: 'intl-messageformat', patch: './lib/locales' },
  { name: 'intl-relativeformat', patch: './lib/locales' },
  { name: 'intl', patch: './locale-data/complete.js' }
];

packages.forEach((pkg) => {
  try {
    const path = `node_modules/${pkg.name}/package.json`;
    const file = fs.readFileSync(path, 'utf8');

    var json = JSON.parse(file)
    json['react-native'] = { [pkg.patch]: pkg.patch };

    const jsonString = JSON.stringify(json, null, 2);
    fs.writeFileSync(path, jsonString);
  } catch (e) { }
});
```
