### ISSUE TITLE
What format should the translations for the user's locale have?

### ISSUE THREAD

**Issue by michalczaplinski** [yahoo/react-intl#622]
In multiple places in the docs, it is pointed out that one has to supply the translations oneself as a prop on `IntlProvider`. E.g in the section [creating an i18n context](https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context) there is a following snippet:
```javascript
ReactDOM.render(
    <IntlProvider
        locale={usersLocale}
        messages={translationsForUsersLocale}
    >
        <App/>
    </IntlProvider>,
    document.getElementById('container')
);
```

 What format should `translationsForUsersLocale` have? As far as I can see, it is not defined anywhere in the docs.

**Comment by ericf** [comment]
It's a simple object that maps, message id to translated message string: https://github.com/yahoo/react-intl/wiki/Components#intlprovider

```js
{
  "greeting": "Hello, {name}"
}
```
