### ISSUE TITLE
character entities in messages such as &#x00026;(ampersand) in messages

### ISSUE THREAD

**Issue by kellyrmilligan** [yahoo/react-intl#623]
https://dev.w3.org/html5/html-author/charref

what is the preferred way to have character entities in a message file? break the messages up around  them and pass them in as values?  is there a way to have a message defined with a special character in it?

"Free shipping &amp; returns"

for example?

I did not want to use formatHtml message because the docs say not to.

**Comment by ericf** [comment]
You can escape them, but it requires that you escape the `\u` e.g. `\\u0026` in the message string:
```
"Free shipping \\u0026 returns"
```

**Comment by kellyrmilligan** [comment]
ah, so also is it preferred to do it in unicode? http://unicode-table.com/en/#0026
