### ISSUE TITLE
React-intl and react-router doesn't work together well.

### ISSUE THREAD

**Issue by DWboutin** [yahoo/react-intl#625]
Hi!

All my "onClick" events on the Link component of react-router are not bind to the `a` tag in the DOM on Safari (see: http://imgur.com/a/GA7bI, the first is Chrome and second is Safari).

When i remove `<IntlProvider>` from my main component and other things related, all works.

Do you have any ideas on this?

Thank you

**Comment by ericf** [comment]
You can look at the React Router example app here: https://github.com/yahoo/react-intl/tree/master/examples/react-router

Feel free to reopen this issue with a branch of that demo app that shows the issue if you're still hitting it.

**Comment by NaLLiFFuNT** [comment]
https://github.com/yahoo/react-intl/tree/master/examples/react-router this link is broken :( do you have another one with such example?
