### ISSUE TITLE
FormatNumber - number of decimal places being converted to 3 in tests

### ISSUE THREAD

**Issue by iam-peekay** [yahoo/react-intl#629]
We are snapshot testing our React components using jest snapshotting. We are running into issues where if we use `formatNumber` in our component's render method, the number is being converted to 3 decimals places (even if we set `minimumFractionDigits: 4` in the `formatNumber` configuration). 

When we run the tests locally, they work fine. As soon as we run them in CircleCI, the fraction digits is being converted to 3 instead of 4, causing our tests to fail in CircleCI. 

```
    expected: 1.0000 BTC will arrive in your wallet instantly
    actual: 1.000 BTC will arrive in your wallet instantly
```

We're wondering if it's a bug related to some environment config within React Int'l?

thank you for the help in advance.

**Comment by ericf** [comment]
It might be related to the Node version that you're using locally vs what's used on CircleCI. Can you try running your tests locally with the same node version? Also can you list of the metadata about what locale and what the options to `formatNumber` look like?

**Comment by iam-peekay** [comment]
Hi @ericf -- we are in fact using a different Node version on CircleCI. However, I tried running the tests locally with the same node version as what we are using in CircleCI and they seem to pass just fine locally. 

In terms of the metadata:
- locale for tests: "en"
- formatNumber options: 
```
formatNumber(transferData && transferData.amount || 0, {
      style: 'decimal',
      minimumFractionDigits: 4,
    })
```

**Comment by iam-peekay** [comment]
@ericf actually, you're right. it is due to different node versions running locally vs. what is running in CircleCI

**Comment by ericf** [comment]
What Node version is running on CircleCI?

**Comment by iam-peekay** [comment]
v4.3.0
