### ISSUE TITLE
how to format date in inputBox using react-intl

### ISSUE THREAD

**Issue by sandyksit** [yahoo/react-intl#634]
I want to format string date in inputbox, please guide me, i am using like below code:

import { FormattedDate } from 'react-intl'

@withStyles
@bindRedux([calendarSelector])
export default class CalendarPopup extends Component {
    static propTypes = {
      Weekday: PropTypes.string
    }
    constructor(props) {
        super(props)
        const className = props.className || ''
        this.state = {
            modal: false,
            className,
            activeClassName: (props.activeClassName || '') + ' ' + className,
            fromDate: props.fromDate,
            toDate: props.toDate,
            openCalendar: false
        }
    }

<input className={styles.calenderImage}
                                  type="text"
                                  id="calender"
                                  name="calender"
                                  value={fromDate || ''}
                                  onClick={()=>this.openCalendarPopUp()}
                                  onChange={this.handleChange.bind(this, fromDate)}
                          />

**Comment by ericf** [comment]
https://github.com/yahoo/react-intl/wiki/API#formatdate

**Comment by sandyksit** [comment]
Thanks ericf :+1: 
I created this function and its working fine:
_renderFormatDate(date) {
        let formateDate = Intl.DateTimeFormat({month:'long',  day:'numeric', year:'numeric'}).format(date)
        return formateDate
    }

**Comment by ericf** [comment]
You don't have to use `Intl.DateTimeFormat` directly, and I also wouldn't recommend it.
