### ISSUE TITLE
How to make react-intl work well with Safari

### ISSUE THREAD

**Issue by vnorguet** [yahoo/react-intl#635]
Hi,

React Intl work perfectly on Chrome and Firefox, but on Safari I just see an blank page, with this error:
```
Invariant Violation: [React Intl] The `Intl` APIs must be available in the runtime, and do not appear to be built-in. An `Intl` polyfill should be loaded.
See: http://formatjs.io/guides/runtime-environments/
invariant — browser.js:47
```

I've seen many question about it, all redirects to the formatjs.io guide, but I can't see any code sample that really works.

NB: I'm on a Meteor+React stack, I don't use babel, and my translation file is loaded this way:

```js
import {IntlProvider} from 'react-intl';
import frTranslations from '../translation/fr.json';

// React template view
const Layout = ({content}) => (
  <IntlProvider
    locale="fr"
    messages={frTranslations}>
    <div>{content}</div>
  </IntlProvider>
)

//  Container for router with reactive data
export default LayoutContainer = createContainer(() => {
  // Do all your reactive data access in this method.
  // Note that this subscription will get cleaned up when your component is unmounted

  return {};
}, Layout);
```

I've tried to add <head> tag to add the polyfill, but no way to get it working. Does some of you have an idea or experience on how to fix it? A clear solution may help lots of people.

**Comment by ericf** [comment]
The polyfill must come first, before your script:
```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en"></script>
```
