### ISSUE TITLE
Property value of JSXAttribute expected node to be of a type ["JSXElement","StringLiteral","JSXExpressionContaine

### ISSUE THREAD

**Issue by Honghe** [yahoo/react-intl#636]
It is used as follow:
```
<Helmet
  title=<FormattedMessage id="title" />
  titleTemplate="%s App"
/>
```
get the error:
```
Property value of JSXAttribute expected node to be of a type ["JSXElement","StringLiteral","JSXExpressionContaine
```

Thanks!

**Comment by ericf** [comment]
Assuming that `title` ends up being the `title` attribute of a `<span>` or some HTML element, you'd need to pass a string. See: https://github.com/yahoo/react-intl/wiki/API#string-formatting-apis
