### ISSUE TITLE
currency + maximumFractionDigits not working on Firefox/Safari

### ISSUE THREAD

**Issue by bergonom** [yahoo/react-intl#637]
I'm trying to display something like "$###k" but I am running into this issue:

                            <IntlProvider locale="en">
                                <FormattedNumber currency='USD'
                                                 maximumFractionDigits={0}
                                                 style='currency'
                                                 value={123.45} />
                            </IntlProvider>k

Results in `$123k` on Chrome, `123.45k` on Firefox and Safari.

I can at least get the currency symbol to display if I remove `maximumFractionDigits`

                            <IntlProvider locale="en">
                                <FormattedNumber currency='USD'
                                                 style='currency'
                                                 value={123.45} />
                            </IntlProvider>

Results in `$123.45k` on Chrome, Firefox and Safari

And it does no good to pass in a pre-rounded number because the default
style for currency is to have two digits after the decimal:

                            <IntlProvider locale="en">
                                <FormattedNumber currency='USD'
                                                 style='currency'
                                                 value={123} />
                            </IntlProvider>k

Results in `$123.00k` on Chrome, Firefox and Safari

**Comment by ericf** [comment]
Make sure that `minimumFractionDigits` <= `maximumFractionDigits`. In your case setting them both to `0` should resolve this issue.
