### ISSUE TITLE
[RFC] React Intl Component Details

### ISSUE THREAD

**Issue by ericf** [yahoo/react-intl#65]
A core principal behind [FormatJS][] is providing a declarative way to format data and strings by providing high-level integrations with template/component libraries. The first version of React Intl only have an imperative API provided by `ReactIntlMixin`, but `v1.1.0` will provide a declarative way via React Intl Components. See #23 

We feel that formatting data and strings using the declarative form is superior to using the imperative JavaScript APIs, and the plan is to update all the docs to encourage people to use the React Intl Components going forward. Knowning that this is a much different way to use React Intl (luckily everything is backwards compatible) we decided to cut [RC releases][v1.1.0-rc-1] before making `v1.1.0` final.

So far the feedback from people who've been testing out the `v1.1.0-rc-*` releases has been great! After reflecting on this feedback we still have some open questions that we'd like to settle before cutting the final `v1.1.0` release…

### 1. How should the React Intl Components be named?

@pselden raised a concern about the name of React Intl's module exports for each of the components in #60. Currently on `master` the exports are named assuming that they will be accessed on the `ReactIntl` namespace object; i.e., `ReactIntl.Number`.

While the current naming scheme makes sense when it's written as above, it quickly breaks down in a few ways…

#### Components with '.'s Feel Awkward to Use

Since JSX compiles down into JavaScript function calls it's perfectly valid to use '.'s when referencing components; e.g., `<ReactIntl.Number>`, but there's a worry that this might feel odd to use since JSX looks like HTML and you don't see '.'s used in HTML tag names.

#### ES6 Destructuring and Module Imports

@pselden mentions in #60 how he's been using ES6 destructuring assignments as loving it. But there's a problem with this and the current naming scheme for React Intl Components:

```js
var {Number, Date, Mixin} = require('react-intl');
```

**Built-ins are shadowed!** This is horrible, especially for `Date` which is commonly accessed in JavaScript application code. ES6 Module imports pose a similar problem, but it can be remedied using `as`:

```js
import {
    Number as IntlNumber,
    Date as IntlDate,
    Mixin as IntlMixin
} from 'react-intl';
```

While this solves the shadowing problem, it adds a ton of extra typing that will make React Intl annoying to use via ES6 Modules.

For whatever naming scheme that's chosen, we'd like to put more weight behind one with ergonomics that fit with the future direction of JavaScript; i.e. we like the ES6 shorthand destructuring syntax.

#### [Proposal] Prefixed Exports with `Intl`

This proposal was brought up by @pselden and the change is sitting in PR #64. It renames all of React Intl's exports to be prefixed with `Intl`:

- `IntlMixin`
- `IntlDate`
- `IntlTime`
- `IntlRelative`
- `IntlNumber`
- `IntlMessage`
- `IntlHTMLMessage`

**This proposal keeps the Component names noun-y.**

There is a tradeoff for ES5-compatible syntax since you end up with a double "Intl":

```js
var ReactIntl  = require('react-intl');
var IntlNumber = ReactIntl.IntlNumber;
```

But feels worth it when looking forward to the future (or today when you use a transpiler!):

```jsx
import {Component} from 'react';
import {IntlNumber} from 'react-intl';

export class Count extends Component {
    render(props, state) {
        return <IntlNumber>{props.count}</IntlNumber>;
    }
}
```

_Note: The React Component class example is from [react-future][react-future-classes]._

#### [Proposal] Prefix Component Exports with `Format`

This is similar to the proposal above, **but it uses verb-y component names:**

- `IntlMixin`
- `FormatDate`
- `FormatTime`
- `FormatRelative`
- `FormatNumber`
- `FormatMessage`
- `FormatHTMLMessage`

It's very uncommon to see components with verb-y names, it makes slightly more sense when thinking about the `Format` prefixed naming scheme in conjunction with the next open question…

### 2. Should the React Intl Components Be Self-Closing?

Currently, _all_ of the React Intl Components are implemented to accept the value they're formatting as the single child of the component:

```jsx
<ReactIntl.Number style="percent">{0.9}</ReactIntl.Number>
```

This is a bit odd and uncommon to see in React since the component's child is _not_ another React component. An alternate approach would be to use a `value` prop and make the Component self-closing:

```jsx
<ReactIntl.Number value={0.9} style="percent" />
```

#### Self-Closing + Naming Proposals

And this is how it would look in conjunction with the naming proposals from above:

```jsx
<IntlNumber value={0.9} style="percent" />
<FormatNumber value={0.9} style="percent" />
```

When using the self-closing approach with a `value` prop, the `FormatNumber` naming scheme looks less odd and arguably reads better than `IntlNumber`.

#### Message Components as an Exception?

The `Message` and `HTMLMessage` components are the exception here and probably benefit from keeping with the current approach where the ICU Message template string is the single child of the component:

```jsx
var intlData = {
    locales: ['en-US'],
    messages: {
        VISITOR: 'Visitor {count, number}'
    }
};

<App {...intlData}>
    <ReactIntl.Message count={1000}>
        {this.getIntlMessage('VISITOR')}
    </ReactIntl.Message>
</App>
```

The reason for this is disambiguation of the values the message is formatted with and the message string itself without needing to hijack a prop like `message` making it unavailable as a variable name inside the ICU message string.

That said, if people prefer the self-closing approach, it would make sense to entertain self-closing messages components as well:

```jsx
<IntlMessage message={this.getIntlMessage('VISITOR')} count={1000} />
<FormatMessage message={this.getIntlMessage('VISITOR')} count={1000} />
```

----

We want to make the declarative way of using React Intl intuitive, and idiomatic. We feel we're close, but want to have solid answers to the above open questions and make these decisions before the final release of `v1.1.0`.

**Please feel free to offer your thoughts on these questions and any alternate ideas you may have. Thanks!**

[FormatJS]: http://formatjs.io/
[v1.1.0-rc-1]: https://github.com/yahoo/react-intl/releases/tag/v1.1.0-rc-1
[react-future-classes]: https://github.com/reactjs/react-future/blob/master/01%20-%20Core/01%20-%20Classes.js

**Comment by caridy** [comment]
two notes:

## 1
Format* seems better (as we have discussed offline), paving the road for formatjs library in the future.

## 2
for `<FormatMessage count={1000}>{"Visitor {count, number}"}</FormatMessage>`, It is very confusing, two main reasons:

    a) you will, most likely, never have a hardcoded ICU message in the component, it will be a value provided somehow thru props or by using the lookup mechanism, it will really be something like: `<FormatMessage count={1000}>{this.props.myMessages.VISITOR}</FormatMessage>`, which is really not that diffirent from: `<FormatMessage count={1000} message={this.props.myMessages.VISITOR} />`.
     
     b) people might get confused thinking that what you put inside `<FormatMessage>` or `<FormatNumber>` can be any markup and/or components, while the reality is very different.

**Comment by caridy** [comment]
As for my proposal, I'm not sure between `<FormatMessage value={this.something} />` vs `<FormatMessage message={this.something} />`

**Comment by ericf** [comment]
> for `<FormatMessage count={1000}>{"Visitor {count, number}"}</FormatMessage>`, It is very confusing

I was just trying to keep the example simple, and show there's a string as the child of the component, that's all. I agree that in practice it's bad.

**Comment by caridy** [comment]
I don't think beautiful examples should drive our design. :icecream:

**Comment by sebmarkbage** [comment]
One thing to consider. At FB, with our equivalent of FormatMessage, we:

A) Always write messages inline and extract/replace them with a transform for translation.

B) Allow complex components to be nested within messages.

```javascript
<FormatMessage>
  A user named <ProfilePicture pic={user.pic}  /> {user.name} visited
  <FormatNumber value={count} /> times.
</FormatMessage>
```

**Comment by ericf** [comment]
> beautiful examples should not drive our api.

@caridy I updated the examples to show how we normally do it with the message strings being external.

**Comment by ericf** [comment]
@sebmarkbage I'm very interested in your thoughts around:

1. Noun-y vs. Verb-y component names in React
2. Self-closing components vs. components with non-component children

The way we want to handle the example message you gave would be to still stick with the ICU Message format since it can be understood by professional translators, and the string is externalized from the source and can be used by other client apps. Using external ICU Message strings limits how "rich" a single string message can be, i.e. you wouldn't be able to mix JSX inside the message string, but you could use HTML — although using JSX in messages was brought up in #26. This would lead us to handling the example like this:

```jsx
var intlData = {
    locales: ['en-US'],
    messages: {
        VISITED: '{name} visited {count, plural, one{# time} other{# times}}.'
    }
};

<App {...intlData}>
    <ProfilePicture pic={user.pic} />
    <IntlMessage name={user.name} count={count}>
        {this.getIntlMessage('VISTED')}
    </IntlMessage>
</App>
```

The `count` will be formatted automatically by `Intl.NumberFormat` and the `"time(s)"` label will have the correct pluralization. But I had to change the messages to move `<ProfilePicture>` outside.

**Comment by turadg** [comment]
The noun form does feel more React-y, but `ReactInt.IntlMessage` does feel odd. What if it were `FormattedMessage` (a noun) and then abbreviated to `FMessage`? Or for that matter, `LMessage` for "localized message". That really is the noun that the instantiated component is representing, a displayable entity that is not just parameterized to be used internationally but that has in this instance been localized to the current locale.

In the self-closing case of Message, for readability it would be nice to be able to pass just the key:
```
    <LMessage key="VISITED" name={user.name} count={count}>
```

Naive implementation:
```
    var $$components$message$$IntlMessage = $$react$$default.createClass({
        displayName: 'IntlMessage',
        mixins     : [$$mixin$$default],

        render: function () {
            var props   = this.props;
            var message = this.props.key ?
                this.getIntlMessage(this.props.key) :
                this.props.message;

            return $$react$$default.DOM.span(null, this.formatMessage(message, props));
        }
    });
```

**Comment by sebmarkbage** [comment]
@ericf Moving the component outside of the message is not always possible. E.g. with emoticons that needs to be embedded into the message or something like that. Even if you prefer the message source to be externalized, it seems like I should be able to pass a component as one of the parameters.

```javascript
var intlData = {
    locales: ['en-US'],
    messages: {
        VISITED: 'A user named {picture} {name} visited {count, plural, one{# time} other{# times}}.'
    }
};

<IntlMessage name={user.name} count={count} picture={<ProfilePicture pic={user.pic} />}>
  {this.getIntlMessage('VISITED')}
</IntlMessage>
```

Regarding Noun-y vs. Verb-y names. I'm not sure if it's really that important to preserve the noun-y names. You can also change the prefix to "Formatted". E.g. `<FormattedDate />`.

Technically children are really just considered data so a component can put any requirements they want on it. We might want to turn it into a special data type to make it easier to work with iterables of children that preserve key information in a set, but for now it's just data.

In general, I prefer to put even components as props. Named props can convey more information by being explicitly named than arbitrary children can.

**Comment by sebmarkbage** [comment]
@turadg Note that as of React 0.12, `key` is a reserved property name in JSX and the value is not available user code so your example doesn't work without renaming it to something else.

**Comment by ericf** [comment]
> Even if you prefer the message source to be externalized, it seems like I should be able to pass a component as one of the parameters.

@sebmarkbage the only ["safe"] way I could think to support this is to update the [HTMLMessage component](https://github.com/yahoo/react-intl/blob/988f21a65a6de78060c68ec69f6e2e6c0d634dda/src/components/html-message.js) to check `props` for values that pass `React.isValidElement()`, then call `React.renderToString()` on them. This way I can pass along the string representation as the value for the `{picture}` placeholder in the message string.

From there the underlying `IntlMessageFormat` library will interpolate the string and substitute the value, and the [fully formatted message string injected into the DOM via `dangerouslySetInnerHTML`](https://github.com/yahoo/react-intl/blob/988f21a65a6de78060c68ec69f6e2e6c0d634dda/src/components/html-message.js#L38-47).

It seems like this will wreak havoc on perf though :( Another option would be to insert have `IntlMessageFormat#format()` use string identifiers for the values that are represented as React elements, then split the resulting string into multiple children and replace the identifier strings with references to the React elements. I just worry about the safety of this approach.

**Comment by sebmarkbage** [comment]
We have our precompiler split the string up into its pieces ahead of time. Then we fill in the blanks at runtime at the right place in the set, which may of course vary by language. We also place a key each item so that we can preserve nested component's state in case the sentence is updated or reordered.

Effectively, you pass something like this to React:

```javascript
new Map([
['partial0', 'A user named '],
['picture', <ProfilePicture pic={user.pic} />],
['partial1', ' '],
['name', name],
['partial2', ' visited '],
['count', count],
['partial3', ' times']
])
```

**Comment by sebmarkbage** [comment]
Note that for pluralization etc, we use a different once of these templates at runtime.

**Comment by ericf** [comment]
Here's what I have so far to support React Elements inside of formatted messages:
https://gist.github.com/31996579873a92e08d3c

It can take something like this:
```jsx
<FormatMessage name={<b>Eric</b>}>
    {"Hello, {name}!"}
</FormatMessage>
```

And render this:
```html
<span data-reactid=".1lpa6dq7ncw" data-react-checksum="1647393318"><span data-reactid=".1lpa6dq7ncw.0">Hello, </span><b data-reactid=".1lpa6dq7ncw.1">Eric</b><span data-reactid=".1lpa6dq7ncw.2">!</span></span>
```

So this seems like a step in the right direction, especially when looking at an example that uses relative time formatting since `relative` currently isn't part of the ICU Message grammar:

```jsx
<FormatMessage 
        ago={<FormatRelative value={post.date} />}
        favs={post.favs}>
    {"Posted {ago}, has {favs, number, integer}"}
</FormatMessage>
```

**Comment by sebmarkbage** [comment]
Nice! Definitely a step in the right direction. Your keys will be implied which screws up any stateful components in case of updated sentences but that can be fixed later.

**Comment by sebmarkbage** [comment]
Although since you're not actually embedding them as children, I'd probably still prefer the `message={""}` prop instead of JSX children.

**Comment by ericf** [comment]
> Your keys will be implied which screws up any stateful components in case of updated sentences but that can be fixed later.

I don't think I follow what you're getting at here.

> I'd probably still prefer the `message={""}` prop instead of JSX children

Yeah, the only tradeoff with this is that the ICU Message string cannot contain a `message` variable; e.g.:

```js
var ERR_MESSAGE = "Error {code}: {message}";
```

Since in React-land the `message` prop would be special, the dev would need to update the above string to something like:

```js
var ERR_MESSAGE = "Error {errCode}: {errMessage}";
```

Then when they use React Intl things would work properly:

```jsx
<FormatMessage message={ERR_MESSAGE} errCode={404} errMessage="Not Found." />
```

So that's one tradeoff I'm wrestling with, and as @caridy mentioned earlier, we want to encourage people to externalize their strings since they will be different depending on the current user's locale.

**Comment by sebmarkbage** [comment]
> > Your keys will be implied which screws up any stateful components in case of updated sentences but that can be fixed later.

> I don't think I follow what you're getting at here.

I mean React keys. Normally you would do something like `<AnimatedEmoticon key="the-smiley" />` to indicate that this particular item should retain state even if it's position within the set changes. E.g. switching between two different messages or sentence order.

> Since in React-land the message prop would be special

In React-land you will also have the same trade-off with the `children` prop regardless. You can't do:

```javascript
<FormatMessage children="something">{"something else"}</FormatMessage>
```

Because the child position in React's JSX is just an alias for the `children` prop.

**Comment by ericf** [comment]
> Because the child position in React's JSX is just an alias for the `children` prop.

Yeah, good point. Saying it this way makes that much clearer to me :smile:

**Comment by ericf** [comment]
## Update

So it seems we're all converging on:

1. Prefix React Intl Component `exports` with `Formatted`.
2. React Intl Components should be self-closing and not use nesting.

### Examples

```jsx
import React from 'react';

import {
    IntlMixin,
    FormattedDate, 
    FormattedMessage, 
    FormattedNumber, 
    FormattedRelative
} from 'react-intl';

var intlData = {
    locales: ['en-US'],
    
    formats: {
        number: {
            USD: {
                style: 'currency',
                currency: 'USD',
                minimumFractionDigits: 2
            }
        }
    },
    
    messages: {
        POST: 'Posted {ago}, {likes, plural, one{# like} other{# likes}}'
    }
};

var App = React.createClass({
    mixins: [IntlMixin],
    
    render: function () {
        return (
            <FormattedNumber value={4200} locales="fr-FR" />
            <FormattedNumber value={0.9} style="percent" />
            <FormattedNumber value={99.95} format="USD" />
            
            <FormattedDate value={new Date()} />
            <FormattedRelative value={Date.now() - 2000} />
            
            <FormattedMessage message={this.getIntlMessage('POST')}
                ago={<b><FormattedRelative value={post.date} /></b>}
                likes={post.likes} />
        );
    }
});

Read.render(
    <App {...intlData} />,
    document.getElementById('container')
);
```

**Comment by ericf** [comment]
#66 and #67 have been merged which implement decision made against the questions in this thread.

**Comment by necolas** [comment]
@sebmarkbage the approach you're using at facebook would be my preferred option. that makes it really easy to read the source code, and understand the format of the message from within the component itself! reminds me of the [soy template `msg` command](https://developers.google.com/closure/templates/docs/commands#msg). do you have any longer-term plans to open source any of that?
