### ISSUE TITLE
character entities in messages such as &#x00026;(ampersand) in messages break when  building for production

### ISSUE THREAD

**Issue by kellyrmilligan** [yahoo/react-intl#659]
#623

I escaped it as recommended, but when I build for prod 
<img width="245" alt="screen shot 2016-09-21 at 10 24 52 am" src="https://cloud.githubusercontent.com/assets/2642088/18717483/b0dbfe5e-7fe5-11e6-818a-7d6b80ded189.png">

it is not rendering correctly. 

```
import messages from 'constants/messages-en-US.json'

...

<IntlProvider
                locale="en"
                messages={messages}
              >

```

i'm building with webpack, and it's run through uglify js in the process. 

any ideas?

**Comment by ericf** [comment]
What's the message in `messages-en-US.json`? Does it look like this?
```
"Free shipping \\u0026 returns"
```

**Comment by kellyrmilligan** [comment]
yes

**Comment by ericf** [comment]
If this is still happening, can you reopen and provide a failing test case as a PR?
