### ISSUE TITLE
Children don't update when context changes

### ISSUE THREAD

**Issue by adowsky** [yahoo/react-intl#660]
Hi,
I noticed that IntlProvider blocks update of its children when Provider's parent updates state with objects transferred to context.
It will be something like that:
Parent class:
```
class Parent extends React.Component{
	constructor(props){
		super(props);
		
		this.state = {
			someContextObject: {}
		};
	}
	
	static childContextTypes = {
		someContextObject: React.PropTypes.object,
	};
	
	getChildContext() {
        return {
            someContextObject: this.state.someContextObject,
        };
    }
	
	render() {
		 return (
			<IntlProvider locale="en" messages={myMessages}>
				<MyDearChild/>
			</IntlProvider>
			);
	}
 }
```
 
MyDearChild's render:
``
render() {
	 return this.context.someContextObject; // object provided by parent
 }
``
 
After change someContextObject in parent class, ie.
` this.setState({someContextObject: myNewContextObject}) `
child stays with old context.
If I remove IntlProvider from parent's render, problem dissapears.

Is it intentional behaviour or bug?

**Comment by ericf** [comment]
It's a known issue/current limitation in React. See https://github.com/yahoo/react-intl/issues/234#issuecomment-163417939 for a similar issue with Redux.

To test whether this is indeed the issue trying doing this right after you import `IntlProvider`:
```js
delete IntlProvider.prototype.shouldComponentUpdate;
```

If so, you're best solution for now will be to force `IntlProvider` into re-rendering.

**Comment by ericf** [comment]
I could implement a `pure` or similar prop on `<IntlProvider>` which would effectively mean `shouldComponentUpdate()` will always return `true` when `pure={false}`. This is what Redux uses for `connect()` to get around the same issue: https://github.com/reactjs/react-redux/blob/93cdfaeaf9d3e5400ffc05fe9d177118286109ca/docs/troubleshooting.md#my-views-arent-updating-when-something-changes-outside-of-redux

**Comment by ericf** [comment]
But like the Redux doc say, this will make things less performant. If you passed the `context` and props directly to `<MyDearChild/>` the issue would be resolved, and `<MyDearChild/>` (assuming that's your `<App/>` can stick them on its `getChildContext()`.

**Comment by adowsky** [comment]
That was just an example. I added property to IntlProvider which triggers update.
Problem appeared when I was writing tests, so the workaround is enough for my case.
Thanks for answer.
