### ISSUE TITLE
FormattedDate always in English server side / Locale client side ?

### ISSUE THREAD

**Issue by jbracoupeau** [yahoo/react-intl#678]
Hi all

```
import fr from 'react-intl/locale-data/fr';
import {IntlProvider, FormattedDate, addLocaleData } from 'react-intl';
addLocaleData([...fr])
...
<IntlProvider locale="fr-FR">
<FormattedDate value={new Date(events.dateStart)} year='numeric' month='long' day='numeric' weekday='long' />
</IntlProvider>
````

I tried with locale='fr', locale={navigator.language}...

it always displays the date in english, then in French, with this nice markup warning :
 _(client) n data-reactid="40">lundi 10 octobre 201
 (server) n data-reactid="40">2016 M10 10, Mon</sp_

**Comment by ericf** [comment]
See the links here about `Intl` in Node: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript
