### ISSUE TITLE
rollup includes all locale-data

### ISSUE THREAD

**Issue by mbrevda** [yahoo/react-intl#684]
Using rollup, all locale-data is included in the bundle. I would expect just the requested files to be included. Perhaps locale-data should be excluded by default from the es6 build?

Here is what I'm including:
```js
import {IntlProvider, addLocaleData} from 'react-intl'
import en from 'react-intl/locale-data/en'
addLocaleData([...en])
```

and my rollup config:
<details>
```js
import babel from 'rollup-plugin-babel'
import eslint from 'rollup-plugin-eslint'
import resolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import includePaths from 'rollup-plugin-includepaths'
import uglify from 'rollup-plugin-uglify'
import replace from 'rollup-plugin-replace'

export default {
    entry: './src/app.js',
    dest: './build/app.js',
    format: 'iife',
    //sourceMap: 'inline',
    plugins: [
        includePaths({paths: ['src']}),
        eslint(),
        replace({
            NODE_ENV: process.env.NODE_ENV,
            PRODUCTION: true
        }),
        babel({exclude: 'node_modules/**'}),
        resolve({
            module: true,
            jsnext: true,
            main: true,
            browser: true
        }),
        commonjs({
            namedExports: {
                'node_modules/react/react.js': [
                    'Component',
                    'PropTypes',
                    'Children',
                    'isValidElement',
                    'createElement'
                ],
                'node_modules/react-dom/index.js': ['findDOMNode'],
                'node_modules/react-history/index.js': ['Back']
            }
        }),
        uglify({
            sourceMap: false
        })
    ]
}

```
</details>

**Comment by ericf** [comment]
The [`package.json` file](https://github.com/yahoo/react-intl/blob/260313961c5baec189295ff9bf4f3cd7644af29d/package.json#L32-L38) is setup with metadata for excluding all locale data for `"browser"`, which it seems you have set in your `resolve()` options. So I'm not sure why it would be including it.

If you have a chance to dig deeper to find out what's going on, let me know what you find and what I can change in this repo to resolve it.

**Comment by mbrevda** [comment]
Using the browser version would be unfortunate, as it isn't in es6 (no tree shaking, dead code elimination, etc). Is there a reason to preload all the data in the es version? Perhaps make that optional or add another version that doesn't include the locale-data?

**Comment by ericf** [comment]
I meant that I setup the `"browser"` field in `package.json` (linked above) to explicitly ignore the file that includes locale data for all locales. The reason for this is so that bundlers like Browserify, Webpack, and Rollup don't include it in their bundle.

Maybe there's something wrong with the `resolve()` plugin. Have you looked through its issues relating to the `"browser"` field? https://github.com/rollup/rollup-plugin-node-resolve/issues?utf8=✓&q=browser

**Comment by mbrevda** [comment]
Glancing at the code, the `browser` field should, indeed, be the file used. But if it **was** used then we would lose the rollup benefits (ts, dce, etc) as the `browser` build is not es 6.

Hence, we need an es6 file that doesn't include locale-data that can be included in rollup projects.

**Comment by ericf** [comment]
I don't understand the connection here. Where is the "browser" build defined? I think it's just that Rollup's resolve plugin might not be merging the `"browser"` and `"module"` fields?

**Comment by mbrevda** [comment]
Rollup's resolve plugin is preferring `node_modules/react-intl/lib/index.es.js`. Is that what you expected?

**Comment by mbrevda** [comment]
Due to the amount of time it was taking to get simple stuff working, I have given up on rollup for the time being. I still think there are ways to optimize the bundle, Ill open another ticket with a different angle.

**Comment by ericf** [comment]
@mbrevda sorry, I just haven't had time to look into what's going in inside of Rollup's code. My expection would be that Rollup _does_ use `lib/index.es.js` _and also_ ignore `locale-data/index.js` as defined in the `"browser"` field in `package.json`.

**Comment by mbrevda** [comment]
No worries, would rather put the resources somewhere I know will work across the board, atm while rollup has its uses (probably for lib/module authors) I dont find it to be the best choice as a browserify/webpack replacement for a typical package.

For the record, again, `locale-data/index.js` **was** included in the final bundle.
