### ISSUE TITLE
Unit testing issues with formatNumber.

### ISSUE THREAD

**Issue by andrewheppner** [yahoo/react-intl#686]
I am having the following issue when trying to test out a component that uses the formatNumber method.

`ERROR: '[React Intl] Error formatting number.
ReferenceError: No locale data has been provided for this object yet.'
ERROR: '[React Intl] Error formatting number.
ReferenceError: No locale data has been provided for this object yet.'`

Here is the unit test setup...

```
import React from 'react';
import SkinDeep from 'skin-deep';
import { CountryMenu } from '../index';
import 'intl';
import { IntlProvider, addLocaleData } from 'react-intl';
import enLocaleData from 'react-intl/locale-data/en';

addLocaleData(enLocaleData);

describe('Research/Toolbar/AdvancedFiltersPanel/Location/CountryMenu', () => {
    const intlProvider = new IntlProvider({
        locale: 'en',
        messages: { test: 'test' },
    }, {});
    const { intl } = intlProvider.getChildContext();
    let tree;
    let instance;

```

```
beforeEach(() => {
    tree = SkinDeep.shallowRender(
        <CountryMenu
            onSelect={() => {}}
            location={{
                buyerCountryCode: 'US',
                sellerCountryCode: 'UK',
            }}
            filterTotals={{
                US: '1',
                UK: '2',
            }}
            filterOption="buyerCountryCode"
            intl={intl}
        />
    );
    instance = tree.getMountedInstance();
});

it('shouldComponentUpdate is working correctly when filterTotals prop changes', () => {
    const nextProps = Object.assign({}, instance.props, {
        filterTotals: {
            US: '2',
            UK: '2',
        },
    });
    expect(instance.shouldComponentUpdate(nextProps)).toEqual(true);
});`
```

I am running these tests using Karma and phantomJS.

Any ideas about why the locale is still being seen as not provided? What am I missing?

**Comment by ericf** [comment]
In PhantomJS, you'd need to make sure the `Intl` APIs exist or are polyfilled, and that React Intl has its locale data loaded:

- https://github.com/yahoo/react-intl/wiki#i18n-in-javascript
- https://github.com/yahoo/react-intl/wiki#loading-locale-data

**Comment by bziorkiewicz** [comment]
@ericf, thank you for this answer. I spent few days looking for solution. In my case PhantomJS didn't show any error. Shouldn't react-intl throw some errors to console when there is no Intl API?

**Comment by ericf** [comment]
@bziorkiewicz it does: https://github.com/yahoo/react-intl/blob/master/src/components/provider.js#L52

**Comment by bziorkiewicz** [comment]
@ericf that's strange. I'm wondering why PhantomJS doesn't show any errors.
