### ISSUE TITLE
Minimize bundled code size

### ISSUE THREAD

**Issue by mbrevda** [yahoo/react-intl#687]
It seems that all modules are bundled into a single dist file, leading to ~31k of imports. This is true even if only some of the packages functionality is used. Other packages, such as [react-router](https://github.com/ReactTraining/react-router/blob/v4/website/examples/Basic.js#L2-L4) and [react-virtualized](https://github.com/bvaughn/react-virtualized/issues/427#issuecomment-252367465) have taken to providing direct module imports where the indevidual modules are built and can be included without importing the entire package.

In the name of saving bytes, I propose breaking down react-intl's components, if possible, to separate modules. For the sake of backwards compatibility, the current single file import would stay, with sinlge modules files complimenting it.

**Comment by ericf** [comment]
Isn't this moot with Rollup and Webpack 2 once the issues is resolved in Rollup between `"module"` and `"browser"` in `package.json`?

**Comment by mbrevda** [comment]
The utopia of perfect tree shaking seems to be far off even for those that **are** using rollup/webpack (and not everybody is...). [See here](https://github.com/ReactTraining/react-router/pull/3410) for more discussion. In the meantime, we have direct imports.

**Comment by mbrevda** [comment]
Is lib size not a priority for this project?

**Comment by ericf** [comment]
This isn't actionable without a major version bump. I'd rather setup specific issues related to actions that can happen for the current major version. I have some ideas on how to do that.

**Comment by mbrevda** [comment]
Great to hear, looking forward to seeing what you come up with!

**Comment by jacobgreen25** [comment]
Would greatly appreciate this @ericf. Thanks @mbrevda for bringing this up.
