### ISSUE TITLE
When browser CLDR data is stale...?

### ISSUE THREAD

**Issue by vvohra** [yahoo/react-intl#691]
@ericf @caridy @jasonmit 

I have a question that encompasses FormatJS/Intl.js Polyfill and I'm not sure the best place to ask, but I'll ask it here.

Using CLDR rules for formatting is great except when browsers are not using the latest CLDR releases. Either because the user isn't using the latest browser or the browser hasn't pulled in the latest CLDR release.

I'm not sure how often this happens, so maybe you might have some insight. How often are browsers pulling in the latest CLDR data?

And let's say an issue is found with a browser like https://github.com/andyearnshaw/Intl.js/issues/221.

Because it's not possible to override the format, one option I can see is to force Intl.js Polyfill irrespective of the browser/version for the affected locales. The other option would be to deal with the formatting as a one-off with a conditional and check back when the browsers update to the latest CLDR release.

I was wondering if anyone had run into this issue before.

**Comment by ericf** [comment]
@vvohra yes, it ends up being a moving target, but we're working to better standardize this in TC39. The first start is ECMAScript pinning to a particular version of Unicode. The two approaches you mentioned are what I see teams doing.

**Comment by caridy** [comment]
There is another effort that can help with this as well: https://github.com/andyearnshaw/Intl.js/issues/242. By breaking the Intl polyfill into small pieces, will help to patch only the offender instead of penalizing all Intl features.
