### ISSUE TITLE
Should allow specifying a pre-defined formattedMessage as a <FormattedMessage> prop

### ISSUE THREAD

**Issue by spiderworm** [yahoo/react-intl#692]
It's ugly to have some message details defined in a defineMessages({ }) block, but other messages defined in <FormattedMessage> blocks in render().

It would be cleaner if we could, for instance, use a syntax something like the following:

(outside of render())
`const messages = defineMessages({
  key1: { ... },
  key2: { ... }
});`

(and inside render())
`<div>
  <FormattedMessage formattedMessage={messages.key1} />
  <FormattedMessage formattedMessage={messages.key2} values={{ ... }} />
</div>`

This way, message details that are not render-specific can be always defined in a higher scope, and they can all be stored in the same place. Also can do away with intl references in the render method in some cases taking this approach.

**Comment by ericf** [comment]
This is possible today:
```js
const messages = defineMessages({
  greeting: {
    id: 'home.greeting',
    defaultMessage: 'Hello, {name}!',
  },
});

<FormattedMessage {...messages.greeting}/>
```
