### ISSUE TITLE
today midnight - FormattedRelative - shows incorret relative day

### ISSUE THREAD

**Issue by evilnemesis** [yahoo/react-intl#693]
when I have today midnight in FormattedRelative it shows yesterday 0:00 except today 0:00
if date has one more second it shows correctly.
for example:
imagine that today is 2016-10-18 00:00:00 UTC
when a I put this date to FormattedRelative it shows yesterday 0:00, but it should show today 0:00
I and my colleagues think that it should show today 0:00.
Is someone capable to explain me if this is a correct behavior or not?
If not, is it possible to repair it?
thx

**Comment by ericf** [comment]
I'm not sure I totally follow, so could you create a PR for a new test case that shows the issue? https://github.com/yahoo/react-intl/blob/master/test/unit/format.js#L325

**Comment by evilnemesis** [comment]
Hi @ericf a very big sorry.
I have figured it out that I made a mistake.

**Comment by ericf** [comment]
Okay, glad to hear you got it fixed!
