### ISSUE TITLE
Whether can Internationalize array?

### ISSUE THREAD

**Issue by codepandy** [yahoo/react-intl#694]
Hi,

Now I need Internationalize a array,the below is my code:
var categories=['微软','谷歌','百度','阿里巴巴'];

**Comment by codepandy** [comment]
how to do it?

**Comment by ericf** [comment]
We don't currently support list formatting. But it is a feature I'd like to see!

**Comment by ericf** [comment]
Some work has started on `Intl.ListFormat`: https://github.com/zbraniecki/proposal-intl-list-format

**Comment by leoyli** [comment]
Would be curious on the status of `ListFormat`, now in stage 3.

**Comment by codepandy** [comment]
@ericf thank you very much.
