### ISSUE TITLE
What actually happens if I change locale? Remount?

### ISSUE THREAD

**Issue by adjourn** [yahoo/react-intl#695]
I accidentally noticed something and it got me wondering..

I have a component that animates up and down if boolean `state` changes. This component is **always** rendered in my app. However, if it's in non-default `state` and I change locale, it doesn't animate to default `state` or remain to same `state`, it just goes &#42;poof&#42; to it's original position. 

I concluded that it doesn't just get re-rendered, it gets remounted, otherwise it would animate or what?

Am I right or have I made a mistake somewhere? I would prefer to avoid that kind of jank. Could I?
## 

My theory: if this is a conscious choice, it's because `react-intl` uses `context` which doesn't automatically re-render components if it changes and we would have to write this to every component that uses `react-intl` (which also has some caveats):

``` js
shouldComponentUpdate(nextProps, nextState, nextContext) {
    return !shallowEqual(this.props, nextProps) ||
           !shallowEqual(this.state, nextState) ||
           !shallowEqual(this.context, nextContext)
  }
```

If Im right and this is intentional, it means that I have to choose language switcher location very carefully, because all `state` goes to default and it will make a jank in app flow (closes all modals, clears inputs _etc_).

**Comment by unirey** [comment]
I found issue #234 after few hours of browsing and it that seems to describe my issue: I had `key={locale}` on `<IntlProvider>` and it forces full teardown.

 facebook/react#2517 is still open and doesn't seems to be resolved. I take that `key={locale}` is still our only workaround. If I understand the issue correctly, only other solution would be to expose all components to `context` and use `shouldComponentUpdate()` but that would lose the purpose of  `context` and probably had an impact to performance.

Does anybody has suggestions to make transition as smooth as possible? 

--
Few ideas:
- keep track of inputs, if user has filled any inputs, ask a confirmation before locale switch
- make a short (_e.g_ 500ms) fade-in-out overlay animation before actually switching locale

**Comment by ericf** [comment]
Redux has this same issue, but they are working on ways around not having to implement `shouldComponentUpdate` on their `<Provider>`. Ideally we'd be able to rebuild `<IntlProvider>` in a similar fashion so it can be performant without `shouldComponentUpdate()`.

I don't currently have the time to do this, but would be up for working with someone who does.

**Comment by Dmitry-N-Medvedev** [comment]
@ericf, what if the context is not used at all for locale switching? what if every component that depends on locale just listens for an locale switching "event" on redux store?

**Comment by bhouser** [comment]
@ericf I have a very similar problem with context.  I'm not changing the locale, I'm just lazy-loading some intl messages.  I pass an updated `messages` prop to IntlProvider.  Deep in my react tree, I try to access the new message ID's but they don't exist (they do exist on context immediately below IntlProvider).  Setting "key" on my IntlProvider isn't an option for me, I don't want to erase state in the tree every time I load some messages.

I did some research, and I believe libraries like Redux solve this problem by passing an event emitter through context.  The event emitter itself is never updated throughout the session lifetime, but it can push new data, even to components which are added below a `shouldComponentUpdate` barrier.

I haven't looked at the implementation details in redux's source code, but I believe it would be possible to solve this problem by re-implementing react-intl's context usage, without changing the API.  Thoughts?

**Comment by bhouser** [comment]
I have a workaround for the `messages` prop, which solves my immediate problem: when adding new messages, don't create a new javascript object with the additional message IDs added.  Mutate the object passed to IntlProvider previously as a prop (and pass it again as a prop).  This is the messages object available on context, so the new message IDs will be available in the whole tree, regardless of `shouldComponentUpdate` blocking context propagation.

Problems not solved by this workaround:
- Updating existing usages of message IDs, which have already been rendered in the react tree.  I don't personally want to do this, but wanted to note for anybody else: this workaround does not cause any existing components to update.  The new message IDs are definitely available for components mounted after the IDs were added.
- Changing the locale.  The locale is a primitive, so you can't mutate it, it can only be replaced.  Even if you could mutate it, when changing the locale you almost certainly need a change propagation mechanism.

I still think that the change I recommended above is a good direction for the react-intl library, which can be implemented before [facebook/react#2517](https://github.com/facebook/react/issues/2517) is resolved.

**Comment by sanchosa** [comment]
A few words about my situation and what i did. I used IntlProvider and my components rerendered on language change, good. But only before i connected first component throught connect(Component). This connected component do not render on locale change any more, bad. Solution can be to use injectIntl on every nested component where you need to change locale above connect(Component) from this discussion https://github.com/yahoo/react-intl/issues/371, but that is not comfortably. Another solution is to use key={locale} in IntlProvider, but all the page components wil rerender on locale change and you will lose selected data in components, not good. I deside to injectIntl on first MainComponent, then receive intl in MainComponent props and pass it as intl prop to all child components where i need a locale change. In such situation i have intl in component props if i need it and no necessary to injectIntl on each Component, and yes, data is not loose in this situation, so all became good i think. Here is an example:
`const Order = props => {
	console.log('render Order')
	return <Row key="row" type="flex" justify="center">
		<Col span={10}>
			<GroupSelector intl={props.intl}/>
			<StyledSearch intl={props.intl}/>
			<Label>Channels Sorter</Label>
			<SortableList items={props.items.toArray()}>
				<ChannelSorterItem/>
			</SortableList>
		</Col>
		<Divider type="vertical"/>
		<Col span={10}>
			<SortableList items={props.items.toArray()}>
				<ChannelSorterItem/>
			</SortableList>
		</Col>
	</Row>
}

const Component = props => {
	console.log('render ListEditor')
	switch (props.control) {
	case 'edit':
		return <span key="edit">Editor</span>
	case 'order':
		return <Order intl={props.intl} key="order"/>
	case 'export':
		return <span key="export">Export</span>
	default:
		return <span>Editor</span>
	}
}

export default injectIntl(connect(Component))
`

**Comment by adjourn** [comment]
Im closing this, we should focus our effort to #1106 which should fix all the issues related to context.
