### ISSUE TITLE
Where are messages defined?

### ISSUE THREAD

**Issue by joetidee** [yahoo/react-intl#698]
I am coming from another i18n package that used *.json files to store messages in a particular language, for example en-GB.i18n.json would look like:

```
{
  "1" : "Some message",
  "2" : "Another bit of txt",
   ...
}
```

My application is built using Meteor/React. From having read around it appears that the language files need to be compiled, but is there a way to simply defin the messages in json format within a file or database?

**Comment by ericf** [comment]
You can simply pass the parsed contents of that JSON file to `<IntlProvider>`'s `messages` prop.

See: https://github.com/yahoo/react-intl/wiki/Components#intl-provider-component

**Comment by joetidee** [comment]
But in a Meteor application, I am not sure if the process creates the language file(s) from all the inline messages within the components, as intended. Is there a way to check?

**Comment by ericf** [comment]
I don't know about how Meteor works to say.
