### ISSUE TITLE
Not sure how to access the messages...

### ISSUE THREAD

**Issue by joetidee** [yahoo/react-intl#699]
Apologies for this, I'm sure I'm missing something obvious. I have the following code:

```
import React, {Component} from 'react';
import ReactIntl, {IntlProvider, defineMessages } from 'react-intl';
import en from 'react-intl/locale-data/en';
ReactIntl.addLocaleData([...en]);

const messages = defineMessages ({
    test: {
        id: 'app.test',
        defaultMessage: 'Hello World!'
    }
});

export default class AppWrapper extends Component {

    constructor(props) {
        super(props);
    }

    render(){
            return (
                <IntlProvider locale="en-GB" messages={messages}>

                    <Login />

                </IntlProvider>
            )
    }
};
```

I am using a Meteor/React application. How do I access the message from within the `<Login />` component?

**Comment by ericf** [comment]
By passing the correct `id` to `<FormattedMessage>`: https://github.com/yahoo/react-intl/wiki/Components#formattedmessage

Ideally you'd use `defineMessages` inside your `<Login>` component's file though to co-locate the messages with where they are used.
