### ISSUE TITLE
FormattedMessage Component Doesn't Accept className

### ISSUE THREAD

**Issue by tswardenski** [yahoo/react-intl#704]
I've noticed when using the `<FormattedMessage id="some.string.id" />` component, the output is something along the lines of:

```html
<span>Some message from my i18n strings file.</span>
```

I don't mind the `<span>` container or any other potential container that I can specify, however I am unable to add a `className` to the `<FormattedMessage />` component to add a class to the containing element. 

This is a decently large inconvenience when trying to keep clean markup output in my web app. I understand I can use the `formattedMessage` function, but I'd prefer to use components when possible in JSX. Thoughts on adding the `<FormattedMessage className="some-class" />` functionality or suggestions on how to properly add a class to the containing `<span>`? 

Thanks!

**Comment by dccourtney** [comment]
👍 to being able to pass className through

**Comment by divyamistry** [comment]
Yes please! This would be useful. MUCH nicer than wrapping `<FormattedMessage />` into another `div` or `span` with some styling.

**Comment by sf-adam-randall** [comment]
👍 yeah I would use this

**Comment by ericf** [comment]
This has been brought up many times, and is not something I plan to support. You can always provide a function-as-child to customize the rendering.

In the future, React will likely be supporting components returning strings from `render()` with React Fiber, so then React Intl won't have have to wrap everything with `<span>`s.

Also, I'm thinking about this a the future direction for `<FormattedMessage>`, which would allow customization without needing to provide a function as a child: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by mctep** [comment]
I like decision which is used in [React Semantic UI](http://react.semantic-ui.com/elements/label) with `as` property for resolving this issue. 

```jsx
<FormattedMessage as="div" id="..." />
// transforms to
<div>message</div>

<FormattedMessage as={ props => <span { ...props } className="class" /> } id="..." />
// transforms to
<span class="class">message</span>
```

It looks like it has [pretty simple realization](https://github.com/Semantic-Org/Semantic-UI-React/blob/d41aef02f3e6ba2195b4d207cbaac128c4bd491c/src/lib/getElementType.js#L10) and support.

**Comment by JetFault** [comment]
Now that React 16 supports `render` returning a `string`, whats the plan for `FormattedMessage`?

**Comment by bjornicus** [comment]
For the common case where you're ok with <span> and just want to be able to pass a classname, defining your own component like this seems to work ok:

```
const FormattedMessageWithClass = props => (
    <FormattedMessage {...props}>
      {(txt) => (
        <span className={props.className}>
          {txt}
        </span>
      )}
    </FormattedMessage>
  );
```

**Comment by FreddyFY** [comment]
You can return your content also without a surrounding component:
```javascript
<FormattedMessage id="foo">
    {...content => content}
</FormattedMessage>
```

**Comment by mukesh210** [comment]
@bjornicus Can you please provide some pointer on how to test it. I want to do unit testing on it.
