### ISSUE TITLE
intl.formatDate - month - 2-digits doesn't work on Chrome Window

### ISSUE THREAD

**Issue by lauterry** [yahoo/react-intl#706]
Hello

I'm trying to have a list of 2-digits month in a select component with the following code : 

```
var month2Digits = intl.formatDate(new Date(1970, +month - 1, 1), {month: '2-digit'})
```

Here is what i got : 

| month | month2Digits |               |
|-------|--------------|---------------|
| 1     | 01           |               |
| 2     | 02           |               |
| 3     | 03           |               |
| 4     | 03           | problem here  |
| 5     | 04           |               |
| 6     | 05           |               |
| 7     | 06           |               |
| 8     | 07           |               |
| 9     | 08           |               |
| 10    | 09           | probleme here |
| 11    | 11           |               |
| 12    | 12           |               |

I have this issue on Chrome 54.0.2840.71 m (64 bits) Window 10 Professional

Best regards

**Comment by lauterry** [comment]
I have tried to put 2016 instead of 1970 and it works.

It seems to have a problem with 1970 on chrome window

**Comment by ericf** [comment]
Can you open an issue on Chrome/V8's issue tracker?
