### ISSUE TITLE
How to add ukranian localeData?

### ISSUE THREAD

**Issue by Undeadlol1** [yahoo/react-intl#708]
It's seems like currently there is no ua.js locale data available.
I don't seem to understand how can i make my own, to make a Pull Request.
Can you point me at the right direction? Is there any guides?

**Comment by ericf** [comment]
The data exist under `locale-data/uk`: https://unpkg.com/react-intl@2.1.5/locale-data/uk.js

**Comment by Undeadlol1** [comment]
Well, that's a little bit confusing since international code of Ukraine is 'ua'.
Thank you very much for the response.

**Comment by ericf** [comment]
btw, all the locale data comes from CLDR: http://cldr.unicode.org
