### ISSUE TITLE
Zero values not rendering

### ISSUE THREAD

**Issue by mimecuvalo** [yahoo/react-intl#711]
Related to underlying Intl-messageformat bug https://github.com/yahoo/intl-messageformat/issues/144
Problem being here:

```
StringFormat.prototype.format = function (value) {
    if (!value) {
        return '';
    }
```

**Comment by ericf** [comment]
Closing since this is mentioned in another repo and has been discussed many times. Use `{foo, number}`

**Comment by mimecuvalo** [comment]
Seeing that there's many dupes of this and it's for dev's to shoot themselves in the foot here: https://github.com/yahoo/intl-messageformat/issues/88

Would it make sense at least when using a `plural` rule that it's implicitly treated as a number?

**Comment by ericf** [comment]
> Would it make sense at least when using a plural rule that it's implicitly treated as a number?

This feature already exists for plural rules using `#`. http://formatjs.io/guides/message-syntax/#plural-format

**Comment by mimecuvalo** [comment]
Sure, I've seen that - but it's easy to forget that.  Is there any reason you wouldn't expect/want a variable that's being treated as a plural to be implicitly as a number?
