### ISSUE TITLE
FormattedDate method displays the date in local lang, but not date

### ISSUE THREAD

**Issue by piyaa** [yahoo/react-intl#719]
Basically I'm trying to render the date in the japanese local time, which is a day ahead of US time.but formatteddate just translates the date in jp, rather than display the actual jp local date. what im i missing?
```
 return (<div><FormattedDate
                    value={props.data.lastUpdated} //value is nov 8 and accord to jp date it nov 9, but only translates in jp and renders the nov 8 as the date.
                    day="numeric"
                    month="short"
                    year="numeric" /></div>);
      },
```
How to display local date using FormattedDate method?

**Comment by ericf** [comment]
You can set the `timeZone` prop to a IANA TimeZone string.

See: https://github.com/yahoo/react-intl/wiki/Components#date-formatting-components
See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat
