### ISSUE TITLE
Allow tagName to be null

### ISSUE THREAD

**Issue by jmz7v** [yahoo/react-intl#721]
Hi, 

I'm seeing from #130 and #131 that `FormattedMessage` allows you to change the tag of the element that will be returned, however, I'm trying to translate the placeholder of an input element, in this particular case the translation should be returned as pure text instead of `<tag>Translation</tag>`.

I tried to set my message like `<FormattedMessage id='translationid' tagName={null} />` but it still returns an object, am I missing something from the docs or returning text only is not supported at the moment?

Thanks for this awesome project!

**Comment by ericf** [comment]
You should use the API for this: https://github.com/yahoo/react-intl/wiki/API#injection-api
