### ISSUE TITLE
How to load the json files while accessing the FormattedMessage comp

### ISSUE THREAD

**Issue by piyaa** [yahoo/react-intl#723]
I currently have :
```
`render() {
    return (
           <FormattedMessage
              id='description'
              defaultMessage='Hello, World!'

          />
    );
  }`
```

how do i load my json files containing the strings to load the string inside the 'id' field?

**Comment by ericf** [comment]
Please see the docs on the wiki and the example apps in this repo.
https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context
