### ISSUE TITLE
FormattedMessage camelCase values property issue

### ISSUE THREAD

**Issue by web2style** [yahoo/react-intl#728]
```
<FormattedMessage
      id='containers.Auth.AlreadyAccount.text'
      defaultMessage='Already have an account? {signIn}'
      values={{
        signIn: <Link className='arrowLink' to='/sign-in'>
          <FormattedMessage
            id='containers.Auth.AlreadyAccount.link'
            defaultMessage='Sign in'
          />
        </Link>
      }}
    />
```
This piece of code won't work, as `react-intl` lowercases `{signIn}` (transforms to `{signin}`) so that it doesn't match `signIn` property in the specified values object.

This is pretty important as we can't use `sign-in` as object property and just `signin` is unreadable and is even highlighted by my IDE as a typo.

**Comment by ericf** [comment]
This shouldn't be the case. There shouldn't be code that calls `toLowerCase()`. Can you create a simple reproducible example or failing test case?

**Comment by web2style** [comment]
I don't claim there's `toLowerCase()`. But the code above throws the following error for me:
```
[React Intl] Error formatting message: "containers.Auth.AlreadyAccount.text" for locale: "en", using default message as fallback.
Error: A value must be provided for: signin
```
Note the lowercase `signin`.

When I change both to `signin` myself, it works as expected.

**Comment by ericf** [comment]
Could you create a simple example to show the issue? Maybe you could make tweaks to the https://github.com/yahoo/react-intl/tree/master/examples/hello-world example and show the problem?

**Comment by ericf** [comment]
Closing this, but please reopen if you have a running example that I can use to reproduce the issue.
