### ISSUE TITLE
custom component 'wrappers'

### ISSUE THREAD

**Issue by athibaud** [yahoo/react-intl#73]
another thing i think would be useful is to be able to wrap react-intl components in our own components

i see there already is support for [string tags](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L13), but that limits us to html only.
say i have a `Text`component, i'd like to do
```js
<ReactIntl.FormattedMessage
  message="yizeerr"
  component={require('components/Text')}
/>
```

i tried it out quickly yesterday and it worked, so it should be quite easy to implement. i could submit a pull request soon if you're okay with that.

one thing i still don't know is how to properly 'propType' that component.
i suppose with react 0.13 we could have something like `React.PropTypes.instanceOf(React.Component)`

i've only needed that for `FormattedMessage` so far but it could be useful for the other components

**Comment by caridy** [comment]
can you explain more what the use-case is? why do you want to use a custom component implemented by yourself for the wrapper element?

**Comment by athibaud** [comment]
well, in the same way that `<p>` or `<h*>` tags have default styling and behaviour in browsers, you could want your own component which come with its own styles and event handlers..

the fact that you already let the user chose which html tag will wrap the react-intl component i thought it could be easily extended to having custom components wrap react-intl components.

we've gone the full css in js way and it seems like more people are going that direction.
so here is our use case: we have a `Text` component that we use for most of our text blocks which has default styling like `line-height` and `::selection` etc. that component merges the `style` prop its passed with its internal default style.

so we'd like to be able to do something like this:

```js
<ReactIntl.FormattedMessage
  message="hello {maintainer}"
  component={require('components/Text')}
  maintainer="caridy"
  style={{ color: blue }}
/>
```

rather than:
```js
var Text = require('components/Text');
<Text
  style={{ color: blue }}>
  <ReactIntl.FormattedMessage
     message="hello {maintainer}"
     maintainer="caridy"
  />
</Text>
```
and have an 'extra' span in my dom tree...

**Comment by athibaud** [comment]
closing this one because as i mention [here](https://github.com/yahoo/react-intl/issues/72#issuecomment-72436796) it has deeper implications than i thought. namely if the wrapper component needs specific props it would complicate the current implementation.

i'm convinced there is little use for this now. friday evening issue. bad idea :)
