### ISSUE TITLE
FormattedRelative: "Invalid Date" on iOS

### ISSUE THREAD

**Issue by mxmtsk** [yahoo/react-intl#733]
Hey,
I'm using FormattedRelative to show a more human readable date and it works perfectly fine on desktop, but on iOS I'm getting Invalid Date with no console error/warning.

`<FormattedRelative value={post.publish_date} />`

The value is a datetime value from my database. How can I debug it or is this a known error?

**Comment by ericf** [comment]
It would be helpful to have more information about the browser version and the actual value of `post.publish_date` from your database.

**Comment by mxmtsk** [comment]
Hi @ericf! The value looks like this: "2016-11-04 13:49:58". The Browser is Safari on iOS 10.1 (14B67).

**Comment by ericf** [comment]
@mxmtsk you need to make sure the value conforms to the date strings that can be processed by `Date.parse()`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

http://tools.ietf.org/html/rfc2822#page-14
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

**Comment by mxmtsk** [comment]
@ericf thank you very much, works now!
