### ISSUE TITLE
How to specify a value within a value?

### ISSUE THREAD

**Issue by joetidee** [yahoo/react-intl#734]
I have the following sentence in my translation file:

`"mytext": "(this issue {spanOpen}will{spanClose} be solved)"`

and I have tried to format this using the following code:

```
<FormattedMessage
     id="mytext"
     values={{spanOpen: <span style={{color:'#888',textDecoration:'underline'}}>,spanClose: </span>}}
/>
```

but get the following error in the browser console:

> [React Intl] Error formatting message: "mytext" for locale: "en-GB"
> Error: A value must be provided for: spanClose

**Comment by ericf** [comment]
This is a current limitation where there isn't a great/clean solution for. I wrote a proposal on how to address this here: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

_Marking this as a dup of #513_
