### ISSUE TITLE
[Question] How to check if translation string/id exists?

### ISSUE THREAD

**Issue by tswardenski** [yahoo/react-intl#747]
I have a bit of an odd scenario where I'm displaying a list of mixed values; some system default string values that need to be translated, and some user defined strings that shouldn't be translated. 

I've gone through the docs a handful of times to see if there's a "pretty" way to check if a translation string ID exists and I ended up just implementing:

```JavaScript
if (formatMessage({ id: `some.key.${value}` }) !== `some.key.${value}`) { 
  // do stuff
}
else {
 // do other stuff
}
```

I don't like this method as it ends up giving me a TON of console errors. I'm wondering if there's a better way to do this. Any direction is appreciated!

Thanks!

**Comment by ericf** [comment]
@tswardenski yeah this has come up before. My recommendation is to create a component to handle this. I'm not sure on your exact API of how to you want to receive `value`, but here's a place to start: https://github.com/yahoo/react-intl/pull/488#issuecomment-224945705

**Comment by tswardenski** [comment]
@ericf thanks for the reference. It looks like maybe I could get away with doing something like this?

```JavaScript
const stringExists = !!this.props.intl.messages[`some.key.${value}`];
```

Thoughts?

**Comment by ericf** [comment]
Yeah, exactly!
