### ISSUE TITLE
Extra spaces in FormattedDate break style in Edge browser

### ISSUE THREAD

**Issue by lauterry** [yahoo/react-intl#748]
Hi

The following code in Edge browser

```
<div>
<FormattedDate value={ new Date() } weekday="short" day="2-digit" month="short">
</div>
```

generates 

```
<div><span>ven.‎ ‎02‎ ‎déc.</span></div>
```

which, one escaped, gives

```
&lt;div&gt;&lt;span&gt;ven.&#x200e; &#x200e;02&#x200e; &#x200e;d&eacute;c.&lt;/span&gt;&lt;/div&gt;
``` 

As you may see, there is extra ```&#x200e;``` surrounding the space between ```ven.``` and ```02``` which break style.

You can see what I mean by going [here](http://codepen.io/anon/pen/eBWKLz) with Edge

**Comment by lauterry** [comment]
Seems to be related to https://github.com/Microsoft/ChakraCore/issues/1282

**Comment by ericf** [comment]
Yeah, there isn't anything we can safely do to remove these control chars that works in all cases. The Chakra repo is the right place to follow-up on this issue.
