### ISSUE TITLE
Question: How can use formatMessage inside a redux action?

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#751]
I need to use translated messages in a redux action. How do I do that?

**Comment by ericf** [comment]
It would be helpful to know more about what you're trying to do.

**Comment by mschipperheyn** [comment]
Well, I have redux actions that can fail. If this happens I generate a failureStatus action that takes a message as an argument. That message needs to be i8n

**Comment by mschipperheyn** [comment]
This seems like a solution: https://github.com/yahoo/react-intl/issues/416#issuecomment-223039994

**Comment by ericf** [comment]
I also like passing React Elements through actions. It seems a little weird at first, but React Elements are descriptors of rich messages, and that's exactly what you're looking to pass through Redux with your action.
