### ISSUE TITLE
Is it possible to use the api with typescript ?

### ISSUE THREAD

**Issue by ermoca** [yahoo/react-intl#752]
I would like to use the formatMessage function of the react-intl API to insert a message as placeholder, but I can't figure out the right way to access this function.

Here is a simplified version of what I have :

    //index.tsx
    <IntlProvider locale={`fr-FR`} messages={messages_fr}>
        <NameForm/>
    </IntlProvider>,

    //nameForm.tsx
    interface NameFormProps {
       intl?: InjectedIntlProps,
    }

    export default injectIntl(NameForm);

    class NameForm extends React.Component<NameFormProps, {}> {

    render() {
        let namePlaceholder = this.props.intl.formatMessage(
            {id: "NAME_PLACEHOLDER",
            defaultMessage: "name"
        });
        
        return (
            <form>
                <input placeholder={namePlaceholder} type="text"/>
            </form>
        );
    }

I used InjectedIntlProps as type of the intl prop, because IntlShape didn't seems to offer a formatMessage method.

I Added a ? to the intl prop because I kept having a "Property 'intl' is missing" (but isn't injectIntl supposed to return a component without this prop ?)

Now it compiles, but when running I get an error ("Cannot read property 'displayName' of undefined" I guess because the default export doesn't have an explicit name).

I feel I'm not going in the right direction, but can't find any example of a typescript/react-intl project.

Thanks for your help !

**Comment by bcage29** [comment]
Add "@types/react-intl": "2.1.0", to your packages.json in devDependencies

**Comment by ericf** [comment]
@bcage29 would you mind adding this to the docs on the wiki?

**Comment by ermoca** [comment]
thank you @bcage29 ! I hadn't thought of that.

**Comment by ermoca** [comment]
well, I just tried and it doesn't solve my problem 
I already had "react-intl" : "*" in my packages.json listed in dependencies and using @types/react-intl instead didn't change the errors

**Comment by bcage29** [comment]
@ermoca did you do an npm install?

**Comment by ermoca** [comment]
yes. I already use react-intl to create <FormattedMessage> elements and it works like a charm so I guess I have all the needed dependencies. It's just when trying to use the api to translate a placeholder attribute that I can't find the right way.

**Comment by ericf** [comment]
Since the TypeScript bindings aren't officially supported (in that I don't work on them), I'm gonna close this out.

**Comment by karlfus** [comment]
Try moving the "export default injectIntl(NameForm);" to come *after* the NameForm definition.

**Comment by ermoca** [comment]
Oh sorry, I forgot to put the answer i found. Thanks anyway Karlfus ! 


The problem was due to the version of the typescript definition. When using @types/react-intl": "^2.2.0", it works like a charm.

(Few changes -> move the export default line + use InjectedIntlProps) :

```
//index.tsx
<IntlProvider locale={`fr-FR`} messages={messages_fr}>
  <NameForm/>
</IntlProvider>,

//nameForm.tsx
interface NameFormProps extends InjectedIntlProps {
  placeholder: string,
}

class NameForm extends React.Component<NameFormProps, {}> {

  render() {
    let namePlaceholder = this.props.intl.formatMessage({
       id: this.props.placeholder,
       defaultMessage: "name"
      });

    return (
      <form>
        <input placeholder={namePlaceholder} type="text"/>
      </form>
    );
}

export default injectIntl(NameForm);
```

**Comment by baurine** [comment]
In the react-intl new version (3.12.0), we don't need `@types/react-intl` anymore, react-intl has its own type definition, and `InjectedIntlProps` doesn't exist anymore, it is named `WrappedComponentProps` instead.

My sample code:

```ts
import { FormattedMessage, injectIntl, WrappedComponentProps } from 'react-intl'
import { Form, Input, Radio, Button } from 'antd'

type Props = {
  name: string
} & WrappedComponentProps

function MyComponent({ name, intl }: Props) {
  // ...
  return (
    // ...
    <Form.Item label={intl.formatMessage({id: 'xxx'})}...>...</Form.Item>
  )
}

export default injectIntl(MyComponent)
```

**Comment by baurine** [comment]
After reading the docs about [upgrade to 3.x](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md), now it has simpler way, just  use `useIntl` hook:

Sample code:

```ts
import { FormattedMessage, useIntl } from 'react-intl'
import { Form, Input, Radio, Button } from 'antd'

type Props = {
  name: string
}

function MyComponent({ name }: Props) {
  const intl = useIntl()
  // ...
  return (
    // ...
    <Form.Item label={intl.formatMessage({id: 'xxx'})}...>...</Form.Item>
  )
}
```
