### ISSUE TITLE
Generate Messages with configuration files.

### ISSUE THREAD

**Issue by ole3021** [yahoo/react-intl#753]
hi , i love the idea of react-intl, and we are currently use it in our project, but i have a problem, and looking for your help or suggestions of the best way to use react-intl with configurations files. 

The case is i have define a bunch of items (like menus items) in a configuration file, like below 

```javascript
{
    'name': 'Broadcasts',
    'category': 'FUNCTIONS',
    'href': '/functions/broadcast',
    'title': 'Broadcast',
    'subTitle': 'Send messages to followers',
    'iconClass': 'fa fa-fw fa-question',
    'baseUrl': '/'
  },
...
```

and i would love to use the configuration's `name` as `id` and `title` as `default message`, but i cant use it simply with set the property to the `id` and `default message`. 

currently we have generate another file to save the `defineMessages ` and reference to the messages with the configuration's `name`. 

I wondering what the best practical to make this happen, or what you guys do when you have this kind of problem. 

Thanks for your help

**Comment by ericf** [comment]
You could write a mapping function to do this simply and at runtime:
```js
messages = messages.map(({name: id, title: defaultMessage}) => {id, defaultMessage});
```
