### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by lirsacc** [yahoo/react-intl#754]

**Comment by MarianyFerreira** [comment]
/* Component FormattedMessage */
<FormattedMessage
   id="key"
   values={{
     breakingLine: <br />,
   }}
/>
 
/* function intl.formatMessage() */
 
 
{ intl.formatMessage({ id: "key", values={ breakingLine: <br /> } }) }
 
 
/* strings file */
 
key: `This is a {breakingLine} breaking line`,

**Comment by douira** [comment]
I'd like to add that this also works with newlines. Formatjs seems to remove newlines from strings (at least in my code, using it with React Native). The same thing works for inserting newlines in the string:
```tsx
<FormattedMessage
  id="FooPage.headline"
  defaultMessage="First line{newline}Second line"
  description="description"
  values={{ newline: "\n" }}
/>
```

**Comment by longlho** [comment]
we discouraged using `\n` for the sake of positioning. Newline is i18n-sensitive. Some languages don't even have spaces.
