### ISSUE TITLE
Browser Infinite Loading

### ISSUE THREAD

**Issue by andregoncalvesdev** [yahoo/react-intl#755]
I already used this plugin and i had no problems. But now i´m using webpack dev server and it seems that everytime i use Formatted Message component or formatMessage function, the browser freezes and keeps on infinite loading. 

My component: 

```
import React, { Component } from 'react';
import { FormattedMessage } from 'react-intl';
import messages from './messages.js';
import styles from './styles.scss';

class App extends Component {
  render() {
    return (
      <div className={styles.appContainer}>
        <FormattedMessage {...messages.example} />
      </div>
    );
  }
}

export default App;
```

Messages file:

```
import { defineMessages } from 'react-intl';

export default defineMessages({
  example: {
    id: 'app.containers.app.example',
    defaultMessage: 'Example Message !',
  },
});
```

Also the IntlProvider is set:
![screen shot 2016-12-02 at 11 34 51](https://cloud.githubusercontent.com/assets/9271177/20832677/7d193a56-b883-11e6-8d3a-0586f252e839.png)

The strange thing is that if i build the project, it works. Using webpack-dev-server it freezes.

**Comment by ericf** [comment]
In order to help, I'd need to be able to run a simplified example app that shows the issue. If you wanted to create a very simple app that uses React Intl and webpack-dev-server in a repo that I can access let me know and I can try it.

**Comment by ericf** [comment]
Please feel free to reopen with a reproducing example where I can debug the problem if you're still experiencing it.
