### ISSUE TITLE
Add method setAliasForDefaultMessage()

### ISSUE THREAD

**Issue by helgiborg** [yahoo/react-intl#756]
This library is in many ways brilliant but a drawback imho is that the way to format messages is quite bloated. When you have a lot of short text in your React components, as is sometimes the case, the readability of the jsx part of the render() method will suffer because the texts "FormattedMessage" and "defaultMessage" are quite long.

How about to add a setAliasForDefaultMessage() method to the library?

index.js:

```
import { IntlProvider, addLocaleData, setDefaultMessageAlias } from 'react-intl';  

setAliasForDefaultMessage('m');

```

MyComponent.js

```
import { FormattedMessage as _ } from 'react-intl';

// In the render method of MyComponent:
<_ id="more" m="More" />
```

Best regards, 
Helgi Borg

**Comment by ericf** [comment]
This is a dup of #609 + #612, but this is on hold for a more radical approach to solving the bloat problem described in: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827
