### ISSUE TITLE
Is it possible to add a <span> tag to style a part of the message?

### ISSUE THREAD

**Issue by steven5210** [yahoo/react-intl#766]
Is it possible to add a <span> tag to be apart of the message so that for example I can make a part of the message to be bold? I.E. "```blah blah is <span className="bold">7.99</span> blah```."  Right now I"m using formattedmessage to have it render the currency as USD. I tried doing it like this below but it throws an error that it's not a number and that's due to the <span> tags that's part of the message. The only way I can think of doing this is not using formattedMessage or having a nested formattedMessage. Thanks!

![image](https://cloud.githubusercontent.com/assets/10110177/21117733/ccdfed0c-c06f-11e6-9d0b-0fbc0425cba8.png)

**Comment by Chatatata** [comment]
What kind of approach did you prefer to solve the issue?

**Comment by steven5210** [comment]
Without using formattedHtmlMessage we went with the nested formattedMessage approach.

```    
    const shippingMessage = (
      <span className="product-list-shipping-total bold">
        <FormattedMessage
          id="cxo/product-list-title/shipping-message"
          description="total shipping cost"
          defaultMessage="{shippingTotal, number, USD}"
          values={{
            shippingTotal
          }}
        />
      </span> 
```
        <span className="product-list-shipping-total pull-right">
          <FormattedMessage
            id="cxo/cxo-items/active/list/totalShippingCost"
            description="totalShipCost"
            defaultMessage="Shipping cost is {shippingMessage}"
            values={{
              shippingMessage
            }}
          />
        </span>
```

**Comment by ericf** [comment]
I'm working towards a better solution for rich text messages: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by steven5210** [comment]
Thanks for the update! It looks good so far!
