### ISSUE TITLE
How to handle HTML?

### ISSUE THREAD

**Issue by joetidee** [yahoo/react-intl#767]
I have the following HTML in my language file:

`"blah" : "<p style={{paddingBottom:'10px'}}>This is some text with {numItems} in it. Here is a second variable called {anotherVar}.</p>"`

I am using this:

`<FormattedMessage id="blah" values={{ numItems: "some text", anotherVar: "foobar"}} />`

Looks like the process is escaping the HTML, so how do I have the text in the language file and pass the two variable to it?

**Comment by yodaddyp** [comment]
[`<FormattedHTMLMessage />`?](https://github.com/yahoo/react-intl/blob/master/src/components/html-message.js)

**Comment by joetidee** [comment]
The docs say that FormattedHTMLMessage should only be used for legacy code and to use FormattedMessage going forward.

**Comment by maxdeviant** [comment]
This is how we have been doing it:

```jsx
<FormattedMessage
  id='my_message'
  defaultMessage='Here is some {bolded} text.'
  values={{
    bolded: (
      <strong>
        <FormattedMessage
          id='bolded'
          defaultMessage='bolded' />
      </strong>
    )
  }} />
```

It seems that HTML within the `values` prop is not escaped.

**Comment by joetidee** [comment]
Thank you very much.
