### ISSUE TITLE
Is there a way to load i18n messages from server ?

### ISSUE THREAD

**Issue by kopax** [yahoo/react-intl#768]
I am trying to figure out how to implement two things with the current internationalization

1. How to inject in production extra messages from server
1. How to store message in advance in order to read it from an id key returned by the server

I have an API endpoints with some messages that are not stored on the client with the following structures `[{ id: 'com.hello', defaultMessage: 'Hello' }]`

I would like to know if there is a way to inject them in the application, these translation would be downloaded during login.

Alternatively, I also would like to know if it's possible to have these key bundled with the client app if it's not used at all in any components.

This way, the key returned by the server could load a previously local translation.

**Comment by m1m6** [comment]
I'm working on something like that, What i tried to do is -
 1- send a sync request to endpoint to get translations as JSON, then store the results in localStorage
2- When providing the messages to IntlProvided, I did the following` IntlProvider locale="en-US" messages={localStorage.getItem("TranslationLanguage")}`

**Comment by ericf** [comment]
You can treat the translated messages as data, and fetch them from your endpoint like you mentioned. Simply pass the translated messages to `messages` and set the `locale` on your `<IntlProvider>` element.
