### ISSUE TITLE
How to generate multiple locale translation files and merge them

### ISSUE THREAD

**Issue by bensampaio** [yahoo/react-intl#770]
I have found several discussions about this but none of them provide a concrete answer, so here I am :)

I recently started using react-intl in my project and I am quite happy with the way it works. My all app is working in English but the problem now is. How do I add translations for Dutch and Spanish, for example?

I am using [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) but I don't really understand the point of it... It generates JSON files for every translation file in my `src`, but since I need to support multiple locales I would expect a JSON file per locale for each translation file in my `src`. However, [babel-plugin-react-intl](https://github.com/yahoo/babel-plugin-react-intl) has no option to specify the locales of my application. Am I missing the point of this plugin? My translation files already have a default message written in English so I assume I don't need translation files for English, then why generate just one JSON file per translation file? Also, I would like to merge all translations for every locale into a single locale JSON file and this doesn't seem to provide a way to do that.

As an example, if I have the following folder structure:

```
src/
  components/
    app/
      translations.js (translations for App component)
    home/
      translations.js (translations for Home component)
```

After running `babel-plugin-react-intl` I would expect:

```
build/
  components/
    app/
      es.json (Spanish translations for App component)
      nl.json (Dutch translations for App component)
    home/
      es.json (Spanish translations for Home component)
      nl.json (Dutch translations for Home component)
```

And after editing the translations I would like to be able to do something to get:

```
public/
  trans/
    es.json
    nl.json
```

I also came across [react-intl-translations-manager](https://github.com/GertjanReynaert/react-intl-translations-manager) and from the description I think it does what I expect (but not sure since I didn't try yet).

So my questions are:

- Am I missing the point of `babel-plugin-react-intl`?
- Is `react-intl-translations-manager` a good option?
- Are there any plans to add similar functionality to the one `react-intl-translations-manager` provides to `babel-plugin-react-intl` in the future? I ask this because this seems to be a very typical use case and I find it weird that a library for i18n doesn't provide a clear way on how to support multiple translations... And don't get me wrong, I'm quite thankful that this project exists but I only decided to use it because the documentation gave me the impression this part would be relatively easy to accomplish instead I am lost in dependencies trying to understand if I should use them, create my own solution, or give up on react-intl. This makes me question if this is a future proof solution...

Thank you!

**Comment by ericf** [comment]
The Babel plugin extracts the default (English in your case) messages from your source files into JSON data files. This allows you to co-locate your message definitions where the messages are actually used in your UI. Since Babel works on a per-file basis, the plugin ends up outputting a `.json` file for every `.js` file that has messages defined in it.

You can checkout the _Translations_ example app in this repo: https://github.com/yahoo/react-intl/tree/master/examples/translations

This example shows how you can aggregate all of the `.json` files created by the Babel plugin into one big JSON file. The idea is that you would then send this file off to your translation system/service and get back translated messages. Once you have the translated messages in their own `.json` files, you can then use them to create a `{'message-id': 'translated message'}` object which can be fed into `<IntlProvider message={}>` at runtime.

Does that make sense?

**Comment by bensampaio** [comment]
Hi @ericf,

Thank you for the detailed answer. I get it now. In the meantime, I also tried `react-intl-translations-manager` and it seems to do exactly what I wanted (only not in the way I expected).

Just to make sure I understood: when you say that Babel works on a per-file basis, you mean that it cannot generate more then one `.json` file per `.js` file? If that's the case, is there no way to keep the resultant JSON file in memory so it can be passed into a tool like `react-intl-translations-manager` and then this tool would be responsible for generating JSON files for every locale? I ask this because at the moment what I am doing is:

- Run the babel plugin and save it's output into a `tmp` folder;
- Run `react-intl-translations-manager` in the `tmp` folder and save the result in a `trans` folder;
- Delete the `tmp` folder;

While this works, I think creating a `tmp` folder is a bit weird, imo it would be better to be able to pass the result of the babel plugin into another tool without saving it to the filesystem. But maybe this kind of behaviour is not supported by Babel and if that's the case then I guess this is the best option.

**Comment by ericf** [comment]
The role of the Babel plugin is still internationalization, not localization. Co-locating your default strings with your source code is a better developer experience, and doing that pushes move the i18n problem to the compiler where the Babel plugin can extract the strings programmatically. The strings the Babel plugin extracts are still the default English strings, but it's provides them in a JSON format which you can more easily bundle up and send to your translator, translations system, or service.

It's the job of the translator person, system, or service to do the actual localization of the strings and create some data file per language you want your app to work in. Once you have these translated strings you can then feed them into `<IntlProivder>` by setting the `locale` and `messages` props. At runtime `<FormattedMessage>` will attempt to use the translated string passed in via `messages` to `<IntlProvider>` before falling back to using the default English string defined on the `defaultMessage` prop.

**Comment by bensampaio** [comment]
Ok, I think that's clear enough. Thank you a lot for the detailed answers. I think this should be a bit more clear in the documentation, though.

**Comment by ericf** [comment]
Yeah I agree, sorry.

**Comment by adamklepacz** [comment]
The documentation says only about API options and it has one pure example, but it should have a full tutorial on **how to apply this library to React app.** 

I'm currently fighting with this reac-intl and after 4hours I'm still not able to get one file with all the translations from defaultMessages....

Documentation is very pure, to be honest guys.
