### ISSUE TITLE
defaultFormats without "format" prop on every Formatted*?

### ISSUE THREAD

**Issue by souptown** [yahoo/react-intl#772]
I'd like all <FormattedDate/> components in my app to use 2 digits months and days. 

Is it possible to specify this using \<IntlProvider\> without adding a format="foo" prop to every \<FormattedDate\>?

This doesn't seem to do it:
```
<IntlProvider ... defaultFormats={{ date: { month: '2-digit', day: '2-digit' } }}>
```

**Comment by ericf** [comment]
There isn't a way to do this because the recommendation is to just use React and create a component which has your defaults pre-set.

```js
import {FormattedDate} from 'react-intl';
export const MyFancyDate = (props) => (
  <FormattedDate month='2-digit' day='2-digit' {...props}/>
);
```

**Comment by souptown** [comment]
Thank you for the clarification.
