### ISSUE TITLE
FormattedDate displays the wrong date in Japanese 

### ISSUE THREAD

**Issue by JohnSmith0602** [yahoo/react-intl#776]
```javascript
<IntlProvider locale='ja-JP'>
    <FormattedDate value={date} year='numeric' month='long' day='2-digit'/>
</IntlProvider>
```

It's just a simple case, the output of it is like: September 01, 2016.
It seems like a default date in English rather than a date in Japanese.

I change the locale to zh-CN & fr-FR, it works as expected, like 2016年11月01日.

I have the latest version 2.1.5 of react-intl, wonders what I can do then. Many thanks!

**Comment by ericf** [comment]
What browser and version is this in?

**Comment by JohnSmith0602** [comment]
Chrome  55.0, Safari 10.0.1, Firefox 50.1.0, they all have this issue, seems independent of the browser.

**Comment by JohnSmith0602** [comment]
Sorry, I just made a stupid mistake of missing ja file when addLocaleData.
