### ISSUE TITLE
Is it possible to lazy load language files into my app?

### ISSUE THREAD

**Issue by joetidee** [yahoo/react-intl#780]
As far as I understand it, react-intl will extract language message from code files and place them into seperate files to be bundled into the application. However, if the application switches language based on the end-user selecting which language they prefer, or by referncing the end-users language setting (in their Account, for example), is there a way to dynamically load in a language when needed rather than include all the languages up front. My concern is that including all the languages up front would mean that the application would have to download a lot of informatino even though the user is likely just to use one language.

**Comment by ericf** [comment]
Yes this is possible. The best way to think about the translated messages is thinking of them as data you'd get back from an API response. You'd just need to load the them async from the network, and re-render once they're loaded by updating `<IntlProvider>` with the new `locale` and `messages` values.

Many people have asked about this so there's other issues you can dig through to see different strategies people have done with Redux, React Router, Webpack `require.ensure()`, etc.

All that said, you can also think about client-side locale switching similar to a client-side user switching. In that the simplest thing to do is just reload the app from the server when the user wants to switch locales, as this isn't something people are doing to do frequently, or more than once.

So, it's entirely possible, think of translated messages as any other API data, but likely overkill.
