### ISSUE TITLE
Is it possible to cal api methods without inject each component

### ISSUE THREAD

**Issue by m1m6** [yahoo/react-intl#781]
Hi , i'm wondering if there's any way to call API methods without inject each component ?

somthing like providing a function that will call intl.formatMessage for example

export function t(id,defaultmessage){
  console.log("Called ",id,defaultmessage);
  return intl.formatMessage(
    {
      id: id,
      defaultMessage: defaultmessage
    }
  )
  }

**Comment by ericf** [comment]
Possible, sure, you can create an instance of a component with `intl` injected and save a ref to its `this.props.intl.formatMessage` function in an outer scope. But I wouldn't recommend this. If you want to provide a function that builds on the injected `intl` context, then you might want to write an HOC that either replaces `injectIntl()` or wraps it and adds your function which delegates to `intl.formatMessage`

**Comment by m1m6** [comment]
Thanks exicf for your reply,
for the first point i'm not sure that i understand what you said exactly, but it seems like 
creating a component and inject it with injectIntl, then use a VAR and set its value to be this.props.intl.formatMessage , then by exporting this var i can use it form outside?

for the second point,may i'll try it if the first doesn't seem to be good enough.

**Comment by idarbuashvili** [comment]
@beeant Its interesting to use injectIntl in this way, but is this good practice to use?
