### ISSUE TITLE
Style prop and linters

### ISSUE THREAD

**Issue by brainlessdeveloper** [yahoo/react-intl#785]
Hello there and thanks for the wonderful library,

The `style` prop on `FormattedRelative`, `FormattedNumber` and `FormattedPlural` triggers errors/warnings on most widespread linter configurations, which expect its value to be an object for CSS-like styles.

I think these linter configurations have a point, and the `style` prop on these components should be named with a new name that's not reserved by React or HTML.

I know such a change, even if simple, would be breaking for many existing apps. Is it worth considering an alias or a secondary way of defining the `style` prop, while keeping the ability to name it `style`?

**Comment by ericf** [comment]
This is a bug in the linter. `style` isn't a reserved, predefined prop in React. The linters should only be enforcing this on primitive elements (lowercase), `<span>`, etc.

`style` is part of the Intl API options which React Intl uses: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by brainlessdeveloper** [comment]
Got it, you're totally right! Thanks, I'll look into fixing my linter configs.

**Comment by bryant988** [comment]
@brainlessdeveloper were you able to successfully exclude it in linter configs?

**Comment by brainlessdeveloper** [comment]
@bryant988 I set the prop gravity to zero. There's some discussion https://github.com/yannickcr/eslint-plugin-react/issues/849 but I don't want to bother with the problem anymore.

**Comment by SidFerreira** [comment]
@ericf I just read both this and the ESLint discussion. And I was wondering: would it be too much a problem if we add a `intlStyle` prop, that's an alternative way to set the `style`? I know it is silly, but it's freaking annoying that message. And I would like to keep the default settings of the lint at the same time.

**Comment by ivanmorales** [comment]
I was able to solve the problem by passing the `style` as a prop to the component with a default string value:

```JSX
const Money = ({ value, style="currency" }) => (
  <FormattedNumber style={style} value={value} currency="USD" />
)
```

This gets rid of the eslint warning for me.

**Comment by ziemkowski** [comment]
I'd suggest an attribute named `variant` that maps to the Intl API style prop, since it more correctly describes what is being requested and is used frequently in other projects (such as material-ui).  

```jsx
<FormattedNumber variant="currency" value={value} />
```

I doubt the average developer using `react-intl` is going to know that the root API uses a different term. At the same time, accepting a `style` attribute that isn't rendered on the returned `span` is a React anti-pattern, though I understand that'll be difficult to walk back (unless a typeof string check would suffice for legacy behavior?).

**Comment by joshunger** [comment]
@ziemkowski maybe you could open a new issue? 👍

**Comment by phlare** [comment]
this worked for me to ditch the lint warning:
`<FormattedNumber
    value={price}
    style={`currency`}
    currency={currency || 'USD'}
    minimumFractionDigits={2}
    maximumFractionDigits={2} 
/>`

**Comment by enuchi** [comment]
Unfortunately the above workaround violates another lint rule:
`Curly braces are unnecessary here. eslintreact/jsx-curly-brace-presence`

**Comment by lhrnd0** [comment]
For future reference, the linter rule that causes this problem now has an option to allow certain components.

```yaml
react/style-prop-object:
  - error
  - allow:
    - FormattedNumber
    - FormattedNumberParts
    - FormattedRelativeTime
```

**Comment by thmsgbrt** [comment]
Thanks @lhrinaldi, adding tis to my .eslintrc.js did the job:
`
'react/style-prop-object': [
  'error',
  { allow: ['FormattedNumber', 'FormattedDateParts', 'FormattedRelativeTime'] },
],
`

**Comment by strarsis** [comment]
@thmsgbrt, @lhrinaldi: Is there a mechanism that allows `formatjs` to inject these exceptions for `react/style-prop-object` into the project? Can this extra config be inherited automatically?

**Comment by lhrnd0** [comment]
@strarsis the only way I think this could be done is through their eslint plugin https://formatjs.io/docs/tooling/linter

**Comment by pjchender** [comment]
Adding the rule in your ESLint config might help:

```json
{
  "rules": {
    "react/style-prop-object": ["error", {
      "allow": ["FormattedNumber"]
    }],
  }
}
```
