### ISSUE TITLE
Regression: missing "key" prop warning

### ISSUE THREAD

**Issue by ipanasenko** [yahoo/react-intl#787]
Hi, guys!

I've updated to 2.2.0 and noticed that when I provide a message as a value to another message, React started throwing warning regarding missing key prop.

Here are a couple of jsbins to show you what I mean, have a look in the console

2.1.5: http://jsbin.com/jumogusomo/2/edit?html,js,output
2.2.0: http://jsbin.com/jumogusomo/3/edit?html,js,output

Can you have a look, please?

**Comment by ipanasenko** [comment]
I think this is what causing it: https://github.com/yahoo/react-intl/commit/f211d024f8a97df2934dca77720eed06abf937c7#diff-b7d9ab5e91ff171c3c4dcfad50320401R132

**Comment by ericf** [comment]
Thanks for reporting this. I see the error that you mentioned. I'll look at resolving it.

**Comment by ericf** [comment]
@ipanasenko I verified that your hunch was right. I will work on reverting this change, and also adding a test for it.
