### ISSUE TITLE
React Native: missing message key leads to red screen of death

### ISSUE THREAD

**Issue by mschipperheyn** [yahoo/react-intl#789]
When a message is missing from the message store, it is reported through a console.error. 
In React-Native, this leads to a red screen of death and basically blocks you until you add the key. This is extremely annoying and unproductive. Is it possible that a missing key is reported through a console warning instead of an error? 

I personally don't consider a missing key is an error because they tend to be handled in one go through a third party extraction tool. But I know the Yahoo team feels different about this.

**Comment by ericf** [comment]
If no message `id` is provided, it will cause an error to be thrown because there's nothing that can be rendered.

Can you be clearer as to what exactly you're talking about that's throwing the error? Can you provide an example?

**Comment by mschipperheyn** [comment]
<img width="375" alt="screen shot 2016-12-29 at 13 54 59" src="https://cloud.githubusercontent.com/assets/384959/21547623/6fcf01c2-cdce-11e6-9494-6b6493001d4f.png">
Sure, so, in this example I'm trying to render a not yet existing message id. The behaviour I would like is for it to just render the id "ui.liked", perhaps give a console.warning. The behaviour I'm getting is a console error. In React Native, a console.error, leads to the red screen of death like in above.

It forces me to stop, manually add the message key and continue.

**Comment by ericf** [comment]
The pattern of using `console.error` is to provide a stack trace. This is the same thing that React does with its warnings — all warning level items still use `console.error`:

> React uses console.error instead of console.warn for warnings so that browsers show a full stack trace in the console. (Our warnings appear when you use patterns that will break in future releases and for code that is likely to behave unexpectedly, so we do consider our warnings to be “must-fix” errors.)

https://github.com/facebook/react/blob/d77c42a26d000c4b8c89daa1505060b894b11078/CHANGELOG.md#notable-enhancements

If you're testing a different locale, like `pt`, just make sure to set both `locale` and `defaultLocale` to `"pt"` and that won't cause any of these warnings/errors while you're developing.

I don't want to change this behavior with using `console.error` for the same reasons that React uses `console.error`, and I consider this an error that shouldn't go unseen.
