### ISSUE TITLE
Code with ES5 -> Can I use React-intl to manage translation ? If yes how ?

### ISSUE THREAD

**Issue by Selsynn** [yahoo/react-intl#801]
Hello, I'm currently developping with Laravel 5 (framework PHP) and ES5 (because i can't have more recent like ES6)
The babel-plugin-react-intl is available only with ES6. And I don't have webpack on the project (I have Elixir/gulp)

I struggle for achaiving the traduction. 
Is it possible without having ES6 ?
how to do it ?

(sorry for bad english, it's not my maternal language)

**Comment by ericf** [comment]
`babel-plugin-react-intl` on npm is compiled to ES5.

**Comment by Loewenhardt** [comment]
You have probably this issue: [yahoo/babel-plugin-react-intl/issues/6](https://github.com/yahoo/babel-plugin-react-intl/issues/6).
