### ISSUE TITLE
Support suppressing errors

### ISSUE THREAD

**Issue by rokoroku** [yahoo/react-intl#807]
With async translation resources,  my console is messed up with ``console.error`` from ``[React Intl] ...`` while testing. 
I couldn't find any options to suppress these errors. The code is saying ``process.env.NODE_ENV === 'production' ``, but it doesn't make sense during testing process. 

Could you support this feature?

**Comment by rokoroku** [comment]
I found that this issue is duplicated (#619), but it is really required feature.

**Comment by ericf** [comment]
Do you have `locale` and `defaultLocale` props set to the same value on your `<IntlProvider>`?

**Comment by rokoroku** [comment]
I want to test this scenario : 
```jsx
<IntlProvider locale={browserLocale} defaultLocale={defaultLocale}>
    ...
</IntlProvider>
```

I can get browser's locale from ``navigator.language``, but sometimes it returns undefined depends on browsers.

So you want to say, if browserLocale is null, we need to set it as defaultLocale like this?

```jsx
<IntlProvider
        locale={locale || defaultLocale}
        defaultLocale={defaultLocale}
        messages={translation[locale || defaultLocale]}>
    ...
</IntlProvider>
```

Then what's the purpose of prop ``defaultLocale`` ? What does it exist for?

**Comment by ericf** [comment]
`defaultLocale` exists to signal what locale your app's default messages are written in. It's used as the fallback locale in case something went wrong with loading locale data. In the case where your `locale` and `defaultLocale` are the same — which would be the case when testing, then errors will be suppressed. But when `locale` and `defaultLocale` are different, then the intention is to warn about missing message translations.

**Comment by rokoroku** [comment]
Okay, sorry for late reply.
I updated my test code like above. This is maybe only needs for our test environment, and not an critical issue. So I close this issue :)
