### ISSUE TITLE
injectIntl bug React.Component instance

### ISSUE THREAD

**Issue by marlonmleite** [yahoo/react-intl#811]
I've implemented **ref="myRef"** in my component and it does not return an instance of the component.
It is returning an instance of InjectIntl ​​instead of the component.

This happens because of this:
`export default injectIntl(MyInput) or @injectIntl ​​annotation`.

I need to instantiate my component for actions and focus on my **input** and react-intl is disrupting this.

My entry code:
```
  render() {
    const {children, placeholder, intl, ...props} = this.props
    const formattedMessage = placeholder ? intl.formatMessage({id: placeholder}) : ''

    return(
      <div className="default">
        <input
          className="input"
          placeholder={formattedMessage}
          ref={(elem) => this.configInput(elem)}
          {...props}
        />
        <div className="err">{children}</div>
      </div>
    )
  }
```

**Comment by ericf** [comment]
You should set the `withRef` option when calling `injectIntl()`: https://github.com/yahoo/react-intl/wiki/API#injection-api

This would allow you to access the wrapped instance via `getWrappedInstance()`. You keep your original `ref` to the inject intl wrapper component, and call `getWrappedInstance()` on it.
