### ISSUE TITLE
BUG: formatNumber won't set a different locale on server render

### ISSUE THREAD

**Issue by Dindaleon** [yahoo/react-intl#813]
No matter what I do, it just won't accept any other locale than 'en' on server render. So, react gives me the following error:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) .$/=10.0.0.0.0.0.1">4.292,35&nbsp;VEF</s
 (server) .$/=10.0.0.0.0.0.1">VEF4,292.35</span></
```

This is an example code on my server rendering script:

```
<IntlProvider
                        key="es"
                        locale="es"
                        defaultLocale="es"
                        messages={ lang[store.getState().user.data.locale] }>
```

Everything works ok on the client side; but somehow, on the server it just won't take "es" as the default locale for `formatNumber` I have not tried with other components.

I even tried with a nested IntlProvider but it keeps gettng 'en' as the default locale instead of 'es'

**Comment by ericf** [comment]
Not a bug, you need to make sure there's `Intl` locale data in Node: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript
