### ISSUE TITLE
"await" error in Microsoft Edge

### ISSUE THREAD

**Issue by vebaspect** [yahoo/react-intl#814]
Hello,

When I open my really simple application in _Microsoft Edge_ (v25) I get a blank screen and the following error in console:
`SCRIPT1048: The use of a keyword for an identifier is invalid`

I found that this keyword is **await** (line 2574 in `dist/react-intl.js`).

In _Google Chrome_ (v55), _Mozilla Firefox_ (v50), _Internet Explorer_ (v11) and _Opera_ (v42) everything works correctly. 

How can I fix this? I use **2.2.2** version of _react-intl_.

**Comment by ericf** [comment]
This is an issue with how Rollup and Babel are integrating during the build causing the AsyncToGenerator helper to be included which uses `await` as a member name. I'll look at fixing the build to remove these extra helpers from being included which will resolve this.

**Comment by vebaspect** [comment]
Everything works correctly now.

Thanks for your help. Best regards from Poland.
