### ISSUE TITLE
How to include only a few locales in a commonjs environment?

### ISSUE THREAD

**Issue by johanneslumpe** [yahoo/react-intl#82]
It seems that additional, separate locales are only available in the `dist` folder. In `lib` we only have `locales.js` which imports all available locales. Is there a way that we can just import certain locales in commonjs? Basically mirroring the ability from using the files in `dist`.

Maybe something like this:
```javascript
import ReactIntl from 'react-intl';
import de from 'react-intl/locales';

ReactIntl.__addLocaleData(de);
```

So when bundling my app I only get the locales I want, instad of all the locales which are crammed into the `locales.js` file.

Does this make sense or am I missing something?

**Comment by zemirco** [comment]
I have the same issue (using browserify). My current workaround is copying the object content `{"locale":"de", ... }` from `react-intl/dist/locale-data/de.js` into a seperate file in my workspace and use `module.export = {...}` to make it available for my main application.

Inside my main application I run
```js
var ReactIntl = require('react-intl');
var de = require('./react-intl-de.js'); // my custom language file
ReactIntl.__addLocaleData(de);
```

That works but isn't really nice.

**Comment by johanneslumpe** [comment]
Yeah that's the obvious way to get it going in the short run - but it shouldn't be necessary. Manually extracting data from the library seems really wrong.

**Comment by johanneslumpe** [comment]
@caridy Any thoughts on this? I'd be up for a PR to move the locales around.

**Comment by gpbl** [comment]
I run into this as well. To require them I set a a global `ReactIntl`, on browser and node.js.

**Comment by johanneslumpe** [comment]
A global is, just like the solution above, just a quick fix, but not a real solution though.

**Comment by gpbl** [comment]
@johanneslumpe absolutely, actually a way to solve this issue could be via React context/props.

**Comment by ericf** [comment]
We've talked about this before and we'd like to improve this, however whatever solution we arrive at must work for ES6, CommonJS (Node), CommonJS (Browserify/Webpack), and no module system with `<script src="">`. 

Ideally the locale data modules would export objects, those would be transpiled to CommonJS and that would solve it for all the module systems. But for using in the browser without a module system, we still need to keep doing what we do today with having the file self-register the data on a global. This limitation has lead us to keeping things how they are since it can easily work within a module system by simply exposing `ReactIntl` as a global.

**Comment by johanneslumpe** [comment]
@ericf how about having a script which generates the files in `dist` and `lib` from a `src/locales` folder? Any issue with that, apart from duplicate data?

That way in the browser without any module system the files from `dist` could loaded.

In a commonjs env we'd just grab the pre-transpiled files from `lib/locales`. And if somebody wants to use  the original es6 files, they can grab them from `src/locales`.

**Comment by ericf** [comment]
The main "issue" I see with that is adding a new public API based around importing modules from within the package based on folder structure. This is generally a gray area at best, anti-pattern at worst. And it's unclear how this might work with ES6 modules and the WHATWG Loader. /cc @caridy

**Comment by gpbl** [comment]
@ericf thanks for the answers. Since with react-intl we are already passing specific props to our components, couldn't we pass the locale data as well?

**Comment by johanneslumpe** [comment]
@gpbl That's actually not a bad idea. I didn't take a look at the codebase yet, so I don't know how much changes it would involve, but in general that might be nice. The only issue that will still remain is: where do we pull the locale data from?

**Comment by caridy** [comment]
Pulling the data is easy, we are working on it here: https://github.com/yahoo/formatjs-extract-cldr-data/. Passing the locale data down the same way we pass messages, locales and formats should be doable, but we will have to discuss it in details. @ericf is pretty busy these days with some internal refactor of the library, we will probably discuss it at some point next week.

**Comment by ericf** [comment]
@gpbl @johanneslumpe I'm unsure that passing around the locale data React Intl needs to operate will make sense as React Intl's locale data is generic. While the locale data passed through props/context today: `locales`, `formats`, and `messages` are all specific to each app.

Using our [formatjs-extract-cldr-data](https://github.com/yahoo/formatjs-extract-cldr-data) lib that @caridy mentioned enables you to easily extract the generic locale data that React Intl will need to support your app. If you only support a few locales, you could do something like this in your **build** to _generate_ a locale data module:

```js
// Build task to generate React Intl data needed by our app.
'use strict';

var fs          = require('fs');
var extractData = require('formatjs-extract-cldr-data');
var serialize   = require('serialize-javascript');

var MY_APPS_LOCALES = ['en-US', 'fr-FR', 'es'];

var localeData = extractData({
    locales       : MY_APPS_LOCALES,
    pluralRules   : true,
    relativeFields: true
});

var generatedFile = 'module.exports = ' + serialize(localeData) + ';';
fs.writeFileSync('locale-data.js', generatedFile, 'utf8');
```

And then in your app's main [entry point] module you would `require()` and add the locale data to React Intl like this:

```js
// In the app's main.js file...

var ReactIntl  = require('react-intl');
var localeData = require('./locale-data.js');

Object.keys(localeData).forEach(function (locale) {
    ReactIntl.__addLocaleData(localeData[locale]);
});
```

**Comment by johanneslumpe** [comment]
@ericf Yeah doing something like that is possible, but it feels a bit odd, that this is pushed out to the consumer. My use case is not that we're supporting only a few locales, but rather that the locale data is being loaded on the fly, instead of pushing everything down to the client instantly.

If this is the last word on the topic then that's fine and I'll most likely use something similar to what you suggested. Thanks!

**Comment by ericf** [comment]
@johanneslumpe not the last word. It will make sense to offer up modules or an API for accessing this data; I'd like to figure out a way that's aligned with ES6 modules and site package first, that's all. For now generating the data you need is easy, although slightly hacky as you've mentioned. We could look towards figuring out progress on this for `v1.3.0`.

**Comment by johanneslumpe** [comment]
Ok cool! If you could post back here when some change comes up, that'd be highly appreciated :)

**Comment by yloubry** [comment]
Any news on this topic?

Thanks

**Comment by ericf** [comment]
@yloubry yeah, it's fixed on the [`v2-dev` branch](https://github.com/yahoo/react-intl/tree/v2-dev). The `lib/locale-data/` will contain data-only modules with no side-effects. The default for Node will be to load all locale data, and only `en` when using Browserify/Webpack. When creating your bundle for the client you'll be able to do this:

```
import {addLocaleData} from 'react-intl';
import en from 'react-intl/locale-data/en';
import fr from 'react-intl'/locale-data/fr'

addLocaleData(en);
addLocaleData(fr);
```

**Comment by ericf** [comment]
See: #162
