### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by khankuan** [yahoo/react-intl#825]
Hi, I would like to know if other languages can be added besides those that are supported by the library. Cheers :)

**Comment by ericf** [comment]
The library supports languages in the Unicode CLDR: http://cldr.unicode.org

**Comment by khankuan** [comment]
Ah, a followup question: If i have a locale `en-GB`, do i do `addLocaleData(ReactIntlLocalData.en)` or  `addLocaleData(ReactIntlLocalData['en-GB'])`?

**Comment by ericf** [comment]
It's the former. `ReactIntlLocaleData.en` will be an array that actually contains all the locale data for all `en-*` locales. The data is setup to be organized by language because in most cases the specific locales inherit most of their rules from the main rules for that language.

**Comment by khankuan** [comment]
Ah cool, thanks!
