### ISSUE TITLE
Article featuring react-intl

### ISSUE THREAD

**Issue by yury-dymov** [yahoo/react-intl#827]
Hey guys,

my article, which features react-intl, was published recently in the SmashingMagazine.
If you find it good enough, feel free to add the URL to the docs.

https://www.smashingmagazine.com/2017/01/internationalizing-react-apps

Kind regards,
Yury.

**Comment by ericf** [comment]
@yury-dymov awesome! Feel free to add it to the docs on the Wiki.

**Comment by yury-dymov** [comment]
@ericf, added URL to the Wiki: https://github.com/yahoo/react-intl/wiki.
Feel free to close the issue if I haven't messed up anything.

**Comment by ericf** [comment]
Looks good, thanks!
