### ISSUE TITLE
How dispalay time with seconds?

### ISSUE THREAD

**Issue by clairekh** [yahoo/react-intl#828]
Hi!

I use `<FormattedTime value={date}/>` to display time. And result is  `2:32 PM` for **en** locale or `14:32` for **de** locale. But I need display seconds also: `2:32:05 PM` or `14:32:05`. 

How can I do this? Please, help me. I can not find a description in documentation.

**Comment by clairekh** [comment]
Empirically found the answer to my question:

<FormattedTime value={date} hour='numeric' minute='numeric' second='numeric'/>

**Comment by xanderiel** [comment]
Who would have thought 😂 
Didn't find that in the docs neither, though.

**Comment by MikeTaylor** [comment]
The docs are bizarre. https://github.com/formatjs/react-intl/blob/master/docs/Components.md doesn't seem to say anything much about properties.
