### ISSUE TITLE
Can't make the library to work on some Android devices with React-Native

### ISSUE THREAD

**Issue by alexmngn** [yahoo/react-intl#829]
I recently updated my Android Studio and many components/sdk and since then React-Intl complains about intl library missing, even though it was working fine before.

I have installed the `intl` polyfill and I import it at the very top of my main file `App.js`. I also import the `localeData` from `react-intl` and add it. Then, I render my view within the `IntlProvider` specifying the `locale` with no messages (I only use `FormattedNumber` at the moment)

This is a simplified version of my code:

```
    import 'intl';
    import { IntlProvider, FormattedNumber, addLocaleData } from 'react-intl';
    import en from 'react-intl/locale-data/en';
    
    addLocaleData(en);
    
    [...]
    
    render() {
    	return (
    		<IntlProvider locale="en">
    			<Text>
    				<FormattedNumber value={123} />
			</Text>
    		</IntlProvider>
    	)
    }
```

I get the following error:

> [React Intl] Error formatting number. ReferenceError: No locale data
> has been provided for this object yet.

![image](https://cloud.githubusercontent.com/assets/4203845/22232324/4eebc6d2-e21b-11e6-911b-1fe452732c54.png)

**Comment by ericf** [comment]
This looks like an error being caught and by React Intl and logged. It might be that Android has some differences with its implementation of the ECMAScript `Intl` APIs. Can you try the following to see if you get a similar error?

```js
const nf = new Intl.NumberFormat('en');
nf.format(1000);
```

**Comment by alexmngn** [comment]
It seems to be an issue from Android which doesn't like Intl anymore...

This is what happens when I remove entirely react-intl and use your code:

<img width="574" alt="screen shot 2017-01-25 at 09 55 49" src="https://cloud.githubusercontent.com/assets/4203845/22276207/ac9ec058-e2e4-11e6-85eb-866db8ad3a67.png">

And this is when I import the `intl` polyfill:

<img width="574" alt="screen shot 2017-01-25 at 09 56 24" src="https://cloud.githubusercontent.com/assets/4203845/22276212/b53cd5ce-e2e4-11e6-9069-8e4b81a4e013.png">

**Comment by ericf** [comment]
Ah okay. So this is soulvable. You need to load the locale data for the Intl polyfill if you're using that. You can refer to its docs for how.

**Comment by suhooh** [comment]
@alexmngn Did you solve this? I have exactly same problem in iOS.

**Comment by alexmngn** [comment]
@suhooh Yes I solved it. http://stackoverflow.com/questions/41736735/react-native-and-intl-polyfill-required-on-android-device
