### ISSUE TITLE
Style prop conflicting with react tyle. Lint warning.

### ISSUE THREAD

**Issue by rsolci** [yahoo/react-intl#833]
When using a FormattedNumber component and passing a style as string to it, ract-creat-app lint shows me this warn:
`warning  Style prop value must be an object  react/style-prop-object`

As default, react validates the type of style prop to be an object that defines a component inline css.

**Comment by ericf** [comment]
`style` is not a reserved prop name for custom components in React. It's used in React Intl because it maps to options on the `Intl` APIs. This is an issue that should be brought up in the lint rule's repo.

**Comment by pjchender** [comment]
Adding the rule in your ESLint config might help:

```json
{
  "rules": {
    "react/style-prop-object": ["error", {
      "allow": ["FormattedNumber"]
    }],
  }
}
```
