### ISSUE TITLE
Translating defaultProps

### ISSUE THREAD

**Issue by rafatwork** [yahoo/react-intl#834]
I have a component which renders a status as an icon.
The status' text (title attribute) can be configured through props.
Using defaultProps, it defaults to "Yes" for true, "No" for false. But I can't figure out how to translate those strings, since you don't have access to this.props.intl in [Component].defaultProps.

**Comment by ericf** [comment]
You probably want to remove them as defaults and require that these props are passed in and that way it delegates to the user of the component.

If the status icon is always going to display "Yes" or "No" (localized) in its `title` attribute, then you could remove these props from the component. Or split it into two: a lower level component, `<StatusIcon>`, that requires props, and `<DefaultStatusIcon>` which doesn't require the props and defaults to "Yes" and "No" messages.

**Comment by jacobi85** [comment]
It is possible to use defaultProps + injectIntl combo
Just make sure that the translation key also exists in the rendered json file when trying it out.

ie stateless component
`import { injectIntl } from 'react-intl';

const LoadingScreen = ({intl: {formatMessage}, message = formatMessage({id: 'boilerplate.Notification.Loading'})}) => (
  <div className="loading-screen">
    <CircularProgress size={20} className="loading-screen-progress" />
    <Typography variant="body2">{message}</Typography>
  </div>
);

export default injectIntl(LoadingScreen);`

**Comment by tybenz** [comment]
Is there still no way to do this with react-intl?
