### ISSUE TITLE
FormattedDate in safari for iOS 8

### ISSUE THREAD

**Issue by rubentd** [yahoo/react-intl#835]
Hi.
I'm having an issue with FormattedDate in safari for iOS 8.

When I format dates that end in :00 minutes, it only displays one zero

<FormattedMessage ... hour="numeric" minute="numeric" />

![image](https://cloud.githubusercontent.com/assets/1794079/22470668/c8be21c4-e7ae-11e6-9e0f-fe4b45a03730.png)

**Comment by ericf** [comment]
Which version of the Intl.js polyfill are you using?

**Comment by rubentd** [comment]
I'm using intl 1.1.0

**Comment by rubentd** [comment]
I just updated to 1.2.5 and the problem is still happening

**Comment by ericf** [comment]
Try using "2-digit" instead of "numeric". https://github.com/yahoo/react-intl/wiki/API#date-formatting-apis

**Comment by rubentd** [comment]
It works perfectly using 2-digit 👍 Thank you very much for taking the time
