### ISSUE TITLE
Rich-text in FormattedMessage function-as-children pattern

### ISSUE THREAD

**Issue by p10ns11y** [yahoo/react-intl#836]
@ericf Would you like to help me reasoning about why this fails

When nodes passed in here it is not rendered only first child (text until the first delimitedToken ) is rendered

https://github.com/p10ns11y/react-intl/blob/rich-text-FormattedMessage/src/components/message.js#L129

https://github.com/p10ns11y/react-intl/tree/rich-text-FormattedMessage

**Comment by ericf** [comment]
See my comment here: https://github.com/p10ns11y/react-intl/commit/527567efbb3a5292137b83d8be9ad6e9a309d29b#commitcomment-20699749
