### ISSUE TITLE
IE11 getLocale problem 

### ISSUE THREAD

**Issue by Catx7** [yahoo/react-intl#841]
Hello,

Using the following code :
```

import {IntlProvider, addLocaleData} from 'react-intl';
------
------
let currentLocale = getCurrentLocale();
```

The current Locale is always 'en-US' in IE11 ,Windows 10.
It is tested on latest versions of Chrome and Firefox and  it works fine.
Any ideas about this issue?

Thank you.

**Comment by ericf** [comment]
I don't know what `getCurrentLocale()` does. You'd have to provide the implementation details in order to help any further.

See: https://formatjs.io/guides/runtime-environments/#user-locale-client

Feel free to reopen if you're still having issues.
