### ISSUE TITLE
Webpack path fails

### ISSUE THREAD

**Issue by KulakovSerg** [yahoo/react-intl#845]
After webpack builds everything successfully, I have 
`Uncaught Error: Can not find module ../locale-data/index.js`

The problem is into my webpack config:
...
resolve: {
         root: [
             path.resolve ('./src/js/'),
         ],
         ...
} 

And I have fixed it by replacing 
`'../locale-data/index.js'`
with 
`'react-intl/locale-data/index.js'`
in react-intl/lib/index.js

Relative paths are true evil.

So, I can not change root for my project and have to fork react-intl or fix it in any way...

**Comment by ericf** [comment]
You'll want to ignore this file. It's setup to be excluded from webpack builds.

**Comment by KulakovSerg** [comment]
> You'll want to ignore this file. It's setup to be excluded from webpack builds.
Thank you! I have added it to IgnorePlugin:
`new webpack.IgnorePlugin(/\.\/locale/, /^\.\.\/locale-data\/index\.js$/),`
And everything works!
