### ISSUE TITLE
formatRelative: Ability to omit "in" or "ago" keywords?

### ISSUE THREAD

**Issue by joncursi** [yahoo/react-intl#847]
I'd like to use `formatRelative` to calculate the age of something. So rather than "9 years ago", I'd like to say that the age of something in "9 years". Is there a way to prevent "ago" from being printed?

I thought about doing a regex against the english word 'ago', however this would only work for the english users (app supports multiple languages). Thanks!

**Comment by ericf** [comment]
See #393

**Comment by rnicholus** [comment]
As far as i can tell, #393 has nothing to do with this question.

**Comment by rnicholus** [comment]
spoiler alert: there is no way to do this

**Comment by rnicholus** [comment]
Won’t that fail when the language is not English?

**Comment by sofiia-hlyniana** [comment]
@rnicholus Obviously needs translation for words being replaced

**Comment by rnicholus** [comment]
well, no. if it were that simple, this issue wouldn't exist in the first place. you can'y simply translate "ago", search for it in a string, and expect to find/replace it. That simply isn't correct logic in all languages.

**Comment by gaurav414u** [comment]
Any update on this?

**Comment by rikardbakkehaug** [comment]
Any solutions to this? I have a table populated with time to expiration date, and don't want "in" to show for every element in English, and "om" in Norwegian.
