### ISSUE TITLE
Offer plain JSON data files ... not just IIEF data files

### ISSUE THREAD

**Issue by swernerx** [yahoo/react-intl#853]
For improved integration into my project which uses SSR protection it would be useful to offer data files in plain JSON. Intl.JS offers both JS (as JSON-P) and plain JSON. It would be nice to have the same basic data set for React-Intl as well. IIEF only data is not a good idea in a world were most people are using some kind of bundler to produce the application output.

**Comment by ericf** [comment]
The data is not JSON-serializable, it contains functions.

The `.js` files contain UMD modules which work fine with bundlers.
