### ISSUE TITLE
Importing formatMessage

### ISSUE THREAD

**Issue by megawac** [yahoo/react-intl#858]
Sorry if this is a basic question. I'm having trouble figuring out how to import [`formatMessage`](https://github.com/yahoo/react-intl/wiki/API#formatmessage) and the rest of the `format*` methods  as documented from the npm bundle.

As far as I can tell its not being exported in [`react-intl.js`](https://github.com/yahoo/react-intl/blob/master/src/react-intl.js) causing them not to be accessible from npm

The following two import attempts didn't work in 2.2.3

```
import { defineMessages, format } from 'react-intl';
import { defineMessages, formatMessage } from 'react-intl';
```

**Comment by megawac** [comment]
Never mind I see the upgrade guide. Docs are just confusing

**Comment by ericf** [comment]
@megawac feel free to update the docs on the wiki if you think they can be improved for the next person.

**Comment by alitorbati** [comment]
@megawac can you please describe your solution or link to the relevant docs that helped you resolve the issue?

**Comment by megawac** [comment]
All you have to do is wrap the component you want to use `formatMessage` in
with `injectIntl`. That component will now have access to `props.intl`
which contains `intl.formatMessage`

 For example


import React from 'react';
import { injectIntl, defineMessages } from 'react-intl';

const messages = defineMessages({
   greeting: {
     id: 'app.home.greeting',
     description: 'Message to greet the user.',
     defaultMessage: 'Hello!',
   },
});

class MyComponent extends React.Component {
   render() {
     const { intl } = this.props
     return <div>{intl.formatMessage(messages.greeting)}</div>
   }
};

// Using `injectIntl()` to make React Intl's imperative API available to
format
// the date to a string value for the `title` attribute.
const MyWrappedComponent = injectIntl(MyComponent)

**Comment by marcosanfilippo** [comment]
What if I need to use it as import without being inside a component?

**Comment by megawac** [comment]
You shouldn't be using react-intl outside of the component workflow. You
can always do a `formatMessage` and pass that to your backend when you
trigger the action

**Comment by marcosanfilippo** [comment]
Why should I not use it outside the component workflow?
Also, do you mind explaining the 
```
you can always do a `formatMessage` and pass that to your backend when you trigger the action
```

**Comment by samajammin** [comment]
I'm also looking to use `formatMessage` outside of a component. Is anyone able to explain how to accomplish that or why I "shouldn't be using react-intl outside of the component workflow."?

Thanks in advance!
