### ISSUE TITLE
Mixin methods not cascading down the component hierarchy

### ISSUE THREAD

**Issue by kosmotaur** [yahoo/react-intl#86]
Hi,

When requiring `react-intl`, the exported object's `IntlMixin` property links back to the exported object, making it impossible to use the mixin. 

Please consider this code:

```js
var ReactIntl = require('react-intl');

console.log(ReactIntl);
console.log(ReactIntl.IntlMixin);
console.log(ReactIntl.IntlMixin.IntlMixin);
console.log(ReactIntl === ReactIntl.IntlMixin);
```

and it's output:
![screen shot 2015-03-06 at 14 28 01](https://cloud.githubusercontent.com/assets/213450/6526758/27cab352-c40d-11e4-9b07-0d2c108c9d07.png)

I believe this is due to [lines 15-24 in index.js](https://github.com/yahoo/react-intl/blob/master/index.js#L15)

Are there any workarounds? Thanks!

**Comment by ericf** [comment]
Yes this is on purpose for back-compat with v1.0.0 as the comments say for those lines. But why is this preventing you from using the mixin? We haven't had a problem using it.

**Comment by kosmotaur** [comment]
ah, my bad, sorry, the required `getIntlMessage` and other props are present on the exported object

it's this line from the docs that confused me:

> it's recommended that you add this Mixin to your app's root Component.

> The Intl Mixin will automatically propagate the following props throughout your app's Component hierarchy:

It's not really working that way, the mixin's methods are not cascading down to subcomponents, and neither do the translated messages. This is the code I am working with:

```js
// index.js
'use strict';

var React = require('react/addons');
var App = require('./modules/App');
var intl = {
  messages: {
    test: 'test'
  }
};

module.exports = React.render(
  <App {...intl} />,
  document.getElementById('content')
);

```

```js
// App.js
'use strict';

var React = require('react');
var IntlMixin = require('react-intl');
var I18nComponent = require('./I18nComponent');

module.exports = React.createClass({
  mixins: [IntlMixin],
  render: function() {
    console.log(this.getIntlMessage('test')); // outputs "test"
    return (
      <I18nComponent />
    );
  }
});
```

```js
// I18nComponent.js
'use strict';

var React = require('react');

module.exports = React.createClass({
  render: function() {
    return (
      this.getIntlMessage('test') // throws Uncaught TypeError: this.getIntlMessage is not a function
    );
  }
});

```

**Comment by ericf** [comment]
Okay, I see how the docs are confusing. Only the props listed will be propagated. If you want to use the mixin's methods, then you have to add the mixin to each component where you call one of its methods.

**Comment by caridy** [comment]
Yeah, we can change the docs to say something like: 

> ...it's recommended that you add this Mixin to your app's root Component. This data will be accessible to all React Intl Components, and any React Component in the hierarchical structure can access it through the React Context or thru the Mixin helpers.

**Comment by ScreenDriver** [comment]
+1 for changing the docs

**Comment by ericf** [comment]
See: #162
