### ISSUE TITLE
Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry. Not working with GatsbyJs (static site generator)

### ISSUE THREAD

**Issue by mtt87** [yahoo/react-intl#865]
GatsbyJs is a static site generator powered by React and Webpack.

React-intl works great on development since everything is running in the browser but it fails at build time, I suspect because `intl` is not defined in Node/Webpack.

There are some advice on how to add `intl` polyfill to webpack but it's kinda hard with the special config of GatsbyJs, do you have a clue?

**Comment by ericf** [comment]
Never used GatsbyJS. But this error is related to a `<Formatted*>` component being used outside of a `<IntlProvider>` ancestor.

**Comment by mtt87** [comment]
@ericf yes makes sense now I think there is something strange happening on server-side rendering (might be related to `react-router` not sure) and that context is lost.

I'm indeed using the `<IntlProvider>` ancestor and it works fine during development (browser rendering) but not on build.

```
exports.wrapRootComponent = (Root) => {
  const locale = cookie.load('locale') || 'en';
  const messages = translations[locale];
  const Wrapper = () => (
    <IntlProvider locale={locale} messages={messages} >
      <Root />
    </IntlProvider>
  )
  return Wrapper;
}
```

Have you ever had side-effects using `react-router` or server-side rendering of an app?

Thank you

**Comment by ericf** [comment]
There's an example app here if you want to check it out: https://github.com/yahoo/react-intl/tree/master/examples/react-router

**Comment by mtt87** [comment]
Thanks @ericf I've been digging into this problem and I have a clue: I think it's not related to your package at all but it's related to https://github.com/markdalgleish/static-site-generator-webpack-plugin

When you do `gatsby build` it's doing server-side rendering using that plugin and seems like the `context` (given by `<Intlprovider >`) is lost somewhere.

Last question for you then I think you can close this issue:
Is there another way to get translations without using the `<IntlProvider >`?

Thanks for your time

**Comment by ericf** [comment]
Not really. You can look how I did server + client app using Next.js + React Intl here for some ideas: https://github.com/yahoo/react-intl/pull/844

**Comment by mtt87** [comment]
Found a way to make it work, completely unrelated to this package so I'm closing the issue.
Thanks for your time @ericf 😄

**Comment by MartinKuzdowicz** [comment]
@mtt87 could you share your solution, i have a similar issue when i do server side rendering with node

**Comment by mtt87** [comment]
@MartinKuzdowicz if it's related to GatsbyJs I've patched it here (already merged)
https://github.com/gatsbyjs/gatsby/pull/695/files

**Comment by Malarkey-Jhu** [comment]
@mtt87 have the same problem with gatsby, i put IntlProvider in wrapRootElement , it fails in gatsby build, do you have the solution?
