### ISSUE TITLE
Performance issue of injectIntl HOC

### ISSUE THREAD

**Issue by toan2406** [yahoo/react-intl#866]
I get a wasted time reported from React perf tool (react-addons-perf) on the intl injected component, although the component is pure. Below is my code snippets and the results:

```javascript
const Title = () =>
  <div>
    <FormattedMessage id='greeting' />
  </div>

// use recompose to enhance
const enhance = compose(
  injectIntl,
  pure,
  setPropTypes({
    intl: intlShape.isRequired
  })
)

export default enhance(Title)

// somewhere is the <App />, I render <Title />
```
Then whenever the App is re-rendered (like by changing route), the Title stays the same, but I keep getting the wasted report of ```InjectIntl(pure(Title))```

<img src="https://d1ro8r1rbfn3jf.cloudfront.net/ms_70988/TwfDzcfPRKrD8G0iTVXuqK8ASdULBb/Express%2B2017-02-23%2B16-01-51.png?Expires=1487926935&Signature=JQQu1IUln-2Uo3xmCcSFkrNZsQwa~IxBcCBVXJkMug-x6gjNQ4B1qaBp-In3fsgvH1eaKETTv8Bxa-wM68wSK4Rtvui7oUZP1DWfhN~4b3a4AgBG~ytaf4vWP18RqevEAmmrwdhmJie3eD619dBWceRp2TPs-MU~u7zAlGOkyHp0xiskZMS4cL9KY~TBFhniNpWzlEQ10T-NWzhab-gej1Evk5XQIRaDwqvvQEYmh9bxAs35eWU7DNoaLT8z9uxMkSJCBAmUjJ7lBB7xLnd~URjGgVqdJ05ha5QLrBoazUHmSU9wwmAVUv1K0PB4TUnFiojg7OrCftPDGQ6jYPjexg__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA" />

After investigating, I think the cause is the wrapper component ```InjectIntl``` didn't handle ```shouldComponentUpdate```, so there always be wasted time of executing the wrapper's ```render``` method. Then I try modify the ```injectIntl``` function a bit and the issue seem to be resolved:

```javascript
  // in class InjectIntl
  shouldComponentUpdate (nextProps, nextState, nextContext) {
    return !shallowEquals(nextProps, this.props) ||
           !shallowEquals(nextContext.intl, this.context.intl)
  }
```

Is there any better way to fix this, if ok I can do a PR.
Also thanks @khanghoang for helping resolve this.
Regards
Toan

**Comment by ericf** [comment]
I don't think the HOC should be the one implementing sCU. The component your wrapping should be the one to implement it if it's needed.

sCU isn't a magic bullet and in some cases, like a simple component, it can be slower than just re-rendering. The way `injectIntl` is implemented today gives developers control.

It's unclear that doing the multiple shallow equals checks will take less time then re-rendering. The `props` could be a huge set of things that need to be compared.

**Comment by toan2406** [comment]
Ah I see. I just want to clear the perf tool result, but you're right. Thanks for your advice.
