### ISSUE TITLE
Guidance on use of "input" tag with "placeholder" attribute using Components

### ISSUE THREAD

**Issue by asutherland** [yahoo/react-intl#87]
From reading the docs, it's not immediately clear to me how I should be creating an input element using a placeholder attribute using react-intl.  Currently I would guess I should use formatMessage(), but http://formatjs.io/react/ says "these methods will likely be deprecated in v2.0, so use the Components." and I'm not sure how to do that.  I did look in the provided example and I think I read/searched the docs sufficiently, but I could be missing something.  If it is missing, I think it would be a great addition to the docs!

**Comment by ericf** [comment]
I guess the guidance for now would be to use `this.messageFormat()` in this case since there isn't another option right now. Once we have a better option, we'll setup a migration path.

**Comment by ericf** [comment]
As for the docs, if you're feeling up for it, you could send a PR to the website adding an example like this :)

**Comment by asutherland** [comment]
Thanks for the super-quick reply!  I need to gain a little more experience with react and input elements before I will feel confident about the quality of advice I can dispense, but that should hopefully be later this week.  I'd be happy to provide a pull request at that point.

**Comment by surkova** [comment]
I have exactly the same issue right now and `this.messageFormat()` doesn't exist. Did you guys do anything to get a better support of i18ned attributes?

**Comment by ericf** [comment]
@surkova sorry, typo: `this.formatMessage()`. (I updated my original comment)

**Comment by ericf** [comment]
See: #162
