### ISSUE TITLE
Add support for `tagName` and `className` props in React components

### ISSUE THREAD

**Issue by ipanasenko** [yahoo/react-intl#872]
Hi, guys

I've submitted PR that adds support for `tagName` and `className` props.

This will allow better styling for components without wrapping them into another component

https://github.com/yahoo/react-intl/pull/873

**Comment by ericf** [comment]
This has been discussed several other times and is not something we'll be supporting. Sorry that you took the time to make a PR 😢

**Comment by ipanasenko** [comment]
No problem, just couldn't find original discussion
