### ISSUE TITLE
Dynamically changing images with locale

### ISSUE THREAD

**Issue by Ank49** [yahoo/react-intl#875]
Hi guys !

I'm trying to change some images while changing language on my website (It's one of my app screenshots and I have them both in French and English) but I can't figure on how to do it..
I tried changing the path of theses images but as webpack compile all the images called with a `require('img/path')`, the path is not the same after that.
Even after precising the right path (e.g. the path after a compilation), it doesn't work either. 😔

I'm pretty sure there's a way, and an easier one, to do that but I must say, didn't manage to find it yet..

If anyone knows, I'll be more than glad to know how ! 😁

**Comment by bang88** [comment]
can we define a few variables to hold your image.

```js
var image1 = require('/path/english/img')
var image2 = require('/path/french/img')

// then use it in your app 

var image  =  english ? image1 : image2

// i dont test this, but you can try it.

```

**Comment by Ank49** [comment]
Your answer's quite interesting but.. where does your english const (I assume it's a variable) come from ?

**Comment by bang88** [comment]
Check your props, but you must know the current language right?

**Comment by Ank49** [comment]
Actually this is what's bothering me.. can't find how to get access to the current browser locale provided by react-intl..

**Comment by bang88** [comment]
At first check your props try to find the locale, if its not exist, you can store your current locale in some place, when you change the current language, you should have the locale value.  i haven't any code so i can't help you more, but this is very easy to resolve.  😄

**Comment by PatrickBRT** [comment]
shouldn't that do the trick?

const {locale} = window.App; (
https://github.com/yahoo/react-intl/blob/master/examples/translations/src/client/index.js
.)



2017-03-02 15:47 GMT+01:00 邦 <notifications@github.com>:

**Comment by Ank49** [comment]
Oh my... this was so easy.. 😂

Thanks for your help guys and @bang88 for you advice, just had to do this : 
`const locale = this.props.intl.locale`and here I have the locale... 🙄😅

This'll be a lot easier from now on !
