### ISSUE TITLE
Nested/recursive message parameters

### ISSUE THREAD

**Issue by pinebit** [yahoo/react-intl#895]
Consider a message template having one parameter, which is to be another translated item:
```
prompt: {
   id: '...',
   defaultMessage: "Do you want to {action} the record?",
},
deleteAction: {
   id: '...',
   defaultMessage: "delete",
}
copyAction: {
   id: '...',
   defaultMessage: "copy",
}

// Now I want to do this:
<FormattedMessage {...messages.prompt, values: {action: messages.deleteAction}} />

```
I tried this and this did not work. If it is supported, how else can I achieve this? (hopefully not using `injectIntl` stuff).
Thanks!

**Comment by ghostd** [comment]
Hi,

You can't. <FormattedMessage/> uses the values (almost) "as is", so you need to pass a translated string as 'action' value. See:
https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L110
https://github.com/yahoo/react-intl/blob/master/src/format.js#L209
