### ISSUE TITLE
How can I extract Date and Time format strings our of the current locale?

### ISSUE THREAD

**Issue by harel** [yahoo/react-intl#896]
I have a calendar component that requests a date and time format string. I'd like to extract those from the current locale. Is there a way to get, for example, HH:mm string our of React-Intl (or Intl)? 
This would save me defining that data separately as its already in the locale data anyway.

**Comment by harel** [comment]
I'll answer my own question:
Generate time based options (or date based ones for date format):
```
options = {
  hour: 'numeric', minute: 'numeric', second: 'numeric',
  timeZoneName: 'short'
}
```
and simply you can use the context intl api: 
```
this.cotext.intl.formatters.getDateTimeFormat(new Date(), options)
```
and parse the `resolvedOptions()` output to determine the different lcoale based formats

**Comment by tocttou** [comment]
Doesn't seem to work anymore @harel
