### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by AndyOGo** [yahoo/react-intl#898]
You have a typo in your wiki at https://github.com/yahoo/react-intl/wiki/API#message-syntax
A "be" is missing.

**Comment by StorytellerCZ** [comment]
You can edit the wiki, so you could have fixed that without opening an issue. Seems like somebody fixed it (or I'm not seeing it), so this can be closed.

**Comment by AndyOGo** [comment]
alright thanks
