### ISSUE TITLE
FormattedRelative not work with timeZone

### ISSUE THREAD

**Issue by texmex44** [yahoo/react-intl#900]
All is in the title.

When i do :
`<FormattedTime timeZone={'America/Los_Angeles'} value={new Date(myDate)}/>`
It's ok that work fine.

But now i have an issue when i do : 
`<FormattedRelative timeZone={'America/Los_Angeles'} value={new Date(myDate)}/>`
The timeZone parameter do anything

Anyone can help me ?

**Comment by langpavel** [comment]
@texmex44 Can you provide expected vs given output?

**Comment by texmex44** [comment]
@langpavel Sure

`<FormattedDate timeZone={'America/Los_Angeles'} value={new Date(1489586863000)}/>`
Output => 3/15/2017 (OK)

`<FormattedTime timeZone={'America/Los_Angeles'} value={new Date(1489586863000)}/>`
Output => 7:07 AM (OK)

`<FormattedRelative timeZone={'America/Los_Angeles'} value={new Date(1489586863000)}/>`
Output => 3 hours ago (KO)  defaultServerTimeZone => 'Europe/Paris'
Normal output => 10 hours ago

**Comment by langpavel** [comment]
@texmex44 
```js
new Date(1489586863000).toISOString() === '2017-03-15T14:07:43.000Z'
```
`1489586863000` is number of *ms* since `00:00:00 Coordinated Universal Time (UTC), Thursday, 1 January 1970`. All js dates are in UTC internally, so span must be same regardless timezone.

**Comment by texmex44** [comment]
Hum ok ...

But what i have to do in my case ?

**Comment by langpavel** [comment]
Which database are you using?

**Comment by texmex44** [comment]
I use MYSQL database

**Comment by langpavel** [comment]
Check how you can convert between dates and if your database gives you right time on server side in js.
https://dev.mysql.com/doc/refman/5.7/en/datetime.html
And please close this issue :-)
