### ISSUE TITLE
[help] How to use a component inside a formatted message?

### ISSUE THREAD

**Issue by kud** [yahoo/react-intl#902]
I've got `"noMatchText": "Nothing here.<br />Go back to <Link to=\"/\">Home</Link>." in a json file,` but with `<FormattedMessage />` it's rendered as string. And if I use `<FormattedHTMLMessage />` I will have `<link>` instead of the react-router component `<Link>`, how to deal with it?

**Comment by ghostd** [comment]
You cannot have React elements inside your translation.

`<FormattedHTMLMessage />` only deals with the HTML tags.

To achieve what you want, you can try:
```
"noMatchText": "Nothing here.<br />Go back to {linkHome}." 
```
and
```
<FormattedMessage id="noMatchText" values={{ linkHome: <Link to=\"/\">Home</Link>}} />
```
Maybe what you need is described here: https://github.com/yahoo/react-intl/issues/513#issuecomment-252114827

**Comment by kud** [comment]
Thank you @ghostd. it means I've got to also translate "Home" too.

I really wonder if I should stay with a json format or use a "smart" js file.

**Comment by kud** [comment]
Done that:

```javascript
import styles from './index.css'

import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import { FormattedMessage } from 'react-intl'

class NoMatch extends Component {
  render() {
    return (
      <div style={{ backgroundImage: "url('http://i.giphy.com/dyEsD3pfEZPQA.gif')" }} className={styles.root}>
        <p className={styles.text}>
          <FormattedMessage
            id="noMatch.text"
            values={{
              link: <Link to="/"><FormattedMessage id="noMatch.text.link" /></Link>
              }}
          />
        </p>
      </div>
    )
  }
}

export default NoMatch
```

```json
{
  "locale": "fr",
  "messages": {
    "noMatch.text": "Il n'y a malheureusement rien ici. Retournez à l'{link}.",
    "noMatch.text.link": "accueil"
  }
}
```

With a convention, `{variable}` must be `namespace.element.variable` just after.

**Comment by alex-stripe** [comment]
I actually think we would really benefit from something that allowed us to keep these messages as a single message, but allowed wrapping subsections of the output. In this case the translator needs to know exactly where the `Home` variable is going to end up in a sentence, and in general, they just don't have that kind of insight.

I'd love something, that essentially allowed you to pass wrappers to subsections of the messages.

```
// maybe some sort of fancy markdown-addition or something
const message = "Click [{componentVarName}](here) to return to the home page.";
return formatMessage(message, {
  componentVarName: <a href="/home" target="_blank" />
});
```

**Comment by krupalox** [comment]
How can I fetch variable (title1) written inside nested json file (en.json) using `<FormattedMessage>`?

"menu": {
		 "title1": "Get started with Our Product for free",
    	         "desc1": "Watch The system",
	},

**Comment by papasmile** [comment]
Hi, @krupalox see https://github.com/yahoo/react-intl/wiki/Upgrade-Guide#flatten-messages-object
