### ISSUE TITLE
Need `<FormattedReactMessage />`

### ISSUE THREAD

**Issue by kud** [yahoo/react-intl#905]
The more I use this lib, the more I think we should have a `<FormattedReactMessage />` to be able to use strings like `<Link to="/">`. :)

**Comment by langpavel** [comment]
This is really bad idea. Possible solution will be too much opinionated and probably not performant.
But if you have idea, you can create your own package.
What you think it should look like? Can you provide piece of code? I'm curious..

**Comment by kud** [comment]
I need this to do that: https://github.com/yahoo/react-intl/issues/902#issuecomment-287054427 do you see a better way?

**Comment by langpavel** [comment]
Have you an idea how to implement this?
Have you an idea how it can looks like when using this?

**Comment by kud** [comment]
For the moment, no, I must admit.

I thought about this:

```<FormattedMessage id="noMatch.text"  />```

```
{
  "locale": "fr",
  "messages": {
    "noMatch.text": "Il n'y a malheureusement rien ici. Retournez à l'<Link to=\"/\">accueil</Link>.",
  }
}
```

**Comment by langpavel** [comment]
This is realy bad idea. You must parse string, then there is another problem, that you have no context so you cannot instantiate proper react component, so simply, this is not possible.
Use approach from your second issue and close this one. Thanks!

**Comment by ghostd** [comment]
@kud you need this #513

Meanwhile, you can check out and test my PR #878
