### ISSUE TITLE
format date to dd mmm yyyy (e.g. 20 Mar 2017) 

### ISSUE THREAD

**Issue by ShenAdrada** [yahoo/react-intl#909]
how can we arrange the format to dd mmm yyyy? currently I have the code below, but the output is Mar 20, 2017 and I want it to look like 20 Mar 2017. 

```
<IntlProvider locale="en" formats={{}} defaultLocale="en" >
		<FormattedDate
		value={ this.props.value }
		year="numeric"
		day="2-digit"
		month="short"/>
</IntlProvider>
```

**Comment by danicr83** [comment]
Maybe you see the output as "Mar 20, 2017" because of your locale. It is set to 'en'. To see the date as you would you should use 'it' locale (or simply don't force it, that's because react-intl exist ;) )

**Comment by ShenAdrada** [comment]
thanks @danicr83 ! I changed my locale to en-UK to achieve the dd mmm yyyy format. thanks
