### ISSUE TITLE
Can't display EUR symbol on Chrome for Android

### ISSUE THREAD

**Issue by cell303** [yahoo/react-intl#91]
This is probably not specific to react-intl but this is where I noticed it first.

I'm using `formatNumber` like this: 

    this.formatNumber(price, {
      style: 'currency',
      currency: 'EUR'
    });

On Chrome for Android the result looks like this:

![zeichensatzfehler](https://cloud.githubusercontent.com/assets/951987/6580804/3375be38-c753-11e4-9a1c-30fa068bf058.jpg)

**Comment by ericf** [comment]
This could be a character encoding issue. Could you try to hard-code the expected value and see if it shows up correctly in Android?

**Comment by cell303** [comment]
Yes, when I use the "€" char (as created by a german keyboard) it gets displayed correctly.

**Comment by ericf** [comment]
Can you provide a URL, or a simplified example that demonstrates this issue?

**Comment by cell303** [comment]
Occured here: http://bibi.irian.at/search

**Comment by nebirhos** [comment]
This happens to me too, and with all currencies. Even the USD $ is not rendered, so I don't think it's an encoding problem.
I'm using Chrome 41.0.2272.96 on Android 5.0.1

**Comment by ericf** [comment]
@nebirhos do you have an example that shows the problem?

**Comment by ericf** [comment]
Can you guys check if the page was served as UTF-8?

Also you can try this in a React component, and if it's still a problem, then this is an Android/Chrome issue:

```js
render: function () {
    var nf = new Intl.NumberFormat(null, {
        style: 'currency',
        currency: 'USD'
    });

    return <p>{nf.format(1000)}</p>;
}
```

**Comment by nebirhos** [comment]
Thanks @ericf for the quick support! Unfortunately the app I'm working on is not yet published, I can create an ad-hoc example to show the problem if it could help.

I can confirm page is encoded as UTF-8. I just tried your code snippet and the issue remains:

![screenshot from 2015-03-24 17 05 43](https://cloud.githubusercontent.com/assets/312270/6806303/1693bc5c-d248-11e4-95f3-a281ac5dee8b.png)

**Comment by ericf** [comment]
@nebirhos That code is running on the Android device?

**Comment by nebirhos** [comment]
@ericf yep, the console is attached to a Nexus 5

![screenshot from 2015-03-24 17 01 03](https://cloud.githubusercontent.com/assets/312270/6806955/fcdf782e-d24b-11e4-932f-070ab6da993f.png)

**Comment by ericf** [comment]
Okay, then this is not a React Intl issue; it's an Android/Chrome issue. Something is not correct with the implementation of ECMA-402 spec. on the device.

A work-around would be to load the `Intl.js` polyfill and assign its constructors to `Intl`:

```js
Intl.NumberFormat = IntlPolyfill.NumberFormat;
Intl.DateTimeFormat = IntlPolyfill.DateTimeFormat;
```

See: http://formatjs.io/guide/#patch-runtime

**Comment by nebirhos** [comment]
@ericf overriding the native code with a polyfill solved the issue, thanks :+1:
