### ISSUE TITLE
FormattedMessage component doesn't pass on className, etc.

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [yahoo/react-intl#913]
When using the component like:

```jsx
<FormattedMessage className='foo' id='xyz' defaultMessage='bar' />
```

I would expect the "foo" className to be applied, but it isn't. This makes it impossible to style a `FormattedMessage` using styled-components.

**Comment by ghostd** [comment]
Hi,

This is a duplicate of #854

**Comment by okuryu** [comment]
Duplicate of #854.
