### ISSUE TITLE
Missing locale causes broken messages.

### ISSUE THREAD

**Issue by Liamonade** [yahoo/react-intl#917]
When a locale is detected that I haven't loaded the locale data for I see the following errors in the console:

```
Missing locale data for locale: "el". Using default locale: "en" as fallback.
```

I understand why I am getting this error, but what I don't understand is why i'm also getting the following errors.

```
Missing message: "hello" for locale: "en"
Cannot format message: "hello", using message id as fallback.
Missing message: "world" for locale: "en"
Cannot format message: "world", using message id as fallback.
```

I would expect it to still use the translations that I have passed in to IntlProvider messages property. Where is looking for the "en" translation of "world" to think that its missing?

Here is the code:

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {IntlProvider, FormattedMessage} from 'react-intl';
import request from 'superagent';
import {addLocaleData} from 'react-intl';

const App = () => (
    <h1>
        <FormattedMessage id="hello" />{' '}
        <FormattedMessage id="world" />
    </h1>
);

class Root extends Component {
    render() {
        let children;

        var messages = { hello: 'Hello', world: 'World', };

        children = (
            <IntlProvider locale="el" messages={ messages }>
                <App/>
            </IntlProvider>
        );

        return <div>{children}</div>;
    }
}

ReactDOM.render(
    <Root />,
    document.getElementById('container')
);
```

**Comment by Liamonade** [comment]
I found a work around to maintain a list of loaded locales and if it is not loaded then default to "en". 

```
class Root extends Component {
    render() {
        let children;

        var messages = { hello: 'Hello', world: 'World', };

        var locale = 'el'; // usually detected from browser

        var loadedLocales = ['en','fr','es'];

        if(loadedLocales.indexOf(locale) == -1){
            locale = 'en';
        }

        children = (
            <IntlProvider locale={locale} messages={ messages }>
                <App/>
            </IntlProvider>
        );

        return <div>{children}</div>;
    }
}
```

**Comment by ghostd** [comment]
Hi,

By default, IntlProvider fallback to 'en', see:
https://github.com/yahoo/react-intl/wiki/Components#intlprovider

To avoid the warnings/errors you can (inclusively) either:
- set the default locale to IntlProvider:
```
<IntlProvider locale={locale} defaultLocale={locale} messages={ messages }>
    <App/>
</IntlProvider>
```
- set a defaultMessage to FormattedMessage
```
<FormattedMessage id="hello" defaultMessage="my default hello message"/>
```
See https://github.com/yahoo/react-intl/wiki/Components#formattedmessage

**Comment by ydeshayes** [comment]
Hello,

I've got the same problem here:

Let say I only have 'en' has available local, but a French navigator load my page. 

If I pass my messages like `<IntlProvider locale={language} messages={localeData}>` localeData will contain the EN translation, and language 'FR'. In this case 'react-intl' will not load the localeData messages but log  `Missing message: "xxx" for locale: "en"` and then fallback to the `id`. Is it a normal behaviour or a bug ?

**Comment by ghostd** [comment]
It is the expected behavior. You application is responsible to pass the correct language value (which is used to correctly format the numbers, dates and other stuff)

**Comment by ydeshayes** [comment]
Ok thanks @ghostd :)

**Comment by kujma10** [comment]
> It is the expected behavior. You application is responsible to pass the correct language value (which is used to correctly format the numbers, dates and other stuff)
[edit] You can also set the defaultLanguage property to fr.

What's the point of using "en" as fallback if it doesn't work anyway then?

**Comment by ShyamRajVerma** [comment]
1. 

- 

- 

- 

> ### **_`[](url)`_**

**Comment by adjenks** [comment]
I know this is a bit old but...

I think I was having the same problem people were having here. Basically I was wondering why I was seeing the values interpolated into the foreign languages, but not interpolated into the default language. It was because I didn't have any message descriptor files for the default language because well, it's the default and I was using the `id` as the default message. If I silence the soft errors, everything works fine like that for me until I have a message with values to interpolate, because the values get ignored and the `id` shows up with curly braces and variable names.

My solution was as simple as wrapping the `formatMessage()` function to copy the id to a `defaultMessage` like so:

```ts
import {createIntl, createIntlCache, IntlFormatters, MessageDescriptor} from '@formatjs/intl'

var cache = createIntlCache()

,intl = createIntl(
    {
        locale: 'en',
        defaultLocale: 'en',
        messages:{
            /**
            You can leave this empty because of the addDefaultMessage :)
            */
        },
        onError: function(err){
            console.log('soft error:',err)
        }
    }
    ,cache
)

,el = document.querySelector('body')

,addDefaultMessage =
    (fm:IntlFormatters["formatMessage"]) =>
        (md:MessageDescriptor,...rest) =>
        fm({defaultMessage:md.id,...md},...rest)

,_ = addDefaultMessage(intl.formatMessage)

,msg: string = _({id:"We're going"}) + ' ' + _({id:"from {from} to {to}"},{from:'1234',to:'5678'})

el.innerHTML = msg
```
