### ISSUE TITLE
Add "now" threshold for formatRelative

### ISSUE THREAD

**Issue by romeovs** [yahoo/react-intl#919]
I have a component that in some cases gets frequent updates, and where the frequency of the updates is around 1s.

This means that the label is constantly flipping between `now` and `1 second ago`, `2 seconds ago`, `now`, `1 second ago`, `now`, etc.

It would be great if I could set the threshold for where the `now` should change to the seconds format, so I can set this to 5 seconds for instance. That way if the status updates often, it will always show the `now` label.

**Comment by okuryu** [comment]
IMO, `intl-relativeformat` doesn't support it. Cloud you file an issue for `intl-relativeformat`?
https://github.com/yahoo/intl-relativeformat
