### ISSUE TITLE
Missing currency sign: SGD

### ISSUE THREAD

**Issue by brendonco** [yahoo/react-intl#928]
```
new Intl.NumberFormat("en-SG", { style: "currency", currency: "SGD" });

OR

locale: en
<FormattedNumber value={value} format="money" {...props} />;

```

e.g. in IE shows $
Chrome/Safari shows SGD

**Comment by ghostd** [comment]
Hi @brendonco,

It seems it is not a react-intl issue, i think you can report the problem here: https://github.com/andyearnshaw/Intl.js

**Comment by brendonco** [comment]
@ghostd Thanks will do.
