### ISSUE TITLE
Cant access component functions through ref

### ISSUE THREAD

**Issue by githubdoramon** [yahoo/react-intl#941]
If I try to get a injectIntl component as a ref, I get a ProxyComponent, and not the component, and for this reason I can't call functions from that component.

#1 
export default ComponentA;

In ComponentB I can do -> <ComponentA ref={(el) => {this.a = el}} , And then
this.a.someFunction();

#2
export default injectIntl(ComponentA);
In ComponentB I can do -> <ComponentA ref={(el) => {this.a = el}} , BUT then
this.a.someFunction() -> someFucntion is not available...

This happens because ComponentA is a ProxyComponent, and not the real component... How to solve this?

**Comment by githubdoramon** [comment]
Ok... {withRef: true} and getWrappedInstance resolved the problem!

**Comment by okuryu** [comment]
Closing this. Please file an issue if you still have any problems.
