### ISSUE TITLE
Missing SEK sign in English, French, German, Swedish, Turkish,... languages

### ISSUE THREAD

**Issue by ikarmous** [yahoo/react-intl#943]
Hi, 
The SEK currency symbol 'Kr' is missing for the above languages.
Any chance to have it added please?

Thank you

**Comment by ikarmous** [comment]
Note: In IE, the currency symbol 'Kr' is displayed, but not in FF and Chrome.

**Comment by ghostd** [comment]
Hi @ikarmous

It seems it is not a react-intl issue, i think you can report the problem here: https://github.com/andyearnshaw/Intl.js

**Comment by okuryu** [comment]
Right, it's probably an issue on Intl.js or CLDR.

**Comment by ikarmous** [comment]
Thank you for your reply.
Reported the issue here https://github.com/andyearnshaw/Intl.js/issues/279 as suggested.

Cheers.
