### ISSUE TITLE
Month text is wrong in Chrome for Icelandic 

### ISSUE THREAD

**Issue by vaskort** [yahoo/react-intl#953]
Hello,

First of all thanks for this library, it is really helpful. 

We seem to have an issue in the Icelandic language only in Chrome. For month "May" for instance instead of showing "Maí" it shows "M05". In other languages we use (en-GB, en-US, fr-FR) everything seems to work great.

Any ideas how to overcome this issue? Let me know if you need more info about the project.

P.S. Apologies if this is not 100% related to the library

**Comment by ghostd** [comment]
Hi,

Not sure it's a react-intl bug. Did you try to format your month with Intl.js (polyfill or native browser impl) to check the result?

If you test with a recent chrome version you can use this doc:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat
(look at the 'Using options' paragraph to get some month examples)

**Comment by vaskort** [comment]
Hi @ghostd thanks a lot for your quick reply, I will check the link and come back with more info.

**Comment by vaskort** [comment]
Sorry for the very slow response. 

Just noticed that I didn't add any code and need to add more info. 

So what I do is I have a date inside my render function like the following: 
```javascript
formatTheDate(date) {
   return this.props.intl.formatDate(date, {day: 'numeric', month: 'short'});
},
render() {
   return <span className="messageDate">   
       {this.formatTheDate(new Date(message.date).toString())}
   </span>
}
```
The above in **Icelandic** language works correctly on iOS(webview) and Safari showing the following date for instance: 
`10. maí`
but on Chrome and quite old androids the result is like the following
`M05 10`

Any thoughts of where to investigate? 

Appreciate your time guys, 
Vasilis

**Comment by ghostd** [comment]
Try this in your browser to check if it's a react-intl bug:
```js
var date = new Date('2017-05-10');
var options = {day: 'numeric', month: 'short'};
console.log(new Intl.DateTimeFormat('is', options).format(date));
```

**Comment by vaskort** [comment]
Yep same result @ghostd: `M05 10`

**Comment by ghostd** [comment]
`react-intl` uses the [CLDR project](https://github.com/unicode-cldr/cldr-dates-full/) for its data. It seems the `is` locale uses by default the same month as the generaic `ca` locale (and not the gregorian one):
https://github.com/unicode-cldr/cldr-dates-full/tree/master/main/is

**Comment by okuryu** [comment]
I think it's an issue for native browser not `react-intl`, closing.

**Comment by vaskort** [comment]
It was indeed a browser issue (Chrome Version 60.0.3112.113 (Official Build) (64-bit)). 
Just to let you know I used https://github.com/andyearnshaw/Intl.js and then I tried again the following in my console:
```
var date = new Date('2017-05-10');
var options = {day: 'numeric', month: 'short'};
console.log(new IntlPolyfill.DateTimeFormat('is', options).format(date));
```
and I got the correct output which is:
```
10. maí
```
Thanks for pointing to the correct direction @ghostd :)
