### ISSUE TITLE
FormattedMessage doesn't pass props to textComponent

### ISSUE THREAD

**Issue by redwind** [yahoo/react-intl#955]
Hi !
i'm use FormattedMessage in React-native component and try to pass props like style to FormattedMessage but when i inspect element, there isn't style property there.
Does anybody has the same problem with me ?
thanks !

**Comment by ghostd** [comment]
Hi,

According to the [source](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L135), the props are not passed to the wrapper child. See #913, #913, #854 

I think we can close this issue as duplicate

**Comment by okuryu** [comment]
Duplicate of #854.
