### ISSUE TITLE
children render function of FormattedMessage doesn't work with rich values

### ISSUE THREAD

**Issue by Floriferous** [yahoo/react-intl#958]
When using `FormattedMessage` with children, it doesn't render rich values:

```jsx
// messages
{
  "test-id": "{value1} and {value2}",
}

// my component
<FormattedMessage
  id="test-id"
  values={{
    value1: 'hello1',
    value2: <span>hello2</span>
  }}
>
  {formattedMessage => (
    <span>{formattedMessage}</span>
  )}
</FormattedMessage>
```

This renders: 

```jsx
<span>hello1 and </span>
```

But I'd expect it to render:
```jsx
<span>hello1 and <span>hello2</span></span>
```

**Comment by ghostd** [comment]
Hi,

According to the [source](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L130) your function receives several arguments. So you could try (not tested):
```
{(...args) => (
    <span>{args}</span>
)}
```

**Comment by Floriferous** [comment]
You're completely right, thanks @ghostd. I had never seen these so called "rest parameters", very useful!
