### ISSUE TITLE
defaultMessage should be able to be blank

### ISSUE THREAD

**Issue by eduardoinnorway** [yahoo/react-intl#959]
When you build language files with "yarn extract-intl"

SyntaxError: unknown: [React Intl] Message Descriptors require an `id` and `defaultMessage`. ✓

This should NOT throw and error on blank defaultMessage, a warning yes, but not error.

The reason you build is to have someone else write the texts based on the keys on the generate language files, so a blank defaultMessage error has no value here.

**Comment by ghostd** [comment]
Hi,

According this [source](https://github.com/yahoo/babel-plugin-react-intl/blob/master/src/index.js#L123), it seems your issue is related to another [project](https://github.com/yahoo/babel-plugin-react-intl)
