### ISSUE TITLE
How to prevent automatic conversion of "ß" into "ss" in German locale?

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [yahoo/react-intl#960]
Hi!

How to preserve symbols like ß from being converted?

**Comment by okovpashko** [comment]
@Dmitry-N-Medvedev could you provide more details on this issue? We use `react-intl` in our project with German translations and `ß` symbol is displayed correctly.

**Comment by Dmitry-N-Medvedev** [comment]
Khm... Something very strange. It now works. I am sorry.

**Comment by fabianjaehnke** [comment]
can you please explain how you got it working?
