### ISSUE TITLE
[question] accent in wording js

### ISSUE THREAD

**Issue by asicfr** [yahoo/react-intl#963]
I have a Reactjs application with react-intl translation module.
For translation, i store all messages in javascript files like this :
export default {
'key_label_1': 'Tableau des départs & arrivées',
}
Can i use accent in javascript string or should i use unicode ?
Is there any good reference or explanation of the best practices for that ?

**Comment by ghostd** [comment]
Hi,

We have this kind of text in our french translations: "nos équipes techniques" and all is fine.

**Comment by asicfr** [comment]
Thanks

**Comment by obedparla** [comment]
Anything you had to do to make it work @ghostd ? I'm having errors with that accent in Spanish. It shows the '?' weird symbol that Chrome displays when it doesn't recognize a symbol.

**Comment by ghostd** [comment]
@obedparla nothing special

Check your JS files are correctly UTF-8 encoded (source and bundle received by the browser)

**Comment by obedparla** [comment]
Weird thing is, I have other languages that work correctly, all except for Spanish. No idea why. #1063
