### ISSUE TITLE
Gender Distinction?

### ISSUE THREAD

**Issue by cyberhck** [yahoo/react-intl#967]
Is there a way to do Gender related translation?

I need to translate a string where I'd mention a gender and it should fill my values accordingly. Does that feature exists? or is it planned?

Thanks.

**Comment by ghostd** [comment]
Hi,

react-intl uses https://github.com/yahoo/intl-messageformat
There is no "gender" support. You could use the ["select" format](https://formatjs.io/guides/message-syntax/#select-format)

**Comment by cyberhck** [comment]
Thank you :) that was helpful
