### ISSUE TITLE
How to access the intl.formatMessage():string function in deep nested component

### ISSUE THREAD

**Issue by dennisat** [yahoo/react-intl#972]
_First of all thanks for this great tool!_

We assume to have something like this.
```
<IntlProvider locale="en" messages={enENMessages}>
    <Component1>
        <Component2 />
    </Component1>
</IntlProvider>
```
In past, in Component2 the `this.context.intl.formatMessage({id: 'HELLO_WORLD'})` probably it was working.  In "react-intl": "^2.3.0" this is not valid anymore, `this.context.intl`is `undefined`.

How can I access this function?

**Comment by ghostd** [comment]
Hi,

Dont use the context, use the props. Read [the doc](https://github.com/yahoo/react-intl/wiki/API#injectintl)
