### ISSUE TITLE
adding more messages to locale data not work

### ISSUE THREAD

**Issue by heinhoang** [yahoo/react-intl#976]
```
import { addLocaleData } from 'react-intl';
import fr from 'react-intl/locale-data/fr';

const localeData = {
    locale: "fr",
    "wellcome": "wellcome trnslated",
};
addLocaleData([...fr]);
addLocaleData(localeData);
```
using in a component:
```
                    <FormattedMessage
                        id="wellcome"
                    />
```
error message in browser console:
`[React Intl] Missing message: "wellcome" for locale: "fr"`

**Comment by ghostd** [comment]
Hi,

I think you misunderstood the API. [`addLocaleData`](https://github.com/yahoo/react-intl/wiki#loading-locale-data) loads data allowing react-intl to format the data, handling plural (and other stuff). Your translations must be passed as argument to the [Provider component](https://github.com/yahoo/react-intl/wiki/Components#intl-provider-component).

You can look at the [examples](https://github.com/yahoo/react-intl/tree/master/examples).

**Comment by heinhoang** [comment]
Thanks, I understand now.
