### ISSUE TITLE
FormattedMessage get object.

### ISSUE THREAD

**Issue by TimonPeng** [yahoo/react-intl#977]
I want to set document.title.

```
componentDidMount() {
  document.title = <FormattedMessage id='title'/>;
}
```

But title became an `[object Object]`.

What's API can I use?

Thank you very much!

**Comment by ghostd** [comment]
Use
* https://github.com/yahoo/react-intl/wiki/API#injectintl
* https://github.com/yahoo/react-intl/wiki/API#formatmessage

**Comment by TimonPeng** [comment]
Thank you! @ghostd

**Comment by guangming21** [comment]
![qq 20170802002337](https://user-images.githubusercontent.com/18028721/28835712-e6ea2806-7718-11e7-92dd-945322625cec.png)
![qq 20170802002348](https://user-images.githubusercontent.com/18028721/28835711-e6e7f5ea-7718-11e7-9b47-a2443da8efcb.png)
why i use this , it will throw this error
