### ISSUE TITLE
Does react-intl support React 0.13? 

### ISSUE THREAD

**Issue by smonev** [yahoo/react-intl#98]
I am getting ```Uncaught TypeError: A message must be provided as a String or AST.``` when trying to use React 0.13. This happens both in a function call, and in a component. FormattedNumber works.
Does react-intl support React 0.13?  Or what am I doing wrong?

```javascript

var React = require('react/addons');

var ReactIntl = require('react-intl');
var IntlMixin = ReactIntl.IntlMixin;
var FormattedRelative = ReactIntl.FormattedRelative;
var FormattedNumber = ReactIntl.FormattedNumber;

var i18n = {
    locales: ['en-US']
};
var App = React.createClass({
    mixins: [IntlMixin],

    render: function() {

        var postDate = Date.now() - (1000 * 60 * 60 * 24);
        //var foo = this.formatRelative(postDate);

        return (
            <div>
                <FormattedNumber value={1000} style="currency" currency="USD" />
                <FormattedRelative value={postDate}/>
            </div>
        );
    }
});

React.render(<App locales={i18n.locales}  />, document.body);
```

**Comment by ericf** [comment]
Are you using Browserify? If so, which version?

**Comment by ericf** [comment]
I'm guess it's the same issue as this: https://github.com/yahoo/react-intl/issues/84#issuecomment-78417830

**Comment by smonev** [comment]
You are right @ericf , it is the same as #84. After updating to the latest Browserify version everything works. Thanks for your help!

**Comment by ericf** [comment]
:+1:
