### ISSUE TITLE
Upgrade cadence for CLDR data

### ISSUE THREAD

**Issue by mimecuvalo** [yahoo/react-intl#982]
package.json has version 2.0.0 listed for `formatjs-extract-cldr-data`
That repo in turn has its package.json using version 29.0.0 for `cldr-dates-full`
`cldr-dates-full` is currently on 31.0.1 which is from a year ago.

On our end we're hoping to see some of the latest fixes from those downstream packages in react-intl. Is there a general policy on updating? Thanks!

**Comment by papasmile** [comment]
It looks like they take PRs for dependency uplifts: check out https://github.com/yahoo/react-intl/pull/986

**Comment by okuryu** [comment]
Released v2.4.0.
