### ISSUE TITLE
FormattedMessage as value for props of other React components without nesting

### ISSUE THREAD

**Issue by vegarsti** [yahoo/react-intl#995]
I want to pass several internationalized messages as props to another React component, which in my case is a (homebrewed) Input field.

```react
<Input label={localeLabel} placeholder={localePlaceholder) />
```

The way I have seen to solve this is to do
```react
<FormattedMessage id="input-label">
  { (label) =>
        <FormattedMessage id="input-placeholder>
            { (placeholder) =>
                <Input label={label} placeholder={placeholder} />
            }
        </FormattedMessage>
  }
</FormattedMessage>

If I need more locale dependant props, this gets ugly quick.
```
My app uses Typescript, so I can't do the following, because the types don't match (`string` and `Element`).

```
const label: string = <FormattedMessage id="input-label>
const placeholder: string = <FormattedMessage id="input-placeholder>
return <Input label={label} placeholder={placeholder} />
```

This gets ugly quick if I should need any more props. Is there any cleaner way to do this?

**Comment by ghostd** [comment]
I think you can do something like this by using [injectIntl](https://github.com/yahoo/react-intl/wiki/API#injection-api) (not declarative but should work, not tested):
```
import React from 'react'
import { injectIntl } from 'react-intl'

const I18nLabel = ({ labelId, placeholderIntl, intl }) => (
  <Input
    label={intl.formatMessage({ id: labelId })}
    placeholder={intl.formatMessage({ id: placeholderId })}
   />
)

export default injectIntl(I18nLabel)
```

**Comment by vegarsti** [comment]
Thanks!

**Comment by azizgharbi** [comment]
> <FormHeader
>       title={<FormattedMessage {...messages.headerTitleMessage} />}
>       descriptionTitle={<FormattedMessage {...messages.headerTitleDescriptionMessage} />}
>       description={<FormattedMessage {...messages.headerDescriptionMessage} />}
>   />

It's works like that for me is it good ? i am confused
